### ISSUE TITLE
Can't up Appfile for my workload

### ISSUE THREAD

**Issue by shikanon** [oam-dev/kubevela#1010]
**Describe the bug**

I write a `workloaddefinitions` like this:
```yaml
apiVersion: core.oam.dev/v1alpha2
kind: WorkloadDefinition
metadata:
  name: mpserver
  annotations:
    definition.oam.dev/description: "mpserver is quwan of recommend service which is long-running, scalable, containerized services."
spec:
  definitionRef:
    name: deployments.apps
  extension:
    template: |
      outputs: app: {
        apiVersion: "apps/v1"
        kind:       "Deployment"
        metadata: {
        	name: context.name
        	labels: {
        		"app.oam.dev/component": context.name
        		"app":                   context.name
        	}
        }
        spec: {
        	selector: matchLabels: {
        		"app.oam.dev/component": context.name
        		"app":                   context.name
        	}
        	template: {
        		metadata: labels: {
              "app.oam.dev/component": context.name
              "app":                   context.name
        		}
        		spec: {
              containers: [{
                name:  context.name
                image: parameter.image
                if parameter["cmd"] != _|_ {
                	command: parameter.cmd
                }
                if parameter["env"] != _|_ {
                	env: parameter.env
                }
                if context["config"] != _|_ {
                	env: context.config
                }
                ports: [
                	for k, v in parameter.ports {
                		containerPort: v
                		protocol:      "TCP"
                	},
                ]
                if parameter["cpu"] != _|_ {
                	resources: {
                		limits:
                      cpu: parameter.cpu
                		memory: parameter.memory
                		requests:
                      cpu: parameter.cpu
                		memory: parameter.memory
                	}
                }
              }]
        	}
        	}
        }
      }
      outputs: service: {
        apiVersion: "v1"
        kind:       "Service"
        metadata: {
        	name: context.name
        	labels: {
        		"app.oam.dev/component": context.name
        		"app":                   context.name
        	}
        }
        spec: {
        	type: "ClusterIP"
        	selector: matchLabels: {
        		"app.oam.dev/component": context.name
        		"app":                   context.name
        	}
        	ports: [
        		for k, v in parameter.ports {
              name:       "tcp-\(k)"
              port:       v
              targetPort: v
              protocol:   "TCP"
        		},
        	]
        }
      }
      #Config: {
        name:  string
        value: int
        other: {
        	key:   string
        	value: string
        }
      }
      parameter: {
        // +usage=Which image would you like to use for your service
        // +short=i
        image: string
        // +usage=Commands to run in the container
        cmd?: [...string]
        // +usage=Which port do you want customer traffic sent to
        // +short=p
        ports: [...int]
        // +usage=Define arguments by using environment variables
        env?: [...{
        	// +usage=Environment variable name
        	name: string
        	// +usage=The value of the environment variable
        	value?: string
        	// +usage=Specifies a source the value of this var should come from
        	valueFrom?: {
        		// +usage=Selects a key of a secret in the pod's namespace
        		secretKeyRef: {
              // +usage=The name of the secret in the pod's namespace to select from
              name: string
              // +usage=The key of the secret to select from. Must be a valid secret key
              key: string
        		}
        	}
        }]
        // +usage=Number of CPU units for the service, like `0.5` (0.5 CPU core), `1` (1 CPU core)
        cpu?: string
        // +usage=Number of CPU units for the service, like `0.5` (0.5 CPU core), `1` (1 CPU core)
        memory?: string
      }
```
and My Appfile is this:
```yaml
name: test-mpserver
services:
  test-mpserver:
    type: mpserver
    image: crccheck/hello-world
    ports: [8000]
```

I am up Appfile, it is Error.

I check this application for command:
```
$ vela system dry-run -f test-mpserver-application.yaml
Error: generate OAM objects: from source
``` 

this `test-mpserver-application.yaml` is:
```yaml
apiVersion: core.oam.dev/v1alpha2
kind: Application
metadata:
  name: test-mpserver
spec:
  components:
  - name: test-mpserver
    scopes:
      healthscopes.core.oam.dev: test-mpserver-default-health
    settings:
      image: crccheck/hello-world
      ports:
      - 8000
    type: mpserver
```

I try to run the cue to check this template, and it is work:
```cue
parameter: {
	image: "crccheck/hello-world"
	ports: [8000]
}

context: {
	name: "test-mpserver"
}
```

run and output:
```bash
$ cue eval ./ -e outputs --out yaml
app:
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: test-mpserver
    labels:
      app: test-mpserver
      app.oam.dev/component: test-mpserver
  spec:
    selector:
      matchLabels:
        app: test-mpserver
        app.oam.dev/component: test-mpserver
    template:
      metadata:
        labels:
          app: test-mpserver
          app.oam.dev/component: test-mpserver
      spec:
        containers:
          - name: test-mpserver
            image: crccheck/hello-world
            ports:
              - containerPort: 8000
                protocol: TCP
service:
  apiVersion: v1
  kind: Service
  metadata:
    name: test-mpserver
    labels:
      app: test-mpserver
      app.oam.dev/component: test-mpserver
  spec:
    selector:
      matchLabels:
        app: test-mpserver
        app.oam.dev/component: test-mpserver
    ports:
      - name: tcp-0
        protocol: TCP
        port: 8000
        targetPort: 8000
    type: ClusterIP
```

**Cluster information**

```bash
$ vela version
Version: refs/tags/v0.3.2
GitRevision: git-18f184d
GolangVersion: go1.14.14
```

```bash
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-r0-CCE20.8.1.3.B001-17.36.5", GitCommit:"d61c11191a704802f93e5d86877a8fcffe208d58", GitTreeState:"clean", BuildDate:"2020-10-16T09:38:58Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
