### ISSUE TITLE
creat workload with outputs raise error: TraitDefinition.core.oam.dev "AuxiliaryWorkload" not found

### ISSUE THREAD

**Issue by shikanon** [oam-dev/kubevela#1022]
**Describe the bug**

I create a workload have `outputs`, when I use `vela system dry-run` to exports applications, and kubectl apply it, It raise up error of TraitDefinition.core.oam.dev "AuxiliaryWorkload" not found.

**To Reproduce**

I have a workloads like this:
```yaml
apiVersion: core.oam.dev/v1alpha2
kind: WorkloadDefinition
metadata:
  name: mpserver
  annotations:
    definition.oam.dev/description: "mpserver is quwan of recommend service which is long-running, scalable, containerized services."
spec:
  definitionRef:
    name: deployments.apps
  extension:
    template: |
      output: {
        apiVersion: "apps/v1"
        kind:       "Deployment"
        metadata: {
        	name: context.name
        	labels: {
        		"app.oam.dev/component": context.name
        		"app":                   context.name
        	}
        }
        spec: {
        	selector: matchLabels: {
        		"app.oam.dev/component": context.name
        		"app":                   context.name
        	}
        	template: {
        		metadata: labels: {
              "app.oam.dev/component": context.name
              "app":                   context.name
        		}
        		spec: {
              containers: [{
                name:  context.name
                image: parameter.image
                if parameter["cmd"] != _|_ {
                	command: parameter.cmd
                }
                if parameter["env"] != _|_ {
                	env: parameter.env
                }
                if context["config"] != _|_ {
                	env: context.config
                }
                ports: [
                	for k, v in parameter.ports {
                		containerPort: v
                		protocol:      "TCP"
                	},
                ]
                if parameter["cpu"] != _|_ {
                	resources: {
                		limits:
                      cpu: parameter.cpu
                		memory: parameter.memory
                		requests:
                      cpu: parameter.cpu
                		memory: parameter.memory
                	}
                }
              }]
        	}
        	}
        }
      }
      outputs: service: {
        apiVersion: "v1"
        kind:       "Service"
        metadata: {
        	name: context.name
        	labels: {
        		"app.oam.dev/component": context.name
        		"app":                   context.name
        	}
        }
        spec: {
        	type: "ClusterIP"
        	selector: matchLabels: {
        		"app.oam.dev/component": context.name
        		"app":                   context.name
        	}
        	ports: [
        		for k, v in parameter.ports {
              name:       "tcp-\(k)"
              port:       v
              targetPort: v
              protocol:   "TCP"
        		},
        	]
        }
      }
      #Config: {
        name:  string
        value: int
        other: {
        	key:   string
        	value: string
        }
      }
      parameter: {
        // +usage=Which image would you like to use for your service
        // +short=i
        image: string
        // +usage=Commands to run in the container
        cmd?: [...string]
        // +usage=Which port do you want customer traffic sent to
        // +short=p
        ports: [...int]
        // +usage=Define arguments by using environment variables
        env?: [...{
        	// +usage=Environment variable name
        	name: string
        	// +usage=The value of the environment variable
        	value?: string
        	// +usage=Specifies a source the value of this var should come from
        	valueFrom?: {
        		// +usage=Selects a key of a secret in the pod's namespace
        		secretKeyRef: {
              // +usage=The name of the secret in the pod's namespace to select from
              name: string
              // +usage=The key of the secret to select from. Must be a valid secret key
              key: string
        		}
        	}
        }]
        // +usage=Number of CPU units for the service, like `0.5` (0.5 CPU core), `1` (1 CPU core)
        cpu?: string
        // +usage=Number of CPU units for the service, like `0.5` (0.5 CPU core), `1` (1 CPU core)
        memory?: string
      }
```

about `outputs` usage like [workload multi output example](https://github.com/oam-dev/kubevela/blob/dc8358f910ab13fa95955589ba5d59d396d80f32/docs/examples/advanced-cue/webserver.yaml#L12)

I run `vela system dry-run`, use the applications is this:
```yaml
apiVersion: core.oam.dev/v1alpha2
kind: Application
metadata:
  name: test-newwebserver
spec:
  components:
  - name: test-newwebserver
    scopes:
      healthscopes.core.oam.dev: test-mpserver-default-health
    settings:
      image: crccheck/hello-world
      ports:
      - 8000
    type: newwebserver
```

 and it is output components and traits:
```yaml
- apiVersion: core.oam.dev/v1alpha2
  kind: ApplicationConfiguration
  metadata:
    creationTimestamp: null
    labels:
      application.oam.dev: test-newwebserver
    name: test-newwebserver
  spec:
    components:
    - componentName: test-newwebserver
      scopes:
      - scopeRef:
          apiVersion: core.oam.dev/v1alpha2
          kind: HealthScope
          name: test-mpserver-default-health
      traits:
      - trait:
          apiVersion: v1
          kind: Service
          metadata:
            labels:
              trait.oam.dev/type: AuxiliaryWorkload
          spec:
            ports:
            - port: 80
              targetPort: 80
            selector:
              app.oam.dev/component: test-newwebserver
  status:
    dependency: {}
    observedGeneration: 0
- apiVersion: core.oam.dev/v1alpha2
  kind: Component
  metadata:
    creationTimestamp: null
    labels:
      application.oam.dev: test-newwebserver
    name: test-newwebserver
  spec:
    workload:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        labels:
          workload.oam.dev/type: newwebserver
      spec:
        selector:
          matchLabels:
            app.oam.dev/component: test-newwebserver
        template:
          metadata:
            labels:
              app.oam.dev/component: test-newwebserver
          spec:
            containers:
            - image: crccheck/hello-world
              name: test-newwebserver
              ports:
              - containerPort: 80
  status:
    observedGeneration: 0
```
It a new type of trait `trait.oam.dev/type: AuxiliaryWorkload`. When I use `kubetcl` to apply, it has error like this:
```bash
$ kubectl apply -f test-mpserver-applicationconfigure.yaml
component.core.oam.dev/test-newwebserver created
Error from server (cannot get trait definition in component "test-newwebserver": TraitDefinition.core.oam.dev "AuxiliaryWorkload" not found): error when creating "test-mpserver-applicationconfigure.yaml": admission webhook "validating.core.oam.dev.v1alpha2.applicationconfigurations" denied the request: cannot get trait definition in component "test-newwebserver": TraitDefinition.core.oam.dev "AuxiliaryWorkload" not found
```

**Expected behavior**

**Screenshots**

**Cluster information**

```bash
$ vela version
Version: refs/tags/v0.3.2
GitRevision: git-18f184d
GolangVersion: go1.14.14
```

```bash
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-r0-CCE20.8.1.3.B001-17.36.5", GitCommit:"d61c11191a704802f93e5d86877a8fcffe208d58", GitTreeState:"clean", BuildDate:"2020-10-16T09:38:58Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
