### ISSUE TITLE
[Feature] about trait load parameter of workload

### ISSUE THREAD

**Issue by shikanon** [oam-dev/kubevela#1025]
**Is your feature request related to a problem? Please describe.**

I write a server workload `mpserver` which has a field of `port` ,and write a trait of istio virtualservices which also need to set `port` from the workload. 

A workload example like this:
```yaml
apiVersion: core.oam.dev/v1alpha2
kind: WorkloadDefinition
metadata:
  name: mpserver
  annotations:
    definition.oam.dev/description: "mpserver is quwan of recommend service which is long-running, scalable, containerized services."
spec:
  definitionRef:
    name: deployments.apps
  extension:
    template: |
      output: {
        apiVersion: "apps/v1"
        kind:       "Deployment"
        spec: {
        	template: {
        		spec: {
               containers: [{
                name:  context.name
                image: parameter.image
                ...
                ports: [
                	for k, v in parameter.ports {
                		containerPort: v
                		protocol:      "TCP"
                	},
                ]
                
              }]
        	}
        	}
        }
      }
      outputs: service: {
        apiVersion: "v1"
        kind:       "Service"
        metadata: {
        	name: context.name
        	labels: {
        		"app.oam.dev/component": context.name
        		"app":                   context.name
        	}
        }
        spec: {
        	type: "ClusterIP"
        	selector: {
        		"app.oam.dev/component": context.name
        		"app":                   context.name
        	}
        	ports: [
        		for k, v in parameter.ports {
              name:       "tcp-\(k)"
              port:       v
              targetPort: v
              protocol:   "TCP"
        		},
        	]
        }
      }

      parameter: {
        // +usage=Which image would you like to use for your service
        // +short=i
        image: string
        // +usage=Commands to run in the container
        cmd?: [...string]
        // +usage=Which port do you want customer traffic sent to
        // +short=p
        port: int
        ...
      }
```
In this workload, we have a parameter of the `port` field.
In traits, I am also need to need a same ports:
```cuelang
output: {
	apiVersion: "networking.istio.io/v1beta1"
	kind:       "VirtualService"
	metadata: {
		name: context.name
	}
	spec: {
		gateways: parameter.gateways
		hosts: parameter.hosts
		http: {
			route: {
				destination: {
					host: "\(context.name).default.svc.cluster.local"
					port: {
						number: parameter.port
					}
				}
			}
		}
		
	}
}

parameter: {
	// +usage=Which gateways would you like to binds for your virtualservice
	// +short=g
	gateways: [...string]

	// +usage=hosts to access app url
	hosts?: [...string]

	port: int
}
``` 

if make like this, the people write the `appfile` need duplicate value like this:
```yaml
name: test-mpserver
services:
  test-mpserver:
    type: mpserver
    image: crccheck/hello-world
    port: 8000
    vritualservice:
      port: 8000 # this a deplicate value
```

we need a method to load workload parameter, and give trait to use, for exmaple use `workload.parameter` mean from workload parameter etc.
