### ISSUE TITLE
[Feature] support simple data passing from workload to trait

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela#1026]
**Is your feature request related to a problem? Please describe.**

When a workload created by cue template, some of the parameters can be re-used in trait, we should not define it multiple times.

Below is an example, that the trait will rely on the workload output and outputs to fill themself.

1. the main workload object(Deployment) in this example will render into the `context.output` before rendering traits.
2. the `context.outputs.<xx>` will keep all these rendered trait data and can be used in the traits after them.

template.yaml

```
apiVersion: core.oam.dev/v1alpha2
kind: WorkloadDefinition
metadata:
  name: worker
spec:
  definitionRef:
    name: deployments.apps
  extension:
    template: |
      output: {
      	apiVersion: "apps/v1"
      	kind:       "Deployment"
      	spec: {
      		selector: matchLabels: {
      			"app.oam.dev/component": context.name
      		}

      		template: {
      			metadata: labels: {
      				"app.oam.dev/component": context.name
      			}
      			spec: {
      				containers: [{
      					name:  context.name
      					image: parameter.image
                                         ports:[{containerPort: parameter.port}]
      					envFrom: [{
      						configMapRef: name: context.name + "game-config"
      					}]
      					if parameter["cmd"] != _|_ {
      						command: parameter.cmd
      					}
      				}]
      			}
      		}
      	}
      }

      outputs: gameconfig: {
      	apiVersion: "v1"
      	kind:       "ConfigMap"
      	metadata: {
      		name: context.name + "game-config"
      	}
      	data: {
      		enemies: parameter.enemies
      		lives:   parameter.lives
      	}
      }

      parameter: {
      	// +usage=Which image would you like to use for your service
      	// +short=i
      	image: string
      	// +usage=Commands to run in the container
      	cmd?: [...string]
      	lives:   string
      	enemies: string
        port: int
      }



---
apiVersion: core.oam.dev/v1alpha2
kind: TraitDefinition
metadata:
  name: ingress
spec:
  extension:
    template: |
      parameter: {
        domain: string
        path: string
        exposePort: int
      }
      // trait template can have multiple outputs in one trait
      outputs: service: {
        apiVersion: "v1"
        kind: "Service"
        spec: {
          selector:
            app: context.name
          ports: [
            {
              port: paramter.exposePort
              targetPort: context.output.spec.template.spec.containers[0].ports[0].containerPort
            }
          ]
        }
      }
      outputs: ingress: {
        apiVersion: "networking.k8s.io/v1beta1"
        kind: "Ingress"
        metadata:
          name: context.name
          labels: config: context.outputs.gameconfig.data.enemies
        spec: {
          rules: [{
            host: parameter.domain
            http: {
              paths: [
                  path: parameter.path
                  backend: {
                    serviceName: context.name
                    servicePort: paramter.exposePort
                  }
              ]
            }
          }]
        }
      }
```

app.yaml

```
apiVersion: core.oam.dev/v1alpha2
kind: Application
metadata:
  name: application-sample
spec:
  components:
    - name: myweb
      type: worker
      settings:
        image: "busybox"
        cmd:
          - sleep
          - "1000"
        lives: "3"
        enemies: "alien"
        port: 80
      traits:
        - name: ingress
          properties:
            domain: "www.example.com"
            path: "/"
```

Related issue: 

1. traits can not use `output`, or it will conflict with workload output #1023
2. workload parameters pass through to traits  #959 #1025

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
