### ISSUE TITLE
[Feature] Add ApplicationTemplate for multi-cluster deployment

### ISSUE THREAD

**Issue by LeoLiuYan** [oam-dev/kubevela#1048]
**Is your feature request related to a problem? Please describe.**
When we use vela to deploy application in multi environments, like `QA`,`PRE`,`PROD`, there is no GVK to describe it.

**Describe the solution you'd like**
The `ApplicationTemplateDefinition` and `ApplicationTemplate` design below.

1.  ApplicationTemplateDefinition

    The `ApplicationTemplateDefinition` to generate `ApplicationTemplate`.
    
        apiVersion: core.oam.dev/v1alpha1
        kind: ApplicationTemplateDefinition
        metadata:
          name: generic
        spec:
          definitionRef:
            name: applicationTemplates.core.oam.dev
          extension:
            template: |
              output: |
                 apiVersion: core.oam.dev/v1alpha1
                 kind: ApplicationTemplate
                 metadata:
                    name: parameter.name
                 spec:
                   baseInfo: parameter.baseInfo
                   template: |
                     output: parameter.template.output
                     parameter: parameter.template.parameter
              parameter: {
                  name: string
                  baseInfo: {}
                  template: {
                    output: {}
                    parameter: {}
                  }
              }

2. ApplicationTemplate

    The `ApplicationTemplate` generate from `ApplicationTemplateDefinition` may be like this. 
    It includes an application's base information and  `Application` template to deploy use.
    
        apiVersion: core.oam.dev/v1alpha1
        kind: ApplicationTemplate
        metadata:
          name: vela-demo
          version: 2
        spec:
          baseInfo:
            name: vela-demo
            appType: GO
            gitRepo: git@github.com:oam-dev/kubevela.git
            owner: kubevela
            devs:
              - dev-1
            pes:
              - pe-1
          template: |
            output: |
              apiVersion: core.oam.dev/v1alpha1
              kind: Application
              metadata:
                env: parameter.env
                idc: parameter.idc
                name: paramter.name
              spec:
                components:
                  - name: instance
                    type: parameter.components[0].workloadType
                    settings:
                      cmd:
                        - sleep 100
                    traits:
                      - name: ingress
                  - name: database
                    type: parameter.components[1].workloadType
            parameter: {
              name: string
              env: *qa | string
              idc: string
              components: [
                 ...{
                   workloadType: string
                 }
              ]
            }
        status:
          appliedTo:
            - application1
            - application2
          phase: deployed

The architecture of kubevela may be like this from user's perspective.
![image](https://user-images.githubusercontent.com/5344039/107342935-c9ce2d00-6afb-11eb-829f-6b0bf1ea1f5f.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by hongchaodeng** [comment]
AFAICT, this is about having  application CR templates and have different CR configurations in different environments, right?

If so, first of all, we probably should NOT describe it as a CRD for the following reasons:
- The multi-environment application management is being handled in [velacp](https://github.com/oam-dev/velacp). This scope should be covered there. If so it is RESTful API that would be exposed.
- This is just a rendering work. There is no control logic involved. So there is no need to write a controller to do the heavy reconcile work.

Secondly, it seems there are ApplicationTemplate and another Template for ApplicationTemplate called ApplicationTemplateDefinition. This could go on forever and it is not a wise idea that every time we need to template an object we create another CRD. We should probably create a generate Template API to resolve this kind of problem.

All in all, the application templates and multi-environment deployment management are within the scope of velacp and they are in my scope to implement.

**Comment by resouer** [comment]
@hongchaodeng In this issue, we will focus on designing the model of `ApplicationTemplate` instead of implementation detail (i.e. CRD controller or not). Any spec is essentially plain JSON data so it should not be a concern at all.

Also, the current scope of `velacp` is heavily focusing on system modules distribution with many issues to address (https://github.com/oam-dev/kubevela/issues/1019) for now, I don't think we are able to expand its scope unless there're extra bandwidth on it (good to know!).

**Comment by resouer** [comment]
@LeoLiuYan Thank you for bringing this up!

I think the direction is more like a template to generate `Application`, think about last mile patch for Helm chart `.values` but works on server side.

It's very easy to templating a given `Application`, for example:
```yaml
template:
  apiVersion: core.oam.dev/v1alpha2
  kind: Application
  metadata:
    name: '{{clusterName}}-myapp' # templating
  spec:
    components:
      - name: myweb
        type: worker
        settings:
          image: "busybox"
          cmd:
          - sleep
          - "1000"
```

The issue here is where should the per environment/cluster values (i.e. `clusterName`) come from? In ArgoCD there's concept named [generator](https://github.com/argoproj-labs/applicationset/blob/master/examples/git-files-discovery.yaml) to auto inject such values based on cluster information stored in Git category. 

Another idea is we go manual approach, it's basically like what Helm is doing:

```yaml
template:
  apiVersion: core.oam.dev/v1alpha2
  kind: Application
  metadata:
    name: '{{.clusters.name}}-myapp' # templating
  spec:
    components:
      - name: myweb
        type: worker
        settings:
          image: "busybox"
          cmd:
          - sleep
          - "1000"
clusters:
- name: prod
   server: cluster-1.cluster
- name: test
   server: cluster-2.cluster
```

Eager to know your use case better and have wider inputs from the community!

**Comment by LeoLiuYan** [comment]
@hongchaodeng 

You are right, `velacp` could cover solutions of the following issues:

1.  `ApplicationTemplate` management
2.  Render `ApplicationTemplate` to generate `Application` object of server side
3.  Deploy `Application` to difference environments and difference clusters

But, think those cases:

1.  Users want to build their own `Controller Plane` but use `velacp`
2.  Users have a `deploy CRD` to control `Application` publish of difference environments and difference clusters

So, `ApplicationTemplate` should be independent from `velacp`.
The design based on CRD may get more people interested in `ApplicationTemplate`.   😁

**Comment by LeoLiuYan** [comment]
@resouer 

`ApplicationTemplate` also should have versions. 

To make it clear, use a picture to describe:
![image](https://user-images.githubusercontent.com/5344039/107461504-1ade2f80-6b95-11eb-8ba9-39f332da769b.png)


For example, in `ApplicationTemplate` version1 only have one component called `instance`, 
then we deploy it to cluster `qa-cluster1` of `QA environment`, and  `prod-cluster1`,`prod-cluster2` of `PROD environment`.

After two days, we need a database, so add a component called `database` to `ApplicationTemplate`, 
then we changed the template version to version2. We deploy version2 to `qa-cluster1`. After test, deploy to `prod-cluster1`, but not to `prod-cluster2` for canary publish.

Again, after two days, we need a cache, so we add a component called `cache`. We changed the template version to version3 and deploy it to `qa-cluster1` for test.

**Comment by ryanzhang-oss** [comment]
> For example, in `ApplicationTemplate` version1 only have one component called `instance`,
> then we deploy it to cluster `qa-cluster1` of `QA environment`, and `prod-cluster1`,`prod-cluster2` of `PROD environment`.
> 
> After two days, we need a database, so add a component called `database` to `ApplicationTemplate`,
> then we changed the template version to version2. We deploy version2 to `qa-cluster1`. After test, deploy to `prod-cluster1`, but not to `prod-cluster2` for canary publish.
> 
> Again, after two days, we need a cache, so we add a component called `cache`. We changed the template version to version3 and deploy it to `qa-cluster1` for test.

This process sounds very much like an application "revision" management process instead of a "template".  It seems that you are looking for a way to deploy a certain "version" of an application. I am not sure if you are trying to achieve more than that in your issue.

**Comment by resouer** [comment]
@ryanzhang-oss I offline talked with LeoLiuYan, he is definitely talking about application template, but he also has an extra requirement that the template could be partially different for different environments, so it's app template + kustomization. That's why he introduced a `definition` for template, it's basically a template for template.

**Comment by LeoLiuYan** [comment]
Is it possible that the following  `template + kustomization` could solve the problem which is different environments has different templates?

 ```yaml
  apiVersion: core.oam.dev/v1alpha2
  kind: ApplicationTemplate
  metadata:
    name: vela-demo
    version: 2
  spec:
    baseInfo:
      name: vela-demo
      appType: GO
      gitRepo: git@github.com:oam-dev/kubevela.git
      owner: kubevela
  template: 
    apiVersion: core.oam.dev/v1alpha2
    kind: Application
    metadata:
      env: {{ .environments.*.destinations.*.properties.env }}
      idc: {{ .environments.*.destinations.*.properties.idc }}
      name: {{ .environments.*.destinations.*.name }}
    spec:
      components:
        - name: instance
          type: 
          settings:
          cmd:
            - sleep 
            - '100'
          traits:
            - name: ingress
  environments:
    - name: prod
      overlays:
        version: 3
        kustomize:
          namePrefix: prod
          patchesStrategicMerge:
            - apiVersion: core.oam.dev/v1alpha2
              kind: Application
              spec:
                components:
                  - name: cache
      destinations:
        - name: prod.1
          properties:
            env: prod
            idc: prod-1
    - name: qa
      overlays:
        version: 4
        kustomize:
          namePrefix: qa
          sourceRef:
            kind: GitRepository
            name: webapp
      destinations:
        - name: qa.1
          properties:
            env: qa
            idc: qa-1
 ```

There are some preconditions:
1.  `ApplicationTemplate Controller` should  parse `environments.overlays` to generate  [Kustomization Kind](https://toolkit.fluxcd.io/components/kustomize/kustomization/), and then `Kustomize Controller` will create `Application` object.
2.  The [Source Controller](https://github.com/fluxcd/source-controller) should support CRD source.

**Comment by resouer** [comment]
@LeoLiuYan Your sample yamls are theoretically correct ^^ i.e. you basically need to define your per environment diff as kustomize patch. 

While as you have noticed, kustomize works best with git/folder layout. It looks ugly in a CR.

I created a multi-environment app delivery sample with kustomize + git layout which looks much better. The layout is like this:
```
vela-demo
├── LICENSE
├── README.md
├── apps
│   ├── base
│   │   └── podinfo
│   │       ├── app.yaml
│   │       ├── kustomization.yaml
│   │       └── namespace.yaml
│   ├── production
│   │   ├── app.yaml
│   │   └── kustomization.yaml
│   └── staging
│       ├── app.yaml
│       └── kustomization.yaml
├── deployments
│   ├── production
│   │   ├── apps.yaml
│   │   └── environment.yaml
│   └── staging
│       ├── apps.yaml
│       └── environment.yaml
└── environments
    ├── base
    │   ├── addons
    │   │   ├── nginx
    │   │   │   ├── kustomization.yaml
    │   │   │   ├── namespace.yaml
    │   │   │   └── release.yaml
    │   │   └── redis
    │   │       ├── kustomization.yaml
    │   │       ├── kustomizeconfig.yaml
    │   │       ├── namespace.yaml
    │   │       ├── release.yaml
    │   │       └── values.yaml
    │   ├── definitions
    │   │   ├── components
    │   │   │   └── webapp-chart.yaml
    │   │   └── traits
    │   ├── kustomization.yaml
    │   └── repositories
    │       ├── bitnami.yaml
    │       ├── kustomization.yaml
    │       └── podinfo.yaml
    ├── production
    │   ├── definitions
    │   │   └── components
    │   │       └── webapp-chart.yaml
    │   └── kustomization.yaml
    └── staging
        ├── definitions
        │   └── components
        │       └── webapp-chart.yaml
        └── kustomization.yaml
```

Please check the full sample [here](https://github.com/resouer/vela-demo). You can [directly apply ](https://github.com/resouer/vela-demo#plain-apply)the files with kubectl if you don't use GitOps.

Not sure if you are OK to adopt this approach? (i.e. use a git/folder layout instead of defining patches in a CR)

**Comment by resouer** [comment]
First of all, you need to allow `Application` to claim its target `Environment`:

```yaml
apiVersion: core.oam.dev/v1alpha2
kind: Application
metadata:
  name: sample
spec:
  components:
    - name: instance
      type: webservice
      settings:
        cmd:
          - sleep 100
      traits:
        - name: ingress
    - name: database
      type: mysql
  environment: # please use Environment CRD when it's ready
    cluster: kubeconfig-configmap
    namespace: project-1
    properties:
      env: prod
      idc: cluster1.me
```
Please also check `Environment CRD`: https://github.com/oam-dev/kubevela/issues/176

**How to?**

First, use OAM definition to templating it and register as a component in control plane cluster.
```yaml
apiVersion: core.oam.dev/v1alpha2
kind: WorkloadDefinition # ComponentDefinition
metadata:
  name: sample-app
spec:
  extension:
    template: |
      output: {
        apiVersion: core.oam.dev/v1alpha2
        kind: Application
        metadata:
          name: paramter.name
        spec:
          components:
            - name: instance
              type: webservice
              settings:
                cmd:
                  - sleep 100
              traits:
                - name: ingress
            - name: database
              type: parameter.databaseType
          environment:
            cluster: parameter.cluster
            namespace: parameter.env
            properties:
              env: parameter.env
              idc: parameter.idc
      }
      parameter: {
        name: string
        env: *qa | string
        idc: string
        cluster: string
        databaseType: string
      }
```

Second, now you can use OAM `Application` to define a multi-cluster application like below:

```yaml
apiVersion: core.oam.dev/v1alpha2
kind: Application
metadata:
  name: my-app
spec:
  components:
    - name: qa
      type: sample-app
      settings:
        name: test-123
        env: qa
        idc: hangzhou-1
        databaseType: mysql
        cluster: qa-kubeconfig
    - name: prod
      type: sample-app
      settings:
        name: prod-123
        env: prod
        idc: hangzhou-2
        databaseType: aliyun-rds
        cluster: prod-kubeconfig
```

In this app object, you can even use advanced features such as [patch trait](https://kubevela.io/#/en/cue/trait) to add more components and traits in the application template if you want (but I think the workload definition can already cover all your cases).

**Comment by LeoLiuYan** [comment]
@resouer 

I think `ApplicationGroup` is better.  

But if we define a new kind, should it like this is better? Consider that if we deploy multi clusters of an app in `QA Environment`. The multi clusters are refers to app not to k8s.

```yaml
apiVersion: core.oam.dev/v1alpha1
kind: ApplicationGroup
metadata:
  name: my-app-grp
spec:
  applications:
    - environment: qa
      appClusters:
        - name: vela-demo-qa-cluster1
          template: sample-app-template
          values:
            cluster: qa
            databaseType: mysql
            project: qa-1
        - name: vela-demo-qa-cluster2
          template: sample-app-template
          values:
            cluster: qa
            databaseType: aliyun-rds
            project: qa-2
    - environment: prod
      appClusters:
        - name: vela-demo-prod-cluster1
          template: sample-app-template
          values:
            cluster: prod
        - name: vela-demo-prod-cluster2
          template: sample-app-template
          values:
            cluster: prod
```

**Comment by wonderflow** [comment]
We're going to re-visit this issue and @hongchaodeng will send a PR about the design.

**Comment by wonderflow** [comment]
@hongchaodeng My draft Solution: 

## Application Template Object

```
apiVersion: core.oam.dev/v1alpha1
kind: ApplicationTemplate
metadata:
  name: sample-app-template
spec:
    template: |
      output: {
        apiVersion: core.oam.dev/v1alpha2
        kind: Application
        metadata:
          name: context.name
        spec:
          components:
            - name: instance
              type: webservice
              settings:
                cmd:
                  - sleep 100
              traits:
                - name: ingress
            - name: database
              type: parameter.databaseType
          environment:
            namespace: parameter.project
      }
      parameter: {
        project: string
        databaseType: string
      }
```

## Env Object


```
apiVersion: core.oam.dev/v1alpha1
kind: Env
metadata:
  name: prod
spec:
  clusters:  # deploy to the following clusters
    - prod-cluster
  secrets: # The secrets that will be created for applications if not existed.
    - name: redis
      data:
        url: redis-url
        password: redis-password
  definitions: # The definitions that will be created for applications if not existed.
    - type: Component
      name: function
      source:
        git: catalog-url
        path: pacakge/function
    - type: Trait
      name: logging
      source:
        git: catalog-url
        path: package/logging
```


## Application Group Object

```
apiVersion: core.oam.dev/v1alpha1
kind: ApplicationGroup
metadata:
  name: my-app-grp
spec:
  applications:
    - name: prod-app1
      targetEnvs:
      - prod
      template: sample-app-template
      values:
        databaseType: mysql
        project: qa-1
    - name: prod-app12
      template: sample-app-template
      targetEnvs:
      - prod
      values:
        databaseType: aliyun-rds
        project: qa-2
```
