### ISSUE TITLE
Trait with strategic merge patch fails

### ISSUE THREAD

**Issue by hprotzek** [oam-dev/kubevela#1062]
Using this trait:
```
apiVersion: core.oam.dev/v1alpha2
kind: TraitDefinition
metadata:
  annotations:
    definition.oam.dev/description: "add an init container and use shared volume with pod"
  name: init-container
spec:
  appliesToWorkloads:
    - webservice
    - worker
  extension:
    template: |-
      patch: {
      	spec: template: spec: {
      		// +patchKey=name
      		containers: [{
      			name: context.name
      			// +patchKey=name
      			volumeMounts: [{
      				name:      parameter.mountName
      				mountPath: parameter.appMountPath
      			}]
      		}]
      		initContainers: [{
      			name:    parameter.name
      			image:   parameter.image
      			command: parameter.command
      			// +patchKey=name
      			volumeMounts: [{
      				name:      parameter.mountName
      				mountPath: parameter.initMountPath
      			}]
      		}]
      		// +patchKey=name
      		volumes: [{
      			name:     parameter.mountName
      			emptyDir: {}
      		}]
      	}
      }

      parameter: {
      	name:  string
      	image: string
      	command?: [...string]
      	mountName:     *"workdir" | string
      	appMountPath:  string
      	initMountPath: string
      }
```

with this manifest:

```
name: holgers-test
services:
  init-container-test:
    type: webservice
    image: nginx:stable
    port: 80
    init-container:
      name: init-container
      image: debian:strech
      mountName: html-share
      appMountPath: /usr/share/nginx/html
      initMountPath: /usr/share/nginx/html
```

fails with this error:

`
	2021-02-17T09:46:55.433Z	ERROR	Application	[Handle GenerateApplicationConfiguration]	{"application": "vela-e2e-test-e2e-sninit-container-trait-a7eed96ea475/holgers-test", "error": "evaluate template trait=init-container app=init-container-test: invalid patch trait init-container into workload: compile patch file: spec.template.spec.initContainers.command: reference \"parameter\" not found", "errorVerbose": "spec.template.spec.initContainers.command: reference \"parameter\" not found\ncompile patch file\ninvalid patch trait init-container into workload\nevaluate template trait=init-container app=init-container-test\ngithub.com/oam-dev/kubevela/pkg/appfile.(*Parser).GenerateApplicationConfiguration\n\t/workspace/pkg/appfile/parser.go:233\ngithub.com/oam-dev/kubevela/pkg/controller/core.oam.dev/v1alpha2/application.(*Reconciler).Reconcile\n\t/workspace/pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go:107\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:235\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:209\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:188\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:90\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373"}
`

**Comment by zzxwill** [comment]
Thanks for reporting this issue.

The error could be quickly fixed by adding parameter `command` in the appfile as below.

```
name: holgers-test
services:
  init-container-test:
    ...
    init-container:
      ...
      initMountPath: /usr/share/nginx/html
      command:
        - "sleep 2"
```

Or you can also try installing the application by `Application` CRD https://kubevela.io/#/en/cue/trait?id=add-init-container.

But parameter `command` is defined as optional, your Appfile should work. I am looking into this problem.
