### ISSUE TITLE
[Feature] Template modules should also be revisioned

### ISSUE THREAD

**Issue by resouer** [oam-dev/kubevela#1064]
**Is your feature request related to a problem? Please describe.**

We need the full snapshot of the whole application as well as the template it's using.

One option is we revision the definition objects, while this would be problematic since we will have to use `-v1` as part of the definition name.

**Describe the solution you'd like**

One possible solution is:

1. Store template modules (e.g. `xxx.cue`) in [immutable `ConfigMap`](https://kubernetes.io/docs/concepts/configuration/configmap/#configmap-immutable) 

2. Ref the immutable `ConfigMap` in definition:
```yaml
kind: ComponentDefinition
metadata:
  name: webservice
spec:
  schematic:
    cue:
      templateData: webservice-cue-v1 # configmap name
```

So the revision object can simply record the definition object, template module itself is already revisioned.

The cons is we can't even see the template and parameters directly in the definition object. Doc gen is must have for end users to define application.

**Describe alternatives you've considered**

The alternative is generating immutable objects:
ˇ
```yaml
kind: ComponentDefinition
metadata:
  name: webservice
spec:
  definitionRef:
    name: deployments.apps
  schematic:
    cue:
      template:
        # mutable cue template data
---
kind: ComponentDefinitionRevision
metadata:
  name: deployments.apps-{revision number}
spec:
  module:
    cue:
      template:
        # immutable cue template data of {revision number}
        ...
```
Then `ComponentDefinition` change will keep generating above immutable `ComponentDefinitionRevision` objects.

This is helpful for non-k8s impl, and can provide a generic revision approach, but brought extra complexity for k8s runtime IMO. 

**Additional context**
