### ISSUE TITLE
The same type services in the appfiles is Invalid

### ISSUE THREAD

**Issue by shikanon** [oam-dev/kubevela#1079]
**Describe the bug**

I have a app contains multiple entities, and when we set they in the same type, it will be only one by generated.

**To Reproduce**

install `mpserver` workloaddefinitions in this link: 
https://github.com/shikanon/vela-example/blob/main/mpserver/workloaddefinition.yaml

create the appfile:
```yaml
name: mpserver-deploy-kafka
services:
  test-deploy-kafka:
    type: mpserver
    image: wurstmeister/kafka:2.12-2.5.0
    env:
      - name: KAFKA_ADVERTISED_LISTENERS
        value: "INSIDE://test-deploy-kafka:9092,OUTSIDE://test-deploy-kafka.rcmd.testing.mpengine:10000"
      - name: KAFKA_LISTENERS
        value: "INSIDE://:9092,OUTSIDE://:10000"
      - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
        value: "INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT"
      - name: KAFKA_INTER_BROKER_LISTENER_NAME
        value: "INSIDE"
      - name: KAFKA_ZOOKEEPER_CONNECT
        value: test-deploy-zookeeper:2181
      - name: KAFKA_BROKER_ID
        value: "0"
    ports: [9308]
    
  test-deploy-zookeeper:
    type: mpserver
    image: bitnami/zookeeper:3.6.2
    env:
      - name: ALLOW_ANONYMOUS_LOGIN
        value: "yes"
      - name: ZOO_SERVER_ID
        value: "1"
      - name: ZOO_SERVERS
        value: 0.0.0.0:2888:3888
    ports: [2181, 2888, 3888]
```

up the App:
```bash
$ vela up -f mpserver-deploy-kafka.yaml
Parsing vela appfile ...
Load Template ...

Rendering configs for service (test-deploy-kafka)...

Rendering configs for service (test-deploy-zookeeper)...
Writing deploy config to (.vela/deploy.yaml)

Applying application ...
Checking if app has been deployed...
App exists, updating existing deployment...
✅ App has been deployed 🚀🚀🚀
    Port forward: vela port-forward mpserver-deploy-kafka
             SSH: vela exec mpserver-deploy-kafka
         Logging: vela logs mpserver-deploy-kafka
      App status: vela status mpserver-deploy-kafka
  Service status: vela status mpserver-deploy-kafka --svc test-deploy-kafka
  Service status: vela status mpserver-deploy-kafka --svc test-deploy-zookeeper
```

and we find it only `mpserver-deploy-kafka` is created and `test-deploy-zookeeper` is not exists:
```
$ kubectl get applications -nrcmd
NAMESPACE   NAME                    AGE
rcmd        mpserver-demo-01        14h
rcmd        mpserver-deploy-kafka   7m39s
```

**Expected behavior**

like this https://kubevela.io/#/en/developers/learn-appfile , it can create multi app services

**Screenshots**

![image](https://user-images.githubusercontent.com/7250620/108580474-934baa00-7366-11eb-82be-f07dbce86d10.png)

**Cluster information**

vela versions
```bash
$ vela version
Version: refs/tags/v0.3.2
GitRevision: git-18f184d
GolangVersion: go1.14.14
```

k8s
```bash
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-r0-CCE20.8.1.3.B001-17.36.5", GitCommit:"d61c11191a704802f93e5d86877a8fcffe208d58", GitTreeState:"clean", BuildDate:"2020-10-16T09:38:58Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
