### ISSUE TITLE
[Feature] KubeVela control plane mode

### ISSUE THREAD

**Issue by resouer** [oam-dev/kubevela#1086]
**Is your feature request related to a problem? Please describe.**

Recently, based on the discussion around multi-cluster and GitOps (ref https://github.com/oam-dev/kubevela/issues/1048), there's a strong community request for using KubeVela both in control plane (handling env, cluster, multi-env deployment etc) and runtime clusters (modeling app, performing day 2 operation etc).

**Describe the solution you'd like**

Thus, we should enable KubeVela to be used as control plane component and set this as goal for v1.0, or v1.1. The control plane (as designed) will use VelaCP as the main user interface, it will use KubeVela control plane mode to reconcile status of runtime clusters:

```
velacp --> apiserver --> control plane k8s (w/ kubevela in control plane mode) <-- reconcile --> runtime clusters (w/ kubevela)
```

There are already on-going effort drops in scope of KubeVela control plane mode:

1. Multi-env app deployment design: https://github.com/oam-dev/kubevela/issues/1048 /cc @LeoLiuYan
2. `Enviroment` CRD (and with modeling clusters in comments) https://github.com/oam-dev/kubevela/issues/176 /cc @Cweiping

Some missing parts:
1. Promotion: how to promote a app from staging to production
2. Pipeline: how to define a CD pipeline for the whole process (NOT a CI pipeline)

User Interface:

- [velacp](https://github.com/oam-dev/velacp) currently PoC a bit on UI + MongoDB, this will continue with KubeVela control plane.

/cc @wonderflow @ryanzhang-oss 

The existing dashboard effort should continue @zzxwill , we will migrate it to velacp when it's usable (target: mid of 2021).

**Describe alternatives you've considered**

**Additional context**

**Comment by wonderflow** [comment]
Yes, I totally agree with this idea, and the env section in Application(control plane mode) should be named to `binding`

```
apiVersion: core.oam.dev/v1alpha2
kind: Application
metadata:
  name: sample
spec:
  components:
    - name: instance
      type: webservice
      settings:
        cmd:
          - sleep 100
      traits:
        - name: ingress
    - name: database
      type: mysql
  binding: 
    envName: project-1
    traits:
    - solutionRef: ingress-v1 
       properties:
         hostname: xxx.test

```

**Comment by resouer** [comment]
Some other thoughts:

1. We use `Application` CRD as the envelop to carry app from control plane cluster to runtime clusters, so this CRD must carry destination information and control plane should handle it.
2. The main difference of `Application` CRD vs. Helm chart etc is it can carry cloud resources and other non-k8s resources (powered by component model, and enable you to do (3) and (4).
3. We have no opinion on how user templating/overlay the `Application` CR in control plane. They can use whatever they like (Helm, Kustomize, DSL) to generate a `Application` CR (w/ destination information).
4. We out-of-box supports using `Application` CRD itself to template and generate a `Application` CR (i.e. app-for-app pattern). In this case, we use CUE as the templating tool which can enable some advanced features like `patch`.

**Comment by hongchaodeng** [comment]
Here are some of the updates that I have been discussing offline with a couple of folks.
Let me share the latest update and summarize the plan here.

Updates:
- We have decided that velacp will implement the four major concepts, i.e. Applications, Environments, Clusters, Catalogs, as CRDs and controllers. 
- The UI remain the same, the GRPC server will still serve the APIs, but the major logic will be put into control cycles.

Plans:
- For the next step, the Application, Environment, Cluster CRDs will be implemented first.
- The env-based patch for Application config will be implemented as in [this doc](https://github.com/oam-dev/velacp/blob/main/docs/environment.md)
```yaml
name: example-app
env: staging | prod
components:
- name: backend
  settings:
    cmd:
      - /bin/myservice
  traits:
    - name: logging
      properties:
        rotate: 1d
patch: # strategic merge patch to the components based on env
  - env: staging
    components:
      - name: backend
        settings:
          image: staging/myimage
        traits:
          - name: autoscaling
            properties:
              max: 1
  - env: prod
    components:
      - name: backend
        settings:
          image: production/myimage
        traits:
          - name: autoscaling
            properties:
              min: 1
              max: 10
```
- For now I will implement the code in velacp as quickly as possible. But the controller code will eventually merge with KubeVela once the requirements are verified. This includes:
  - The API types will be added into pkg/apis/velacp.oam.dev
  - The controller will be added to pkg/controller/velacp.oam.dev
  - The controller will be registered into ctrl-manager at startup.
  - Add e2e tests and code coverage to satisfy production requirements.
