### ISSUE TITLE
webserver workloaddefinition not work

### ISSUE THREAD

**Issue by kinnylee** [oam-dev/kubevela#1116]
**Describe the bug**
kubevela engine can not render application to applicationconfiguration when appfile has a webserver workload.

**To Reproduce**
1. Go to 'https://kubevela.io/#/en/cue/workload-type?id=composition'
2. Save the WorkloadDefinition with type webserver to file workload-definition-webserver.yaml
```yaml
apiVersion: core.oam.dev/v1alpha2
kind: WorkloadDefinition
metadata:
  name: webserver
  annotations:
    definition.oam.dev/description: "webserver is a combo of Deployment + Service"
spec:
  definitionRef:
    name: deployments.apps
  extension:
    template: |
      output: {
          apiVersion: "apps/v1"
          kind:       "Deployment"
          spec: {
              selector: matchLabels: {
                  "app.oam.dev/component": context.name
              }
              template: {
                  metadata: labels: {
                      "app.oam.dev/component": context.name
                  }
                  spec: {
                      containers: [{
                          name:  context.name
                          image: parameter.image
      
                          if parameter["cmd"] != _|_ {
                              command: parameter.cmd
                          }
      
                          if parameter["env"] != _|_ {
                              env: parameter.env
                          }
      
                          if context["config"] != _|_ {
                              env: context.config
                          }
      
                          ports: [{
                              containerPort: parameter.port
                          }]
      
                          if parameter["cpu"] != _|_ {
                              resources: {
                                  limits:
                                      cpu: parameter.cpu
                                  requests:
                                      cpu: parameter.cpu
                              }
                          }
                      }]
                  }
              }
          }
      }
      // an extra template
      outputs: service: {
          apiVersion: "v1"
          kind:       "Service"
          spec: {
              selector: {
                  "app.oam.dev/component": context.name
              }
              ports: [
                  {
                      port:       parameter.port
                      targetPort: parameter.port
                  },
              ]
          }
      }
      parameter: {
          image: string
          cmd?: [...string]
          port: *80 | int
          env?: [...{
              name:   string
              value?: string
              valueFrom?: {
                  secretKeyRef: {
                      name: string
                      key:  string
                  }
              }
          }]
          cpu?: string
      }
```
3. Run `kubectl apply -f workload-definition-webserver.yaml`
4. Run `vela workloads` show the webserver that we has registed
5. Add vela.yaml file, content is:
```yaml
name: bookinfo
services:
  productpage:
    type: webserver
    image: docker.io/istio/examples-bookinfo-productpage-v1:1.16.2
    port: 9080
  details:
    type: webserver
    image: docker.io/istio/examples-bookinfo-details-v1:1.16.2
    port: 9080
  ratings:
    type: webserver
    image: docker.io/istio/examples-bookinfo-ratings-v1:1.16.2
    port: 9080
  reviews:
    type: webserver
    image: docker.io/istio/examples-bookinfo-reviews-v1:1.16.2
    port: 9080
```
6. Run `vela up -f vela.yaml`
7. Run `vela ls`, see show nothing; `kubectl get application.core.oam.dev -A` show successfully, but `kubectl get applicationconfiguration.core.oam.dev -A` also show nothing

**Expected behavior**
- `vela ls` can show the app info
- `kubectl get applicationconfiguration` can show app config info

**Screenshots**
![image](https://user-images.githubusercontent.com/10666512/109474147-2a270d80-7aaf-11eb-87da-3f9ceee3b0e4.png)
![image](https://user-images.githubusercontent.com/10666512/109474262-4c209000-7aaf-11eb-8ef0-8f8900821cd4.png)
![image](https://user-images.githubusercontent.com/10666512/109475064-36f83100-7ab0-11eb-8ebc-63bc156ba643.png)

**Cluster information**
[root@middleware-1810-02 bookinfo]# kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.6", GitCommit:"fbf646b339dc52336b55d8ec85c181981b86331a", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:30Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.6", GitCommit:"fbf646b339dc52336b55d8ec85c181981b86331a", GitTreeState:"clean", BuildDate:"2020-12-18T12:01:36Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

[root@middleware-1810-02 bookinfo]# vela version
Version: refs/tags/v0.3.2
GitRevision: git-18f184d
GolangVersion: go1.14.14

**Additional context**
