### ISSUE TITLE
How to model a native istio application using OAM (kubevela) ?

### ISSUE THREAD

**Issue by ghostbody** [oam-dev/kubevela#1122]
RT

Suppose we have a istio application. How can I turn istio's Gateway, VirtualService, DestinationRule, ServiceEntry and etc into a OAM Application Model using kubevela?

For example, we need to model the "demo app" of istio named "bookinfo" using kubevela, how can I get it work?

https://istio.io/latest/docs/examples/bookinfo/

- Is istio Gateway a trait or a component?
- Is VirtualService a trait or a component?

I feel quite confusing and can not get this application modeled.

**Comment by hongchaodeng** [comment]
Hi @ghostbody 

Thanks for your interest in raising such excellent question. Let me help you clarify it.

First of all, KubeVela can natively include all kinds of Kubernetes capabilities/resources into the platform per se. So it should be no problem to model Istio into KubeVela theoretically.

To take the bookinfo app for example, I think there is only one Component, which is the Deployment, and the Istio concepts like Gateway, VirtualService, etc. should be modeled as Traits. Moreover, I think the Istio itself could be modeled as single one trait, and all of the resources could be outputs by rendering pre-defined templates. 

------

To follow up on this issue, which is a good one, we should probably write some best practice docs on how to integrate with Istio or Dapr or anything such service platforms.

**Comment by ghostbody** [comment]
Thanks for your advice. But to be more specifically, as for the bookinfo app, it's a microservices app which is consists  of 4 microservices:

- productpage. The productpage microservice calls the details and reviews microservices to populate the page.
- details. The details microservice contains book information.
- reviews. The reviews microservice contains book reviews. It also calls the ratings microservice.
- ratings. The ratings microservice contains book ranking information that accompanies a book review.

The Service Mesh architecture is mostly like the picture below:

![image](https://user-images.githubusercontent.com/8371330/109755331-c91f4700-7c20-11eb-8a8d-6a89784c709d.png)


> To take the bookinfo app for example, I think there is only one Component

Is it a best practice to model 4 microservices of an application into one Component or 4 Compoonents？ 

I think thre maybe a appfile like this:

```yaml
name: testapp

services:
  productpage: # 1st service
    ...
    istio: # trait

  details:
     ...
    istio: # trait

   ratings:
     ...
    istio: # trait

   review:
     ...
    istio: # trait

```

> and the Istio concepts like Gateway, VirtualService, etc. should be modeled as Traits. Moreover, I think the Istio itself could be modeled as single one trait, and all of the resources could be outputs by rendering pre-defined templates.

Two more questions here:

1. In Istio practice, a Gatway is responsible for routing request to the service mesh at the boundry. In fact, **multiple services (or components in OAM) may share a common Gateway**. In other word, **an Trait instnace is likely to be attached by two or components** if the Istio Gatway is a kind of Trait ( or a part of somehing like a istio Trait). It's likely we need something like "Appllication Level Trait Instance"
2. To define an Big Istio Trait seems very hard. To archive this, we have to design a schema to cover most of istio concepts, or we need to design a abstract layer between Istio Trait and Istio itself. Moreover, it maybe more diffcult to manage the istio k8s-resources from the OAM perspective itself as I considered.

**Comment by resouer** [comment]
@ghostbody Please check the [bookinfo example](https://github.com/oam-dev/catalog/tree/master/applications/istio/bookinfo) which is based on OAM spec v0.2.1 release. You can see how `VirtualService` is defined as Trait and `Gateway` defined as [ApplicationScope](https://github.com/oam-dev/spec/blob/v0.2.1/5.application_scopes.md) etc.

But, above sample does NOT work in KubeVela (at least for now). This is partially because we tend to avoid modeling application blindly like that, it brings very limited value to users except proving that OAM can "model" everything. Instead, we hope to work out useful traits, for example, `Canary` or `Rollout` based on Istio - this is a better way to enable service mesh in your platform.

Btw, have you ever tried to use Helm chart to package Bookinfo and use it to produce workable k8s resources? If yes, we are eager to see your example because Helm support in KubeVela is almost there.

**Comment by chace20** [comment]
@resouer Thank you for you answer. Still something to be discuss.

Is Trait only support operation on single component? If [Trait](https://github.com/oam-dev/spec/blob/master/6.traits.md) represents "application operation", operator may not only take action on single component, but operating **multi-components configuration** even  **application level configuration**. In current OAM [Application](https://github.com/oam-dev/spec/blob/master/7.application_configuration.md) definition, a component can tied with multi-traits, but trait can only apply to single component. 

Is any plan to improve that in future?

**Comment by ghostbody** [comment]
@chace20 I have the same confusion as you.

**Comment by ghostbody** [comment]
@resouer The hlem chart idea is a decent one, I am going to have a try.

**Comment by resouer** [comment]
@chace20 @ghostbody As clarified in OAM spec, traits attach operational behavior to **component**, not application. And for application level behavior, the `Application Scope` is the correct concept.

> Is any plan to improve that in future?

Yes, considering most use case of `Application Scope` is more like `Application Level Trait`, we are seriously discussing having a new concept, see https://github.com/oam-dev/spec/issues/247.

In KubeVela, the `Rollout` capability is definitely a "global trait", but we haven't find out a proper spec level name for it, so this is how it looks like today:

```yaml
apiVersion: core.oam.dev/v1alpha2
kind: Application
metadata:
  name: nginx-deployment
spec:
  components:
    - name: frontend
      type: webservice 
      ...
  rollout:
    - componentRef: frontend
       rolloutPlan:
         ... # cool canary rollout spec
```

I am thinking about sth like:

```yaml
apiVersion: core.oam.dev/v1alpha2
kind: Application
metadata:
  name: myapp
spec:
  components:
    - name: frontend
      type: webservice 
       ...
  strategies: # global traits
    - name: rollout
      properties:
        - componentRef: frontend
           rolloutPlan:
             ... # cool canary rollout spec
```

Feel free to propose your idea and we will definitely consider it (naming is hard).
