### ISSUE TITLE
A story of Provision and Consume more Cloud Resources

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela#1128]
# Background

KubeVela can compose an appliction with cloud resource and K8s workload, currently the cloud resources supported in kubevela story is a bit less. KubeVela need cloud resources have a K8s controller to provision and it is now provided by crossplane alibaba-provider which only support `mongodb`.

According to the community feedback, we need to support more cloud resources working with kubevela.
The priority of cloud resources needed may be: `SLS` > `OSS` > `VPC` >`Redis` > `SLB` > `RDS(mysql)` > `DRDS` > `MongoDB` > `ACR` > `SMS` > `EDAS` > `ACM` >`ECS` > `RoketMQ` > `SCHEDULER_X`...

* **The first issue here is that we need to provision more types cloud resources.**
* **Besides the resource provision, we also need a standard way to consume the cloud resources.**

# Provision more Cloud Resources

There are some optional solutions to provision cloud resources:

1. Write/Use a terraform K8s controller which run `terraform cli` inside the controller. We can write a controller from scratch or consider these candidates: https://github.com/rancher/terraform-controller  https://github.com/isaaguilar/terraform-operator . If writing a new one, we need to implement at least these features:
   - Run a K8s job for every resource provision request and gather the results. We must not block the main reconcile logic.
   - Keep the terraform state of the cloud resources, store in configmap or somewhere reliable.
   - A terraform HCL contain full information should be embeded inside the terraform controller CRD, it needed to be clearly understood and see.
   - The lifecycle Management of Cloud resources should be supported align with the CR, once the CR deleted/updated, the resources should be deleted/updated.
   - Create a K8s secret after the cloud resources are provisioned.

2. Extend Crossplane [Alibaba-provider](https://github.com/crossplane/provider-alibaba), there are two options:
  - Write controller one by one.
  - Generate Controller from API/Code just like the https://github.com/crossplane/provider-aws

# Consume the resources provided

To consume the resources in Application, we need to define the binding process from the data provider and the consumer.

For the data provider, let's add a context variable called `outputSecretSchema`(the name is open for discuss) in workloadDefinition. The `outputSecretSchema` defines the name of the secret that the underlying cloud resource provider will create.

Assuming we're using crossplane(it's the same for terraform controller if we implement), the workflow will be as follows.

Once the cloud resources created successfully, the crossplane will create a secret, assuming the data is:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: secret-sample
type: <workload-type> // we can mark the type to `my-db` which point to the workloadDefinition name if the controller is implemented in OAM/KubeVela ecosystem.
data:
  dbName: "mydb"
  password: "my-password"
```

The workloadDefinition should define like this:

```yaml
kind: WorkloadDefinition
metadata:
  name: rds
spec:
  schematic:
    cue:
       template: |
          parameter:
             region: string
             version: string
          outputs:
            apiVersion: database.aws.crossplane.io/v1beta1
            kind: RDSInstance
            spec:
              forProvider:
                region: parameter.region
                engine: postgres
                engineVersion: parameter.version
              writeConnectionSecretToRef:
                namespace: context.namespace
                name: context.outputSecretName
```

Along with the `context.outputSecretSchema` , we need to add a **keyword** `outputSecretName` implicitly into parameter.

Application can use the workload like this:

```yaml
apiVersion: core.oam.dev/v1alpha2
kind: Application
metadata:
  name: data-provision
spec:
  components:
    - name: mydb
      type: rds
      settings:
        region: "us-east-1"
        version: "1.9.0"
        outputSecretName: "mydb-outputs"
```

The `outputSecretName` in component settings is not defined in template.parameters, it's a implicit parameter defined by kubevela system which will pass into the `context.outputSecretName`.

For the secret consumer, we need to define the schema it wants to consume, mostly for data validation.

```yaml
kind: WorkloadDefinition
metadata:
  name: webserver
spec:
  schematic:
    cue:
       template: |
          parameter:
             image: string
             //+k8sSecretSchema=mydata 
             mysecret: string
          mydata: {
             dbName:  string
             password: string
          }
          outputs:
            kind: MyWorkload
            spec:
              image: parameter.image
              password: context.mydata.password
```

The key point is the annotation `//+k8sSecretSchema=mydata`, then the KubeVela engine will know the parameter is a K8s secret which follows the schema mydata. The engine will read the secret and pass it into the context.

```
apiVersion: core.oam.dev/v1alpha2
kind: Application
metadata:
  name: data-consumer
spec:
  components:
    - name: myweb
      type: webserver
      settings:
        image: "nginx"
        mysecret: "mydb-outputs"
```

# Dependency

This issue will not include the Dependency discussed here https://github.com/oam-dev/kubevela/issues/873.

I assume the cloud resource provider and consumer are two apps.

**Comment by LeoLiuYan** [comment]
Hi, @wonderflow 

In my point of view, to implement a terraform controller there be some tough problems to solve:

1. A controller is reconciling `desire status` and `final status`, but a terraform controller use  kubernetes job to avoid block the reconcile process. So how could terraform controller known the status of cloud resource? For example, if a `RDS` is down, how could the terraform controller know?
2. How could we get `RDS` or `Redis` resource use kubectl command?  For example, when we create a application with a component named test which type is webservice, we could use `kubectl get webservice` to get all webservice resources.

But if use the solution of extending Crossplane's Alibaba-provider, it's not general for other cloud provides. 😁

**Comment by ryanzhang-oss** [comment]
> * The lifecycle Management of Cloud resources should be supported align with the CR, once the CR deleted/updated, the resources should be deleted/updated.

We need to be careful about deleting resources, they can be shared between applications or even users (90% of the time)

**Comment by ryanzhang-oss** [comment]
> But if use the solution of extending Crossplane's Alibaba-provider, it's not friendly for other cloud providers. 😁

I wonder why is the Crossplane's provider mechanism not friendly for other cloud providesr?

**Comment by ryanzhang-oss** [comment]
> 1. A controller is reconciling `desire status` and `final status`, but a terraform controller use  kubernetes job to avoid block the reconcile process. So how could terraform controller known the status of cloud resource? For example, if a `RDS` is down, how could the terraform controller know?

I think the Terraform controller will have to reconcile (by creating a job) periodically to check the state of the resources and store it in a configMap or a custom CR.

**Comment by ryanzhang-oss** [comment]
> The key point is the annotation `//+k8sSecretSchema=mydata`, then the KubeVela engine will know the parameter is a K8s secret which follows the schema mydata. The engine will read the secret and pass it into the context.

I am not sure why the consuming workloadDefinition needs to declare the schema of the secret instead of the resource provider.  Isn't it the provider's responsibility to announce the secrete schema?

**Comment by wonderflow** [comment]
> Isn't it the provider's responsibility to announce the secrete schema?

Yes, it is. But the consumer also need to declare the schema that they can consume.

**Comment by LeoLiuYan** [comment]
> > But if use the solution of extending Crossplane's Alibaba-provider, it's not friendly for other cloud providers. 😁
> 
> I wonder why is the Crossplane's provider mechanism not friendly for other cloud providesr?

You lost the word `Alibaba-provider`.  I mean just extend Crossplane's Alibaba-provider is not meet the needs of other cloud providers to create resources.

**Comment by 0902horn** [comment]
apiVersion: core.oam.dev/v1alpha2
kind: Application
metadata:
  name: data-consumer
spec:
  components:
    - name: myweb
      type: webserver
      settings:
        image: "nginx"
        mysecret:
          secretName: "mydb-outputs"
          keyMapping:
          - username: user
            password: password


It is a great idea to inject credentials into workloads by leveraging k8s secrets! And I think using this feature in traits is also a strong need. However, declaring the secret schema in workload definition make it not so generalized as I expected.

There are 3 roles in this use case:
- The secret provider, e.g. crossplane
- The secret consumer, e.g. workload definition/trait definition 
- The KubeVela Applicaiton

A secret provider would never know a consumer's idea about how to name each key, and it should never do it.

A generalized consumer should use a secret in a constantly way, no matter which provider it comes from.

A KubeVela Application should work as a shim to fit both secrets provider and consumer.

After a hard thinking, I think we might make it better if extend the original design a little more.

Assume we have a secret like this (no matter who creat it):

```
apiVersion: v1
kind: Secret
metadata:
  name: rds-secret-sample
type: Opaque
data:
  username: "mydbuser"
  password: "mypassword"
```


The consumer uses the secret in a way it likes:

```
kind: WorkloadDefinition
metadata:
  name: webserver
spec:
  schematic:
    cue:
      template: |
        parameter:
          image: string
          mysecret: {
            name: 
            data: {
              dbUsername: {
                key: string
                value: string
              }
              dbPassword: {
                key: string
                value: string
              }
            }
          }
        outputs:
          kind: MyWorkload
          spec:
            image: parameter.image
            args:
            - password=context.mysecret.data.dbPassword.value
            env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef: 
                  name: mysecret.name
                  key: context.mysecret.data.dbUsername.key
```


We could map key names via settings of the component in Application like this:

```
apiVersion: core.oam.dev/v1alpha2
kind: Application
metadata:
  name: data-consumer
spec:
  components:
    - name: myweb
      type: webserver
      settings:
        image: "nginx"
        mysecret:
          name: "rds-secret-sample"
          data:
            dbUsername:
              key: username
            dbPassword:
              key: password
```

Well, this may not look like a perfect solution, but seems work nicer in this use case. Comments are welcome.

**Comment by wonderflow** [comment]
After discussed with @0902horn  offline, I have understand that we wants a way to do secret schema convert when the secret provider and consumer has the different schema.

So we can write a secret/configmap converter trait(with a CRD controller) to do the converting/mapping.

The converter trait will work for this case as long as the following rules exist:

1. secret provided by the cloud resources has immutable schema. If the schema changed, the application need to update.
2. secret was created outside from the application, so the secret is always ready when the application deployed. Currently, the application controller won't handle the complexity DAG for both provider and consumer in the same Application.
3. users can specify the new created secret name with the converter trait.

A working example could be:

```
apiVersion: core.oam.dev/v1alpha2
kind: Application
metadata:
  name: data-consumer
spec:
  components:
    - name: myweb
      type: webserver
      settings:
        image: "nginx"
        mysecret: "mydb-outputs-converted1"
      traits:
      - name: oss-trait
        settings:
          mysecret: "mydb-outputs-converted2"
      - name: key-mapping-trait
        settings:
        - secretName: "mydb-outputs"
          outputSecret: "mydb-outputs-converted1"
          keyMapping:
            ossUsername: username
            ossPassword: password
        - secretName: "mydb-outputs"
          outputSecret: "mydb-outputs-converted2"
          keyMapping:
            ossUsername: username1
            ossPassword: password2
```

**Comment by wonderflow** [comment]
We have supported design in this issue: https://kubevela.io/docs/platform-engineers/cloud-services .

As there're still many discussions here, I'll keep the issue open and leave it to the next milestone.

**Comment by zzxwill** [comment]
Here are some items we need to consider on improvising the current design of cloud resource provisioning and consuming https://kubevela.io/docs/platform-engineers/cloud-services in upcoming releases.

# Limitations

- The namespace of a cloud resource provisioning application has to be the same as that of the consuming one

KubeVela 1.0 doesn't support cross-namespace cloud resource secret consuming.

- Users have to be careful not generate a same secret name by two same or different cloud resources

KubeVela 1.0 doesn't support validate whether two same secrets (namespace + name) are used all over the cluster.

- When provisioning and consuming a cloud resource in a same application, using a secret value isn't supported.

KubeVela 1.0 doesn't support using a value of a secret's item due to the issue https://github.com/oam-dev/kubevela/issues/1350

# Cloud resources provisioning

## How to expose the secret and its items?

- Crossplane: Expose the secret name and namespace in `writeConnectionSecretToRef`

```yaml
apiVersion: "database.alibaba.crossplane.io/v1alpha1"
kind:       "RDSInstance"
spec: {
  writeConnectionSecretToRef: {
  namespace: context.namespace
  name:      context.outputSecretName
  }
  }
```

- Terraform: Expose the key-value items in output

```yaml

{
  "resource": {
    ...
  },
  "output": {
    "BUCKET_NAME": {
      "value": "${alicloud_oss_bucket.bucket-acl.bucket}.${alicloud_oss_bucket.bucket-acl.extranet_endpoint}"
    }
  },
  "variable": {
    ...
  }
}

```

- KubeVela 1.0

Both of Crossplane and Terraform provided a unified way for cloud resrouce exposing.

Currently KubeVela expose the secret name in `spec.*.properties.outputSecretName`, but actually it's not an item of parameter of ComponentDefinition.

```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: webapp
spec:
    - name: sample-db
      type: alibaba-rds
      properties:
        ...
        username: oamtest
        outputSecretName: db-conn
```

Platform team needs to use `context.outputSecretName` as the secret reference.

```yaml
apiVersion: "database.alibaba.crossplane.io/v1alpha1"
kind:       "RDSInstance"
spec: {
  ...
  writeConnectionSecretToRef: {
  namespace: context.namespace
  name:      context.outputSecretName
  }
  ...
}
```

We are going to replace `outputSecretName` with a user-defined secret name like `secretName`, `secret` and so on. Then in ComponentDefinition, it's convenient to use `parameter.secretName`, `parameter.secret` can refer to the key. In this design, application developer has to be tell what's the secret name of the cloud resource or they won't know by `secretName`, `secret`, `xxx` which is not a fixed property.


```yaml
schematic:
cue:
  template: |
    output: {
        apiVersion: "database.alibaba.crossplane.io/v1alpha1"
        kind:       "RDSInstance"
        spec: {
            forProvider: {
                engine:                parameter.engine
                engineVersion:         parameter.engineVersion
                dbInstanceClass:       parameter.instanceClass
                dbInstanceStorageInGB: 20
                securityIPList:        "0.0.0.0/0"
                masterUsername:        parameter.username
            }
            writeConnectionSecretToRef: {
                namespace: context.namespace
                name:      parameter.secretName
            }
            providerConfigRef: {
                name: "default"
            }
            deletionPolicy: "Delete"
        }
    }
    parameter: {
        engine:          *"mysql" | string
        engineVersion:   *"8.0" | string
        instanceClass:   *"rds.mysql.c1.large" | string
        username:        string
        secretName: string
    }
```

## How to consume cloud resources?


### Referebces

- [Service broker resource connection mapping](https://kubernetes.io/docs/concepts/extend-kubernetes/service-catalog/#mapping-the-connection-credentials)


- [service binding spec](https://github.com/k8s-service-bindings/spec#service-binding)



- [docker swarm](https://docs.docker.com/engine/swarm/secrets/#use-secrets-in-compose)


It assumes the number of environments, and all names of environments are the same as all items of a secret, which is ideal beyond the production experiences.

```yaml
wordpress:
 depends_on:
   - db
 image: wordpress:latest
 ports:
   - "8000:80"
 environment:
   WORDPRESS_DB_HOST: db:3306
   WORDPRESS_DB_USER: wordpress
   WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
 secrets:
   - db_password

```


- [VMWare service bindings](https://github.com/vmware-labs/service-bindings)



- [azure-service-operator](https://github.com/Azure/azure-service-operator/blob/master/docs/howto/resourceprovision.md)
