### ISSUE TITLE
[Feature] ApplicationDeployment CRD to support application level rollout, traffic, and multi-cluster strategies

### ISSUE THREAD

**Issue by hongchaodeng** [oam-dev/kubevela#1144]
# Background

Currently Vela supports Application CRD which templates the low level resources and exposes high level parameters to users. But that's not enough. It requires a couple of standard techniques to deploy an application in production:

1. **Rolling upgrade** (aka rollout): To continuously deploy apps requires to rollout in a safe manner which usually involves step by step rollout batches and analysis.
2. **Traffic shifting**: When rolling upgrade an app, it needs to split the traffic onto both the old and new revisions to verify the new version while preserving service availability.
3. **Multi-cluster**: Modern application infrastructure involves multiple clusters to ensure high availability and maximize service throughput.

# Proposal

This issue proposes to add a new ApplicationDeployment CRD to achieve to satisfy the above requirements.

```yaml
kind: ApplicationDeployment
name: example-app
spec:
  trafficRules:
    - trafficType: http
      weightedTargets:
        - revisionName: 1
          percent: 50
        - revisionName: 2
          percent: 50
    - trafficType: event
      ...

  appRevisions:
    - # The name must be number so that we can differentiate the old and new
      # and specify them in rollout plan 
      name: 1
      services:
        http:
          domain: example-app-v1.aliyun.com
        event:
          ...
      template: # The template of Application CR
        spec:
          components:
          - name: backend
            type: worker
            settings:
              image: myimage-v1
              cmd: ...
            traits:
              - name: autoscaler
                properties:
                  min: 1
                  max: 10
    - name: 2
      services:
        http:
          domain: example-app-v2.aliyun.com
        event:
          ...
      template: # The template of Application CR
        spec:
          components:
          - name: backend
            type: worker
            settings:
              image: myimage-v2
              cmd: ...
            traits:
              - name: autoscaler
                properties:
                  min: 1
                  max: 10

  clusterStrategies:
    - labelSelector:
        usage: production

      # options:
      #   alone: deploy all revisions to only one of the clusters
      #   twin: deploy all revisions to two of the clusters to achieve HA
      #   all: deploy all revisions to all of the clusters to achieve maximum HA
      deployMode: "all"

```

In above proposal, the `clusterStrategies` part requires a Cluster CRD that we are proposing here too:

```yaml
kind: Cluster
metadata:
  labels:
    usage: production
spec:
  kubeconfig: ...
```

# Technical details

TODO

# Considerations

**Comment by resouer** [comment]
Consider `clusterStrategies` -> `placementStrategies`

**Comment by resouer** [comment]
The `service` seems to be `publish` or `gateway`? I assume it's an app level APIGateway.

For placement, it could be evolved with cluster level rollout strategy in the future, [for example this one](https://github.com/maruina/argocd-progressive-rollout-controller).

**Comment by hongchaodeng** [comment]
@resouer 

> The service seems to be publish or gateway? I assume it's an app level APIGateway.

It's per app config for service routing. For example, in Istio we could use it to infer part of the DestinationRule fields.
It is not gateway anyway which is a global concept.

> For placement, it could be evolved with cluster level rollout strategy in the future, for example this one.

Sure. I will keep that in `Considerations` too.

**Comment by hongchaodeng** [comment]
@resouer 

I also take a look into the the multi-stage rollout in [this example](https://github.com/maruina/argocd-progressive-rollout-controller). I think the problem with this style of rollout in spec is that it will automatically rollout to everywhere eventually. The better way to handle it is to have a UI to let users interactively choose and push the trigger of rollout.

**Comment by ryanzhang-oss** [comment]
Synced with @hongchaodeng offline and here is some high-level clarifications

1. This issue is mostly about user-facing API design, not the implementation 
2. The applicationDepolyment object is here for users to declare their end goals with multiple versions of an application. 
3. There will be a translation from the multi-version appDeploy to multiple two version appRollouts as the path way to achieve the multiple version rollout
4. appRollout will use another internal appDeploy, which is not to be confused with the CRD here,  like object to be the executor of the rollout plan.
5. Changing traffic patterns along with replicas is mostly not Okay in a production environment as it will inevitably lead to various performance degradations. We need to verify that with Gaia.

**Comment by wonderflow** [comment]
Can you add a example about how multiple cluster deploy strategy was used?

**Comment by resouer** [comment]
> Changing traffic patterns along with replicas is mostly not Okay in a production environment as it will inevitably lead to various performance degradations. We need to verify that with Gaia.

@ryanzhang-oss Not sure how Flagger handle this? Is it asking user to choose between Istio traffic shifting vs. HPA adjusting instances? I am also a bit concerned that we configure them at same time.

@wonderflow @hongchaodeng Some issues unclear to me:

1. What's the relationship with [Environment-Based Config Patch](https://github.com/oam-dev/velacp/blob/main/docs/env_based_patch.md)?
2. What's the tradeoff of defining `service` as a trait (as it's an ingress and will be versioned) vs. per revision configuration?

For better UX, I'd propose merge revision configuration with traffic rules, this will also give better clarity:

```yaml
kind: ApplicationDeployment
name: example-deployment
spec:
  application: 
    apiVersion: core.oam.dev/v1alpha2
    kind: Application
    name: example-app
          
  traffic:
    revisions:
      - name: 1
        ref: example-app-v1
        service:
          http:
            host: example-app-v1.aliyun.com # can this be a trait? 
            tls:
              mode: mutual
      - name: 2
        ref: example-app-v2
        service:
          http:
            host: example-app-v2.aliyun.com
   rules:
    - component: web
      match:
        - uri:
            prefix: "/web"
      weightedTargets:
        - revisionName: 1
          percent: 50
        - revisionName: 2
          percent: 50

  placement:
    - clusterSelector:
        labels:
          usage: production
      deployMode: "twin"
```
```
