### ISSUE TITLE
vela-core cannot start when use istio sidecar inject

### ISSUE THREAD

**Issue by shikanon** [oam-dev/kubevela#1145]
**Describe the bug**

I want to install vela into namespace which pod will be inject istio-sidecar. I find pod cann't running. I found this port name of `healthz` is full the istio port and not 9440.

the `vela-core` deployment from helm chart is:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vela-core
  namespace: default
  labels:
    helm.sh/chart: vela-core-0.1.0
    app.kubernetes.io/name: vela-core
    app.kubernetes.io/instance: vela-core
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vela-core
      app.kubernetes.io/instance: vela-core
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vela-core
        app.kubernetes.io/instance: vela-core
    spec:
      serviceAccountName: vela-core
      securityContext:
        {}
      containers:
        - name: vela-core
          securityContext:
            {}
          args:
            - "--metrics-addr=:8080"
            - "--enable-leader-election"
            
            - "--use-webhook=true"
            - "--webhook-port=9443"
            - "--webhook-cert-dir=/etc/k8s-webhook-certs"
            
            - "--health-addr=:9440"
            - "--apply-once-only=off"
            
            - "--disable-caps=all"
            
          image: oamdev/vela-core:latest
          imagePullPolicy: "IfNotPresent"
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 50m
              memory: 20Mi
          
          ports:
            - containerPort: 9443
              name: webhook-server
              protocol: TCP
            - containerPort: 9440
              name: healthz
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /readyz
              port: healthz
            initialDelaySeconds: 90
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 90
            periodSeconds: 5
          volumeMounts:
            - mountPath: /etc/k8s-webhook-certs
              name: tls-cert-vol
              readOnly: true
          
      
      volumes:
        - name: tls-cert-vol
          secret:
            defaultMode: 420
            secretName: vela-core-admission
```

when use `isitoctl kube-inject -f deployment.yaml` it will be:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: vela-core
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vela-core
    app.kubernetes.io/version: 0.1.0
    helm.sh/chart: vela-core-0.1.0
  name: vela-core
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: vela-core
      app.kubernetes.io/name: vela-core
  strategy: {}
  template:
    metadata:
      annotations:
        sidecar.istio.io/interceptionMode: REDIRECT
        sidecar.istio.io/status: '{"version":"7986efd232806f426313494de3718f08f6512622122fca9a2327297370a07e95","initContainers":["istio-init"],"containers":["istio-proxy"],"volumes":["istio-envoy","istio-data","istio-podinfo","istio-token","istiod-ca-cert"],"imagePullSecrets":null}'
        traffic.sidecar.istio.io/excludeInboundPorts: "15020"
        traffic.sidecar.istio.io/includeInboundPorts: 9443,9440
        traffic.sidecar.istio.io/includeOutboundIPRanges: '*'
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: vela-core
        app.kubernetes.io/name: vela-core
        istio.io/rev: ""
        security.istio.io/tlsMode: istio
    spec:
      containers:
      - args:
        - --metrics-addr=:8080
        - --enable-leader-election
        - --use-webhook=true
        - --webhook-port=9443
        - --webhook-cert-dir=/etc/k8s-webhook-certs
        - --health-addr=:9440
        - --apply-once-only=off
        - --disable-caps=all
        image: oamdev/vela-core:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /app-health/vela-core/livez
            port: 15020
          initialDelaySeconds: 90
          periodSeconds: 5
        name: vela-core
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        - containerPort: 9440
          name: healthz
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /app-health/vela-core/readyz
            port: 15020
          initialDelaySeconds: 90
          periodSeconds: 5
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 50m
            memory: 20Mi
        securityContext: {}
        volumeMounts:
        - mountPath: /etc/k8s-webhook-certs
          name: tls-cert-vol
          readOnly: true
      - args:
        - proxy
        - sidecar
        - --domain
        - $(POD_NAMESPACE).svc.cluster.local
        - --serviceCluster
        - vela-core.default
        - --proxyLogLevel=warning
        - --proxyComponentLogLevel=misc:error
        - --trust-domain=cluster.local
        - --concurrency
        - "2"
        env:
        - name: JWT_POLICY
          value: third-party-jwt
        - name: PILOT_CERT_PROVIDER
          value: istiod
        - name: CA_ADDR
          value: istiod.istio-system.svc:15012
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: INSTANCE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: CANONICAL_SERVICE
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['service.istio.io/canonical-name']
        - name: CANONICAL_REVISION
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['service.istio.io/canonical-revision']
        - name: PROXY_CONFIG
          value: |
            {"proxyMetadata":{"DNS_AGENT":""}}
        - name: ISTIO_META_POD_PORTS
          value: |-
            [
                {"name":"webhook-server","containerPort":9443,"protocol":"TCP"}
                ,{"name":"healthz","containerPort":9440,"protocol":"TCP"}
            ]
        - name: ISTIO_META_APP_CONTAINERS
          value: vela-core
        - name: ISTIO_META_CLUSTER_ID
          value: Kubernetes
        - name: ISTIO_META_INTERCEPTION_MODE
          value: REDIRECT
        - name: ISTIO_META_WORKLOAD_NAME
          value: vela-core
        - name: ISTIO_META_OWNER
          value: kubernetes://apis/apps/v1/namespaces/default/deployments/vela-core
        - name: ISTIO_META_MESH_ID
          value: cluster.local
        - name: DNS_AGENT
        - name: ISTIO_KUBE_APP_PROBERS
          value: '{"/app-health/vela-core/livez":{"httpGet":{"path":"/healthz","port":9440}},"/app-health/vela-core/readyz":{"httpGet":{"path":"/readyz","port":9440}}}'
        image: docker.io/istio/proxyv2:1.6.13
        imagePullPolicy: Always
        name: istio-proxy
        ports:
        - containerPort: 15090
          name: http-envoy-prom
          protocol: TCP
        readinessProbe:
          failureThreshold: 30
          httpGet:
            path: /healthz/ready
            port: 15021
          initialDelaySeconds: 1
          periodSeconds: 2
        resources:
          limits:
            cpu: "2"
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsGroup: 1337
          runAsNonRoot: true
          runAsUser: 1337
        volumeMounts:
        - mountPath: /var/run/secrets/istio
          name: istiod-ca-cert
        - mountPath: /var/lib/istio/data
          name: istio-data
        - mountPath: /etc/istio/proxy
          name: istio-envoy
        - mountPath: /var/run/secrets/tokens
          name: istio-token
        - mountPath: /etc/istio/pod
          name: istio-podinfo
      initContainers:
      - args:
        - istio-iptables
        - -p
        - "15001"
        - -z
        - "15006"
        - -u
        - "1337"
        - -m
        - REDIRECT
        - -i
        - '*'
        - -x
        - ""
        - -b
        - '*'
        - -d
        - 15090,15021,15020
        env:
        - name: DNS_AGENT
        image: docker.io/istio/proxyv2:1.6.13
        imagePullPolicy: Always
        name: istio-init
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 10Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsGroup: 0
          runAsNonRoot: false
          runAsUser: 0
      securityContext:
        fsGroup: 1337
      serviceAccountName: vela-core
      volumes:
      - name: tls-cert-vol
        secret:
          defaultMode: 420
          secretName: vela-core-admission
      - emptyDir:
          medium: Memory
        name: istio-envoy
      - emptyDir: {}
        name: istio-data
      - downwardAPI:
          items:
          - fieldRef:
              fieldPath: metadata.labels
            path: labels
          - fieldRef:
              fieldPath: metadata.annotations
            path: annotations
        name: istio-podinfo
      - name: istio-token
        projected:
          sources:
          - serviceAccountToken:
              audience: istio-ca
              expirationSeconds: 43200
              path: istio-token
      - configMap:
          name: istio-ca-root-cert
        name: istiod-ca-cert
status: {}
---
```

We can see the `vela-core` container port of livenessProbe and readnessProbe is be change `15020` instead of `9440`.

And when apply this injected deployment.yaml, the pod event logs like that:
```bash
Events:
  Type     Reason                 Age                    From               Message
  ----     ------                 ----                   ----               -------
  Normal   Scheduled              10m                    default-scheduler  Successfully assigned default/vela-core-7dd4c76799-qqp94 to 10.213.20.91
  Normal   Pulling                10m                    kubelet            Pulling image "docker.io/istio/proxyv2:1.6.13"
  Normal   Pulled                 10m                    kubelet            Successfully pulled image "docker.io/istio/proxyv2:1.6.13"
  Normal   SuccessfulCreate       10m                    kubelet            Created container istio-init
  Normal   Started                10m                    kubelet            Started container istio-init
  Normal   Pulling                10m                    kubelet            Pulling image "docker.io/istio/proxyv2:1.6.13"
  Normal   Started                9m59s                  kubelet            Started container istio-proxy
  Normal   SuccessfulMountVolume  9m59s (x2 over 10m)    kubelet            Successfully mounted volumes for pod "vela-core-7dd4c76799-qqp94_default(582695d4-bfc8-44af-8a0a-a41a18700dad)"
  Normal   Pulled                 9m59s (x2 over 10m)    kubelet            Container image "oamdev/vela-core:latest" already present on machine
  Normal   SuccessfulCreate       9m59s (x2 over 10m)    kubelet            Created container vela-core
  Normal   Pulled                 9m59s                  kubelet            Successfully pulled image "docker.io/istio/proxyv2:1.6.13"
  Normal   SuccessfulCreate       9m59s                  kubelet            Created container istio-proxy
  Normal   Started                9m58s (x2 over 10m)    kubelet            Started container vela-core
  Warning  BackOffStart           9m56s (x3 over 9m58s)  kubelet            Back-off restarting failed container
  Warning  Unhealthy              9m56s (x2 over 9m58s)  kubelet            Readiness probe failed: Get http://10.0.2.249:15021/healthz/ready: dial tcp 10.0.2.249:15021: connect: connection refused
  Normal   Healthy                9m54s                  kubelet            container docker://6cfb7656e1fae27e7b59efa363dbd9154e4e63dae365090b43ccaf881259d0d4 in health status
  Warning  BackOffStart           5m5s (x30 over 9m58s)  kubelet            the failed container exited with ExitCode: 2
```

**To Reproduce**
1. Go to `charts/`, use `helm template --dry-run vela-core vela-core/` get the  deployment of `vela-core`, copy it to the file `vela-core-deployment.yaml` 
2. Create a namespace which support istio auto-inject sidcar or Use `istioctl kube-inject -f vela-core-deployment.yaml` to manual inject
3. Apply it to the k8s cluster which installed istio

```bash
kubectl get pod -ndefault vela-core-7dd4c76799-qqp94
NAME                         READY   STATUS             RESTARTS   AGE
vela-core-7dd4c76799-qqp94   1/2     CrashLoopBackOff   8          17m
```

descirbe status:
```
Name:         vela-core-7dd4c76799-qqp94
Namespace:    default
Priority:     0
Node:         10.213.20.91/10.213.20.91
Start Time:   Fri, 05 Mar 2021 13:33:50 +0800
Labels:       app.kubernetes.io/instance=vela-core
              app.kubernetes.io/name=vela-core
              istio.io/rev=
              pod-template-hash=7dd4c76799
              security.istio.io/tlsMode=istio
Annotations:  k8s.v1.cni.cncf.io/network-status:
                [{
                    "name": "default-network",
                    "ips": [
                        "10.0.2.249"
                    ],
                    "default": true
                }]
              sidecar.istio.io/interceptionMode: REDIRECT
              sidecar.istio.io/status:
                {"version":"7986efd232806f426313494de3718f08f6512622122fca9a2327297370a07e95","initContainers":["istio-init"],"containers":["istio-proxy"]...
              traffic.sidecar.istio.io/excludeInboundPorts: 15020
              traffic.sidecar.istio.io/includeInboundPorts: 9443,9440
              traffic.sidecar.istio.io/includeOutboundIPRanges: *
Status:       Running
IP:           10.0.2.249
IPs:
  IP:           10.0.2.249
Controlled By:  ReplicaSet/vela-core-7dd4c76799
Init Containers:
  istio-init:
    Container ID:  docker://81c49cf06cdc5651ceee0cfa8d567a321d6beb170970a391ebd4453c7b83f320
    Image:         docker.io/istio/proxyv2:1.6.13
    Image ID:      docker-pullable://istio/proxyv2@sha256:8b00baa21ff88e2da5b4fdffdb5d11f6c9a788a70fdd89ad43896ff22755997f
    Port:          <none>
    Host Port:     <none>
    Args:
      istio-iptables
      -p
      15001
      -z
      15006
      -u
      1337
      -m
      REDIRECT
      -i
      *
      -x
      
      -b
      *
      -d
      15090,15021,15020
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Fri, 05 Mar 2021 13:33:53 +0800
      Finished:     Fri, 05 Mar 2021 13:33:55 +0800
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  50Mi
    Requests:
      cpu:     10m
      memory:  10Mi
    Environment:
      DNS_AGENT:  
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from vela-core-token-pfkq9 (ro)
Containers:
  vela-core:
    Container ID:  docker://0b0a64427c15bc313fce809f72a43bd3e591a2aa42dccbaebea14e16c1271a33
    Image:         oamdev/vela-core:latest
    Image ID:      docker-pullable://oamdev/vela-core@sha256:42e7a40a36f532630ed056ecdd157fc373465955ff38b71abe6cc1364aef1102
    Ports:         9443/TCP, 9440/TCP
    Host Ports:    0/TCP, 0/TCP
    Args:
      --metrics-addr=:8080
      --enable-leader-election
      --use-webhook=true
      --webhook-port=9443
      --webhook-cert-dir=/etc/k8s-webhook-certs
      --health-addr=:9440
      --apply-once-only=off
      --disable-caps=all
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Fri, 05 Mar 2021 13:39:47 +0800
      Finished:     Fri, 05 Mar 2021 13:39:47 +0800
    Ready:          False
    Restart Count:  6
    Limits:
      cpu:     500m
      memory:  1Gi
    Requests:
      cpu:        50m
      memory:     20Mi
    Liveness:     http-get http://:15020/app-health/vela-core/livez delay=90s timeout=1s period=5s #success=1 #failure=3
    Readiness:    http-get http://:15020/app-health/vela-core/readyz delay=90s timeout=1s period=5s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /etc/k8s-webhook-certs from tls-cert-vol (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from vela-core-token-pfkq9 (ro)
  istio-proxy:
    Container ID:  docker://6cfb7656e1fae27e7b59efa363dbd9154e4e63dae365090b43ccaf881259d0d4
    Image:         docker.io/istio/proxyv2:1.6.13
    Image ID:      docker-pullable://istio/proxyv2@sha256:8b00baa21ff88e2da5b4fdffdb5d11f6c9a788a70fdd89ad43896ff22755997f
    Port:          15090/TCP
    Host Port:     0/TCP
    Args:
      proxy
      sidecar
      --domain
      $(POD_NAMESPACE).svc.cluster.local
      --serviceCluster
      vela-core.default
      --proxyLogLevel=warning
      --proxyComponentLogLevel=misc:error
      --trust-domain=cluster.local
      --concurrency
      2
    State:          Running
      Started:      Fri, 05 Mar 2021 13:33:58 +0800
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     2
      memory:  1Gi
    Requests:
      cpu:      100m
      memory:   128Mi
    Readiness:  http-get http://:15021/healthz/ready delay=1s timeout=1s period=2s #success=1 #failure=30
    Environment:
      JWT_POLICY:                    third-party-jwt
      PILOT_CERT_PROVIDER:           istiod
      CA_ADDR:                       istiod.istio-system.svc:15012
      POD_NAME:                      vela-core-7dd4c76799-qqp94 (v1:metadata.name)
      POD_NAMESPACE:                 default (v1:metadata.namespace)
      INSTANCE_IP:                    (v1:status.podIP)
      SERVICE_ACCOUNT:                (v1:spec.serviceAccountName)
      HOST_IP:                        (v1:status.hostIP)
      CANONICAL_SERVICE:              (v1:metadata.labels['service.istio.io/canonical-name'])
      CANONICAL_REVISION:             (v1:metadata.labels['service.istio.io/canonical-revision'])
      PROXY_CONFIG:                  {"proxyMetadata":{"DNS_AGENT":""}}
                                     
      ISTIO_META_POD_PORTS:          [
                                         {"name":"webhook-server","containerPort":9443,"protocol":"TCP"}
                                         ,{"name":"healthz","containerPort":9440,"protocol":"TCP"}
                                     ]
      ISTIO_META_APP_CONTAINERS:     vela-core
      ISTIO_META_CLUSTER_ID:         Kubernetes
      ISTIO_META_INTERCEPTION_MODE:  REDIRECT
      ISTIO_META_WORKLOAD_NAME:      vela-core
      ISTIO_META_OWNER:              kubernetes://apis/apps/v1/namespaces/default/deployments/vela-core
      ISTIO_META_MESH_ID:            cluster.local
      DNS_AGENT:                     
      ISTIO_KUBE_APP_PROBERS:        {"/app-health/vela-core/livez":{"httpGet":{"path":"/healthz","port":9440}},"/app-health/vela-core/readyz":{"httpGet":{"path":"/readyz","port":9440}}}
    Mounts:
      /etc/istio/pod from istio-podinfo (rw)
      /etc/istio/proxy from istio-envoy (rw)
      /var/lib/istio/data from istio-data (rw)
      /var/run/secrets/istio from istiod-ca-cert (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from vela-core-token-pfkq9 (ro)
      /var/run/secrets/tokens from istio-token (rw)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  tls-cert-vol:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  vela-core-admission
    Optional:    false
  istio-envoy:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  istio-data:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  istio-podinfo:
    Type:  DownwardAPI (a volume populated by information about the pod)
    Items:
      metadata.labels -> labels
      metadata.annotations -> annotations
  istio-token:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  43200
  istiod-ca-cert:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      istio-ca-root-cert
    Optional:  false
  vela-core-token-pfkq9:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  vela-core-token-pfkq9
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason                 Age                    From               Message
  ----     ------                 ----                   ----               -------
  Normal   Scheduled              10m                    default-scheduler  Successfully assigned default/vela-core-7dd4c76799-qqp94 to 10.213.20.91
  Normal   Pulling                10m                    kubelet            Pulling image "docker.io/istio/proxyv2:1.6.13"
  Normal   Pulled                 10m                    kubelet            Successfully pulled image "docker.io/istio/proxyv2:1.6.13"
  Normal   SuccessfulCreate       10m                    kubelet            Created container istio-init
  Normal   Started                10m                    kubelet            Started container istio-init
  Normal   Pulling                10m                    kubelet            Pulling image "docker.io/istio/proxyv2:1.6.13"
  Normal   Started                9m59s                  kubelet            Started container istio-proxy
  Normal   SuccessfulMountVolume  9m59s (x2 over 10m)    kubelet            Successfully mounted volumes for pod "vela-core-7dd4c76799-qqp94_default(582695d4-bfc8-44af-8a0a-a41a18700dad)"
  Normal   Pulled                 9m59s (x2 over 10m)    kubelet            Container image "oamdev/vela-core:latest" already present on machine
  Normal   SuccessfulCreate       9m59s (x2 over 10m)    kubelet            Created container vela-core
  Normal   Pulled                 9m59s                  kubelet            Successfully pulled image "docker.io/istio/proxyv2:1.6.13"
  Normal   SuccessfulCreate       9m59s                  kubelet            Created container istio-proxy
  Normal   Started                9m58s (x2 over 10m)    kubelet            Started container vela-core
  Warning  BackOffStart           9m56s (x3 over 9m58s)  kubelet            Back-off restarting failed container
  Warning  Unhealthy              9m56s (x2 over 9m58s)  kubelet            Readiness probe failed: Get http://10.0.2.249:15021/healthz/ready: dial tcp 10.0.2.249:15021: connect: connection refused
  Normal   Healthy                9m54s                  kubelet            container docker://6cfb7656e1fae27e7b59efa363dbd9154e4e63dae365090b43ccaf881259d0d4 in health status
  Warning  BackOffStart           5m5s (x30 over 9m58s)  kubelet            the failed container exited with ExitCode: 2
```

**Expected behavior**

**Screenshots**

**Cluster information**

```bash
$ istioctl version
client version: 1.6.13
ingressgateway-external version:
pilot version: 1.6.13
data plane version: 1.6.13 (48 proxies)
```
vela git commitID: 570cf01949b4701623bba11c9f6e565480a7b407

**Additional context**
