### ISSUE TITLE
changing application results in multiple appConfig

### ISSUE THREAD

**Issue by captainroy-hy** [oam-dev/kubevela#1167]
**Describe the bug**

With the latest master branch. 
Each time modify an existing Application will trigger to create a new appConfig. And multiple appConfig exist simultaneously. 

**To Reproduce**
Apply below app. 
```yaml
apiVersion: core.oam.dev/v1alpha2
kind: Application
metadata:
  name: website
spec:
  components:
    - name: backend
      type: webservice
      settings:
        image: busybox
        cmd:
          - sleep
          - '1000'
      traits:
        - name: scaler
          properties:
            replicas: 2
```
Make any modifications and apply again. Repeat. Check the appConfig

```shell
kubectl get appconfig

NAME         AGE
website-v1   7m50s
website-v2   7m21s
website-v3   5m32s
```
ping @wonderflow @ryanzhang-oss
