### ISSUE TITLE
old revision workload is not gc when changing Patch trait 

### ISSUE THREAD

**Issue by captainroy-hy** [oam-dev/kubevela#1196]
**Describe the bug**

Latest master branch.
With below application and patch trait, after deploying the application, if I change the patch trait, e.g., remove it from app or change any properties of it, it will create a new revision workload. But the old one is not deleted.

```yaml
apiVersion: core.oam.dev/v1alpha2
kind: Application
metadata:
  name: testapp1
spec:
  components:
    - name: express-server
      type: webservice
      settings:
        cmd:
          - node
          - server.js
        image: oamdev/testapp:v1
      traits:
        - name: virtualgroup
          properties:
            group: "my-group0" # change this property and apply to reproduce
            type: "cluster"
---
apiVersion: core.oam.dev/v1alpha2
kind: TraitDefinition
metadata:
  annotations:
    definition.oam.dev/description: "Add virtual group labels"
  name: virtualgroup
spec:
  appliesToWorkloads:
    - webservice
    - worker
    - deployments.apps
  extension:
    template: |-
      patch: {
          spec: template: {
              metadata: labels: {
                  if parameter.type == "namespace" {
                      "app.namespace.virtual.group": parameter.group
                  }
                  if parameter.type == "cluster" {
                      "app.cluster.virtual.group": parameter.group
                  }
              }
          }
      }
      parameter: {
          group: *"default" | string
          type:  *"namespace" | string
      }
```
Each time repeat changing the trait config, it will create a new revision workload.
```yaml
➜ kubectl get deploy
NAME                 READY   UP-TO-DATE   AVAILABLE   AGE
express-server-v1    2/2     2            2           12m
express-server-v2    2/2     2            2           12m
express-server-v3    2/2     2            2           10m
express-server-v4    2/2     2            2           7m57s
```
But there's always only one appconfig with revision v1.
```yaml
kg appconfig
NAME          AGE
testapp1-v1   13m
```
It seems the problem only occurs in situations where we use a patch trait. Not sure about this.
