### ISSUE TITLE
request for retainKeys patchStrategy in CUE based patch trait 

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela#1235]
**Is your feature request related to a problem? Please describe.**

We have supported `//+patchKey=<name>` for strategy patch. Besides this feature, we also need a way to delete fields in strategy patch.

In K8s strategic merge patch, there's a way called `retainkeys` strategy. We also need to support that.

https://kubernetes.io/docs/tasks/manage-kubernetes-objects/update-api-object-kubectl-patch/#use-strategic-merge-patch-to-update-a-deployment-using-the-retainkeys-strategy

**Describe the solution you'd like**

We can support the `retainkeys` in our patch trait.

## User case 1: use retainkeys alone

1. Assume the Deployment is our base resource.
 
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: retainkeys-demo
spec:
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: rollingUpdate
    rollingUpdate:
      maxSurge: 30%
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: retainkeys-demo-ctr
        image: nginx
```

2. We want to use the `retainkeys` in a patch trait, update the `spec.strategy.type` to `Recreate` and delete the field `spec.strategy.rollingUpdate`.

```
apiVersion: core.oam.dev/v1alpha2
kind: TraitDefinition
metadata:
  name: recreate
spec:
  appliesToWorkloads:
    - deployments.apps
  extension:
    template: |-
      patch: {
         spec: {
              // +patchStrategy=retainKeys
              strategy: type: "Recreate"
           }
      }
```

## User case 2: use retainkeys with `patchKey` in slice

1. Assume the Pod is our base resource.

```
apiVersion: v1
kind: Pod
metadata:
  name: test-cinder
spec:
  containers:
  - image: k8s.gcr.io/test-webserver
    name: test-cinder-container
    volumeMounts:
    - mountPath: /test-cinder
      name: test-volume
  volumes:
  - name: test-volume
    # This OpenStack volume must already exist.
    cinder:
      volumeID: "<volume id>"
      fsType: ext4
```

2. We want to replace the volume `test-volume` with a new volume type, we will find the key name `test-volume` and replace it with the new volume (delete all other fileds).

```
apiVersion: core.oam.dev/v1alpha2
kind: TraitDefinition
metadata:
  name: volume
spec:
  appliesToWorkloads:
    - pods
  extension:
    template: |-
      patch: {
         spec: {
              // +patchStrategy=retainKeys
              // +patchKey=name
              volumes: [parameter]
           }
      }
      parameter: {
         name: string
         configMap ?: #Configmap
         emptyDir ?: #EmptyDir        
      }
```
