### ISSUE TITLE
AppRevision should generate names of AC/components with revision suffix

### ISSUE THREAD

**Issue by hongchaodeng** [oam-dev/kubevela#1243]
Currently the data generated in AppRevision has the following problems:

- AC doesn't have name.
- In AC it should use componentName instead of revision name.
- The label `app.oam.dev/component` in workload should be set to the component revision name.

The above are needed to support https://github.com/oam-dev/kubevela/issues/1144

```yaml
apiVersion: core.oam.dev/v1alpha2
kind: ApplicationRevision
metadata:
  name: example-app-v1
  namespace: default
spec:
  application:
    apiVersion: core.oam.dev/v1alpha2
    kind: Application
    metadata: {}
    spec:
      components:
      - name: testsvc
        settings:
          image: crccheck/hello-world
          port: 8000
        type: webservice
  applicationConfiguration:
    apiVersion: core.oam.dev/v1alpha2
    kind: ApplicationConfiguration
    metadata: {}
    spec:
      components:
      - revisionName: testsvc-v1
  components:
  - apiVersion: core.oam.dev/v1alpha2
    kind: Component
    metadata: {}
    spec:
      workload:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          labels:
            app.oam.dev/component: testsvc
            app.oam.dev/name: example-app
            workload.oam.dev/type: webservice
        spec:
          selector:
            matchLabels:
              app.oam.dev/app-revision: ""
              app.oam.dev/component: testsvc
          template:
            metadata:
              labels:
                app.oam.dev/app-revision: ""
                app.oam.dev/component: testsvc
            spec:
              containers:
              - image: crccheck/hello-world
                name: testsvc
                ports:
                - containerPort: 8000
```
