### ISSUE TITLE
In AppRevision components have no name

### ISSUE THREAD

**Issue by hongchaodeng** [oam-dev/kubevela#1255]
Currently in AppRevision the components have no name like below:

```
  applicationConfiguration:
    apiVersion: core.oam.dev/v1alpha2
    kind: ApplicationConfiguration
    metadata: {}
    spec:
      components:
      - revisionName: testsvc-v1
    status:
      dependency: {}
      observedGeneration: 0
  components:
  - apiVersion: core.oam.dev/v1alpha2
    kind: Component
    metadata: {}
    spec:
...
```

The problem is that there is no way to correlate the  components and ACComponents.
