### ISSUE TITLE
improve cue error message for jsonschema decode error

### ISSUE THREAD

**Issue by cnbailian** [oam-dev/kubevela#1313]
**Describe the bug**
pod log:
```
{"level":"info","ts":1616741475.4151049,"logger":"kubevela","msg":"KubeVela Version: latest, GIT Revision: git-20a31d4."}
{"level":"info","ts":1616741475.415158,"logger":"kubevela","msg":"Disable Capabilities: metrics."}
{"level":"info","ts":1616741475.4151716,"logger":"kubevela","msg":"core init with definition namespace vela-system"}
I0326 06:51:16.465840       1 request.go:621] Throttling request took 1.034080996s, request: GET:https://10.96.0.1:443/apis/monitoring.coreos.com/v1alpha1?timeout=32s
{"level":"info","ts":1616741478.0711453,"logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":":8080"}
{"level":"info","ts":1616741478.0714772,"logger":"kubevela","msg":"creating readiness/health check"}
{"level":"info","ts":1616741478.0714939,"logger":"kubevela","msg":"ApplyOnceOnly is disabled"}
{"level":"error","ts":1616741486.0225084,"logger":"kubevela","msg":"failed to create CRD discovery for CUE package client","error":"constraint not allowed because type array is excluded (and 1 more errors)","stacktrace":"runtime.main\n\t/usr/local/go/src/runtime/proc.go:203"}
```

**Cluster information**
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-19T07:38:38Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:00:47Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by cnbailian** [comment]
I found the cause, because cue-jsonschema does not support the openapi enum syntax.

wrong crd resource:
```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: provisionercapabilities.storage.kubesphere.io
spec:
  group: storage.kubesphere.io
  version: v1alpha1
  preserveUnknownFields: false
  names:
    plural: provisionercapabilities
    singular: provisionercapability
    kind: ProvisionerCapability
    shortNames:
      - pcap
  scope: Cluster
  additionalPrinterColumns:
  validation:
    openAPIV3Schema:
      required:
        - spec
      type: object
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation of an object.'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this object represents.'
          type: string
        spec:
          type: object
          description: 'spec defines the desired characteristics of obejct'
          properties:
            features:
              type: object
              description: 'Features represents plugin capability'
              properties:
                volume:
                  type: object
                  description: 'Volume represents whether plugin supports volume features'
                  properties:
                    expandMode:
                      description: 'Determined by GetPluginCapabilities in IdentityServer'
                      type: string
                      items:
                        type: string
                        enum: ["UNKNOWN", "OFFLINE", "ONLINE"]
```
source: https://github.com/kubesphere/ks-installer/blob/master/roles/common/files/ks-crds/storage.kubesphere.io_provisionercapabilities.yaml

If the cue package can’t fix the problem, can we provide better error message?

**Comment by wonderflow** [comment]
Thanks for the report, we're investigating on it . \cc @leejanee @yangsoon

**Comment by cnbailian** [comment]
> Thanks for the report, we're investigating on it . \cc @leejanee @yangsoon

If there are related discussion, can i join in?

**Comment by mayocream** [comment]
Same problem.
```bash
{"level":"error","ts":1618214748.9174805,"logger":"kubevela","msg":"failed to create CRD discovery for CUE package client","error":"constraint not allowed because type array is excluded (and 1 more errors)","stacktrace":"runtime.main\n\t/usr/local/go/src/runtime/proc.go:203"}
```

**Comment by yangsoon** [comment]
> I found the cause, because cue-jsonschema does not support the openapi enum syntax.
> 
> wrong crd resource:
> 
> ```
> apiVersion: apiextensions.k8s.io/v1beta1
> kind: CustomResourceDefinition
> metadata:
>   name: provisionercapabilities.storage.kubesphere.io
> spec:
>   group: storage.kubesphere.io
>   version: v1alpha1
>   preserveUnknownFields: false
>   names:
>     plural: provisionercapabilities
>     singular: provisionercapability
>     kind: ProvisionerCapability
>     shortNames:
>       - pcap
>   scope: Cluster
>   additionalPrinterColumns:
>   validation:
>     openAPIV3Schema:
>       required:
>         - spec
>       type: object
>       properties:
>         apiVersion:
>           description: 'APIVersion defines the versioned schema of this representation of an object.'
>           type: string
>         kind:
>           description: 'Kind is a string value representing the REST resource this object represents.'
>           type: string
>         spec:
>           type: object
>           description: 'spec defines the desired characteristics of obejct'
>           properties:
>             features:
>               type: object
>               description: 'Features represents plugin capability'
>               properties:
>                 volume:
>                   type: object
>                   description: 'Volume represents whether plugin supports volume features'
>                   properties:
>                     expandMode:
>                       description: 'Determined by GetPluginCapabilities in IdentityServer'
>                       type: string
>                       items:
>                         type: string
>                         enum: ["UNKNOWN", "OFFLINE", "ONLINE"]
> ```
> 
> source: https://github.com/kubesphere/ks-installer/blob/master/roles/common/files/ks-crds/storage.kubesphere.io_provisionercapabilities.yaml
> 
> If the cue package can’t fix the problem, can we provide better error message?

it looks like this crd definition use the incorrect openapi schema, the items keyword is required in arrays.
while `expandMode` is a `string` type.

```yaml
properties:
  expandMode:
    description: 'Determined by GetPluginCapabilities in IdentityServer'
    type: string
    items: // the items keyword is required in arrays 
      type: string
      enum: ["UNKNOWN", "OFFLINE", "ONLINE"]
```
and I find the source crd file generate by controller-gen, the keyword `items` should be added by other operations.

https://github.com/kubesphere/kubesphere/blob/a9a0be79d1528b4ead02e23018f84bd2b7a4aed4/config/crds/storage.kubesphere.io_provisionercapabilities.yaml#L63

I remove the  `items: type: string` and reapply the `storage.kubesphere.io_provisionercapabilities.yaml`, KubeVela can run normally.

**Comment by yangsoon** [comment]
@mayocream did you use the same crd as cnbailian

**Comment by mayocream** [comment]
@yangsoon After edit K8s CRD `provisionercapabilities.storage.kubesphere.io` and `storageclasscapabilities.storage.kubesphere.io`

from
```yaml
  expandMode:
    type: string
    items: // the items keyword is required in arrays 
      type: string
      enum: ["UNKNOWN", "OFFLINE", "ONLINE"]
```
to
```yaml
 expandMode:
  type: string
  enum: ["UNKNOWN", "OFFLINE", "ONLINE"]
```

KubeVela now running normally.

These 2 files:
https://github.com/kubesphere/ks-installer/blob/d7b5e81dc5fd6b253f3d04d9cdcfb92258a69e51/roles/common/files/ks-crds/storage.kubesphere.io_provisionercapabilities.yaml#L86
https://github.com/kubesphere/ks-installer/blob/d7b5e81dc5fd6b253f3d04d9cdcfb92258a69e51/roles/common/files/ks-crds/storage.kubesphere.io_storageclasscapabilities.yaml#L74
