### ISSUE TITLE
[Feature] support part of components to reconcile even the whole application hit reconciling issue

### ISSUE THREAD

**Issue by zzxwill** [oam-dev/kubevela#1350]
**Is your feature request related to a problem? Please describe.**

For example, I have two components, `express-server` will try to consume the output secret `db-conn` generated by RDS instance of component `sample-db`. 

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: webapp
spec:
  components:
    - name: express-server
      type: webservice
      properties:
        image: xxx
        ports: 80
      envMapping
          # environments refer to db-conn secret
          DB_PASSWORD:
            secret: db-conn
            key: password                                    
          endpoint:
            secret: db-conn                           
          username:
            secret: db-conn

    - name: sample-db
      type: alibaba-rds
      properties:
        name: sample-db
        engine: mysql
        engineVersion: "8.0"
        instanceClass: rds.mysql.c1.large
        username: oamtest
        outputSecretName: db-conn
```

If in some situations, `express-server` wants to directly use the value of secret `db-conn` of item like `endpoint`.  Then component `sample-db` has to run first, create an RDS instance, and generate the secret. But currently, application will check both of the component are ready to run, or it will throw exception. As `express-server` will fail to retrieve the secret's value, then two component will stop to reconciling. It hangs.

So I suggest providing a way to enable some of components of an application, instead of running all of them at the same time when Application think it's ready for all of them.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
