### ISSUE TITLE
[Feature] add workload type for components in Application .status

### ISSUE THREAD

**Issue by zzxwill** [oam-dev/kubevela#1351]
**Is your feature request related to a problem? Please describe.**

When I'd like to check whether all components of an application are provisioned, I normally use `kubectl get components`.

```
✗ k get components
NAME             WORKLOAD-KIND   AGE
express-server   Deployment      54s
sample-db        RDSInstance     53s
sample-oss       Bucket          52s
```
Then I can quickly check Crossplane managed resource `RDSInstance` and `Bucket` in a convenient way.

```
✗ k get rdsinstance
NAME        READY   SYNCED   STATE     ENGINE   VERSION   AGE
sample-db   True    True     Running   mysql    8.0       116m
```

As application is the main entry object, so its status should also contain the workload kind of a component.

```
status:
  batchRollingState: ""
  components:
  - apiVersion: core.oam.dev/v1alpha2
    kind: Component
    name: express-server
    uid: e9b9cf7a-0ff5-4aac-8fc8-0a030bb09387
  - apiVersion: core.oam.dev/v1alpha2
    kind: Component
    name: sample-db
    uid: e9b9cf7a-0ff5-4aac-8fc8-0a030bb09387
  - apiVersion: core.oam.dev/v1alpha2
    kind: Component
    name: sample-oss
    uid: e9b9cf7a-0ff5-4aac-8fc8-0a030bb09387
```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by wonderflow** [comment]
@charles-woshicai  We can list the componentName only like below:

```
status:
  batchRollingState: ""
  components:
  - name: express-server
  - name: sample-db
  - name: sample-oss
```
