### ISSUE TITLE
`vela show` can not find component of helm

### ISSUE THREAD

**Issue by sunny0826** [oam-dev/kubevela#1394]
**Describe the bug**

Declare Helm charts as app components via `ComponentDefinition`.

```yaml
apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  name: kibana-chart
  annotations:
    definition.oam.dev/description: helm chart for kibana
spec:
  workload:
    definition:
      apiVersion: apps/v1
      kind: Deployment
  schematic:
    helm:
      release:
        chart:
          spec:
            chart: "kibana"
            version: "7.11.1"
      repository:
        url: "https://helm.elastic.co/"
```

However, it cannot be viewed with the `vela show` command.

**Screenshots**

![image](https://user-images.githubusercontent.com/24563928/113238384-3b944d00-92db-11eb-9c6d-41f73dc19145.png)

![image](https://user-images.githubusercontent.com/24563928/113238524-87df8d00-92db-11eb-9fdb-8f538b9da38c.png)

**Cluster information**

- Kubernetes Version 1.19.1 (kind)
