### ISSUE TITLE
Annotations in TraitDefinition outputs are overwritten

### ISSUE THREAD

**Issue by kinsolee** [oam-dev/kubevela#1422]
**Describe the bug**
The annotations in `TraitDefinition` outputs now will be overwritten once the `Application` is created.

**To Reproduce**
1. Purely install kubevela following [Official Docs](https://kubevela.io/docs/install)
2. Modify the build-in `ingress.yaml` traitdefinition, add an annotation `konghq.com/override` in the `outputs:service` section:
```yaml
        // trait template can have multiple outputs in one trait
        outputs: service: {
          apiVersion: "v1"
          kind:       "Service"
          metadata:
            name: context.name
            annotations:
              "konghq.com/override": "foo"
          spec: {
            selector: {
              "app.oam.dev/component": context.name
            }
            ports: [
              for k, v in parameter.http {
                port:       v
                targetPort: v
              },
            ]
          }
        }
```
3. Apply the demo Application from [Quick Start](https://kubevela.io/docs/quick-start):
```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  generation: 1
  name: first-vela-app
  ...
  namespace: default
spec:
  components:
  - name: express-server
    type: webservice
    properties:
      image: crccheck/hello-world
      port: 8000
    traits:
    - type: ingress
      properties:
        domain: testsvc.example.com
        http:
          /: 8000
```

**Expected behavior**
The annotation `konghq.com/override: foo` should appear in the `Service` object. But it didn't work as expected.

**Screenshots**
![image](https://user-images.githubusercontent.com/5144108/113703713-cf1bb280-970d-11eb-9822-74c42e7beefd.png)

**Cluster information**
- OKD version 4.7
- Kubernetes Version [v1.20.0+5fbfd19-1046]

**Additional context**
Seems like `kubevela` will patch the annotations after creating the output objects.
![image](https://user-images.githubusercontent.com/5144108/113704523-d2fc0480-970e-11eb-8ba9-ac0a91a5924c.png)

**Comment by kinsolee** [comment]
This was caused by a wrong cue grammar, fields must be included in braces or they will be seen as the same hierarchy as the parent field. 

This works as expected:
```yaml
        outputs: service: {
          apiVersion: "v1"
          kind:       "Service"
          metadata:
            name: context.name
            annotations: { // this should have braces
              "konghq.com/override": "foo"
            }
          spec: {
            selector: {
              "app.oam.dev/component": context.name
            }
            ports: [
              for k, v in parameter.http {
                port:       v
                targetPort: v
              },
            ]
          }
        }
```

**Comment by wonderflow** [comment]
https://kubevela.io/docs/platform-engineers/debug-test-cue i think the  `dry-run` command could help next time

**Comment by kinsolee** [comment]
I did use `dry-run` command, but it printed out the correct outputs even though I used the wrong grammar.

The cue template:

![cue template](https://user-images.githubusercontent.com/5144108/113861055-5aae4580-97d9-11eb-86bf-63acb8cd5fbf.png)

The `dry-run` output:

![image](https://user-images.githubusercontent.com/5144108/113861277-9b0dc380-97d9-11eb-97cf-aae81a7a5644.png)

That made me think that there was nothing to do with the cue template till I tried to add braces on it and found the changes.

May this be a bug with `dry-run` command or the controller ? I think the result of them should be consistent.
We can do more investigation about this. @wonderflow

**Comment by wonderflow** [comment]
I tried your example, it turned out:

```
apiVersion: v1
kind: Service
annotations:
  konghq.com/override: foo
metadata:
  labels:
    app.oam.dev/appRevision: ""
    app.oam.dev/component: myweb
    app.oam.dev/name: application-sample
    trait.oam.dev/resource: service
    trait.oam.dev/type: myingress
  name: myweb
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app.oam.dev/component: myweb
```

The annoutations is out of the metadata. The `dry-run` command is right.
