### ISSUE TITLE
[Observability] Provide access to application metrics/tracing/logs/health

### ISSUE THREAD

**Issue by hongchaodeng** [oam-dev/kubevela#1425]
When deploying applications, it is important for developers to understand how they are behaving in order to better operate/improve them. This includes understanding the applications' metrics, tracing, logs, health endpoints.

From system level perspective, we can only collect infra metrics like CPU/Mem. But that doesn't provide good insights in the applications per se. More "application-aware" metrics are so meaningful and helpful that we should collect and display them for users.

While some infra could be setup to collect metrics/traces data (ELK, Prometheus & Grafana, Jaeger), developers often need to write some instrumentation code to provide those data. To achieve better portability and usability, we can adopt **Dapr** framework.

Here's an example user scenario:
- During infra setup, KubeVela will be installed with necessary monitoring add-ons.
- User packages application as helm chart -> uploads to KubeVela
- User/Ops can add monitoring features (metrics/tracing) to the application without modifying the chart at all. 
- Finally User deploys the application.
- Vela will apply Dapr sidecar and Dapr resources alongside the application resources. The infra will collect metrics/traces data and display them in API/UI.

**Comment by hongchaodeng** [comment]
Here's my proposed solution for metrics:

- When deploying application, add 'metrics' trait:

  ```yaml
  kind: Application
  spec:
    components:
    - name: abc
      ...
      traits:
      - type: metrics 
        properties:
          exporter: prometheus
          port: 9090
  ```

- After rendered, its pods should have the following annotations:
  
  ```yaml
  app.oam.dev/metrics-exporter: 'prometheus'
  app.oam.dev/metrics-port: '9090'
  ```

- The Dapr sidecar will detect above annotations, and collect metrics and export them to [OpenTelemetry Collector](https://github.com/open-telemetry/opentelemetry-collector).
  - Note that this doesn't exist yet AFAICT. We need to coordinate with the Dapr team for this feature.

- Then we can use the OTel Collector to further convert it and expose to different backends:
  - For open source, we will use the [Prometheus remote write exporter](https://aws.amazon.com/blogs/opensource/aws-adds-prometheus-remote-write-exporter-to-opentelemetry-collector/) to write to Prometheus.
  - For cloud, we can integrate with Alibaba ARMS service, Datadog, New Relic for smooth hosted experience.

**Comment by hongchaodeng** [comment]
Here's my proposed solution for metrics:

- When deploying application, add 'metrics' trait:

  ```yaml
  apiVersion: core.oam.dev/v1beta1
  kind: Application
  spec:
    components:
    - name: abc
      ...
      traits:
      - type: metrics 
        properties:
          exporter: prometheus
          port: 9090
  ```

- After rendered, its pods should have the following annotations:
  
  ```yaml
  app.oam.dev/metrics-exporter: 'prometheus'
  app.oam.dev/metrics-port: '9090'
  ```

- The Dapr sidecar will detect above annotations, and collect metrics and export them to [OpenTelemetry Collector](https://github.com/open-telemetry/opentelemetry-collector).
  - Note that this doesn't exist yet AFAICT. We need to coordinate with the Dapr team for this feature.
  - KubeVela can be used to automatically configure Dapr with the appropriate remote address:

  ```yaml
  apiVersion: dapr.io/v1alpha1
  kind: Configuration
  spec:
    metrics:
      otel-collector:
        endpointAddress: "http://prometheus-service:8000"
  ``` 

- Then we can use the OTel Collector to further convert it and expose to different backends:
  - For open source, we will use the [Prometheus remote write exporter](https://aws.amazon.com/blogs/opensource/aws-adds-prometheus-remote-write-exporter-to-opentelemetry-collector/) to write to Prometheus.
  - For cloud, we can integrate with Alibaba ARMS service, Datadog, New Relic for smooth hosted experience.
