### ISSUE TITLE
[Feature] AppDeployment support internal SVC traffic management

### ISSUE THREAD

**Issue by yangsoon** [oam-dev/kubevela#1484]
**Is your feature request related to a problem? Please describe.**

Suppose such a scenario:

Component `M` in Application `A` use the service provided by Component `N` in Application `B`, But there are multiple versions of Application `B`: `B-v1`, `B-v2`. 

For Components in Application `A`, they don't need to care about the request was sent to which version of the Component `N`. So they just need to request the SVC `B-N`. The developer of Application `B` set up the distribution of traffic. AppDeployement help manage traffic to SVC `B-v1-N` or SVC `B-v2-N`.

Now AppDeployment supports the management of ingress traffic, AppDeployment will set destination for different versions of Component. Now we need to manage the internal svc traffic.

Here is an [example](https://github.com/oam-dev/samples/tree/master/7.GoogleCloudPlatform_MicroServices_Demo), Component in Application boutique will request the service in Application product, the Application product has 2 version: v1 and v2.

**Describe the solution you'd like**

For Component `N` in Application `B` have multiple versions  , AppDeployment should create a SVC named `B-N`, the SVC `B-N` will be used by Components in Application `A`. 

The VirtualService which create by AppDeployment should set the `hosts` be `B-N`, 
The HTTPRouteDestination same as before. 

**Additional context**

The AppDeployment maybe like:

```yaml
apiVersion: core.oam.dev/v1beta1
kind: AppDeployment
metadata:
  name: example-appdeploy
spec:
  traffic:
    type: service
    hosts:
      - example-app
    http:
      - weightedTargets:
          - revisionName: example-app-v1
            componentName: testsvc
            port: 8000
            weight: 50
          - revisionName: example-app-v2
            componentName: testsvc
            port: 8000
            weight: 50
  appRevisions:
    - revisionName: example-app-v1
      placement:
        - distribution:
            replicas: 1
    - revisionName: example-app-v2
      placement:
        - distribution:
            replicas: 1
```
