### ISSUE TITLE
fail to create  a application with trait , error message : evaluate customStatus.message: value "message" not found'

### ISSUE THREAD

**Issue by xiqiu618** [oam-dev/kubevela#1502]
**Describe the bug**
create a application with trait, application status conditions will print  error

**To Reproduce**
1.  create application
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: first-vela-app
spec:
  components:
    - name: express-server
      type: webservice
      properties:
        image: crccheck/hello-world
        port: 8000
      traits:
        - type: ingress
          properties:
            domain: testsvc.example.com
            http:
              "/": 8000
```
2.  describe application object 

**Screenshots**

![image](https://user-images.githubusercontent.com/73998049/114869568-b86e0d80-9e29-11eb-96a7-d617bb975add.png)

**Cluster information**
- Kubernetes Version [e.g. 1.16.9]

**Additional context**

removing Trait Ingress test passes, suspected to be caused by this issue
