### ISSUE TITLE
[BUG] set annotations for workload alias.

### ISSUE THREAD

**Issue by zzxwill** [oam-dev/kubevela#152]
How about also setting annotations for workload alias, like `oam.appengine.info/alias: containerized`? This will help to retrieve the alias of a workload to list/show/status an application.
```
apiVersion: core.oam.dev/v1alpha2
kind: WorkloadDefinition
metadata:
  annotations:
    oam.appengine.info/apiVersion: core.oam.dev/v1alpha2
    oam.appengine.info/kind: ContainerizedWorkload
  creationTimestamp: "2020-08-12T10:00:37Z"
```
