### ISSUE TITLE
[Feature] Helm ComponentDefinition supports setting chart values

### ISSUE THREAD

**Issue by zzxwill** [oam-dev/kubevela#1534]
**Is your feature request related to a problem? Please describe.**

@xiqiu618 would like to use helm ComponentDefinition, but needs helm chart values to be settable. /cc @captainroy-hy 

```
apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  name: webapp-chart
  namespace: vela-system
  annotations:
    definition.oam.dev/description: helm chart for webapp
spec:
  workload:
    definition:
      apiVersion: apps/v1
      kind: Deployment
  schematic:
    helm:
      release:
        chart:
          spec:
            chart: "podinfo"
            version: "5.1.4"
      repository:
        url: "http://oam.dev/catalog/"
```

**Describe the solution you'd like**

Parse Values of the chart and display all variables (name, structure, type) by `vela show`. Then users can set it in `properties` field in an Application.

**Describe alternatives you've considered**

**Additional context**
