### ISSUE TITLE
[Feature] Consolidate rollout, traffic, placement etc in Application?

### ISSUE THREAD

**Issue by resouer** [oam-dev/kubevela#1549]
Consider using `Application` as entry point to declare app level strategies (global traits). For example:

```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: example-app
spec:
  components:
    - name: testsvc
      type: webservice
      properties:
        addRevisionLabel: true
        image: crccheck/hello-world
        port: 8000
  strategies:
    - type: traffic
      properties:
        hosts:
          - example.com
        http:
          - match:
              - uri:
                  prefix: "/example-app"
            weightedTargets:
              - revisionName: example-app-v1
                componentName: testsvc
                port: 80
                weight: 50
              - revisionName: example-app-v2
                componentName: testsvc
                port: 80
                weight: 50
    - type: placement
      ...
          
```

This UX seems to have more clarity and when `strategies` is present, vela can assume `revision-only: "true"` by default.

**Comment by wonderflow** [comment]
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: example-app
spec:
  components:
    - name: testsvc
      type: webservice
      properties:
        addRevisionLabel: true
        image: crccheck/hello-world
        port: 8000
  globalScopes:
    - type: rollout
      properties:
           # application (revision) reference
        sourceAppRevisionName: test-rolling-v1
        targetAppRevisionName: test-rolling-v2
        componentList:
          - metrics-provider
        rolloutPlan:
          targetSize: 5
          rolloutBatches:
            - replicas: 1
            - replicas: 3
        
```
