### ISSUE TITLE
[Feature] Git repo component

### ISSUE THREAD

**Issue by resouer** [oam-dev/kubevela#1562]
With raw kube approach, we can easily have a built-in `ComponentDefinition` to reference a Git repo as a component (using Flux Kustomization as example but there're many approaches indeed):

```yaml
apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  name: foo
  namespace: default
spec:
  workload: 
    definition: 
      apiVersion: apps/v1
      kind: Deployment # so the system know this is a deployment type workoad
  schematic:
    kube: 
      template:
        apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
        kind: Kustomization
        spec:
          interval: 10m0s
          sourceRef:
            kind: GitRepository
            name: test-repo # ref to a GitRepository resource
          path: test-path
          prune: true
          validation: client 
      parameters: 
      - name: repo
        required: true
        type: string
        fieldPaths: 
        - "spec.sourceRef.name"
      - name: path
        required: true
        type: string
        fieldPaths: 
        - "spec.path"
```
