### ISSUE TITLE
no warning or error msg when CUE error occurs

### ISSUE THREAD

**Issue by captainroy-hy** [oam-dev/kubevela#1595]
**Describe the bug**

**To Reproduce**

For below application, by mistake, I assign an int to a field requiring string type value in CUE template.
```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: myapp
spec:
  components:
    - name: mycomp
      type: webservice
      properties:
        image: nginx:latest
        port: 8080
        env:
          - name: SHOULD_BE_STRING_1
            value: "I'm string"
          - name: SHOULD_BE_STRING_2
            value: 1234 # <=== webservice CUE template requires string type here
```
To reproduce it quickly, just use `dry-run`.
As a result, the `env` is not rendered.
```shell
 🐬 ➜ vela system dry-run -f myapp.yaml
---
# Application(myapp) -- Comopnent(mycomp)
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.oam.dev/appRevision: ""
    app.oam.dev/component: mycomp
    app.oam.dev/name: myapp
    workload.oam.dev/type: webservice
spec:
  selector:
    matchLabels:
      app.oam.dev/component: mycomp
  template:
    metadata:
      labels:
        app.oam.dev/component: mycomp
    spec:
      containers:
      - image: nginx:latest
        name: mycomp
        ports:
        - containerPort: 8080
        # env is not rendered!
---
```
If apply the app into the cluster, the workload will be created successfully, everything looks like good except the `env` is missing.
There's no warning nor error for `env`.
Through debugging, I figured out my mistake...
```
...
		}, {
			name: "SHOULD_BE_STRING_2"
			// +usage=The value of the environment variable
			value: _|_ // conflicting values string and 1234 (mismatched types string and int)
...
```
However, it would be helpful if vela can provide any warning or error to remind users of such a mistake.

\cc @wonderflow @leejanee 
**Expected behavior**

**Screenshots**

**Cluster information**

**Additional context**
