### ISSUE TITLE
[Feature] Revisit Helm based component

### ISSUE THREAD

**Issue by resouer** [oam-dev/kubevela#1603]
Ref: #864 

Today the Helm based component need to add a `ComponentDefinition` for every chart, this is still verbose.

Should we consider this format?

```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: myapp
  namespace: default
spec:
  components:
    - name: demo 
      type: helm 
      properties: 
        chart: "podinfo"
        version: "5.1.4" # omit to latest
        repository: "http://oam.dev/catalog/"
        values:
          image:
            tag: "5.1.2"
```
```yaml
apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  name: helm
spec:
  schematic:
    cue:
      template: |
        output: {
            apiVersion: "helm.toolkit.fluxcd.io/v2beta1"
            kind: "HelmRelease"
            ...
        }
        // an extra template
        outputs: repo: {
            apiVersion: "source.toolkit.fluxcd.io/v1beta1"
            kind: "HelmRepository"
            ...
        }
        parameter: {
            chart: string
            version?: string
            repository: string
            values?: [...#Values]
        }
```
The drawback is we lose a way to define workload type (which is important). A solution is we could have components such as: helm, helm-worker, helm-task (similar to https://github.com/oam-dev/spec/blob/v0.1.0/3.component_model.md#core-workload-types)

Similar pattern also applies to Kustomize support.

/cc @wonderflow
