### ISSUE TITLE
[Feature] Defer Rollout Plan to runtime cluster

### ISSUE THREAD

**Issue by resouer** [oam-dev/kubevela#1605]
I'd propose make KubeVela work on control plane only. The AppRollout (since it only works with a single component), could be deferred to runtime cluster, i.e. it track workload instance and upgrade it in rolling manner.

I am not sure if we want it to rollout Helm chart as a whole on runtime cluster, seems not a critical requirement to me.

**Comment by wonderflow** [comment]
Yes, I agree, we should make kubevela as pure control plane and let the runtime controller work in runtime cluster.

So the architecture should be like:

![image](https://user-images.githubusercontent.com/2173670/117530603-99216500-b010-11eb-97a2-f3c6a74722fa.png)

In this architecture, the Rollout in runtime cluster can be work as Application level（AppRollout） or Component level (Trait).

**Comment by Alpacius** [comment]
Deferred rollout and plans seem nice since there are real-world cases where components (i.e. microservices in an application) are separately rolled out or back for quick recover of emergent failures, forming up a temporary unstable application revision which could be fixed later. Such cases could be handled by apply rollout to components instead of the entire application.

However, it may be worthy to note that AppRollout and Rollout Traits may conflict especially when they do not share the same rollout plan, and it is common that rollout plans are found to vary among components under the premise of SLAs of microservices are kept at acceptable levels.
If we have rollout plans for each component (assuming that there would always be a default one regardless where it comes from), what is the difference between AppRollout's plan and Rollout Traits' plans?

**Comment by LeoLiuYan** [comment]
Agree with @resouer.  Currently we use `AppRollout` only in runtime cluster.  

By the way, `AppDeployment`  which management multiple runtime clusters should support more features.

**Comment by wonderflow** [comment]
Here's the plan:

1. Allow specify externalRevision for Component revision #1884
2. Create a Rollout Controller based on the rolloutPlan code base.
  - the controller should be able to deploy in runtime cluster without kubevela
  - the controller receive the component revision as source and target
  - the controller should support both inplace mode and two workload rolling mode

```
apiVersion: core.oam.dev/v1alpha1
kind: Rollout
metadata:
  name: rolling
spec:
  sourceRevisionName: component-v1
  targetRevisionName: component-v2
  rolloutMode: inplace/rolling
  rolloutPlan:
    rolloutStrategy: "IncreaseFirst"
    rolloutBatches:
      - replicas: 4
    targetSize: 5
```
