### ISSUE TITLE
[Feature] Support App-Level Policies and Custom Control-Logic Workflow

### ISSUE THREAD

**Issue by hongchaodeng** [oam-dev/kubevela#1613]
The current model of Component-Trait has some limitations:

- No application level configuration across components. We should have app-level policies. Here are some use cases:
  - Provide RBAC rules, SSO integration, audit trailts, secret backends for application.
  - Provide deployment insights like lead time, frequence, mttr, etc. metrics for application.
  - Set GitOps pipelines for application.
  - Set multi-cluster placement rules for application.
- Once the Vela controller renders finalized k8s resources, it simply applies them without extension points. We should provide extensible control workflow for custom logic. Here are some use cases:
  - The controller should just renders all resources and put them in App.Status or a ConfigMap for further actions in the workflow.
  - The default apply-resources logic should be just one action that could be disabled.
  - Provide an action to do blue-green upgrade (or canary upgrade) across different app revisions.
  - Provide an action to do traffic-split across two revisions of services.
  - Provide an action for user interaction to do manual approval/rollback.
  - Provide an action to deploy finalized resources to muliple clusters with fine-grained control (e.g. split replicas 70%/30% across two clusters).
  - Provide an action to push finalized k8s resources to Git for GitOps (via Flux/Argo), or to S3/OSS buckets, or to a helm chart, etc.

```yaml
kind: Application
spec:
  componnets:
    ...

  policies:
    - type: security
      properties:
        rbac: ...
        sso: ...
        audit: ...
        secretBackend: vault
    
    - type: deployment-insights
      properties:
        leadTime: ...
        frequency: ...
        mttr: ...

    - type: gitops
      properties:
        source: git-repo-url
        branch: main
        path: config/
    
    - type: placement
      properties:
        clusters:
          # split replicas and traffic 7/3 between two clusters
          - name: cluster-1
            replicas: "70%"
            traffic: "70%"
          - name: cluster-2
            replicas: "30%"
            traffic: "30%"

  # workflow is used to customize the control logic.
  # If workflow is specified, Vela won't apply resources in Components, but provide rendered resources for further actions.
  # workflow steps are executed in array order.
  # Each step should have a "finish mark", e.g. in resource annotation `app.oam.dev/workflow-finish = succeed/fail`
  workflow:
  
    # blue-green rollout
    - type: blue-gree-rollout
      properties:
        rolloutPlan:
          partition: "50%"

    # traffic shift
    - type: traffic-shift
      properties:
        rolloutPlan:
          partition: "50%"

    # promote/rollback
    - type: rollout-promotion
      propertie:
        manualApproval: true
        rollbackIfNotApproved: true
```

More examples of workflow actions:

```yaml

# multi-stage rollout
workflow:
- type: stage-rollout
  properties:
    targetEnv: dev

- type: approval-gate
  properties:
    manualApproval: true

- type: stage-rollout
  properties:
    targetEnv: prod


# push to Git to trigger GitOps via Flux/Argo
workflow:
- type: git-push
  properties:
    repo: ...
    branch: deploy
    credentials: ...
```
