### ISSUE TITLE
Rollout failed when targetSize=totalRolloutSize

### ISSUE THREAD

**Issue by wangyikewxgm** [oam-dev/kubevela#1629]
**Describe the bug**

Rollout failed, and pod cannot be created

**To Reproduce**
1.apply the application yaml
```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: test-rolling
  annotations:
    "app.oam.dev/rolling-components": "metrics-provider"
    "app.oam.dev/rollout-template": "true"
spec:
  components:
    - name: metrics-provider
      type: worker
      properties:
        cmd:
          - ./podinfo
          - stress-cpu=1
        image: stefanprodan/podinfo:4.0.6
        port: 8080
        updateStrategyType: InPlaceIfPossible
        replicas: 2
```

2. apply rollout yaml
```yaml
apiVersion: core.oam.dev/v1beta1
kind: AppRollout
metadata:
  name: rolling-example
spec:
  targetAppRevisionName: test-rolling-v1
  componentList:
    - metrics-provider
  rolloutPlan:
    rolloutStrategy: "IncreaseFirst"
    rolloutBatches:
      - replicas: 1
      - replicas: 1
    targetSize: 2

```
3. verify the approllout

```shell
$  kubectl get  approllout
NAME              TARGET   UPGRADED   READY   BATCH-STATE         ROLLING-STATE   AGE
rolling-example   2        0          0       batchInitializing   rolloutFailed   26s

```

**Comment by Alpacius** [comment]
It seems this bug comes from initial replicas calculation. Attempt to rollout `N` replicas with exact `N` total replicas in AppRollout `rolloutBatches` causes failure.
And if we apply `N-1` replicas in `rolloutBatches`, everything goes well, except that the first two batches are merged with `replicas=1` for the first batch. For example, we boot an Application with:
```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: test-rolling
  annotations:
    "app.oam.dev/rolling-components": "metrics-provider"
    "app.oam.dev/rollout-template": "true"
spec:
  components:
    - name: metrics-provider
      type: worker
      properties:
        cmd:
          - ./podinfo
          - stress-cpu=1
        image: stefanprodan/podinfo:5.0.2
        port: 8080
        replicas: 6
```
and an AppRollout:
```yaml
apiVersion: core.oam.dev/v1beta1
kind: AppRollout
metadata:
  name: rolling-example
spec:
  # application (revision) reference
  targetAppRevisionName: test-rolling-v1
  componentList:
    - metrics-provider
  rolloutPlan:
    rolloutStrategy: "IncreaseFirst"
    rolloutBatches:
      - replicas: 2
      - replicas: 3
    targetSize: 6
```
Keep an eye on its pods, we have:
```
jiuya.wb@ITDA-L-PF1NWRVH MINGW64 /d/aliyun-devops/temp/kubevela-examples
$ kubectl create ns jy-vela-demo
namespace/jy-vela-demo created

jiuya.wb@ITDA-L-PF1NWRVH MINGW64 /d/aliyun-devops/temp/kubevela-examples
$ kubectl apply -f ./podinfo-appfile.yaml -n jy-vela-demo
application.core.oam.dev/test-rolling created

jiuya.wb@ITDA-L-PF1NWRVH MINGW64 /d/aliyun-devops/temp/kubevela-examples
$ kubectl apply -f ./podinfo-rollout.yaml -n jy-vela-demo
approllout.core.oam.dev/rolling-example created

jiuya.wb@ITDA-L-PF1NWRVH MINGW64 /d/aliyun-devops/temp/kubevela-examples
$ kubectl get pods -n jy-vela-demo
NAME                                  READY   STATUS    RESTARTS   AGE
metrics-provider-v1-dbd64b975-2ln8c   1/1     Running   0          3s
metrics-provider-v1-dbd64b975-pz76k   1/1     Running   0          3s
metrics-provider-v1-dbd64b975-rblc4   1/1     Running   0          3s

jiuya.wb@ITDA-L-PF1NWRVH MINGW64 /d/aliyun-devops/temp/kubevela-examples
$ kubectl get pods -n jy-vela-demo
NAME                                  READY   STATUS              RESTARTS   AGE
metrics-provider-v1-dbd64b975-2ln8c   1/1     Running             0          6s
metrics-provider-v1-dbd64b975-2mhqw   0/1     ContainerCreating   0          1s
metrics-provider-v1-dbd64b975-4jwt7   0/1     ContainerCreating   0          1s
metrics-provider-v1-dbd64b975-ldjjv   0/1     ContainerCreating   0          1s
metrics-provider-v1-dbd64b975-pz76k   1/1     Running             0          6s
metrics-provider-v1-dbd64b975-rblc4   1/1     Running             0          6s

jiuya.wb@ITDA-L-PF1NWRVH MINGW64 /d/aliyun-devops/temp/kubevela-examples
$ kubectl get pods -n jy-vela-demo
NAME                                  READY   STATUS    RESTARTS   AGE
metrics-provider-v1-dbd64b975-2ln8c   1/1     Running   0          11s
metrics-provider-v1-dbd64b975-2mhqw   1/1     Running   0          6s
metrics-provider-v1-dbd64b975-4jwt7   1/1     Running   0          6s
metrics-provider-v1-dbd64b975-ldjjv   1/1     Running   0          6s
metrics-provider-v1-dbd64b975-pz76k   1/1     Running   0          11s
metrics-provider-v1-dbd64b975-rblc4   1/1     Running   0          11s
```
---
The problem might come from here:
```go
func (s *DeploymentScaleController) VerifySpec(ctx context.Context) (bool, error) {
        // ...
	// record the target size
	s.rolloutStatus.RolloutTargetSize = *s.rolloutSpec.TargetSize
	klog.InfoS("record the target size", "target size", *s.rolloutSpec.TargetSize)

	// fetch the deployment and get its current size
	originalSize, verifyErr := s.size(ctx)
	if verifyErr != nil {
		// do not fail the rollout because we can't get the resource
		s.rolloutStatus.RolloutRetry(verifyErr.Error())
		// nolint: nilerr
		return false, nil
	}
	s.rolloutStatus.RolloutOriginalSize = originalSize
	klog.InfoS("record the original size", "original size", originalSize)

	// check if the rollout batch replicas scale up/down to the replicas target
	if verifyErr = verifyBatchesWithScale(s.rolloutSpec, int(originalSize),
		int(s.rolloutStatus.RolloutTargetSize)); verifyErr != nil {
		return false, verifyErr
	}
        // ...
```
where `s.size(ctx)` just fetch the replicas from the workload:
```go
func (s *DeploymentScaleController) size(ctx context.Context) (int32, error) {
	if s.deploy == nil {
		err := s.fetchDeployment(ctx)
		if err != nil {
			return 0, err
		}
	}
	// default is 1
	if s.deploy.Spec.Replicas == nil {
		return 1, nil
	}
	return *s.deploy.Spec.Replicas, nil
}
```
When we boot an deployment, `s.size()` returns 1. Thus `verifyBatchesWithScale()` would get wrong estimation of `totalRollout` (exact `targetSize + 1`):
```go
func verifyBatchesWithScale(rolloutSpec *v1alpha1.RolloutPlan, originalSize, targetSize int) error {
	totalRollout := originalSize
	for i := 0; i < len(rolloutSpec.RolloutBatches)-1; i++ {
		rb := rolloutSpec.RolloutBatches[i]
		if targetSize > originalSize {
			batchSize, _ := intstr.GetValueFromIntOrPercent(&rb.Replicas, targetSize-originalSize, true)
			totalRollout += batchSize
		} else {
			batchSize, _ := intstr.GetValueFromIntOrPercent(&rb.Replicas, originalSize-targetSize, true)
			totalRollout -= batchSize
		}
	}
        // ...
}
```
resulting in error `the rollout plan increased too much`, which is also emitted by `verifyBatchesWithScale()`.

**Comment by Alpacius** [comment]
> What's the error message/event?

From an example where `targetSize`=3 with 3 batches (`replicas`=1 for each batch):
```
Events:
  Type     Reason          Age                            From        Message
  ----     ------          ----                           ----        -------
  Normal   Rollout Paused  <invalid> (x2 over <invalid>)  AppRollout  target app revision is not ready for rolling yet
  Warning  VerifyFailed    <invalid>                      AppRollout  the rollout plan increased too much, total batch size = 3, targetSize size = 3
```

**Comment by ryanzhang-oss** [comment]
It should be an easy fix but there is not really a need to "rollout" in this case either, right? Why do you want to "scale" from N to N?

**Comment by Alpacius** [comment]
> The problem is that the Cloneset already has one pod to start with, thus the initial targetSize needs to be 1 more than the rolloutSize.
> 
> I believe there is problem in the deployment side. You don't really need to use the appRollout to scale cloneSets.

The problem here is about deployments rather than clonesets.
On a bootstrap rollout with rollout template enabled, no deployment or pods are created. Thus RolloutPlanController [chooses to use DeploymentScaleController](https://github.com/oam-dev/kubevela/blob/eefc8c13ce98475d28f6c7e52a4f753fc5d6857d/pkg/controller/common/rollout/rollout_plan_controller.go#L357), which treats initial rollout as scaling up the rendered deployment of 0 available replicas, while the fetched workload has a wrong replicas count of 1.

For example (`targetSize`=`3`, batches are `[1, 1, 1]`):
```
$ kubectl apply -f ./podinfo-appfile.yaml -n jy-vela-demo
application.core.oam.dev/test-rolling created

$ kubectl get deploy -n jy-vela-demo
No resources found in jy-vela-demo namespace.

$ kubectl apply -f ./podinfo-rollout.yaml -n jy-vela-demo
approllout.core.oam.dev/rolling-example created

$ kubectl describe AppRollout -n jy-vela-demo
...
Events:
  Type    Reason          Age                            From        Message
  ----    ------          ----                           ----        -------
  Normal  Rollout Paused  <invalid> (x2 over <invalid>)  AppRollout  target app revision is not ready for rolling yet

$ kubectl describe AppRollout -n jy-vela-demo
...
Spec:
  Component List:
    metrics-provider
  Rollout Plan:
    Rollout Batches:
      Replicas:              1
      Replicas:              1
      Replicas:              1
    Rollout Strategy:        IncreaseFirst
    Target Size:             3
  Target App Revision Name:  test-rolling-v1
...
Events:
  Type     Reason          Age                            From        Message
  ----     ------          ----                           ----        -------
  Normal   Rollout Paused  <invalid> (x2 over <invalid>)  AppRollout  target app revision is not ready for rolling yet
  Warning  VerifyFailed    <invalid>                      AppRollout  the rollout plan increased too much, total batch size = 3, targetSize size = 3

$ kubectl get deploy -n jy-vela-demo
NAME                  READY   UP-TO-DATE   AVAILABLE   AGE
metrics-provider-v1   0/1     0            0           3m56s

$ kubectl get deploy -n jy-vela-demo
NAME                  READY   UP-TO-DATE   AVAILABLE   AGE
metrics-provider-v1   0/1     0            0           10m
```
We could find an empty deployment, not a ready one, after rendering is done.
Perhaps it is proper to use available replicas when scaling deployments.

**Comment by captainroy-hy** [comment]
`paused` field behaves differently on CloneSet and Deployment. 
For CloneSet, "paused indicates that Pods updating is paused, controller will not update Pods but just maintain the number of replicas."
For Deployment, an initial Deployment with `paused: true` will not create any replicas until `paused` is switched to `false`.

**Comment by captainroy-hy** [comment]
I think this may be not a bug, but just an unreasonable end-user behavior. 
While a user is authoring the rollout plan for his application, he must be aware of the original number (or the initial number, starting number, whatever it's named) of replicas of his application, then takes the expected final number of replicas into account, and finally design the batches.
Current logic uses `.spec.replicas` as the original number, which makes sense for both CloneSet and Deployment, because end-users don't (indeed don't have to) know how many replicas really exist now, they just know the value of `.spec.replicas`.

**Comment by Alpacius** [comment]
> I think this may be not a bug, but just an unreasonable end-user behavior.
> While a user is authoring the rollout plan for his application, he must be aware of the original number (or the initial number, starting number, whatever it's named) of replicas of his application, then takes the expected final number of replicas into account, and finally design the batches.
> Current logic uses `.spec.replicas` as the original number, which makes sense for both CloneSet and Deployment, because end-users don't (indeed don't have to) know how many replicas really exist now, they just know the value of `.spec.replicas`.

When we apply an Application with rollout template but no AppRollout for the first time, there is no replicas.
It is rendering logic that creates a deployment, and such rendering should not be users' concern since it is kubevela's way of implementation.

By now, the implementation thinks the initially rendered deployment with 0/1 replicas has a `replicas`=`1`. In my opinion it is not natural and forces users (both end and platform) to adapt the way of kubevela implementation.

**Comment by captainroy-hy** [comment]
> By now, the implementation thinks the initially rendered deployment with 0/1 replicas has a replicas=1. 

That's not true.  As the comments show, the logic is aware that the `.spec.replicas` doesn't represent the real number of pods. It follows k8s API convention that, fields in `spec` represent desired state by users but not current status. So it's intended to behave consistently with users' opinions. 
https://github.com/oam-dev/kubevela/blob/9772907d667053cfc5b9e7c480d510ceea9ef4ea/pkg/controller/common/rollout/workloads/deployment_scale_controller.go#L307

**Comment by Alpacius** [comment]
> > By now, the implementation thinks the initially rendered deployment with 0/1 replicas has a replicas=1.
> 
> That's not true. As the comments show, the logic is aware that the `.spec.replicas` doesn't represent the real number of pods. It follows k8s API convention that, fields in `spec` represent desired state by users but not current status. So it's intended to behave consistently with users' opinions.
> https://github.com/oam-dev/kubevela/blob/9772907d667053cfc5b9e7c480d510ceea9ef4ea/pkg/controller/common/rollout/workloads/deployment_scale_controller.go#L307

It's ok for `.spec.replicas` to show the desired number of pods because that's what k8s does.
The point is, the deployment resource is not directly created by the user, and doesn't exist until AppRollout triggers the further reconcilation.
Considering about internal affairs such as "a deployment shall be launched later and it causes difference between first-time rollout and further rollouts because of an initial replicas number used for scaling in DeploymentScaleController but not referenced further in DeploymentController since bootstrap scaling-up is done before" seems not so end-to-end IMO.

**Comment by captainroy-hy** [comment]
A sample scenario for rolling update not scale. Deploying a Deployment with `replicas: 5`, when it comes to 2/5 ready, users apply a Rollout plan to bring it to v2. Namely, the rollout starts from 2/5. And user expects the target v2 replicas number is 8. What should the batches plan be? [1,1,1] or [2,2,2]?(just assuming 3 rounds of rolling) A natural way for user is [1,1,1], because he is always aware of `replicas: 5` but not `2/5`. So we cannot use the real number of pods as the original number. `.spec.replicas` is the only information shared among users' opinion and controller implementation.

**Comment by Alpacius** [comment]
> A sample scenario for rolling update not scale. Deploying a Deployment with `replicas: 5`, when it comes to 2/5 ready, users apply a Rollout plan to bring it to v2. Namely, the rollout starts from 2/5. And user expects the target v2 replicas number is 8. What should the batches plan be? [1,1,1] or [2,2,2]?(just assuming 3 rounds of rolling) A natural way for user is [1,1,1], because he is always aware of `replicas: 5` but not `2/5`. So we cannot use the real number of pods as the original number. `.spec.replicas` is the only information shared among users' opinion and controller implementation.

Both [1, 1, 1] and [2, 2, 2] imply a "base" progression of 2 replicas. However, rolling out is about all replicas shall be updated to the given revision, thus the initial size of 2 might be not so important.

Btw, scaling is the implementation of kubevela's choice when no source target revision is specified, not what I'm expecting.

**Comment by captainroy-hy** [comment]
> However, rolling out is about all replicas shall be updated to the given revision,

It's important to permit users to get each round of batching in a controllable state. That's the reason why users choose progressive rollout. If just update all to the given revision, rollout is redundant.

initial size (not real size) and batches plan work together to determine the result of each round rolling.

**Comment by Alpacius** [comment]
> initial size (not real size) and batches plan work together to determine the result of each round rolling.

Yes, initial size matters. However it should be emit by users directly.
In this case, initial size visible to the user before AppRollout starts should be 0, not 1 created in the rendering phase, for it's not user's intention of doing so.
It might be more reasonable if ihe borderline for initial size is "before the applied AppRollout triggered". Otherwise, users would have to adjust their plans to adapt kubevela, not their situations.

**Comment by captainroy-hy** [comment]
As for the example, it depends on users' expectations or requirements for each round of rolling.
To author a rollout plan, users should have a clear goal of the final target, in your example, it's 3. 
Then, users should think about how many rounds they want to reach the destination, and more importantly, they should think about how many replicas they need at the end of each round rolling. 

If you expect two rounds (round1=>2, round2=>3), then based on the initial replicas(again, not the real number of replicas, we just use `.spec.replicas:1`), you need a batch plan: [1,1].

If you expect three rounds (round1=>1, round2=>2, round3=>3), then you need a batch plan:[0,1,1].(Yes, 0 is acceptable)

So we cannot say which batch is more natural. It depends on requirements.

**Comment by Alpacius** [comment]
> If you expect three rounds (round1=>1, round2=>2, round3=>3), then you need a batch plan:[0,1,1].(Yes, 0 is acceptable)
> 
> So we cannot say which batch is more natural. It depends on requirements.

Let's assume that the user expects 3 rounds with 1 pod per round. S/he have to write the plan [0, 1, 1] and is confused: why 0 pod launch in the first round, and there is still 1 pod running at the end of the round?
Thus we have to answer: kubevela would launch a deployment for them which is counted into total replicas, and such behavior comes from the underlying controllers -- you have to beware and keep this mechanism in mind, at least for deployments.

My opinion is user is free to design rollout situations, but with little knowledge what kubevela do for them under the veil of component.

**Comment by captainroy-hy** [comment]
While defining the batch plan, if use `.spec.replicas` as baseline, users just keep one thing  in mind: 
> `.spec.replicas` + batches[0...N] = number of replicas they can get after round N+1. 

That's straightforward because they are also the author of `.spec.replicas`. They don't have to know how kubevela or diverse workload controllers work under the hood. No matter what kind of workload. What they write is what they finally get.

But if use the real number of replicas rather than `.spec.replicas`, users must know the precise number before authoring rollout plan.  The real number varies from different kind workloads, different situations. The real-time status should be invisible to users at application level. And that would be time-consuming and error-prone stuff for users.

**Comment by Alpacius** [comment]
> `.spec.replicas` + batches[0...N] = number of replicas they can get after round N+1.

Such rule exists because rollout is coupled to kubernetes stories where resources are created with desired state, and further guided to a kubevela story where workloads are created and then scaled.

Although the rule is simple, IMHO it's not ideal, being different from "rollout" concept without underlying machine equivalent specified.

**Comment by captainroy-hy** [comment]
`properties.replicas` is not a valid parameter of `worker`.
Try cmd `vela show worker` to check configurable point of worker or any other kind workload/trait.

**Comment by Alpacius** [comment]
> `properties.replicas` is not a valid parameter of `worker`.
> Try cmd `vela show worker` to check configurable point of worker or any other kind workload/trait.

Well that might be critical since I gave unexpected replica number myself?
I'll check it out.

**Comment by Alpacius** [comment]
> `properties.replicas` is not a valid parameter of `worker`.
> Try cmd `vela show worker` to check configurable point of worker or any other kind workload/trait.

It's just a little twisted when we try to create applications. See the example below:
```yaml
apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  name: nginx-deployment
spec:
  workload: 
    definition: 
      apiVersion: apps/v1
      kind: Deployment
  schematic:
    kube: 
      template:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: nginx-deployment
          labels:
            app: nginx
        spec:
          replicas: 3
          selector:
            matchLabels:
              app: nginx
          template:
            metadata:
              labels:
                app: nginx
            spec:
              containers:
              - name: nginx
                image: nginx
                ports:
                - containerPort: 80
---
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: simple-application
  annotations:
    "app.oam.dev/rolling-components": "metrics-provider"
    "app.oam.dev/rollout-template": "true"
    "appstack.aliyun.com/change-made-by": "UUID-1"
spec:
  components:
  - name: nginx-component
    type: nginx-deployment
    properties: {}
```
and it AppRollout:
```yaml
apiVersion: core.oam.dev/v1beta1
kind: AppRollout
metadata:
  name: rolling-example
spec:
  # application (revision) reference
  #sourceAppRevisionName: simple-application-v1
  #targetAppRevisionName: simple-application-v2
  targetAppRevisionName: simple-application-v1
  componentList:
    - nginx-component
  rolloutPlan:
    rolloutStrategy: "IncreaseFirst"
    rolloutBatches:
      - replicas: 0
      - replicas: 0
      - replicas: 0
    targetSize: 3
    # batchPartition: 1
```
With 3 replicas initially, we could launch a successful rollout by plan [0, 0, 0].
That means we have no control over batches on the first rollout but have to see the total replicas rush out. Sometimes such mess is acceptable. However is it what we want?

**Comment by captainroy-hy** [comment]
The deployment defined in kube-schematic template should not have `.spec.replicas: x`,  otherwise kubevela will fix its replicas to x forever. So rollout makes no sense for such a workload...
Indeed, rollout is exclusive to scaler trait and any others that can set `.spec.replicas: x`

That's true we need to refine and add more doc.

**Comment by Alpacius** [comment]
> The deployment defined in kube-schematic template should not have `.spec.replicas: x`, otherwise kubevela will fix its replicas to x forever. So rollout makes no sense for such a workload...
> Indeed, rollout is exclusive to scaler trait and any others that can set `.spec.replicas: x`
> 
> That's true we need to refine and add more doc.

Sorry made a mistake in the `"app.oam.dev/rolling-components"` annotation just now and I have to rerun my example.
To be brief, rollout still works for the first and the second time:
* For the first time, I have to specify plan [0, 0, 0]. Otherwise the rollout plan will fail.
* For the second time, plan [1, 1, 1] works, which is against the `.spec.replicas` rule because of `.spec.replicas` is now 3.

For now, workarounds are clear enough. 
> Follow the `.spec.replicas` rule only when we boot an application.

As for OAM reconcilation which keeps .spec.replicas, it has quite a history of at least a few months (and crashes into flagger canary when not applied with HPA). It's ok to keep `.spec.replicas` in kube-schematic templates for ad-hoc applications, for users treat is as a pseudo-component and may update its replicas.

The reason behind usage of that ad-hoc kube template is we may want customers' native resources to migrate to kubevela application, and workload template instantiation is not able to describe their specifications with all the configmaps, volumes, and other stuff. However, that's another issue and should not be explained in details here.

Last and least, runnable example for the second rollout:
```yaml
apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  name: nginx-component
spec:
  workload: 
    definition: 
      apiVersion: apps/v1
      kind: Deployment
  schematic:
    kube: 
      template:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: nginx-deployment
          labels:
            app: nginx
        spec:
          replicas: 3
          selector:
            matchLabels:
              app: nginx
          template:
            metadata:
              labels:
                app: nginx
            spec:
              containers:
              - name: nginx
                image: nginx:1.9
                ports:
                - containerPort: 80
---
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: simple-application
  annotations:
    "app.oam.dev/rolling-components": "nginx-component"
    "app.oam.dev/rollout-template": "true"
    "appstack.aliyun.com/change-made-by": "UUID-3"
spec:
  components:
  - name: nginx-component
    type: nginx-component
    properties: {}
```
```yaml
apiVersion: core.oam.dev/v1beta1
kind: AppRollout
metadata:
  name: rolling-example
spec:
  # application (revision) reference
  sourceAppRevisionName: simple-application-v1
  targetAppRevisionName: simple-application-v2
  #targetAppRevisionName: simple-application-v1
  componentList:
    - nginx-component
  rolloutPlan:
    rolloutStrategy: "IncreaseFirst"
    rolloutBatches:
      - replicas: 1
      - replicas: 1
      - replicas: 1
    targetSize: 3
    # batchPartition: 1
```
