### ISSUE TITLE
[Bug] application  "app.oam.dev/rollout-template": "false" annotation don't works

### ISSUE THREAD

**Issue by wangyikewxgm** [oam-dev/kubevela#1632]
**Describe the bug**

**To Reproduce**
apply the application yaml
```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: test-rolling
  namespace: vela-test
  annotations:
    "app.oam.dev/rolling-components": "metrics-provider"
    "app.oam.dev/rollout-template": "false"
spec:
  components:
    - name: metrics-provider
      type: worker
      properties:
        cmd:
          - ./podinfo
          - stress-cpu=1
        image: stefanprodan/podinfo:4.0.6
        port: 8080
        updateStrategyType: InPlaceIfPossible
        replicas: 3
```
application controller still assume the app is not  inplace one.  And don't create appContext for it
