### ISSUE TITLE
[Feature] Reuse existing v1alpha2 Component in v1beta1 Application

### ISSUE THREAD

**Issue by Alpacius** [oam-dev/kubevela#1638]
**Is your feature request related to a problem? Please describe.**

Currently OAM v1alpha2 components could be defined with freestyle spec, offering compatibility with kubernetes resources available. However, kubevela Application specification does not allow reuse of existing components. 
For example, given the component yaml below:
```yaml
apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: nginx-component
spec:
  workload:
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: nginx-deployment
      labels:
        app: nginx
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: nginx
      template:
        metadata:
          labels:
            app: nginx
        spec:
          containers:
          - name: nginx
            image: nginx
            ports:
            - containerPort: 80
```
There is no way to reuse the component with its name. Components field in Application specification asks for type, which could be only available component types (usually one of worker, webservice, task) bound by preset templates. 

**Describe the solution you'd like**

According to application controller implementation, the only way that components are instantiated is through templates. Reuse of existing could be implemented by:
* Trying to get the component (name it Spec A) by name before instantiating with the corresponding template.
* Instantiating the component (name it Spec B) from its template.
* If Spec A exists, patch its missing parts from Spec B; otherwise, just use Spec B.
```go
func (af *Appfile) GenerateApplicationConfiguration() (*v1alpha2.ApplicationConfiguration,
	[]*v1alpha2.Component, error) {
	appconfig := &v1alpha2.ApplicationConfiguration{}
	appconfig.SetGroupVersionKind(v1alpha2.ApplicationConfigurationGroupVersionKind)
	appconfig.Name = af.Name
	appconfig.Namespace = af.Namespace

	if appconfig.Labels == nil {
		appconfig.Labels = map[string]string{}
	}
	appconfig.Labels[oam.LabelAppName] = af.Name

	var components []*v1alpha2.Component

	for _, wl := range af.Workloads {
		var (
			comp   *v1alpha2.Component
			acComp *v1alpha2.ApplicationConfigurationComponent
			err    error
		)
                // TODO: get the component if it exists (Spec A)
                // Still, we have to get traits and other definitions from Application. (Spec B) 
		switch wl.CapabilityCategory {
		case types.HelmCategory:
			comp, acComp, err = generateComponentFromHelmModule(wl, af.Name, af.RevisionName, af.Namespace)
			if err != nil {
				return nil, nil, err
			}
		case types.KubeCategory:
			comp, acComp, err = generateComponentFromKubeModule(wl, af.Name, af.RevisionName, af.Namespace)
			if err != nil {
				return nil, nil, err
			}
		case types.TerraformCategory:
			comp, acComp, err = generateComponentFromTerraformModule(wl, af.Name, af.RevisionName, af.Namespace)
			if err != nil {
				return nil, nil, err
			}
		default:
			comp, acComp, err = generateComponentFromCUEModule(wl, af.Name, af.RevisionName, af.Namespace)
			if err != nil {
				return nil, nil, err
			}
		}
                // TODO Merge Spec A and B, or just use Spec B if Spec A does not exist
		components = append(components, comp)
		appconfig.Spec.Components = append(appconfig.Spec.Components, *acComp)
	}
	return appconfig, components, nil
}
```

**Describe alternatives you've considered**

It is possible to use an ad-hoc component definition for each freestyled component. For example:
```yaml
apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  name: nginx-deployment
spec:
  workload: 
    definition: 
      apiVersion: apps/v1
      kind: Deployment
  schematic:
    kube: 
      template:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: nginx-deployment
          labels:
            app: nginx
        spec:
          replicas: 3
          selector:
            matchLabels:
              app: nginx
          template:
            metadata:
              labels:
                app: nginx
            spec:
              containers:
              - name: nginx
                image: nginx
                ports:
                - containerPort: 80
---
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: simple-application
  labels:
    appstack/last-updated-by: "114514"
spec:
  components:
  - name: nginx-component
    type: nginx-deployment
    properties: {}
```
This workaround allows us to make use of existing kubernetes resources, regardless whether they are supported by core workloads or not.

Thanks to @wangyikewxgm
