### ISSUE TITLE
[Feature] add AppDeployment conditioned status 

### ISSUE THREAD

**Issue by lxd5866** [oam-dev/kubevela#1681]
when i use AppDeployment and my AppDeployment file contains  an undeclared application version, kubevela-vela-core will logs error like :
```
{"level":"error","ts":1621275528.0065122,"logger":"controller","msg":"Reconciler error","reconcilerGroup":

"core.oam.dev","reconcilerKind":"AppDeployment","controller":"appdeployment","name":"example-

appdeploy","namespace":"default","error":"ApplicationRevision.core.oam.dev \"example-app-v2\" not 

found","stacktrace":"...."
```

### would like
reference type AppStatus add status description field  like runtimev1alpha1.ConditionedStatus，and add  the results of reconcile .

### alternatives

when apply AppDeployment，validate appRevisions .

### config yaml
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: example-app
  annotations:
    app.oam.dev/revision-only: "true"
spec:
  components:
    - name: testsvc
      type: webservice
      properties:
        addRevisionLabel: true
        image: crccheck/hello-world
        port: 8000
---
apiVersion: core.oam.dev/v1beta1
kind: AppDeployment
metadata:
  name: example-appdeploy
spec:
  appRevisions:
    - revisionName: example-app-v10
      placement:
        - distribution:
            replicas: 2

    - revisionName: example-app-v2
      placement:
        - distribution:
            replicas: 2

```
