### ISSUE TITLE
[Feature] add  version describe in ComponentDefinition and TraitDefinition

### ISSUE THREAD

**Issue by lxd5866** [oam-dev/kubevela#1682]
### when i apply ComponentDefinition or TraitDefinition to k8s,  kubevela will generate definitionrevisions and set definitionrevisions data in status field。then end-user can list versions of  definition and use  it in application file like : 
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: example-app
  annotations:
    app.oam.dev/revision-only: "true"
spec:
  components:
    - name: testsvc
      type: webservice@v1
      properties:
        addRevisionLabel: true
        image: crccheck/hello-world
        port: 8000
```
but version generation depends on the time you apply definition to k8s ,  so when i apply two  version in different order for two cluster （a.yaml, b.yaml）, a.yaml may version-1 or version-2, i have to change may Application file for different cluster to adapts  different versions of the same definition.

###  you'd like

```
apiVersion: core.oam.dev/v1beta1
kind: xxxDefinition
metadata:
  name: labels
  namespace: vela-system
spec:
  #  version field
  revision:
    #  version name
    version: "v2"
    # describe for this version ,vela cap ls can display describe for end-user 
    describe: "describe this version here"
  schematic:
...
    
```

**Comment by wonderflow** [comment]
```
apiVersion: core.oam.dev/v1beta1
kind: xxxDefinition
metadata:
  name: labels
  namespace: vela-system
  annotations:
     definition.oam.dev/version: v2
spec:
  schematic:
```

Let's add a special annotation `definition.oam.dev/version` for this feature, if this annotation is marked, then we don't generate the revision instead by create/update the revision with the specified name.
