### ISSUE TITLE
vela cannot store parameter to configMap for traitDefinition annotations

### ISSUE THREAD

**Issue by yangsoon** [oam-dev/kubevela#1684]
**Describe the bug**

refer to https://github.com/oam-dev/kubevela/pull/1560

1. when apply a traitdefinition like `annotations`, which parameter is a non-structure type

```yaml
apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  annotations:
    definition.oam.dev/description: "Add annotations for your Workload."
  name: annotations
spec:
  appliesToWorkloads:
    - webservice
    - worker
  schematic:
    cue:
      template: |-
        patch: {
        	spec: template: metadata: annotations: {
        		for k, v in parameter {
        			"\(k)": v
        		}
        	}
        }
        parameter: [string]: string
```

2. vela controller will fail to store configMap.

```shell
cannot store capability annotations in ConfigMap: cannot generate OpenAPI
      v3 JSON schema for capability annotations: capability annotations doesn''t contain
      section `parameter`
```
