### ISSUE TITLE
[Feature] support patch data-pass object in CUE

### ISSUE THREAD

**Issue by yangsoon** [oam-dev/kubevela#1685]
**Is your feature request related to a problem? Please describe.**

Sometimes we want to patch some objects by way of data-pass. 

## User case

```yaml
apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  annotations:
  name: patch-demo
spec:
  schematic:
    cue:
      template: |
        patch: {
        	context: outputs: service: {
        		metadata: annotations: parameter
        	}
        }
        parameter: [string]string
```

```yaml
apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  name: microservice
  annotations:
    definition.oam.dev/description: "Describes a microservice combo Deployment with Service."
spec:
  workload:
    definition:
      apiVersion: apps/v1
      kind: Deployment
  schematic:
    cue:
      template: |
        output: {
          // Deployment
          apiVersion: "apps/v1"
          kind:       "Deployment"
          metadata: {
            name:      context.name
            namespace: "default"
          }
          spec: {
            selector: matchLabels: {
              "app": context.name
              if parameter.addRevisionLabel {
                  "app.oam.dev/appRevision": context.appRevision
                  "app.oam.dev/component": context.name
              }
            }
            template: {
              metadata: {
                labels: {
                  "app": context.name
                  if parameter.addRevisionLabel {
                      "app.oam.dev/appRevision": context.appRevision
                      "app.oam.dev/component": context.name
                  }
                }
              }
              spec: {
                serviceAccountName:            "default"
                terminationGracePeriodSeconds: parameter.podShutdownGraceSeconds
                containers: [{
                  name:  context.name
                  image: parameter.image
                  ports: [{
                    if parameter.containerPort != _|_ {
                      containerPort: parameter.containerPort
                    }
                    if parameter.containerPort == _|_ {
                      containerPort: parameter.servicePort
                    }
                  }]
                  if parameter.env != _|_ {
                    env: [
                      for k, v in parameter.env {
                        name:  k
                        value: v
                      },
                    ]
                  }
                  resources: {
                    requests: {
                      if parameter.cpu != _|_ {
                        cpu: parameter.cpu
                      }
                      if parameter.memory != _|_ {
                        memory: parameter.memory
                      }
                    }
                  }
                }]
              }
            }
          }
        }
        // Service
        outputs: service: {
          apiVersion: "v1"
          kind:       "Service"
          metadata: {
            name: context.name
            labels: {
              "app": context.name
            }
          }
          spec: {
            type: "ClusterIP"
            selector: {
              "app": context.name
            }
            ports: [{
              port: parameter.servicePort
              if parameter.containerPort != _|_ {
                targetPort: parameter.containerPort
              }
              if parameter.containerPort == _|_ {
                targetPort: parameter.servicePort
              }
            }]
          }
        }
        parameter: {
          image:          string
          servicePort:    int
          containerPort?: int
          // +usage=Optional duration in seconds the pod needs to terminate gracefully
          podShutdownGraceSeconds: *30 | int
          addRevisionLabel: *false | bool
          env: [string]: string
          cpu?:    string
          memory?: string
        }
```

We hope `patch-demo` can patch annotations to the service object in ComponentDefinition `microservice` by `context.outputs.service`
