### ISSUE TITLE
How to use the for expression in healthPolicy.isHealth

### ISSUE THREAD

**Issue by cnbailian** [oam-dev/kubevela#1699]
ComponentDefination.yaml
```
apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  name: tekton-run
  annotations:
    definition.oam.dev/description: "tekton TaskRun ComponentDefinition"
spec:
  workload:
    definition:
      apiVersion: tekton.dev/v1beta1
      kind: TaskRun
  status:
    healthPolicy: |
      isHealth: for k, v context.output.status.conditions {
        (v.type == "Succeeded") && (v.status == "true")
      }
  schematic:
    cue:
      template: |
        output: {
        	apiVersion: "tekton.dev/v1beta1"
        	kind:       "TaskRun"
        	metadata:
        		name: context.name
        	spec: {
        		if parameter.saname != _|_ {
        			serviceAccountName: parameter.saname
        		}
        		taskRef: {
        			name: parameter.taskname
        		}
        		resources: {
        			inputs: [{
        				name: "repo"
        				resourceRef: {
        					name: parameter.taskname
        				}
        			}]
        		}
        	}
        }

        parameter: {
        	// +usage=Specify the taskrun TaskRef
        	taskname: string

        	// +usage=Specify the taskrun ServiceAccountName
        	saname: string
        }
```

The TaskRun printer columns：
```
  - additionalPrinterColumns:
    - jsonPath: .status.conditions[?(@.type=="Succeeded")].status
      name: Succeeded
      type: string
    - jsonPath: .status.conditions[?(@.type=="Succeeded")].reason
      name: Reason
      type: string
    - jsonPath: .status.startTime
      name: StartTime
      type: date
    - jsonPath: .status.completionTime
      name: CompletionTime
      type: date
```
