### ISSUE TITLE
[BUG] cannot parser same resource

### ISSUE THREAD

**Issue by lxd5866** [oam-dev/kubevela#1703]
### Demo
```
apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  name: redis-cluster
  namespace: default
  annotations:
    definition.oam.dev/description: "redis-cluster component"
spec:
  workload:
    definition:
      apiVersion: apps/v1
      kind: StatefulSet
  schematic:
    cue:
      template: |
        parameter: {
        	// +usage=名称
        	name: string
        	// +usage=端口号
        	port: *6379 | int
        	// +usage=密码
        	password: string
        	// +usage=镜像地址
        	image: *"docker.io/bitnami/redis:6.2.3-debian-10-r15" | string
        	// +usage=存储大小
        	storage: *"8Gi" | string
        	// +usage=是否添加nodeservice
        	nodeService: *false | bool
        	// +usage=副本数量
        	replicasCount: *3 | int
        	replicasCount: (>=1 & <=10)
        	// +usage=副本规格
        	replicasResource: "0.5C0.5G" | "1C2G" | *"2C4G" | "4C8G" | "nolimit"
        	// +usage=master 规格
        	masterResource: *"4C8G" | "8C16G" | "nolimit"
        }

        //serviceAccount
        output: {
        	"apiVersion": "v1"
        	"kind":       "ServiceAccount"
        	"metadata": {
        		"name":  "sa-redis-" + parameter.name
        		"labels": {
        			"app.kubernetes.io/name": "sa-redis-" +parameter.name
        		}
        	}
        }

        outputs:test: {
        	"apiVersion": "v1"
        	"kind":       "ServiceAccount"
        	"metadata": {
        		"name":  "sa-redis22-" + parameter.name
        		"labels": {
        			"app.kubernetes.io/name": "sa-redis-" +parameter.name
        		}
        	}
        }
```
### Appfile
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: redis-dev
  namespace: default
spec:
  components:
    - name: redis-dev
      type: redis-cluster
      properties:
        password: "123456"
        name: "redis-dev"
        masterResource: "nolimit"
        replicasResource: "nolimit"
        replicasCount: 1
        storage: "500m"
```

### result
```
➜  ~ kubectl get sa
NAME                   SECRETS   AGE
redis-dev              1         2s
sa-redis22-redis-dev   1         2s
```
### want 
i want have two serviceAccount: sa-redis-redis-dev and sa-redis22-redis-dev

**Comment by wonderflow** [comment]
@ryanzhang-oss  @wangyikewxgm   Maybe be we should relax the restrictions on the name? Or just check if it's controlled by RolloutPlan?

**Comment by wonderflow** [comment]
It seems you have already achieved your goal, the result is two SA that you want but not the same name.

**Comment by wangyikewxgm** [comment]
I think KubeVela treat your first SA as a component and override it's name as component name. @lxd5866

**Comment by lxd5866** [comment]
> I think KubeVela treat your first SA as a component and override it's name with component name. @lxd5866

yes ,  when i use component render complex content, the name of first k8s object in output:{ } will be changed to component name。

When I want to use all the prefixes for a name，such component is com_A, i want to make my sa name was mypre_com_A,
i will use cue `"mypre_" + parameter.name` . 

if i have two sa and my component is "redis-dev" ,
    first : `"sa-redis-" + parameter.name` 
    second: `"sa-redis22-" + parameter.name`

i want get :
    first : "sa-redis-redis-dev"
    second: "sa-redis22-redis-dev"

but as @wangyikewxgm  say, KubeVela treat  my first SA as a component ,so i get is:
    first : "sa-redis"
    second: "sa-redis22-redis-dev"

This problem can be replicated in simple applications

**Comment by wangyikewxgm** [comment]
IMO It's not a bug, KubeVela treat `output:{ } ` in componentDefinition as workload, and will override with component's name.I think it's reasonable.You can change componentDefinition  to traitDefinition and put all SA in `outputs:{ } ` to meet you expectation.To be honest a SA isn't a workload truly.

**Comment by lxd5866** [comment]
> IMO It's not a bug, KubeVela treat `output:{ } ` in componentDefinition as workload, and will override with component's name.I think it's reasonable.You can change componentDefinition to traitDefinition and put all SA in `outputs:{ } ` to meet you expectation.To be honest a SA isn't a workload truly.

i agree your opinion， but in my opinion Application component name may  composition with appliication 

example ：
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name:first-application
spec:
  components:
    - name: myweb
      type: worker
      properties:
        image: "busybox"
        cmd:
        - sleep
        - "1000"
---
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: second-application
spec:
  components:
    - name: myweb
      type: worker
      properties:
        image: "busybox"
        cmd:
        - sleep
        - "1000"
```

error logs 
```
2021-05-27T17:23:56.691Z	DEBUG	kubevela	Cannot apply workload	{"controller": "oam/applicationcontext.core.oam.dev", "uid": "368d721e-f381-4208-8254-75645f4e7ee6", "version": "", "error": "cannot apply workload \"myweb\": cannot apply ApplyOption: existing object is not controlled by UID \"368d721e-f381-4208-8254-75645f4e7ee6\"", "errorVerbose": "existing object is not controlled by UID \"368d721e-f381-4208-8254-75645f4e7ee6\"\ngithub.com/oam-dev/kubevela/pkg/utils/apply.MustBeControllableBy.func1\n\t/workspace/pkg/utils/apply/apply.go:184\ngithub.com/oam-dev/kubevela/pkg/utils/apply.executeApplyOptions\n\t/workspace/pkg/utils/apply/apply.go:160\ngithub.com/oam-dev/kubevela/pkg/utils/apply.(*APIApplicator).Apply\n\t/workspace/pkg/utils/apply/apply.go:108\ngithub.com/oam-dev/kubevela/pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration.(*workloads).Apply\n\t/workspace/pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/apply.go:117\ngithub.com/oam-dev/kubevela/pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration.(*OAMApplicationReconciler).ACReconcile\n\t/workspace/pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/applicationconfiguration.go:313\ngithub.com/oam-dev/kubevela/pkg/controller/core.oam.dev/v1alpha2/applicationcontext.(*Reconciler).Reconcile\n\t/workspace/pkg/controller/core.oam.dev/v1alpha2/applicationcontext/applicationconte
```

error mean the first application component `myweb` will effect the second application .  i think name with 'application_name'-'component_name' maybe batter, the deployer don't konw has same name component in the cluster
