### ISSUE TITLE
request for right status for different trait instance with same type

### ISSUE THREAD

**Issue by zou2699** [oam-dev/kubevela#1722]
**Is your feature request related to a problem? Please describe.**

Suppose we have a trait called config, this trait corresponds to a crd,

then a component needs to define multiple config trait (corresponding to multiple crd),

The status of the Application does not show the status of the corresponding crd.

As shown below：

```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: demo-app
spec:
  components: 
    ......
    traits:
    - type: config    
      properties:
        mountType: env
        config:
          kind: secret
          name: demo-app-env-config
        ......
    - type: config    
      properties:
        mountType: file
        config:
          kind: configMap
          name: demo-app-file-html
        ......
```

```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
......
status:  
  services:
  - healthy: true
    name: demo-app
    traits:
    - healthy: true
      message: 'configMap: demo-app-file-html'   // secret: demo-app-env-config
      type: config
    - healthy: true
      message: 'configMap: demo-app-file-html'
      type: config
    workloadDefinition:
      apiVersion: apps/v1
      kind: Deployment

```

**Describe the solution you'd like**
can we obtain the status of the corresponding crd through traitRef.name, not through outputs.unique-name
