### ISSUE TITLE
[BUG] should not add AppRevision to workload's label during renderring

### ISSUE THREAD

**Issue by captainroy-hy** [oam-dev/kubevela#1725]
Currently, in the render by appfile, it [adds AppRevision as a label to workloads](https://github.com/oam-dev/kubevela/blob/181bcda66a859cc74ce8561b8e9176d814d16021/pkg/appfile/appfile.go#L315-L319).
Afterward, while `createOrUpdateComponent` in app controller, it will [use component's spec (including raw data of workload) to compute a new revision](https://github.com/oam-dev/kubevela/blob/181bcda66a859cc74ce8561b8e9176d814d16021/pkg/controller/utils/utils.go#L241-L244) of component.
Since workload always has a label recorded `AppRevision`, the revision will vary due to different revision of application, even if there's no other difference between two workloads.

But I think it should not take app's revision into account to compute component's revision.
```yaml
apiVersion: apps/v1
kind: ControllerRevision
metadata:
  creationTimestamp: "2021-05-28T08:34:39Z"
  labels:
    controller.oam.dev/component: metrics-provider
  name: metrics-provider-v2
revision: 2
data:
 ...
  spec:
    workload:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        labels:
          app.oam.dev/appRevision: test-rolling-v2   # <===== only difference
          app.oam.dev/component: metrics-provider
          app.oam.dev/name: test-rolling
          workload.oam.dev/type: webservice
      spec:
        selector:
          matchLabels:
            app.oam.dev/component: metrics-provider
        template:
          metadata:
            labels:
              app.oam.dev/component: metrics-provider
          spec:
            containers:
            - command:
              - ./podinfo
              - stress-cpu=1
              image: stefanprodan/podinfo:4.0.6
              name: metrics-provider
              ports:
              - containerPort: 8080
  status:
    latestRevision:
      name: metrics-provider-v2
      revision: 2
    observedGeneration: 2
```

```yaml
apiVersion: apps/v1
kind: ControllerRevision
metadata:
  name: metrics-provider-v3
  namespace: default
revision: 3
data:
 ...
  spec:
    workload:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        labels:
          app.oam.dev/appRevision: test-rolling-v3   # <===== only difference
          app.oam.dev/component: metrics-provider
          app.oam.dev/name: test-rolling
          workload.oam.dev/type: webservice
      spec:
        selector:
          matchLabels:
            app.oam.dev/component: metrics-provider
        template:
          metadata:
            labels:
              app.oam.dev/component: metrics-provider
          spec:
            containers:
            - command:
              - ./podinfo
              - stress-cpu=1
              image: stefanprodan/podinfo:4.0.6
              name: metrics-provider
              ports:
              - containerPort: 8080
  status:
    latestRevision:
      name: metrics-provider-v3
      revision: 3
    observedGeneration: 3
```
### solution
Compute component revision diff based on workloads' spec rather than the whole entity.
