### ISSUE TITLE
[Proposal] Use Env as a CRD

### ISSUE THREAD

**Issue by zzxwill** [oam-dev/kubevela#176]
# Problem
Env is a **local** resource which means it only exists in one client (a PC client or a server) and is stored in folder `~/.vela`. When a user switches to another client, or accidentally deletes the folder, all Envs will get lost. As apps, workloads, traits are depended on Envs and its namespace, workloads won't be created, and apps will get lost.

For example, by configured to the same Kubernetes cluster:
- list envs
```
# my PC
➜  /Users/zhouzhengxi/.kube vela env
NAME           	CURRENT	NAMESPACE
abc            	       	def
default        	       	default
env-application	       	env-application
env-e2e-hello  	*      	env-e2e-hello
env-hello      	       	env-hello
env-poc        	       	env-poc
env-trait      	       	env-trait
env-workload   	       	env-workload
poc            	       	poc

# Linux Server
[root@iZ2zebdp4vm2jvwggk2oj5Z ~]# vela env
NAME	CURRENT	NAMESPACE
test	*      	test
```

- list apps
```
# my PC
➜  /Users/zhouzhengxi/.kube vela app:ls
No application found in env-e2e-hello namespace.

# Linus Server
[root@iZ2zebdp4vm2jvwggk2oj5Z ~]# vela app:ls
NAME   	WORKLOAD             	TRAITS	STATUS 	CREATED-TIME
poc0818	ContainerizedWorkload	      	UNKNOWN	2020-08-18 11:45:02 +0800 CS
```

# Proposal
Use Env as a CRD in the Kubernetes Cluster, let Kubernetes, as a database, to store the Envs information.
- Apply Env CRD when `vela system:init`
- Create an Env instance when `vela env:init`
- Retrieve Env instances when `vela env [EnvName]`
- Happy to `vela app:xxx` and `vela WorkloadType:run` when switching to another client or have `~/.vela` destroyed.

**Comment by wonderflow** [comment]
ref #160

**Comment by resouer** [comment]
We shouldn't have any local object in KubeVela, user should be able to use Vela without CLI/appfile/dashboard by simply `kubectl`.

**Comment by ryanzhang-oss** [comment]
AFAIK, we store many other things locally beyond env. I suspect that I have run into some unexpected behaviors b/c of the hidden local copy of the app.

**Comment by wonderflow** [comment]
@Cweiping  please create a CRD ( apiVersion=core.oam.dev/v1apha2  kind=Env) to implement our current env.

**Comment by Cweiping** [comment]
> @Cweiping please create a CRD ( apiVersion=core.oam.dev/v1apha2 kind=Env) to implement our current env.

OK.
/assign

**Comment by zzxwill** [comment]
@hongchaodeng Are we planning to implement it by database in the API Server design?

**Comment by Cweiping** [comment]
I think about two ways to achieve it.

1. use an Env object:
```yaml
apiVersion: core.oam.dev/v1alpha2
kind: Env
metadata:
  name: env-sample
spec:
  currentContext: default
  contexts:
  - name: defualt
    namesapce: default
    issuer: ""
  - name: test
    namespace: test1
    issuer: ""
```
2. use envList:
```yaml
apiVersion: core.oam.dev/v1alpha2
kind: Env
metadata:
  name: defualt
  namesapce: default
spec:
  issuer: ""
  email: ""
status:
  # workload status
---
apiVersion: core.oam.dev/v1alpha2
kind: Env
metadata:
  name: test
  namesapce: test
  labels:
    env.core.oam.dev/is-default: 'true'
spec:
  issuer: ""
  email: ""
status:
  # workload status
```
I prefer to use 2, which is easier to expand. What do you think?

**Comment by wonderflow** [comment]
@Cweiping yes,the second is better, you could try to implement it.

**Comment by wonderflow** [comment]
BTW, the Env CRD MUST be clusterscope resource

**Comment by resouer** [comment]
@Cweiping @wonderflow Any reason we do not model cluster in `Environment`? We can simply start from importing a kubeconfig in `ConfigMap`, and let application controller apply the application to that cluster if `environment` field is present.

```yaml
apiVersion: core.oam.dev/v1alpha2
kind: Application
metadata:
  name: sample-appdistributor
spec:
  components:
    - name: instance
      type: webservice
      settings:
        cmd:
          - sleep 100
      traits:
        - name: ingress
    - name: database
      type: mysql
  environment: prod # this app will be applied to this cluster instead of process in local cluster.
```

```yaml
apiVersion: core.oam.dev/v1alpha2
kind: Environment
metadata:
  name: prod
spec:
  kubeconfig: prod-cluster-config
  namespace: project-1
  ...
```
You can check ArgoCD [cluster example](https://itnext.io/argocd-setup-external-clusters-by-name-d3d58a53acb0), or reuse this part from ArgoCD if you want.

Of course we can leave this as following up design, but maybe claim this clear in comment of CRD fields.
