### ISSUE TITLE
TraitDefinition which contains context parameter in CUE Template fail to generate ConfigMap

### ISSUE THREAD

**Issue by yangsoon** [oam-dev/kubevela#1773]
**Describe the bug**

When apply traitDefinition which use `context` in CUE Template, It will fail to generate openapi json schema to ConfigMap

```yaml
# label.yaml
apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  annotations:
    definition.oam.dev/description: "Add labels for your Workload."
  name: labels
  namespace: vela-system
spec:
  appliesToWorkloads:
    - deployments.apps
  schematic:
    cue:
      template: |-
        patch: {
            spec: template: metadata: labels: {
                for k, v in parameter {
                    "\(k)": v
                }
            }
            spec: template: metadata: annotations: {
                "route-name.oam.dev": #routeName
            }
        }
        
        #routeName: "\(context.appName)-\(context.name)"
        
        parameter: [string]: string
```

```
# error log
I0607 18:02:30.370891   60029 traitdefinition_controller.go:116] "Could not store capability in ConfigMap" err="failed to generate OpenAPI v3 JSON schema for capability labels: openapi: #routeName: undefined field \"appName\""
```

**To Reproduce**

```
kubectl apply -f  label.yaml
```
