### ISSUE TITLE
raise `invalid template of trait xxx after merge with parameter and context` for use the same label in dry-run

### ISSUE THREAD

**Issue by shikanon** [oam-dev/kubevela#1792]
**Describe the bug**
when I use the same labels in traits. Use `dry-run` and it raise the error of "invalid template of trait xxx after merge with parameter and context".

**To Reproduce**

the trait like this:
```yaml
apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  name: test
spec:
  appliesToWorkloads:
    - deployments.apps
  schematic:
    cue:
      template: |
        outputs: test: {
          apiVersion: "networking.istio.io/v1beta1"
          kind:       "test"
          metadata:
            name: context.name
            labels: context.output.spec.selector.matchLabels
          labels: parameter.hosts
        }
        parameter: {
          hosts: string
        }
```
and the component is like webservice, it this:
```yaml
apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  name: serverless
  annotations:
    definition.oam.dev/description: "test is a combo of Deployment + Service"
spec:
  workload:
    definition:
      apiVersion: apps/v1
      kind: Deployment
  schematic:
    cue:
      template: |
        output: {
        	apiVersion: "apps/v1"
        	kind:       "Deployment"
        	spec: {
        		selector: matchLabels: {
        			"app.oam.dev/component": context.name
              "app.kubernetes.io/instance": context.name
              "app.kubernetes.io/name": context.name
        			if parameter.addRevisionLabel {
        				"app.oam.dev/appRevision": context.appRevision
        			}
        		}
        
        		template: {
        			metadata: labels: {
        				"app.oam.dev/component": context.name
                "app.kubernetes.io/instance": context.name
                "app.kubernetes.io/name": context.name
        				if parameter.addRevisionLabel {
        					"app.oam.dev/appRevision": context.appRevision
        				}
        			}
        
        			spec: {
        				containers: [{
        					name:  context.name
        					image: parameter.image
        					ports: [
                    for p in parameter.port {
                      containerPort: p.number
                      protocol: "TCP"
                      name: "\(p.protocol)-\(p.number)"
                    },
                  ]
        
        					if parameter["cmd"] != _|_ {
        						command: parameter.cmd
        					}
        
        					if parameter["env"] != _|_ {
        						env: parameter.env
        					}
        
        					if context["config"] != _|_ {
        						env: context.config
        					}
        
        					if parameter["cpu"] != _|_ {
        						resources: {
        							limits:
        								cpu: parameter.cpu
        							requests:
        								cpu: parameter.cpu
        						}
        					}
        
        					if parameter["memory"] != _|_ {
        						resources: {
        							limits:
        								memory: parameter.memory
        							requests:
        								memory: parameter.memory
        						}
        					}
        
        					if parameter["volumes"] != _|_ {
        						volumeMounts: [ for v in parameter.volumes {
        							{
        								mountPath: v.mountPath
        								name:      v.name
        							}}]
        					}
        
        				}]
        
        			if parameter["volumes"] != _|_ {
        				volumes: [ for v in parameter.volumes {
        					{
        						name: v.name
        						if v.type == "pvc" {
        							persistentVolumeClaim: {
        								claimName: v.claimName
        							}
        						}
        						if v.type == "configMap" {
        							configMap: {
        								defaultMode: v.defaultMode
        								name:        v.cmName
        								if v.items != _|_ {
        									items: v.items
        								}
        							}
        						}
        						if v.type == "secret" {
        							secret: {
        								defaultMode: v.defaultMode
        								secretName:  v.secretName
        								if v.items != _|_ {
        									items: v.items
        								}
        							}
        						}
        						if v.type == "emptyDir" {
        							emptyDir: {
        								medium: v.medium
        							}
        						}
        					}}]
        			}
        		}
        	}
        }
        }
        outputs: service: {
        apiVersion: "v1"
        kind:       "Service"
        metadata:
          name: context.name
          labels: 
            "app.oam.dev/component": context.name
        spec: {
          selector: 
            "app.oam.dev/component": context.name
          ports: [
            for p in parameter.port {
              port:       p.number
              targetPort: p.number
              name:       "\(p.protocol)-\(p.number)"
              protocol:   "TCP"
            },
          ]
        }
        }
        parameter: {
        	// +usage=Which image would you like to use for your service
        	// +short=i
        	image: string
        
        	// +usage=Specify the exposion ports
        	port: [...{
            // +usage=The port value
            number: int
            // +usage=The port protocol
            protocol: *"TCP" | string
          }]
        
        	// If addRevisionLabel is true, the appRevision label will be added to the underlying pods
        	addRevisionLabel: *false | bool
        
        	// +usage=Commands to run in the container
        	cmd?: [...string]
        
        	// +usage=Define arguments by using environment variables
        	env?: [...{
        		// +usage=Environment variable name
        		name: string
        		// +usage=The value of the environment variable
        		value?: string
        	}]
        
        	// +usage=Number of CPU units for the service, like `0.5` (0.5 CPU core), `1` (1 CPU core)
        	cpu?: string
        
        	// +usage=Specifies the attributes of the memory resource required for the container.
        	memory?: string
        
        	// +usage=Declare volumes and volumeMounts
        	volumes?: [...{
        		name:      string
        		mountPath: string
        		// +usage=Specify volume type, options: "pvc","configMap","secret","emptyDir"
        		type: "pvc" | "configMap" | "secret" | "emptyDir"
        		if type == "pvc" {
        			claimName: string
        		}
        		if type == "configMap" {
        			defaultMode: *420 | int
        			cmName:      string
        			items?: [...{
        				key:  string
        				path: string
        				mode: *511 | int
        			}]
        		}
        		if type == "secret" {
        			defaultMode: *420 | int
        			secretName:  string
        			items?: [...{
        				key:  string
        				path: string
        				mode: *511 | int
        			}]
        		}
        		if type == "emptyDir" {
        			medium: *"" | "Memory"
        		}
        	}]
        
        }
```
I create the appfile and use `dry-run` the error is raise.
appfile:
```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: abtestdata
spec:
  components:
    - name: abtestdata-component
      type: serverless
      properties:
        image: xxxx
        env:
          - name: "xxxx"
            value: "xxxx"
        port:
          - protocol: "TCP"
            number: 8000
      traits:
      - type: test
        properties:
          hosts: "aaaa"
```
command:
```bash
$ vela dry-run -d ./ -f ../example/appfile-abtest.yaml
I0613 05:39:03.160844     600 request.go:621] Throttling request took 1.0435646s, request: GET:https://119.3.182.101:8443/k8s/clusters/c-nvs5q/apis/xgboostjob.kubeflow.org/v1?timeout=32s
Error: generate OAM objects: cannot generate AppConfig and Components: evaluate template trait=test app=abtestdata-component: invalid template of trait test after merge with parameter and context: outputs.test.labels: conflicting values context.output.spec.selector.matchLabels and parameter.hosts (mismatched types struct and string)
```

**Expected behavior**

it will work well.

**Screenshots**

**Cluster information**

versions:
```bash
$ vela version
Version: refs/tags/v1.0.5
GitRevision: git-53b49ac
GolangVersion: go1.14.15
```
k8s versions:
```bash
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.8-r1-CCE21.3.1.B003-19.38.2", GitCommit:"e796d381b893b3adcf99c50873f28fd6ef7cd7b1", GitTreeState:"clean", BuildDate:"2021-03-23T12:40:52Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by shikanon** [comment]
it resolved, it is the cue syntax error, I use it like helm and think the type:
```yaml
metadata:
    labels: 
        context.name
```
is equal the grammar：
```cue
metadata: {
    labels: context.name
}
```
