### ISSUE TITLE
mechanism for filter annotations or labels that should not be passed through workloads/traits

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela#1801]
**Is your feature request related to a problem? Please describe.**

Now annotations and labels from Application（and AppConfig） will be passed through workloads and traits.

But these annotations and labels are not all necessary and some of them may contain sensitive information that should be filtered.

**Describe the solution you'd like**

We should provide an mechanism to filter. I suggest we should add special annotations, which can contain filter keys.

```
kind: Application
metadata:
  annotations:
     filter.oam.dev/annotation-keys: "specialKey1,specialKey2"
     filter.oam.dev/label-keys: "specialKey1,specialKey2"
```

```
kind: ApplicationConfiguration
metadata:
  annotations:
     filter.oam.dev/annotation-keys: "specialKey1,specialKey2"
     filter.oam.dev/label-keys: "specialKey1,specialKey2"
```

When these keys are specified, the labels and annotations should be filtered by these keys.

Please separate these into two PRs, one for Application, and one for ApplicationConfiguration.
