### ISSUE TITLE
Expect that traits can be expressed by environment in application

### ISSUE THREAD

**Issue by leejanee** [oam-dev/kubevela#1803]
Now,The traits are written in the configuration of the component, as shown below
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: testapp
spec:
  components:
    - name: express-server
      properties:
        cmd:
          - node
          - server.js
        image: oamdev/testapp:v1
        port: 8080
      traits:
        - type: scaller
          properties:
             replicas: 2
      type: webservice
```
But, The traits of the component may be different in different environments. For example, Trait scaller completes the operation  of controlling the replicas of the component ，So the replicas  maybe different in the testing environment and the production environment
```
// testing environment
----------------
...
      traits:
        - type: scaller
          properties:
             replicas: 2

// production environment
-----------------
...
      traits:
        - type: scaller
          properties:
             replicas: 5
```
It is expected that traits can be expressed by environments，and trait changes in a certain environment will not affect the state of the application in other environments

**Comment by hongchaodeng** [comment]
This problem is actually in the scope of configuration management. To solve this problem, we should make use of community tooling like Kustomize or Helm.

First of all, Vela should support deploying Helm chart or Kustomize dir Components via GitOps. Similar to the following:

```yaml
kind: Application
spec:
  components:

  - name: testapp-1
    type: helm-git
    properties:
      chart:
        repository: app1-git-repo
        name: chart-name
        valuesPath: ./chart/prod-values.yaml
        version: 1.0.0

  - name: testapp-2
    type: kustomize-git
    properties:
        repository: app2-git-repo
      path: ./kustomize/prod
```

In the git repo of the apps, it would look like:

```yaml
# app1
/chart
|
|-- dev-values.yaml
|-- prod-values.yaml

# app2
/kustomize
|
|-- base/
|-- dev/
|-- prod/
```

- For app1, deployment to different env will use different values file.
- For app2, deployment to different env will use different folder.

**Comment by leejanee** [comment]
1. Should I need to define different applications in different environments? as shown below
```
----dev.env--------
kind: Application
spec:
  components:

  - name: testapp-1
    type: helm-git
    properties:
      chart:
        repository: app1-git-repo
        name: chart-name
        valuesPath: ./chart/dev-values.yaml
        version: 1.0.0

  - name: testapp-2
    type: kustomize-git
    properties:
        repository: app2-git-repo
      path: ./kustomize/dev

----prod.env--------
kind: Application
spec:
  components:

  - name: testapp-1
    type: helm-git
    properties:
      chart:
        repository: app1-git-repo
        name: chart-name
        valuesPath: ./chart/prod-values.yaml
        version: 1.0.0

  - name: testapp-2
    type: kustomize-git
    properties:
        repository: app2-git-repo
      path: ./kustomize/prod
```
2. I think there is a difference between traits and variables. Trait is the entry point for operation and maintenance of the application. So I don’t agree that the differences of the apps in various environments are realized through variable differences.
