### ISSUE TITLE
Trait change in one environment of the application should not affect the application status in other environments

### ISSUE THREAD

**Issue by leejanee** [oam-dev/kubevela#1805]
An example is shown below
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: testapp
spec:
  components:
    - name: express-server
      properties:
        cmd:
          - node
          - server.js
        image: oamdev/testapp:v1
        port: 8080

---testing.env---
      traits:
        - type: scaller
          properties:
             replicas: 2

---prod.env---
      traits:
        - type: scaller
          properties:
             replicas: 5
```
Trait scaller completes the operation of controlling the replicas of the component. and the replica of scaller trait is different in testing and production environments

When only adjusting the replicas from 2 to 3 in the testing environment, I except that the application status in the production environment will not change in any way
