### ISSUE TITLE
[Feature] refactor vela cli env command to use Initializer

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela#1836]
**Is your feature request related to a problem? Please describe.**

Currently the vela cli just use local files, and create resources such as namespace directly by client.

And now we have [iniitializer](https://github.com/oam-dev/kubevela/blob/master/design/vela-core/environment.md) design and [implementation](https://github.com/oam-dev/kubevela/pull/1829).

We should refactor vela cli to use the initializer.

**Describe the solution you'd like**

1. don't create local files. Create resources and keep metadata in initializer.
2. List/switch environments by get initializer objects from cluster.
3. Get namespace from initializer object.

**Describe alternatives you've considered**

**Additional context**

**Comment by wonderflow** [comment]
```
kind: Initializer
metadata:
  name: test-env
spec:
  appTemplate:
    spec:
      components:
        - name: my-test-namespace
          type: namespace
          properties:
            name: test-namespace
        - name: metadata
          type: configmap
          properties:
            namespace: test-namespace
            email: my.email.com
        - name: my-config1
           type: configmap  
           properties:
               key1: value1
```

**Comment by chivalryq** [comment]
Maybe it's better to keep matadata in Initializer's metadata. Then we only have to add one componentDefinition: namespace, like:
```
kind: Initializer
metadata:
  name: test-env
  label:
    env.oam.dev/namespace:test-namespace
    env.oam.dev/email:my@email.com
spec:
  appTemplate:
    spec:
      components:
        - name: my-test-namespace
          type: namespace
          properties:
            name: test-namespace

```

**Comment by chivalryq** [comment]
Considering our `vela config` command, we should also define a config type component. So a more complete Initializer about env will be:
```yaml
kind: Initializer
metadata:
  name: test-env
  label:
    env.oam.dev/domain: example.com
    env.oam.dev/email: my@email.com
spec:
  appTemplate:
    spec:
      components:
        - name: env-namespace
          type: namespace
          properties:
            name: test-namespace
       - name: env-config
          type: config
          properties:
            var1: foo
            var2: bar 
```
