### ISSUE TITLE
Create two same type component in a appillcation, only one created.

### ISSUE THREAD

**Issue by shikanon** [oam-dev/kubevela#1848]
**Describe the bug**

When I create a application which has tow same components, that the application is running and HEALTHY is ture. But I find only one components created.
If we split two application, they all will be created and running well.

**To Reproduce**

1. A custom components which is make by service, like the above of end.
2. create the application which has two same components. It is only one was created.

components:
```yaml
apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  name: external-resource
  namespace: vela-system
  annotations:
    definition.oam.dev/description: "external-resource is services which is external resource of access map in the cluster, use serivce as DNS resolution"
spec:
  workload:
    definition:
      apiVersion: v1
      kind: Service
  schematic:
    cue:
      template: |
        output: {
            apiVersion: "v1"
            kind:       "Service"
            metadata: {
                name: context.name
            }
            spec: {
                if parameter.dnstype == "A" {
                    type: "ClusterIP"
                    ports: [ for p in parameter.ports {
                        port: p
                        targetPort: p
                        protocol: parameter.protocol
                    }]
                }
                if parameter.dnstype == "CNAME" {
                    type: "ExternalName"
                    externalName: parameter.cname
                }
            }
        }

        outputs: {
            if parameter.dnstype == "A" {
                endpoints: {
                    apiVersion: "V1"
                    kind: "Endpoints"
                    metadata: {
                        name: context.name
                    }
                    subsets: [
                        {
                            addresses: [ for i in parameter.ips {
                                ip: i
                            }]
                            ports: [ for p in parameter.ports {
                                port: p
                                protocol: parameter.protocol
                            }]
                        }
                    ]
                }
            }
        }

        parameter: {
            // +usage=DNS resolution type, only support "A" and "CNAME"
            dnstype: "A" | "CNAME"
            if dnstype == "A" {
                ips: [...string]
                ports: [...int]
                protocol: *"TCP" | "UDP"
            }
            if dnstype == "CNAME" {
                // +usage=cname value, like xxx.com
                cname: string
            }
        }
```

application:
```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: test-external-resource
  namespace: default
spec:
  components:
    - name: dns-merge-a
      type: external-resource
      properties:
        dnstype: "A"
        ips: ["10.1.1.50"]
        ports: [6379]
    - name: dns-merge-cname
      type: external-resource
      properties:
        dnstype: "CNAME"
        cname: "xxxxx.xxxx.com"
```
Apply it, the application running well:
![image](https://user-images.githubusercontent.com/7250620/123394152-67b92480-d5d1-11eb-938a-08c763da552c.png)

But only one be created:
![image](https://user-images.githubusercontent.com/7250620/123394243-7f90a880-d5d1-11eb-989c-38e3edf45263.png)

If I create two application they all create:
![image](https://user-images.githubusercontent.com/7250620/123394337-a058fe00-d5d1-11eb-86da-013d58af4139.png)

![image](https://user-images.githubusercontent.com/7250620/123394362-a818a280-d5d1-11eb-86d9-242cd201e928.png)

![image](https://user-images.githubusercontent.com/7250620/123398341-f891ff00-d5d5-11eb-88ac-4077e3394df9.png)

**Expected behavior**

the components in the application can be created.

**Version**

```bash
$ vela version
Version: refs/tags/v1.0.5
GitRevision: git-53b49ac
GolangVersion: go1.14.15
```

```bash
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.8-r1-CCE21.4.1.B002", GitCommit:"c4e46ab165577f38a3c4ddea6e9ec48e5f44f852", GitTreeState:"clean", BuildDate:"2021-04-25T09:10:07Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by chivalryq** [comment]
Maybe you just simply misspell the `output` as `outputs`? As I fix that, they create two svc.
![image](https://user-images.githubusercontent.com/47812250/123396767-49a0f380-d5d4-11eb-9217-7d2bd3ead996.png)

**Comment by shikanon** [comment]
@chivalryq I create two application split it will done.

**Comment by shikanon** [comment]
@chivalryq  can you output your fix yaml file? thx.

**Comment by shikanon** [comment]
@chivalryq the components it supports the `output` and `outputs`, your can try this application yaml:

```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: test-external-resource-01
  namespace: default
spec:
  components:
    - name: dns-merge-a
      type: external-resource
      properties:
        dnstype: "A"
        ips: ["10.1.1.50"]
        ports: [6379]
```
or :
```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: test-external-resource-02
  namespace: default
spec:
  components:
    - name: dns-merge-cname
      type: external-resource
      properties:
        dnstype: "CNAME"
        cname: "xxxxx.com"
```
it will created well.
