### ISSUE TITLE
Fail to deploy a Application using helm as component

### ISSUE THREAD

**Issue by chivalryq** [oam-dev/kubevela#1868]
**Describe the bug**

I define a componentDefinition and an Application. The componentDef uses keda helm chart. when applied, pods and CRDS are rendered correctly. But there are error logs in controller. 

**To Reproduce**

1. Component YAML: keda-comp.yaml
```yaml
apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  name: keda
  namespace: default
  annotations:
    definition.oam.dev/description: helm chart for keda
spec:
  workload:
    definition:
      apiVersion: apps/v1
      kind: Deployment
  schematic:
    helm:
      release:
        chart:
          spec:
            chart: "keda"
      repository:
        url: "https://kedacore.github.io/charts"
```
2. Application YAML : keda-app.yaml
```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: keda-app
  namespace: default
spec:
  components:
    - name: keda-comp
      type: keda
```
3. Install KubeVela and [Flux Helm chart](https://kubevela.io/docs/install#4-enable-helm-support)
4. apply YAML
```
kubectl apply -f keda-comp.yaml
kubectl apply -f keda-app.yaml
```
5. see error in vela controller
```
E0701 19:42:14.538142   99542 assemble.go:288] "Failed applying a workload option" err="deployments.apps \"keda-app-keda-comp\" not found" workload="default/keda-comp" name="keda-comp"
E0701 19:42:14.538178   99542 assemble.go:219] "Failed assembling manifests for application" err="cannot apply workload option for component \"keda-comp\": deployments.apps \"keda-app-keda-comp\" not found" name="keda-app" revision="keda-app-v1"
E0701 19:42:14.538201   99542 application_controller.go:189] "Failed to apply application manifests" err="cannot assemble application manifests: cannot assemble resources' manifests for application \"keda-app\": cannot apply workload option for component \"keda-comp\": deployments.apps \"keda-app-keda-comp\" not found" application="default/keda-app"
```
**Expected behavior**

no error logs
**Screenshots**

![image](https://user-images.githubusercontent.com/47812250/124120034-d8ff4880-daa5-11eb-8c90-9f0ce047bd98.png)

**KubeVela Version**

**Cluster information**

kind v0.10.0 go1.15.7 darwin/amd64
k8s v1.20.2

**Comment by wonderflow** [comment]
You should not specify workload on helm chart case, so:

```
apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  name: keda
  namespace: default
  annotations:
    definition.oam.dev/description: helm chart for keda
spec:
  schematic:
    helm:
      release:
        chart:
          spec:
            chart: "keda"
      repository:
        url: "https://kedacore.github.io/charts"
```

**Comment by chivalryq** [comment]
It can't work. Seems workload is a required field:
![image](https://user-images.githubusercontent.com/47812250/124121635-b4a46b80-daa7-11eb-8347-f7f5d85dbb55.png)

**Comment by chivalryq** [comment]
workload should be autodetects.core.oam.dev
```yaml
apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  name: keda
  namespace: default
  annotations:
    definition.oam.dev/description: helm chart for keda
spec:
  workload:
    type: autodetects.core.oam.dev
  schematic:
    helm:
      release:
        chart:
          spec:
            chart: "keda"
      repository:
        url: "https://kedacore.github.io/charts"

---

apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: keda-app
  namespace: default
spec:
  components:
    - name: keda-comp
      type: keda

```
