### ISSUE TITLE
[Feature] EnvBinding Controller for Multi cluster deploy and Configuration Management

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela#1881]
In this proposal we will allow users to deploy to multi clusers and do configuration management in exact one Application.

1. Create the application

```
kind: PolicyDefinition
name: EnvBinding
spec:
  schematic: |
    outputs:{
      kind: EnvBinding
      spec: {
        appTemplate: context.components
        envs: parameter.envs
      }
     }
     parameters:
        envs: #ENVS

---
kind: Application
spec:
  components:
  - name: myweb
    type: webservice
    properties:
      image: abc
    traits:
    - type: ingress
      properties:
        domain: xxx.com
  policies:
  - type: EnvBinding
    properties:
      env1:  
        clusterSelector:
         mycluster: abc  
        patch:
          components:
          - name: myweb
            properties:
              image: xyz1 
      env2:  
        clusterSelector:
         mycluster: abc  
        patch:
          components:
          - name: myweb
            properties:
              image: xyz2               
  workflow:
  - name: deploy-app-resource-from-EnvPatchBinding
    type: deploy
    properties:
      env: env1
      appTemplate: "myapp"

  - name: manualApprove
  
  - name: deploy-app-resource-from-EnvPatchBinding
    type: deploy
    properties:
      env: env2
      appTemplate: "myapp"
```

2. When there's a policy and workflow, the application controller will not apply the resources immediately. It will always deploy policy first and then execute the workflow step.

3.  The policy will create a `EnvBinding` object.

```
kind: EnvBinding
spec:
  engine: ocm // by default, the multi-cluster engine is ocm
  appTemplate:
    components:
    - name: myweb
      type: webservice
      properties:
        image: abc
      traits:
      - type: ingress
        properties:
          domain: xxx.com
  envs:
  - name: env1
    placement:
       clusterSelector:
          mycluster: abc  
    patch:
        components:
        - name: myweb
          properties:
            image: xyz1 
   - name: env2
     placement:
       clusterSelector:
          mycluster: abc2
      patch:
        components:
        - name: myweb
          properties:
            image: xyz2
```

4. We need to write a EnvBinding for cluster scheduling and patch configration.
   - Create ocm placement object for cluster selector. We use namespace to represent the cluster. 
   - Patch the configuration for different applications in different envs in memory.
   - Render the application(in memory) to resources by sharing the same logic with the application controller
   - Create Configmaps which store all the resources inside the  ManifestWork framework.

5. The configmap should looks like below. One manifestWork maps with all the resources deployed in the same cluster of one application

```
kind: ConfigMap
data:
  env1:
  - kind: ManifestWork
     metadata: 
        namespace: <selectedClusterNamespace> # the cluster
    spec:
      workload:
        manifests:
          - apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: hello  # the application namespace
              namespace: default
            spec:
              selector:
                matchLabels:
                  app: hello
              template:
                metadata:
                  labels:
                    app: hello
                spec:
                  containers:
                    - name: hello
                      image: quay.io/asmacdo/busybox
                      command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
          - kind: Service
  env2:
    ... 
```

5. The workflow deploys the configmap key one by one in the step.
