### ISSUE TITLE
[Feature] Allow users to specify component revision name

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela#1884]
**Is your feature request related to a problem? Please describe.**

Now our component revision is automatically generated with incremental number. It has some drawbacks:

1. Real users has their own version standard, some version number is business related. They hope the version in kubvela can match with their own revision. So they can have end to end consistency.
2. Users need to apply application first to know the revision, and list/get the created revision, and then specify revision in workflow. If they can specify a revision, the steps can merge to one.

**Describe the solution you'd like**

Add an externalRevision field in component.

```
kind: Application
spec:
  components:
  - name: mycomp
    type: webservice
    externalRevision: my-revision-v1
    properties:
      ...
```

1. If externalRevision specified, generate the controller revision with the specified name.
2. Add webhook validation, if the `externalRevision` already exist, check their spec hash, if not equal, report an error.
3. Don't create or update component revision when specified externalRevision already exist.
4. If  externalRevision not specified，just work as it is now.

**Describe alternatives you've considered**

**Additional context**
