### ISSUE TITLE
[Feature] Create controller for GC(resource tracker) mechanism

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela#1923]
Currently, we create resourceTracker for every revision, and blindly delete the old revision resource tracker to let the GC mechanism of K8s to do the real GC. This mechanism has some drawbacks:

1. It's not flexible enough for different GC strategies, we always rely on application controller to do GC
2. It could cause resources leak when the revision increase but the reconcile fail. For example, some of  resources in revision v1 created except one, and we change the resource so the new revision(v2) created but it still fails. And we create v3. Then we don't have any way to GC v1 resources.

In conclusion, we should just have one resource tracker to one app per environment(cluster). And we should create a resource tracker controller for it.

```
kind: ResourceTracker
metadata:
  generation: 1
  name: myapp-mynamespace
spec:
  resourcesType:  // resourceType record all resources kind related in ResourceTracker
  - apiVersion: xx
    kind: xx
  strategy:
    stopGC: false // rollout process should set it to true
    GCLoopDuration: 10m
  appName: myapp
  appNamespace: mynamespace
  revision: myapp-v2
  components:
  - name: mycomp
     resources:
    - apiVersion: xx2
       name: yy1
    - apiVersion: xx1
  - name: mycomp-2
     resources:
    - apiVersion: xx2
       name: yy1
    - apiVersion: xx1     
status: 
  observedAppRevision: myapp-v2
  lastGCTime: <rfc-time>
  components:
  - name: mycomp
     resources:
    - apiVersion: xx2
       name: yy1
    - apiVersion: xx1
```

1. update resourceTracker by component
2. after application reconcile success, remove unexisting component.
