### ISSUE TITLE
`patch` in TraitDefinition cannot read `context.output`

### ISSUE THREAD

**Issue by tossmilestone** [oam-dev/kubevela#1947]
**Describe the bug**

The `patch` in `TraitDefinition` cannot read `context.output`, and error occurs if reference the `context.output`.

**To Reproduce**
Created the `TraitDefinition` as follow:
```yaml
# Code generated by KubeVela templates. DO NOT EDIT.
apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  annotations:
    definition.oam.dev/description: "A scaler supports start or stop the component."
  name: start-stop-scaler
  namespace: vela-system
spec:
  appliesToWorkloads:
    - webservice
    - worker
  podDisruptive: false
  schematic:
    cue:
      template: |
        import "strconv"
        
        patch: {
        	if parameter.action == "set" {
        		spec: {
        			replicas: parameter.replicas
        		}
        	}
        	if parameter.action == "start" {
        	let anno = context.output.metadata.annotations
        	if anno["app.oam.dev/lastReplicas"] != _|_ {
        		let lastRep = anno["app.oam.dev/lastReplicas"]
        		spec: {
        			replicas: strconv.Atoi(lastRep)
        		}
        	}
        	}
        	if parameter.action == "stop" {
        		metadata: annotations: {
        			"app.oam.dev/lastReplicas": "\(context.output.spec.replicas)"
        		}
        		spec: replicas: 0
        	}
        }
        
        parameter: {
        	// +usage=Specify the action to scale
        	action: *"set" | "start" | "stop"
        	// +usage=Specify the number of workload, only used for action "set"
        	replicas: *1 | uint
        }
 
```
This is a trait designed to start or stop the component. Then create an application to use the trait:
```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: nginx
  namespace: default
spec:
  components:
  - name: web
    properties:
      addRevisionLabel: false
      env: []
      image: nginx
      port: 80
    traits:
    - properties:
        action: "stop"
        replicas: 2
      type: start-stop-scaler
    - properties:
        domain: test.com
        http:
          /: 80
      type: ingress
    type: webservice
```
the creation failed with error:
```
Error from server: error when creating "nginx-app.yaml": admission webhook "validating.core.oam.dev.v1beta1.applications" denied the request: schematic: Invalid value: v1beta1.Application{TypeMeta:v1.TypeMeta{Kind:"Application", APIVersion:"core.oam.dev/v1beta1"}, ObjectMeta:v1.ObjectMeta{Name:"nginx", GenerateName:"", Namespace:"default", SelfLink:"", UID:"fdc5dde6-77dd-4c10-bcfc-3ab6c0cf7a0b", ResourceVersion:"", Generation:1, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:63762450671, loc:(*time.Location)(0x319ffe0)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"core.oam.dev/v1beta1\",\"kind\":\"Application\",\"metadata\":{\"annotations\":{},\"name\":\"nginx\",\"namespace\":\"default\"},\"spec\":{\"components\":[{\"name\":\"web\",\"properties\":{\"addRevisionLabel\":false,\"env\":[],\"image\":\"quay.io/bitnami/nginx\",\"port\":80},\"traits\":[{\"properties\":{\"action\":\"stop\",\"replicas\":2},\"type\":\"start-stop-scaler\"},{\"properties\":{\"domain\":\"test.com\",\"http\":{\"/\":80}},\"type\":\"ingress\"}],\"type\":\"webservice\"}]}}\n"}, OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry{v1.ManagedFieldsEntry{Manager:"kubectl-client-side-apply", Operation:"Update", APIVersion:"core.oam.dev/v1beta1", Time:(*v1.Time)(0xc017515ac0), FieldsType:"FieldsV1", FieldsV1:(*v1.FieldsV1)(0xc017515a20)}}}, Spec:v1beta1.ApplicationSpec{Components:[]v1beta1.ApplicationComponent{v1beta1.ApplicationComponent{Name:"web", Type:"webservice", Properties:runtime.RawExtension{Raw:[]uint8{0x7b, 0x22, 0x61, 0x64, 0x64, 0x52, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x22, 0x3a, 0x66, 0x61, 0x6c, 0x73, 0x65, 0x2c, 0x22, 0x65, 0x6e, 0x76, 0x22, 0x3a, 0x5b, 0x5d, 0x2c, 0x22, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x22, 0x3a, 0x22, 0x71, 0x75, 0x61, 0x79, 0x2e, 0x69, 0x6f, 0x2f, 0x62, 0x69, 0x74, 0x6e, 0x61, 0x6d, 0x69, 0x2f, 0x6e, 0x67, 0x69, 0x6e, 0x78, 0x22, 0x2c, 0x22, 0x70, 0x6f, 0x72, 0x74, 0x22, 0x3a, 0x38, 0x30, 0x7d}, Object:runtime.Object(nil)}, Traits:[]v1beta1.ApplicationTrait{v1beta1.ApplicationTrait{Type:"start-stop-scaler", Properties:runtime.RawExtension{Raw:[]uint8{0x7b, 0x22, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x3a, 0x22, 0x73, 0x74, 0x6f, 0x70, 0x22, 0x2c, 0x22, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x73, 0x22, 0x3a, 0x32, 0x7d}, Object:runtime.Object(nil)}}, v1beta1.ApplicationTrait{Type:"ingress", Properties:runtime.RawExtension{Raw:[]uint8{0x7b, 0x22, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0x3a, 0x22, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x63, 0x6f, 0x6d, 0x22, 0x2c, 0x22, 0x68, 0x74, 0x74, 0x70, 0x22, 0x3a, 0x7b, 0x22, 0x2f, 0x22, 0x3a, 0x38, 0x30, 0x7d, 0x7d}, Object:runtime.Object(nil)}}}, Scopes:map[string]string(nil)}}, RolloutPlan:(*v1alpha1.RolloutPlan)(nil)}, Status:common.AppStatus{ConditionedStatus:v1alpha1.ConditionedStatus{Conditions:[]v1alpha1.Condition(nil)}, Rollout:common.AppRolloutStatus{RolloutStatus:v1alpha1.RolloutStatus{ConditionedStatus:v1alpha1.ConditionedStatus{Conditions:[]v1alpha1.Condition(nil)}, RolloutOriginalSize:0, RolloutTargetSize:0, NewPodTemplateIdentifier:"", LastAppliedPodTemplateIdentifier:"", RollingState:"", BatchRollingState:"", CurrentBatch:0, UpgradedReplicas:0, UpgradedReadyReplicas:0}, LastUpgradedTargetAppRevision:"", LastSourceAppRevision:""}, Phase:"", Components:[]v1alpha1.TypedReference(nil), Services:[]common.ApplicationComponentStatus(nil), ResourceTracker:(*v1alpha1.TypedReference)(nil), LatestRevision:(*common.Revision)(nil)}}: cannot evaluate trait "start-stop-scaler": invalid patch trait start-stop-scaler into workload: compile patch file: metadata.annotations.app.oam.dev/lastReplicas: reference "context" not found
```

**Expected behavior**

In the `patch` struct, the `context.output` should be valid to provide the data of the workload object.

**Screenshots**

**KubeVela Version**
v1.0.6

**Cluster information**

Kubernetes Version: v1.19.9

**Additional context**
