### ISSUE TITLE
[Feature]Create Service/Worker/Job workload and use PodSpec/replicaSet as low level workload

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela#197]
For Workload, we will support having multiple WorkloadDefinition pointing to the same underlying CRD.

In vela, we will have three workload definition as:

- Web Service
- Backend Worker
- One-off Task

• Among them, Web Service and Backend Worker has the same `WorkloadDefinition.definitionRef` pointing to replicaSet.
• WorkloadDefinition will add labels: https://github.com/oam-dev/spec/issues/392

```
kind: WorkloadDefinition
metadata:
  name: web-service
  labels:
    workload.oam.dev/replicable: true # can be scale
    workload.oam.dev/podspecable: true # can be addressed by k8s podSpec
    domain/route: true
spec:
   definitionRef:
       name: replicasets.apps
  extention:
     template: CUE
     defaultTraits:
        - scale
        - route
        - monitor
```

```
kind: WorkloadDefinition
metadata:
  name: backend-worker
  labels:
    workload.oam.dev/replicable: true # can be scale
    workload.oam.dev/podspecable: true # can be addressed by k8s podSpec
spec:
   definitionRef:
       name: replicasets.apps
  extention:
     template: CUE
     defaultTraits:
        - scale
        - monitor
```

```
kind: WorkloadDefinition
metadata:
  name: expose
spec:
   definitionRef:
     name: routes.serving.knative.io
```
---

```
apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: frontend
spec:
  type: web-service
  properties:
    podSpec:
      containers:
        - name: service-tracker-ui
          image: sonofjorel/rudr-web-ui:0.49   
          env:
            - name: FLIGHT_API_ROOT
              value: "foo"
            - name: WEATHER_API_ROOT
              value: "foo"
            - name: QUAKES_API_ROOT
              value: "foo"                  
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
```

Vela create APpConfig:

```
apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: myapp
spec:
  - component: frontend
    traits:
      - trait:
           apiVersion: alibaba.com/v1
           kind: HPA
          spec:
            min: 10
            max: 100
            cpuUsage: 60
      - type: routes.api.alibaba.com
        spec:
           route: /index
      - type: expose
        spec:
          ports:
           - port: 8001
             target: 80
             type: loadbalancer
           - port: 8081
             target: 8080
             type: nodeport
```

https://github.com/crossplane/oam-kubernetes-runtime/issues/182
