### ISSUE TITLE
The deployment of webservice will be updated failed with `addRevisionLabel: true`

### ISSUE THREAD

**Issue by tossmilestone** [oam-dev/kubevela#1981]
**Describe the bug**
If the `addRevisionLabel` of component in `webservice` is `true`, once the component is updated to a new revision, the workload will be updated failed due to the immutateable `selector` field.

**To Reproduce**
Create an application as follow:
```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: nginx
spec:
  components:
  - name: web
    properties:
      addRevisionLabel: true
      env: []
      image: nginx
      port: 80
    type: webservice
```
then update the application to:
```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: nginx
spec:
  components:
  - name: web
    properties:
      addRevisionLabel: true
      env: []
      image: nginx
      port: 8080
    type: webservice
```
The `vela-core controller` will report error message:
```
I0729 10:23:19.052036       1 applicationconfiguration.go:321] "Cannot apply workload" err="cannot apply workload \"web1\": cannot patch object: Deployment.apps \"web1\" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{\"app.oam.dev/appRevision\":\"nginx-v2\", \"app.oam.dev/component\":\"web1\", \"app.oam.dev/name\":\"nginx\"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable"
```
**Expected behavior**
The workload's `selector` is immutable since `apps/v1`, the revision should not be added to the `selector` in the ComponentDefinition of `webservice`.

**Screenshots**

**KubeVela Version**
vela-core: v1.0.6

**Cluster information**

- Kubernetes Version v1.19.9
**Additional context**
