### ISSUE TITLE
Application object can't get correct status while workload rendering failed

### ISSUE THREAD

**Issue by Mr8** [oam-dev/kubevela#2010]
**Application object can't get correct status while workload rendering failed. 
Bellow is part of my component definition, with healthPolicy to checking whether the workload has been reconcile correctly.**

```
apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  name: edgedaemonset
spec:
  status:
    healthPolicy: |
      isHealth: (context.output.status.desiredNumberScheduled > 0) && (context.output.status.currentNumberScheduled == context.output.status.desiredNumberScheduled)
  workload:
    definition:
      apiVersion: extends.apsara-edge.com/v1
      kind: EdgeDaemonSet
```
If the workload rendered failed, the Application object's status only display like bellow.
```
status:
  conditions:
  - lastTransitionTime: "2021-08-03T01:03:45Z"
    reason: Available
    status: "True"
    type: Parsed
  - lastTransitionTime: "2021-08-03T01:03:45Z"
    reason: Available
    status: "True"
    type: Built
  - lastTransitionTime: "2021-08-03T01:03:46Z"
    reason: Available
    status: "True"
    type: Applied
  - lastTransitionTime: "2021-08-03T01:03:46Z"
    message: 'app=zonda, comp=service, check health error: get template context: failed
      to get obj service with gvk extends.apsara-edge.com/v1, Kind=EdgeDaemonSet :
      edgedaemonsets.extends.apsara-edge.com "service" not found'
    reason: ReconcileError
    status: "False"
    type: HealthCheck
```

In other words, the vela's Application status of health-checking may conflicted with the component's controller error output.

The component I applied
```
apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  generation: 1
  labels:
    app.oam.dev/name: zonda
  name: service
  namespace: ppe-cn1334-deploy-test01
spec:
  workload:
    apiVersion: extends.apsara-edge.com/v1
    kind: EdgeDaemonSet
    metadata:
      labels:
       ...
        workload.oam.dev/type: edgedaemonset
      name: service
      namespace: ppe-cn1334-deploy-test01
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              matchExpressions:
              ...
      selector:
        matchLabels:
          ...
      template:
        metadata:
          annotations:
            esk.aliyun.com/cluster-solution: kubernetes
          labels:
            alibabacloud.com/cmdb-app-divided: "true"
            alibabacloud.com/rd-app: service
        spec:
          containers:
          - env:
            - name: a
              value: b
            - name: b
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metdata.name
            image: registry.cn-hangzhou.aliyuncs.com/acs/busybox
            imagePullPolicy: IfNotPresent
            lifecycle:
              postStart:
                httpGet:
                  port: 8080
                  scheme: HTTP
              preStop:
                exec:
                  command:
                  - sh
                  - -c
                  - /home/admin/stop.sh
            name: service
            readinessProbe:
              exec:         # there is why rendered failed, because trait schema incorrect
              - sh
              - -c
              - sleep 1
              failureThreshold: 10
              initialDelaySeconds: 10
              periodSeconds: 2
              successThreshold: 1
              timeoutSeconds: 5
              type: exec
            securityContext:
              privileged: false
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /var/run/container
              name: zonda-test
          dnsConfig:
            options:
            - name: ndots
              value: "1"
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          volumes:
          - emptyDir:
              medium: Memory
            hostPath:
              path: /var/run/container
            name: shm
      updateStrategy:
        type: OnDelete
status:
  latestRevision:
    name: service-v1
    revision: 1
  observedGeneration: 1

```

**Expected behavior**
Application or component display the rendering failed message in Application.status.conditions rather than status health-checking.

**Screenshots**
![image](https://user-images.githubusercontent.com/5935353/127949509-9a157cc2-5c2d-4b6e-86d6-52a65b110b90.png)

**KubeVela Version**
Version: refs/tags/v1.1.0-alpha.4
GitRevision: git-93234e8
GolangVersion: go1.16.5

**Cluster information**
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-03-01T23:35:19Z", GoVersion:"go1.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.9-aliyunedge.1", GitCommit:"687f4f4", GitTreeState:"", BuildDate:"2021-03-08T09:56:01Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
