### ISSUE TITLE
Manage CUE templates more natively

### ISSUE THREAD

**Issue by hongchaodeng** [oam-dev/kubevela#203]
Currently the CUE templates are stored as raw string in yaml:
https://github.com/cloud-native-application/RudrX/blob/3498e5d68aab8fa65039adf0c58d8bf2ddbdbeab/config/samples/workloads/containerizedworkload_definition.yaml#L18

```yaml
    template: |
      #Template: {
      	apiVersion: "core.oam.dev/v1alpha2"
      	kind:       "ContainerizedWorkload"
      	metadata: name: containerized.name
      	spec: {
      		containers: [{
      			image: containerized.image
      			name:  containerized.name
      			ports: [{
      				containerPort: containerized.port
      				protocol:      "TCP"
      				name:          "default"
      			}]
      		}]
      	}
      }
```

This was designed originally due to simplicity. But it is not native since it is losing CUE's syntax and structure.

We should design something more natively to manage CUE templates. For example, use CUE config to manage definition name to template mapping:

<img width="398" alt="E1F6B492-8036-4A33-B0F7-6442BC26037E" src="https://user-images.githubusercontent.com/920884/91208676-62dcc900-e6bf-11ea-912c-c8b02f3c33ce.png">
