### ISSUE TITLE
vela show cannot display parameters for ComponentDefinition helm 

### ISSUE THREAD

**Issue by yangsoon** [oam-dev/kubevela#2034]
**Describe the bug**

**To Reproduce**

1. Install componentDefinition `helm`
```shell
kubectl apply -f https://raw.githubusercontent.com/oam-dev/kubevela/master/vela-templates/addons/fluxcd/definitions/helm-release.yaml
```

```yaml
apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  name: helm
  namespace: vela-system
  annotations:
    definition.oam.dev/description: "helm release is a group of K8s resources from either git repository or helm repo"
spec:
  workload:
    type: autodetects.core.oam.dev
  schematic:
    cue:
      template: |
        output: {
        	apiVersion: "source.toolkit.fluxcd.io/v1beta1"
        	metadata: {
        		name: context.name
        	}
        	if parameter.repoType == "git" {
        		kind: "GitRepository"
        		spec: {
        			url: parameter.repoUrl
        			ref:
        				branch: parameter.branch
        			interval: parameter.pullInterval
        		}
        	}
        	if parameter.repoType == "helm" {
        		kind: "HelmRepository"
        		spec: {
        			interval: parameter.pullInterval
        			url:      parameter.repoUrl
        			if parameter.secretRef != _|_ {
        				secretRef: {
        					name: parameter.secretRef
        				}
        			}
        		}
        	}
        }

        outputs: release: {
        	apiVersion: "helm.toolkit.fluxcd.io/v2beta1"
        	kind:       "HelmRelease"
        	metadata: {
        		name: context.name
        	}
        	spec: {
        		interval: parameter.pullInterval
        		chart: {
        			spec: {
        				chart: parameter.chart
        				sourceRef: {
        					if parameter.repoType == "git" {
        						kind: "GitRepository"
        					}
        					if parameter.repoType == "helm" {
        						kind: "HelmRepository"
        					}
        					name:      context.name
        					namespace: context.namespace
        				}
        				interval: parameter.pullInterval
        			}
        		}
        	}
        }

        parameter: {
        	repoType: "git" | "helm"
        	// +usage=The Git or Helm repository URL, accept HTTP/S or SSH address as git url.
        	repoUrl: string
        	// +usage=The interval at which to check for repository and relese updates.
        	pullInterval: *"5m" | string
        	// +usage=1.The relative path to helm chart for git source. 2. chart name for helm resource
        	chart: string
            // +usage=The Git reference to checkout and monitor for changes, defaults to master branch.
            branch: *"master" | string
            // +usage=The name of the secret containing authentication credentials for the Helm repository.
        	secretRef?: string
        }
```

2. vela show 
```
vela show helm
Error: no matches for kind "" in version ""
```
**Expected behavior**

vela show should show the parameters for helm

**Screenshots**

**KubeVela Version**

**Cluster information**

**Additional context**
