### ISSUE TITLE
[Feature]"kubectl vela dry-run" generate Not a standard k8s yaml, Cannot be apply

### ISSUE THREAD

**Issue by caiwenhao** [oam-dev/kubevela#2105]
kubectl vela dry-run 生成的yaml配置文件不是一个可以用来apply的配置，缺少了name属性。 
一个场景是，希望把vela当作一个模版工具来过渡使用， 应用部署还是基于k8s标准的yaml配置。 

以下是复现过程
./zadig-apps/one-open-oauth.yaml
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: one-open-oauth
spec:
  components:
    - name: one-open-oauth
      type: one-worker
      properties:
        image: registry.cn-hongkong.aliyuncs.com/sailing-soa/emysale-open-oauth:null-1259
        imagePullSecrets:
          - hongkong-aliyuncs
        envFrom:
          - configMapRef:
              name: sailing-mall-env
        port: 8080
        cpu: 100m
        memory: 128Mi
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - sleep 25
      traits:
        - type: labels
          properties:
            project: emysale
        - type: hpa
          properties:
            min: 2
            max: 10
            cpuUtil: 60
```

```
kubectl vela dry-run -f ./zadig-apps/one-open-oauth.yaml  >/tmp/one-open-oauth.yaml
```
```
---
# Application(one-open-oauth) -- Comopnent(one-open-oauth)
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.oam.dev/appRevision: ""
    app.oam.dev/component: one-open-oauth
    app.oam.dev/name: one-open-oauth
    workload.oam.dev/type: one-worker
spec:
  selector:
    matchLabels:
      app.oam.dev/component: one-open-oauth
  template:
    metadata:
      labels:
        app.oam.dev/component: one-open-oauth
        project: emysale
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: sailing-mall-env
        image: registry.cn-hongkong.aliyuncs.com/sailing-soa/emysale-open-oauth:null-1259
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - sleep 25
        name: one-open-oauth
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      imagePullSecrets:
      - name: hongkong-aliyuncs

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.oam.dev/appRevision: ""
    app.oam.dev/component: one-open-oauth
    app.oam.dev/name: one-open-oauth
    trait.oam.dev/resource: service
    trait.oam.dev/type: AuxiliaryWorkload
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.oam.dev/component: one-open-oauth

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app.oam.dev/appRevision: ""
    app.oam.dev/component: one-open-oauth
    app.oam.dev/name: one-open-oauth
    trait.oam.dev/resource: hpa
    trait.oam.dev/type: hpa
  name: one-open-oauth
spec:
  maxReplicas: 10
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 60
        type: Utilization
    type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: one-open-oauth
---
```

* 应用报错
```
kubectl apply -f /tmp/one-open-oauth.yaml -n default
horizontalpodautoscaler.autoscaling/one-open-oauth created
error when retrieving current configuration of:
Resource: "apps/v1, Resource=deployments", GroupVersionKind: "apps/v1, Kind=Deployment"
Name: "", Namespace: "default"
from server for: "/tmp/one-open-oauth.yaml": resource name may not be empty
error when retrieving current configuration of:
Resource: "/v1, Resource=services", GroupVersionKind: "/v1, Kind=Service"
Name: "", Namespace: "default"
from server for: "/tmp/one-open-oauth.yaml": resource name may not be empty
```
