### ISSUE TITLE
Workflow will render component without resourceName

### ISSUE THREAD

**Issue by FogDong** [oam-dev/kubevela#2118]
**Describe the bug**

Workflow will render component without resourceName

```yaml
steps:
      - message: 'step apply: step #up__: step apply-workload: run step(provider=kube,do=apply):
          cannot apply manifest, name: "" apiVersion: "apps/v1" kind: "Deployment":
          cannot get object: resource name may not be empty'
```

**To Reproduce**

```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: first-vela-workflow
  namespace: default
spec:
  components:
  - name: nginx-server
    type: webservice
    properties:
      image: nginx:1.21
      port: 80
  workflow:
    steps:
      - name: nginx-server
        type: apply-component
        properties:
          component: nginx-server
```

**Expected behavior**

**Screenshots**

**KubeVela Version**

**Cluster information**

**Additional context**

/assign
