### ISSUE TITLE
When component properties don't meet the parameter of the ComponentDefinition, it will hit 'EOF' event

### ISSUE THREAD

**Issue by zzxwill** [oam-dev/kubevela#2132]
**Describe the bug**

When component properties don't meet the parameter of the ComponentDefinition, it will hit 'EOF' error

**To Reproduce**

1. Enable addon `fluxcd` 

2. Apply the application
```
        - name: grafana
          properties:
            chart: grafana
            version: 6.14.1
            repoType: helm
            repoUrl: https://grafana.github.io/helm-charts
            targetNamespace: observability
            releaseName: grafana
          type: helm
```

3. Describe the application

```
Events:
  Type     Reason        Age                   From         Message
  ----     ------        ----                  ----         -------
  Warning  FailedRender  15m (x12 over 15m)    Application  evaluate base template component=grafana app=grafana: EOF
```

**Expected behavior**

`EOF` won't do any help for trouble-shooting.

**Screenshots**

**KubeVela Version**

**Cluster information**

**Additional context**
