### ISSUE TITLE
Get conflicting value when try to patch component name in WorkflowStepDef

### ISSUE THREAD

**Issue by kinsolee** [oam-dev/kubevela#2144]
**Describe the bug**

https://github.com/oam-dev/kubevela/issues/2118 fixed by https://github.com/oam-dev/kubevela/pull/2119 making sure the component name must exist before persisting into storage, which blocks the possibility of patching the component name in workflow, even though we don't declare metadata.name in component templates.

**To Reproduce**

From my way of using workflow, I'd like to define a `workflowstep` to apply multiple versions by patching version information into fields including pod image, the name of deployment and labels so on, but use the same component.

The case below is based on official templates.

I created a `WorkflowStepDef` which will patch the deployment name of component:
```
import (
	"vela/op"
)

"demo-apply": {
	annotations: {}
	attributes: {}
	description: ""
	labels: {}
	type: "workflow-step"
}

template: {
	parameter: {
		image: string
		versions: [...string]
	}
	// apply workload to kubernetes cluster
	apply: op.#Steps & {
		let applyComponents = op.#Steps & {
			versionTag: string
			load:    op.#Load @step(1)

			let workloadPatch = {
                                 // patch the component name here.
				metadata: name: "\(context.name)-\(versionTag)"
				metadata: labels: "version": versionTag
			}

			workloads: op.#Steps & {
				for compName, component in load.value {
					"workload\(compName)": op.#Apply & {
						value: component.workload
						patch: workloadPatch
					}
					"\(compName)Traits": op.#Steps & {
						_key: "trait.oam.dev/resource"
						if component.auxiliaries != _|_ {
							for o in component.auxiliaries {
								let patchName = "\(context.name)-\(versionTag)"

								let patchTrait = {
										metadata: name: patchName
										metadata: labels: "version": "\(versionTag)"
										spec: selector: version: versionTag
									}

								"\(o.metadata.labels[_key])": op.#Apply & {
									value: o
									patch: {
										metadata: name: patchName
										metadata: patchTrait
									}
								}
							}
						}
					} @step(3)
				}
			} @step(2)
		}
		for i, v in parameter.versions {
			"apply\(v)": applyComponents & {
				versionTag: v
			} @step(i)
		}
	}
}

```

Apply an Application resource:
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: demo
  namespace: default
spec:
  components:
    - name: demo
      type: webservice
      properties:
        ports:
          - port: 8000
        image: "crccheck/hello-world"
      traits:
        - type: expose
          properties:
            domain: example.com
            http:
              tcp: 8080
  workflow:
    steps:
      - name: apply
        type: demo-apply
        properties:
          image: "crccheck/hello-world"
          versions:
            - "v1.1.0"
            - "v1.2.0"
            - "v1.3.1"
```

Got conflicting error in the `status.workflow` of application:
```
status:
...
  workflow:
      appRevision: demo-v1
      contextBackend:
        apiVersion: v1
        kind: ConfigMap
        name: workflow-demo-v1
        uid: 6d1ec5cb-dac2-4d69-9506-aff1e8f18a5d
      steps:
      - message: 'step apply: step applyv1.1.0: step workloads: step demoTraits: step tcp: run step(provider=kube,do=apply): result check err: metadata.name: conflicting values "demo" and "demo-v1.1.0"'
        name: apply
        phase: failed
        reason: Execute
        resourceRef: {}
        type: demo-apply
      suspend: false
      terminated: false
```

**Expected behavior**

I think we should allow workflow to overwrite the concrete fields instead of just unifying it when we do `op.#Apply` patch. Now we have to delete the fields from the component/trait def template if we want to patch a field in case of conflicting. This could also be a cumbersome experience as we have to check the fields one by one if we define many components/traits.

We may see the loaded field values from `op.#Load` as default values and allow to patch if we want.

**Screenshots**

**KubeVela Version**
Version: master
GitRevision: git-a88d61ca
GolangVersion: go1.17
