### ISSUE TITLE
Ingress trait couldn't get PORT properly

### ISSUE THREAD

**Issue by BinaryHB0916** [oam-dev/kubevela#2188]
Using example in the doc:

```
➜  Desktop cat <<EOF | kubectl apply -f -
# YAML 文件开始
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: ingress-app
spec:
  components:
    - name: express-server
      type: webservice
      properties:
        image: crccheck/hello-world
        port: 8000
      traits:
        - type: ingress
          properties:
            domain: testsvc.example.com
            http:
              "/": 8000
# YAML 文件结束
EOF
```

From `kubectl get application ingress-app -o yaml` we have message:  No loadBalancer found, visiting by using 'vela port-forward ingress-app --route'

but when typing in vela port-forward ingress-app --route, it gets:

Error: applicationconfigurations.core.oam.dev "ingress-app" not found
