### ISSUE TITLE
[Feature] Periodical health check mechansim for Application

### ISSUE THREAD

**Issue by captainroy-hy** [oam-dev/kubevela#2227]
**Is your feature request related to a problem? Please describe.**

The current app controller will do health checking in long time interval(60min, same as sync time).
We need to check application health status in short interval, i.g., 30s. 

**Describe the solution you'd like**

With help of `health-scope-binding` policy, we can put all components of an application into a health scope.
The health scope controller will check health status periodically and patch checking result into application's status.

**Describe alternatives you've considered**

**Additional context**

**Comment by wonderflow** [comment]
1. The policy name should be `health-check`
2. The policy should receive definition.healthPolicy CUE as input to be the default health check policy, users can define their own by other inputs.

**Comment by hongchaodeng** [comment]
> With help of health-scope-binding policy ...

There is not need to call it **health-scope-xxx** anymore. Just call it health policy. For Component per se, just call it health trait.

**Comment by captainroy-hy** [comment]
A healthy application sample.
```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  finalizers:
  - app.oam.dev/resource-tracker-finalizer
  generation: 1
  name: policy-test
  namespace: default
spec:
  components:
  - name: express-server
    traits:
    - properties:
        domain: testsvc.example.com
        http:
          /: 8000
      type: ingress
    type: webservice
  - name: nginx-server
    type: webservice
  - name: mynginx
    type: webservice
  policies:
  - name: health-check
    type: health
  workflow:
...
status:
  conditions:
  ...
  - lastTransitionTime: "2021-09-03T01:57:01Z"
    reason: AllComponentsHealthy
    status: "True"
    type: Healthy
  ...
  services:
  - healthy: true
    name: nginx-server
    scopes:
    - apiVersion: core.oam.dev/v1alpha2
      kind: HealthScope
      name: health-check
      namespace: default
      uid: 93345ca1-70df-4bfd-9e37-d28539cb839f
    workloadDefinition:
      apiVersion: apps/v1
      kind: Deployment
  - healthy: true
    name: mynginx
    scopes:
    - apiVersion: core.oam.dev/v1alpha2
      kind: HealthScope
      name: health-check
      namespace: default
      uid: 93345ca1-70df-4bfd-9e37-d28539cb839f
    workloadDefinition:
      apiVersion: apps/v1
      kind: Deployment
  - healthy: true
    name: express-server
    scopes:
    - apiVersion: core.oam.dev/v1alpha2
      kind: HealthScope
      name: health-check
      namespace: default
      uid: 93345ca1-70df-4bfd-9e37-d28539cb839f
    traits:
    - healthy: true
      message: |
        No loadBalancer found, visiting by using 'vela port-forward policy-test'
      type: ingress
    workloadDefinition:
      apiVersion: apps/v1
      kind: Deployment
  status: running
  ...
```
An unhealthy application sample.
```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  finalizers:
  - app.oam.dev/resource-tracker-finalizer
  generation: 2
  name: policy-test
  namespace: default
spec:
  components:
  - name: express-server
    traits:
    - properties:
        domain: testsvc.example.com
        http:
          /: 8000
      type: ingress
    type: webservice
  - name: nginx-server
    type: webservice
  - name: bad-server
    properties:
      image: boom:boom
      port: 80
    type: webservice
  policies:
  - name: health-check
    properties:
      probeInterval: 10
    type: health
  workflow:
...
status:
  conditions:
...
  - lastTransitionTime: "2021-09-03T02:10:07Z"
    reason: UnHealthyOrUnknownComponents
    status: "False"
    type: Healthy
...
  services:
  - healthy: false
    message: 'Ready:0/1 '
    name: bad-server
    scopes:
    - apiVersion: core.oam.dev/v1alpha2
      kind: HealthScope
      name: health-check
      namespace: default
      uid: 93345ca1-70df-4bfd-9e37-d28539cb839f
    workloadDefinition:
      apiVersion: apps/v1
      kind: Deployment
  - healthy: true
    message: 'Ready:1/1 '
    name: nginx-server
    scopes:
    - apiVersion: core.oam.dev/v1alpha2
      kind: HealthScope
      name: health-check
      namespace: default
      uid: 93345ca1-70df-4bfd-9e37-d28539cb839f
    workloadDefinition:
      apiVersion: apps/v1
      kind: Deployment
  - healthy: true
    message: 'Ready:1/1 '
    name: express-server
    scopes:
    - apiVersion: core.oam.dev/v1alpha2
      kind: HealthScope
      name: health-check
      namespace: default
      uid: 93345ca1-70df-4bfd-9e37-d28539cb839f
    traits:
    - healthy: true
      message: |
        No loadBalancer found, visiting by using 'vela port-forward policy-test'
      type: ingress
    workloadDefinition:
      apiVersion: apps/v1
      kind: Deployment
  status: running
...

```
