### ISSUE TITLE
[BUG] workload ownerReference field lost because rollout failed

### ISSUE THREAD

**Issue by Chwetion** [oam-dev/kubevela#2246]
**Describe the bug**
workload ownerReference field lost because rollout failed

**To Reproduce**
1. `kubectl create ns rollout-trait-test`
2. `kubectl create -f application.yaml`
3. `kubectl apply -f application-v2.yaml`

yaml file as follow:
```yaml
# application.yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: rollout-trait-test
  namespace: rollout-trait-test
spec:
  components:
    - name: express-server
      type: webservice
      properties:
        image: stefanprodan/podinfo:4.0.3
      traits:
        - type: rollout
          properties:
            targetSize: 5
            rolloutBatches:
              - replicas: 2
              - replicas: 3

# application-v2.yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: rollout-trait-test
  namespace: rollout-trait-test
spec:
  components:
    - name: express-server
      type: webservice
      properties:
        image: stefanprodan/podinfo:4.0.3
        cpu: "0.2"
      traits:
        - type: rollout
          properties:
            targetSize: 5
            rolloutBatches:
              - replicas: 5
              - replicas: 0
```

and then will see rollout failed:
```
[root@vela app-upgrade]# kubectl get rollout
NAME      TARGET   UPGRADED   READY   BATCH-STATE         ROLLING-STATE   AGE
testapp   3        0          0       batchInitializing   rolloutFailed   12m
```

use `kubectl get deploy -n rollout-trait-test -oyaml | grep ownerRef` cannot get anything

**Expected behavior**
best expectation: generate 5 pod of v2 application.
even if rollout failed, ownerReference should not lost in workload, it will cannot be managed by app.

**KubeVela Version**
```
[root@vela app-upgrade]# helm list -n vela-system
NAME    	NAMESPACE  	REVISION	UPDATED                                	STATUS  	CHART          	APP VERSION
kubevela	vela-system	1       	2021-08-24 06:42:25.162278935 -0400 EDT	deployed	vela-core-1.1.0	1.1.0
```

**Cluster information**
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.15", GitCommit:"73dd5c840662bb066a146d0871216333181f4b64", GitTreeState:"clean", BuildDate:"2021-01-13T13:14:05Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.18) exceeds the supported minor version skew of +/-1
```
