### ISSUE TITLE
[Bug]Creating an application prompted that the health check failed

### ISSUE THREAD

**Issue by jingliming** [oam-dev/kubevela#2282]
**Describe the bug**
check health error: evaluate health status: isHealth: undefined field "service"

**To Reproduce**
1. The YAML files of Component/Trait I used.
``` yaml
# Code generated by KubeVela templates. DO NOT EDIT.
apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  name: stateless-component
  namespace: vela-system
  annotations:
    definition.oam.dev/description: "Describes long-running, scalable, containerized services that have a stable network endpoint to receive external network traffic from customers."
spec:
  workload:
    definition:
      apiVersion: apps/v1
      kind: Deployment
  schematic:
    cue:
      template: |
        output: {
          apiVersion: "apps/v1"
          kind:       "Deployment"
          spec: {
            selector: matchLabels: {
              "app.oam.dev/component": context.name
              if parameter.addRevisionLabel {
                "app.oam.dev/appRevision": context.appRevision
              }
            }

            template: {
              metadata: labels: {
                "app.oam.dev/component": context.name
                if parameter.addRevisionLabel {
                  "app.oam.dev/appRevision": context.appRevision
                }
              }

              spec: {
                containers: [{
                  name:  context.name
                  image: parameter.image
                  ports: [{
                    containerPort: parameter.port
                  }]

                  if parameter["cmd"] != _|_ {
                    command: parameter.cmd
                  }

                  if parameter["args"] != _|_ {
                    args: parameter.args
                  }

                  if parameter["env"] != _|_ {
                    env: parameter.env
                  }

                  if context["config"] != _|_ {
                    env: context.config
                  }

                  if parameter["cpu"] != _|_ {
                    resources: {
                      limits:
                        cpu: parameter.cpu.limits
                      requests:
                        cpu: parameter.cpu.requests
                    }
                  }

                  if parameter["memory"] != _|_ {
                    resources: {
                      limits:
                        memory: parameter.memory.limits
                      requests:
                        memory: parameter.memory.requests
                    }
                  }

                  if parameter["volumes"] != _|_ {
                    volumeMounts: [ for v in parameter.volumes {
                      {
                        mountPath: v.mountPath
                        name:      v.name
                      }}]
                  }

                  if parameter["livenessProbe"] != _|_ {
                    livenessProbe: parameter.livenessProbe
                  }

                  if parameter["readinessProbe"] != _|_ {
                    readinessProbe: parameter.readinessProbe
                  }

                }]
                
              if parameter["imagePullSecrets"] != _|_ {
                imagePullSecrets: parameter.imagePullSecrets
              }

              if parameter["volumes"] != _|_ {
                volumes: [ for v in parameter.volumes {
                  {
                    name: v.name
                    if v.type == "pvc" {
                      persistentVolumeClaim: {
                        claimName: v.claimName
                      }
                    }
                    if v.type == "configMap" {
                      configMap: {
                        defaultMode: v.defaultMode
                        name:        v.cmName
                        if v.items != _|_ {
                          items: v.items
                        }
                      }
                    }
                    if v.type == "secret" {
                      secret: {
                        defaultMode: v.defaultMode
                        secretName:  v.secretName
                        if v.items != _|_ {
                          items: v.items
                        }
                      }
                    }
                    if v.type == "emptyDir" {
                      emptyDir: {
                        medium: v.medium
                      }
                    }
                  }}]
              }
            }
          }
        }
        }
        parameter: {
          // +usage=Which image would you like to use for your service
          // +short=i
          image: string

          // +usage=Which image pull secret would you like to use for your deploymet
          imagePullSecrets: [...{
            name: string
          }]

          // +usage=Which port do you want customer traffic sent to
          // +short=p
          port: *80 | int

          // +ignore
          // +usage=If addRevisionLabel is true, the appRevision label will be added to the underlying pods
          addRevisionLabel: *false | bool

          // +usage=Commands to run in the container
          cmd?: [...string]

          args?: [...string]

          // +usage=Define arguments by using environment variables
          env?: [...{
            // +usage=Environment variable name
            name: string
            // +usage=The value of the environment variable
            value?: string
            // +usage=Specifies a source the value of this var should come from
            valueFrom?: {
              // +usage=Selects a key of a secret in the pod's namespace
              secretKeyRef: {
                // +usage=The name of the secret in the pod's namespace to select from
                name: string
                // +usage=The key of the secret to select from. Must be a valid secret key
                key: string
              }
            }
          }]

          // +usage=Number of CPU units for the service, like `0.5` (0.5 CPU core), `1` (1 CPU core)
          cpu?: #Cpu

          // +usage=Specifies the attributes of the memory resource required for the container.
          memory?: #Memory

          // +usage=Declare volumes and volumeMounts
          volumes?: [...{
            name:      string
            mountPath: string
            // +usage=Specify volume type, options: "pvc","configMap","secret","emptyDir"
            type: "pvc" | "configMap" | "secret" | "emptyDir"
            if type == "pvc" {
              claimName: string
            }
            if type == "configMap" {
              defaultMode: *420 | int
              cmName:      string
              items?: [...{
                key:  string
                path: string
                mode: *511 | int
              }]
            }
            if type == "secret" {
              defaultMode: *420 | int
              secretName:  string
              items?: [...{
                key:  string
                path: string
                mode: *511 | int
              }]
            }
            if type == "emptyDir" {
              medium: *"" | "Memory"
            }
          }]

          // +usage=Instructions for assessing whether the container is alive.
          livenessProbe?: #HealthProbe

          // +usage=Instructions for assessing whether the container is in a suitable state to serve traffic.
          readinessProbe?: #HealthProbe
        }

        #Cpu: {
          limits:   string
          requests: string
        }

        #Memory: {
          limits:   string
          requests: string
        }

        #HealthProbe: {

          // +usage=Instructions for assessing container health by executing a command. Either this attribute or the httpGet attribute or the tcpSocket attribute MUST be specified. This attribute is mutually exclusive with both the httpGet attribute and the tcpSocket attribute.
          exec?: {
            // +usage=A command to be executed inside the container to assess its health. Each space delimited token of the command is a separate array element. Commands exiting 0 are considered to be successful probes, whilst all other exit codes are considered failures.
            command: [...string]
          }

          // +usage=Instructions for assessing container health by executing an HTTP GET request. Either this attribute or the exec attribute or the tcpSocket attribute MUST be specified. This attribute is mutually exclusive with both the exec attribute and the tcpSocket attribute.
          httpGet?: {
            // +usage=The endpoint, relative to the port, to which the HTTP GET request should be directed.
            path: string
            // +usage=The TCP socket within the container to which the HTTP GET request should be directed.
            port: int
            scheme: string
            httpHeaders?: [...{
              name:  string
              value: string
            }]
          }

          // +usage=Instructions for assessing container health by probing a TCP socket. Either this attribute or the exec attribute or the httpGet attribute MUST be specified. This attribute is mutually exclusive with both the exec attribute and the httpGet attribute.
          tcpSocket?: {
            // +usage=The TCP socket within the container that should be probed to assess container health.
            port: int
          }

          // +usage=Number of seconds after the container is started before the first probe is initiated.
          initialDelaySeconds: *0 | int

          // +usage=How often, in seconds, to execute the probe.
          periodSeconds: *10 | int

          // +usage=Number of seconds after which the probe times out.
          timeoutSeconds: *1 | int

          // +usage=Minimum consecutive successes for the probe to be considered successful after having failed.
          successThreshold: *1 | int

          // +usage=Number of consecutive failures required to determine the container is not alive (liveness probe) or not ready (readiness probe).
          failureThreshold: *3 | int
        }

```
``` yaml
# Code generated by KubeVela templates. DO NOT EDIT.
apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  annotations:
    definition.oam.dev/description: "Enable public web traffic for the component."
  name: bizworks-ingress-new
  namespace: vela-system
spec:
  status:
    customStatus: |-
      let igs = context.outputs.ingress.status.loadBalancer.ingress
      if igs == _|_ {
        message: "No loadBalancer found, visiting by using 'vela port-forward " + context.appName + " --route'\n"
      }
      if len(igs) > 0 {
        if igs[0].ip != _|_ {
          message: "Visiting URL: " + context.outputs.ingress.spec.rules[0].host + ", IP: " + igs[0].ip
        }
        if igs[0].ip == _|_ {
          message: "Visiting URL: " + context.outputs.ingress.spec.rules[0].host
        }
      }
    healthPolicy: |
      isHealth: len(context.outputs.service.spec.clusterIP) > 0
  appliesToWorkloads:
    - deployments.apps
  podDisruptive: false
  schematic:
    cue:
      template: |
        // trait template can have multiple outputs in one trait
        for _, v in parameter.route {
        	outputs: "\(v.serviceName)": {
        		apiVersion: "v1"
        		kind:       "Service"
        		metadata:
        			name: v.serviceName
        		spec: {
        			selector: {
        				"app.oam.dev/component": context.name
        			}
        			type: v.serviceType
        			ports: [
        				{
        					port:       v.servicePort
        					protocol:   v.serviceProtocolType
        					targetPort: v.port
        				},
        			]
        		}
        	}
        	if v["ingressName"] != _|_ {
        		outputs: "\(v.ingressName)": {
        			apiVersion: "networking.k8s.io/v1beta1"
        			kind:       "Ingress"
        			metadata:
        				name: v.ingressName
        			spec: {
        				if v["ingressProtocolType"] == "HTTPS" {
        					tls: [{
        						hosts: [
        							v.domain,
        						]
        						secretName: v.secretName
        					}]
        				}
        				rules: [{
        					host: v.domain
        					http: {
        						paths: [
        							{
        								path: v.path
        								backend: {
        									serviceName: v.serviceName
        									servicePort: v.servicePort
        								}
        							},
        						]
        					}
        				}]
        			}
        		}
        	}
        }

        parameter: {
        	route: [...{
        		// +usage=Specify the port your server want to expose
        		port: int
        		// +usage=Specify the protocol your service want to expose
        		serviceProtocolType: string
        		// +usage=Specify the name your service want to expose
        		serviceName: string
        		// +usage=Specify the port your service want to expose
        		servicePort: int
        		// +usage=Specify the type your service want to expose
        		serviceType: string
        		// +usage=Specify the type your ingress want to expose
        		ingressProtocolType: string
        		// +usage=Specify the name your ingress want to expose
        		ingressName: string
        		// +usage=Specify the domain you want to expose
        		domain: string
        		// +usage=Specify the path you want to expose
        		path: string
        		// +usage=Specify the tls secret you want to use
        		secretName: string
        	}]
        }

```
2. The YAML file of Application I applied.
``` yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: first-vela-app
  namespace: mingyuan1
spec:
  components:
    - name: express-server
      type: webservice
      properties:
        image: crccheck/hello-world
        port: 8000
        env:
          - name: "test-s"
            value: "value-s"
      traits:
        - type: rollout
          properties:
            targetSize: 2
            rolloutBatches:
              - replicas: 1
              - replicas: 1
        - type: bizworks-ingress-new
          properties:
            route:
              - port:                8080
                serviceProtocolType: "TCP"
                serviceName:         "service-clusterip"
                servicePort:         80
                serviceType:         "ClusterIP"
                ingressProtocolType: "HTTP"
                ingressName:         "ingress1"
                domain:              "appcode.projectcode-envcode.com"
                path:                "/"
              - port:                8080
                serviceProtocolType: "TCP"
                serviceName:         "service-nodeport"
                servicePort:         80
                serviceType:         "NodePort"

```
3. Other operations I have done.
'app=first-vela-app, comp=express-server, trait=bizworks-ingress-new,
       check health error: evaluate health status: isHealth: undefined field "service"'

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/9865050/133069831-f4e85c34-cfa8-48ca-983a-2e94cb7bf610.png)
![image](https://user-images.githubusercontent.com/9865050/133070001-b75f173f-1356-4706-b34f-3f5f414b69cf.png)

**KubeVela Version**

**Cluster information**

**Additional context**
