### ISSUE TITLE
[Dashboard][LowPriority] support identity workload/trait icon in workloaddefinition/traitdefinition

### ISSUE THREAD

**Issue by zzxwill** [oam-dev/kubevela#229]
In order to help users to install capability from those workloads/traits list, an icon representing the capability will do some help at first glance.
![image](https://user-images.githubusercontent.com/2805315/91546422-fe3a9c00-e954-11ea-97ce-7675edf4d64c.png)

So we can add `metadata.icon` in WorkloadDefinition/TraitDefintion and we should encourage capability center builder for the convension.

```
apiVersion: core.oam.dev/v1alpha2
kind: WorkloadDefinition
metadata:
  name: containerizedworkloads.core.oam.dev
  icon: https://xxx.com/imgs/containerized.png
```

The effect might looks similar as below.
![image](https://user-images.githubusercontent.com/2805315/91546647-5ec9d900-e955-11ea-8618-27679f838f72.png)

![image](https://user-images.githubusercontent.com/2805315/91546671-65f0e700-e955-11ea-8b05-dd4f3fb16168.png)
