### ISSUE TITLE
[Feature] Built-in support for basic stateful type components.

### ISSUE THREAD

**Issue by barnettZQG** [oam-dev/kubevela#2364]
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: wordpress
spec:

  policies:
    - name: health
      type: health
  components:
    - name: wordpress
      type: webservice
      properties:
        image: "wordpress:latest"
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql:3306
        - name: WORDPRESS_DB_USER
          value: wordpress
        - name: WORDPRESS_DB_PASSWORD
          value: wordpress
        - name: WORDPRESS_DB_NAME
          value: wordpress
      traits:
      - type: ingress-1-20
        properties:
          http:
            "/": 80
          domain: wordpress.example.ceshi.cc
    - name: mysql
      type: webservice
      properties:
        image: mysql:5.7
        env:
          - name: WORDPRESS_DB_HOST
            value: db:3306
          - name: WORDPRESS_DB_USER
            value: wordpress
          - name: WORDPRESS_DB_PASSWORD
            value: wordpress
          - name: WORDPRESS_DB_NAME
            value: wordpress
        port: 3306
        volumes: 
          - name: data
            mountPath: /var/lib/mysql
            type: pvc
            claimName: wordpress-db-data
      traits:
      - type: expose
        properties: 
          port: 
          - 3306
```

Above is a simple WordPress application configuration. The most basic requirement is that I want MySQL components to be deployed using Statefulset.
