### ISSUE TITLE
[Feature] built-in support for directory persistence traits

### ISSUE THREAD

**Issue by barnettZQG** [oam-dev/kubevela#2365]
```
volumes: 
   - name: data
      mountPath: /var/lib/mysql
      type: pvc
      claimName: wordpress-db-data
```
When the webserver component type is used, the storage requirements can be defined using the above parameters.
But before that, users had to create PVC,  this complexity increases. We support a trait where users define mount paths, shareability, and capacity requirements.
