### ISSUE TITLE
[Feature] Support dependsOn in Component deployment DAG

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela#2370]
Such as: 

![image](https://user-images.githubusercontent.com/2173670/134886565-18c062f5-f1cc-4687-a5ca-b6b0cbef9995.png)

Or

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: wordpress-with-mysql
  namespace: default
spec:
  components:
    - name: mysql
      type: helm
      properties:
        repoType: helm
        url: https://charts.bitnami.com/bitnami
        chart: mysql
        version: "8.8.2"
    - name: wordpress
      type: helm
      inputs:
        # dependsOn the mysql component to be ready
        - dependsOn: mysql
      properties:
        repoType: helm
        url: https://charts.bitnami.com/bitnami
        chart: wordpress
        version: "12.0.3"
```

> 希望能够在Application里直观的看到到底哪些component存在依赖关系. 因为依赖关系是个比较通用的能力，执行过程都是DAG工作流，就看是否可以更友好一点

**Comment by barnettZQG** [comment]
DependsOn and Inputs must be in the same configuration, otherwise, there will be conflict。

Like this?  Compatible with inputs as first-level parameters.
```
dependsOn: 
 - name: mysql
    inputs:
    - from: connInfo
       parameterKey: connInfo
 - name: redis
```

**Comment by hongchaodeng** [comment]
The dependsOn should be a separate field defined like below:

```yaml
components:
  - name: mysql
    type: helm
    properties:
      repoType: helm
      url: https://charts.bitnami.com/bitnami
      chart: mysql
      version: "8.8.2"
  - name: wordpress
    type: helm
    # dependsOn the mysql component to be ready
    dependsOn:
      - mysql
    properties:
      repoType: helm
      url: https://charts.bitnami.com/bitnami
      chart: wordpress
      version: "12.0.3"
```

How dependsOn works:

- dependsOn is a syntax sugar. It will be translated to an input and an output


```yaml
components:
  - name: mysql
    type: helm
    outputs:
    - name: mysql-startup-probe # translated output
      valueFrom: output.startupProbe.ready
  - name: wordpress
    type: helm
    inputs:
    - name: mysql-startup-probe  # translated input
      parameterKey: "" # empty, not filling any value
```

- dependsOn will assume the Component it relies on, in this case the `mysql`, have `startupProbe` key in `healthPolicy`:

    ```yaml
    apiVersion: core.oam.dev/v1beta1
    kind: ComponentDefinition
    spec:
      status:
        healthPolicy: |
          startupProbe: op.#StartupProbe & {
            checkRule: (context.output.status.readyReplicas == context.output.status.replicas)
            failureThreshold: 30
            periodSeconds: 10
          }
    ```

- Once the `mysql` component is ready, the `startupProbe.ready` key will set to `true`.

**Why not reuse isHealth?**

`startupProbe` is different from `isHealth` that it is only executed once, and indicates that the component is ready.
We need to differentiate them because startup and health checking are two separate operational stages.
During startup, a component will be slow to ready because it needs to do other things like service registration.
So it is better to have a separate configuration to define the wait time, and check rule, etc.

**Comment by wonderflow** [comment]
Why not just make it as:
```
   ...
    - name: wordpress
      type: helm
      inputs:
        # dependsOn the mysql component to be ready
        - dependsOn: mysql
      properties:
       ...
```

It will be confuse if we allow dependsOn as a new field along with inputs.

**Comment by FogDong** [comment]
I think it would be more clear to separate `dependsOn` and `inputs`, `dependsOn` is not a field inside of `inputs` though the inner implementation is a syntax sugar of inputs.

**Comment by hongchaodeng** [comment]
Conclusion from offline discussion:

- We will add the `dependsOn` syntax sugar:

  ```yaml
    - name: wordpress
      type: helm
      # dependsOn the mysql component to be ready
      dependsOn:
        - mysql
  ```

  The working details are explained in [my above proposal](https://github.com/oam-dev/kubevela/issues/2370#issuecomment-928895637)

- When `dependsOn` and `inputs` co-exist, the `dependsOn` have higher priority to be ensured first before any data flow in `inputs` happen.

  This can be implemented by prepending the translated input/output to the array as first element.

- We will add the `startupProbe` action per [my above proposal](https://github.com/oam-dev/kubevela/issues/2370#issuecomment-928895637)
