### ISSUE TITLE
[Feature] support multi revision blue-green deploy policy

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela#2383]
I propose we should support a policy for multi revision blue-green deployment.

1. manuelly specify the replica and traffic.

```
kind: Application
spec:
  components:
  - name: mycomp
    type: webservice
    properties:
      image: nginx
  policies:
  - type: multi-revision
    name: blue-green-deploy
    properties:
      traffic:
          - example-app.example.com
        gateways:
          - example-app-gateway
        port: 8000
        weightedTargets:
            - revision: v1
               component: mycomp
               weight: 30
            - revision: v2
               component: mycomp
               weight: 60
            - revision: v3
               component: mycomp
               weight: 10
      replicaPlacement:
            - revision: v1
               component: mycomp
               replicas: 3
            - revision: v2
               component: mycomp
               replicas: 2
            - revision: v3
               component: mycomp
               replicas: 1
```

2. autoscaling with traffic split.

```
kind: Application
spec:
  components:
  - name: mycomp
    type: webservice
    properties:
      image: nginx
    traits:
       type: keda
       properties:
          autoscaling: traffic
  policies:
  - type: multi-revision
    name: blue-green-deploy
    properties:
      traffic:
          - example-app.example.com
        gateways:
          - example-app-gateway
        port: 8000
        weightedTargets:
            - revision: v1
               component: mycomp
               weight: 30
            - revision: v2
               component: mycomp
               weight: 60
            - revision: v3
               component: mycomp
               weight: 10
```
