### ISSUE TITLE
[Feature] vela up

### ISSUE THREAD

**Issue by resouer** [oam-dev/kubevela#239]
Consider a `vela up` command to take `appfile.yaml` as input, similar to `docker-compose up`. 

This also help us to avoid mix usage in `vela app init`.

**Comment by hongchaodeng** [comment]
Update: I have been working on a prototype and have gathered internal consensus on the solution for now.

It looks like:
<details><summary>appfile.yaml</summary>
<p>

```yaml
version: "1.0-alpha.1"

services:
  express-server:
    build:
      image: oamdev/testapp:v1
      docker:
        file: Dockerfile
        context: .
      push:
        local: kind

    # type: webservice (default) | task
    cmd: ["node", "server.js"]
    route:
      domain: example.com
      http: # match the longest prefix
        "/": 8080

    env:
      - FOO=bar
      - FOO3=sec:my-secret # map the same key as the env name from my-secret to env var
      - FOO2=sec:my-secret:key # map specific key from my-secret to env var
      - sec:my-secret # map all KV pairs from my-secret to env var

    files: # Mount secret as a file
      - /mnt/path=sec:my-secret

    scale:
      replica: 2
      auto: # automatic scale up and down based on given metrics
        range: "1-10"
        cpu: 80 # if cpu utilization is above 80%, scale up
        qps: 1000 # if qps is higher than 1k, scale up

    canary: # 额外生成 canary deployment 用来进行验证。Canary 验证通过后才会执行升级。
      replica: 1 # canary deployment size
      headers:
        - "foo:bar.*"

secrets:
  my-secret: /local-path/my-secret # load local file into k8s secret
```


</p>
</details>

Platform builders register the config template via definition:

<details><summary>workload_definition.yaml</summary>
<p>

```yaml
apiVersion: core.oam.dev/v1alpha2
kind: WorkloadDefinition
metadata:
  name: deployment
spec:
  definitionRef:
    name: containerizeds.standard.oam.dev
  extension:
    template: |
      parameter: #deployment
      #deployment: {
        cmd: [...string]
        env: [...string]
        files: [...string]
      }
      
      output: {
        apiVersion: "apps/v1"
        kind: "Deployment"
        metadata:
          name: context.name
        spec: {
          selector: {
            matchLabels:
              app: context.name
          }
          template: {
            metadata:
              labels:
                app: context.name
            spec: {
              containers: [{
                name:  context.name
                image: context.image
                command: parameter.cmd
              }]
            }
          }
        }
      }
```


</p>
</details>

I will come up with more clean and unified documentation to describe the whole picture in the coming days.
