### ISSUE TITLE
In the multi-cluster deployment, the manifest resource of traits and workload will eventually reserve only one resource apply to the corresponding cluster because of the same name

### ISSUE THREAD

**Issue by jianglu6** [oam-dev/kubevela#2393]
**Describe the bug**

In the multi-cluster deployment, the manifest resource of traits and workload will eventually reserve only one resource apply to the corresponding cluster because of the same name

**To Reproduce**
```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: website
spec:
  components:
    - name: front
      type: webservice
      properties:
        cmd:
          - node
          - server.js
        image: oamdev/testapp:v1
        port: 8080
  policies:
    - name: kind-cluster
      type: env-binding
      properties:
        envs:
          - name: jc-pass
            patch:
              components:
                - name: front
                  type: webservice
                  properties:
                    cmd:
                      - node
                      - server.js
                    image: oamdev/testapp:v1
                    port: 8080
                  traits:
                    - type: ingress
                      properties:
                        domain: testsvc.example.com
                        http:
                          "/": 8000
            placement:
              clusterSelector:
                name: cluster-3q9bhcj3onziy315j3u412zuh87u
          - name: jl-test
            patch:
              components:
                - name: front
                  type: webservice
                  properties:
                    cmd:
                      - node
                      - server.js
                    image: oamdev/testapp:v1
                    port: 8080
            placement:
              clusterSelector:
                name: cluster-9ztno07ysqrn31cbx2rf26szn51g
  workflow:
    steps:
      - name: deploy-jd-tpaas
        type: deploy2env
        properties:
          env: jc-pass
          policy: kind-cluster
      - name: deploy-jl-test
        type: deploy2env
        properties:
          env: jl-test
          policy: kind-cluster
```

**Expected behavior**

The deployment、service、ingress applied to cluster-3q9bhcj3onziy315j3u412zuh87u cluster

**Screenshots**
Only ingress was applied to the cluster-3q9bhcj3onziy315j3u412zuh87u cluster.

![image](https://user-images.githubusercontent.com/22437170/135223483-89b93b04-9414-4978-8f90-571214c8f086.png)

**KubeVela Version**

1.1

**Cluster information**
Describe your kubernetes cluster information.
- Kubernetes Version  1.16.15

**Additional context**

_Is it caused by using component.name+"/"+manifest.getname () as key?_

- pkg/controller/core.oam.dev/v1alpha1/envbinding/cluster_gateway_engine.go:95

```go
func (engine *ClusterGatewayEngine) schedule(ctx context.Context, apps []*EnvBindApp) ([]v1alpha1.ClusterDecision, error) {
	for _, app := range apps {
		app.ScheduledManifests = make(map[string]*unstructured.Unstructured)
		clusterName := engine.clusterDecisions[app.envConfig.Name].Cluster
		for _, component := range app.PatchedApp.Spec.Components {
			for _, manifest := range app.assembledManifests[component.Name] {
                                 **// Is it caused by using component.name+"/"+manifest.getname () as key?**
				manifestName := component.Name + "/" + manifest.GetName()
				multicluster.SetClusterName(manifest, clusterName)
				app.ScheduledManifests[manifestName] = manifest
			}
		}
	}
	var decisions []v1alpha1.ClusterDecision
	for _, decision := range engine.clusterDecisions {
		decisions = append(decisions, decision)
	}
	return decisions, nil
}
```
