### ISSUE TITLE
[Feature] Support multiple deployment in one Env for EnvBinding

### ISSUE THREAD

**Issue by Somefive** [oam-dev/kubevela#2433]
**Is your feature request related to a problem? Please describe.**

Currently, we can select target cluster in Env by specifying its name, as follows
```yaml
- name: staging
  placement: # selecting the cluster to deploy to
    clusterSelector:
      name: cluster-worker
```

In the EnvBinding spec, there is also a `LabelSelector` which is designed to select target cluster by label. Previous implementation (old EnvBinding, deprecated now), this `LabelSelector` will only pick out one cluster. As a result, each Env in EnvBinding is always expected to be bind with **exactly one cluster**.

```yaml
- name: staging
  placement:
    clusterSelector:
      labels:
        region: Hangzhou
```

However, there are scenarios where users want to have deployments in **multiple clusters**. For example, users can have clusters grouped by location, like Hangzhou or Beijing. Then for all clusters in one location, they may want to apply the same Env configuration to them. A complex scene is #2385. If we keep current design, it means users need to write N same environments configuration for N clusters in one region, which is not acceptable.

On the other hand, in my opinion, we will need application-level orchestration across clusters for KubeVela multi-cluster application management like [UnitedDeployment](http://openkruise.io/blog/uniteddeployment) in workload-level. Apparently, current design of the EnvBinding spec (regardless of the implementation) is not enough to model such complex challenges.

**Describe the solution you'd like**

As for the `labelSelector` problem, I'm not sure if it is appropriate to add some fields to handle it, like
```yaml
# select one endpoint (anyone available)
placement:
  scheduler: UnicastScheduler
  clusterSelector:
    labels:
      region: Hangzhou
  namespaceSelector:
    name: test
``` 
```yaml
# select 3 endpoints
placement:
  scheduler: MulticastScheduler
  properties:
    replicas: 3
  clusterSelector:
    labels:
      region: Hangzhou  
  namespaceSelector:
    name: staging
``` 
```yaml
# select all endpoints and automatically deploy to newly added clusters
placement:
  scheduler: BroadcastScheduler
  properties:
    acceptNewCluster: true
  clusterSelector:
    labels:
      region: Hangzhou
  namespaceSelector:
    name: prod
``` 
And leave extension space for future, like
```yaml
# select endpoints according to dynamic metrics
placement:
  scheduler: CustomScheduler
  properties:
    key: value
  clusterSelector:
    labels:
      region: Hangzhou
  namespaceSelector:
    name: custom
``` 
**Describe alternatives you've considered**

**Additional context**
