### ISSUE TITLE
first-vela-app cannot bind load balancer in AKS with default nginx ingress controller

### ISSUE THREAD

**Issue by heavenwing** [oam-dev/kubevela#2439]
**Describe the bug**
I tried KubeVela quick-start in AKS, I follow this document to enable ingress. But after I deployed first-vela-app, I got below error:
```yaml
services:
  - healthy: true
    name: express-server
    traits:
    - healthy: true
      message: |
        No loadBalancer found, visiting by using 'vela port-forward first-vela-app'
      type: ingress-1-20
    workloadDefinition:
      apiVersion: apps/v1
      kind: Deployment
  status: running
```

**To Reproduce**
1. Create AKS cluster
2. Enable ingress follow up this [document](https://docs.microsoft.com/en-us/azure/aks/ingress-basic#check-the-load-balancer-service), and verify ingress is working
3. Deploy [quick-start](https://kubevela.io/zh/docs/quick-start) app into the AKS cluster

**Expected behavior**
`curl -H "Host:testsvc.example.com" http://<your ip address>/` will get correct html contents

**Screenshots**

**KubeVela Version**
1.1.3

**Cluster information**
- Kubernetes Version 1.21.2
- Kubernetes Network CNI

**Comment by heavenwing** [comment]
above yaml have a little issue:
need to replace this line
```yaml
namespace: {{.Values.systemDefinitionNamespace}}
```
into 
```yaml
namespace: vela-system
```

And, for app yaml, I have to set class parameter, I mistaken think I can ignore it firstly
```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: first-vela-app
spec:
  components:
    - name: express-server
      type: webservice
      properties:
        image: crccheck/hello-world
        port: 8000
      traits:
        - type: ingress-1-20
          properties:
            class: nginx
            domain: testsvc.example.com
            http:
              "/": 8000
```
