### ISSUE TITLE
The GC after application deletion is not sequential

### ISSUE THREAD

**Issue by FogDong** [oam-dev/kubevela#2449]
**Describe the bug**

The GC after application deletion is not sequential.

If we have a controller and CR in an application, when we delete the application, the controller will be deleted first. In this case, the finalizer managed by the controller will be added to the CR. As a result, the deletion of the CR fails.

**To Reproduce**

```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: mysql
  namespace: default
spec:
  components:
    - name: mysql-controller
      type: helm
      properties:
        repoType: helm
        url: https://presslabs.github.io/charts
        chart: mysql-operator
        version: "0.4.0"
    - name: mysql-cluster
      type: raw
      dependsOn:
        - mysql-controller
      properties:
        apiVersion: mysql.presslabs.org/v1alpha1
        kind: MysqlCluster
        metadata:
          name: mysql-cluster
        spec:
          replicas: 1
          secretName: mysql-secret
```

Apply the yaml above and delete the app later.

**Expected behavior**

**Screenshots**

**KubeVela Version**

**Cluster information**

**Additional context**

**Comment by fourierr** [comment]
the Expected behavior is that mysql-cluster be deleted firstly and waiting done, mysql-controller is deleted secondly?

**Comment by wonderflow** [comment]
@fourierr yes, the reversal order of the creation.

**Comment by fourierr** [comment]
To fix this issue that GC not sequential will have many code changes,  so i think we should have a discussion to talk about it.
I propose the solution and it is not very graceful perhaps:
we have a linked list struct in memory ,and each component match a Node, compName is component's Name.
`
type Node struct {
   compName string,
   Next []*Node
}
`
Step1. in Init Stage, range all component ,if comp_a dependsOn comp_b, it will node_a -> node_b,and node_a was set to root. and there a example, we have five component A,B,C,D,E  the relationship is as follows
A      dependsOn        _
B      dependsOn        _
C      dependsOn        A,B
D      dependsOn        C
E      dependsOn        C,D
![ad721dce6ab0465e2a82dfb96e0dbb3](https://user-images.githubusercontent.com/35767528/160359232-4521c45b-c286-469e-9ed5-c754e196e30a.jpg)
Step2. in Finalize Stage, gc the component from root util the root==nil. and if root have multi Next,  the component that are not be dependent will be set to root Node.
![03293035154a29c9d5c64f454347930](https://user-images.githubusercontent.com/35767528/160360829-4ffe1bea-d273-4633-a0aa-b0ce1fa0ada2.jpg)
ping @wonderflow

**Comment by FogDong** [comment]
Why can't we use `status.workflow.steps` for GC directly?

Right now In `status.workflows.steps`, we'll have all running and finished steps. For those workflow steps that is not starting, it won't be shown in status.
But the status of the steps is now sequential, we do not record `DependsOn` or `Inputs/Outputs` in it, still I think it's enough to handle GC.

**Comment by FogDong** [comment]
> Why can't we use `status.workflow.steps` for GC directly?
> 
> Right now In `status.workflows.steps`, we'll have all running and finished steps. For those workflow steps that is not starting, it won't be shown in status. But the status of the steps is now sequential, we do not record `DependsOn` or `Inputs/Outputs` in it, still I think it's enough to handle GC.

We're now using `resourceTracker` for GC, sorry for the misleading, we should add sequence in `resourceTrackers`'s managedResources like:

```yaml
 managedResources:
  - dependsOn:
         - A
         - B
      C: {...}
  - A: {...}
  - B: {...}
```
