### ISSUE TITLE
missing ',' in struct literal, the order of trait cause the error?

### ISSUE THREAD

**Issue by yigexueshen** [oam-dev/kubevela#2544]
**Describe the bug**
I get a errors 【invalid context of trait ingress: missing ',' in struct literal】
the yaml contain trait **configMap** and **ingress**.
if **configmap** trait is before **ingress**, I will get this error
but when I change The order of trait, it can apply success

**To Reproduce**
> the error yaml
```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  annotations:
    app.oam.dev/description: instance test remark
    app.oam.dev/version: v1
  creationTimestamp: null
  name: configmap-test
  namespace: default
spec:
  components:
  - name: centos:7
    type: webservice
    properties:
      cmd:
      - /bin/bash
    traits:
    - type: configmap
      properties:
        volumes:
        - data:
            nginx.conf: "nginx config"
          mountPath: /workspace
          name: nginx-test
          readOnly: true
    - properties:
        domain: bywin.rdc.test.com
        http:
          /: 80
      type: ingress
```
> panic
```text
Error from server: error when creating "test-configmap.yaml": admission webhook "validating.core.oam.dev.v1beta1.applications" denied the request: schematic: Invalid value: v1beta1.Application{TypeMeta:v1.TypeMeta{Kind:"Application", APIVersion:"core.oam.dev/v1beta1"}, ObjectMeta:v1.ObjectMeta{Name:"configmap-test", GenerateName:"", Namespace:"default", SelfLink:"", UID:"88ac1900-3f8c-44d7-b74d-d5f25a610f56", ResourceVersion:"", Generation:1, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:63770554616, loc:(*time.Location)(0x3507d60)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string{"app.oam.dev/description":"instance test remark", "app.oam.dev/version":"v1", "kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"core.oam.dev/v1beta1\",\"kind\":\"Application\",\"metadata\":{\"annotations\":{\"app.oam.dev/description\":\"instance test remark\",\"app.oam.dev/version\":\"v1\"},\"creationTimestamp\":null,\"name\":\"configmap-test\",\"namespace\":\"default\"},\"spec\":{\"components\":[{\"name\":\"centos:7\",\"properties\":{\"cmd\":[\"/bin/bash\"]},\"traits\":[{\"properties\":{\"volumes\":[{\"data\":{\"nginx.conf\":\"nginx config\"},\"mountPath\":\"/workspace\",\"name\":\"nginx-test\",\"readOnly\":true}]},\"type\":\"configmap\"},{\"properties\":{\"domain\":\"bywin.rdc.test.com\",\"http\":{\"/\":80}},\"type\":\"ingress\"}],\"type\":\"webservice\"}]}}\n"}, OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry{v1.ManagedFieldsEntry{Manager:"kubectl-client-side-apply", Operation:"Update", APIVersion:"core.oam.dev/v1beta1", Time:(*v1.Time)(0xc010573620), FieldsType:"FieldsV1", FieldsV1:(*v1.FieldsV1)(0xc010573608), Subresource:""}}}, Spec:v1beta1.ApplicationSpec{Components:[]common.ApplicationComponent{common.ApplicationComponent{Name:"centos:7", Type:"webservice", ExternalRevision:"", Properties:runtime.RawExtension{Raw:[]uint8{0x7b, 0x22, 0x63, 0x6d, 0x64, 0x22, 0x3a, 0x5b, 0x22, 0x2f, 0x62, 0x69, 0x6e, 0x2f, 0x62, 0x61, 0x73, 0x68, 0x22, 0x5d, 0x7d}, Object:runtime.Object(nil)}, Inputs:common.StepInputs(nil), Outputs:common.StepOutputs(nil), Traits:[]common.ApplicationTrait{common.ApplicationTrait{Type:"configmap", Properties:runtime.RawExtension{Raw:[]uint8{0x7b, 0x22, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x73, 0x22, 0x3a, 0x5b, 0x7b, 0x22, 0x64, 0x61, 0x74, 0x61, 0x22, 0x3a, 0x7b, 0x22, 0x6e, 0x67, 0x69, 0x6e, 0x78, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x22, 0x3a, 0x22, 0x6e, 0x67, 0x69, 0x6e, 0x78, 0x20, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x7d, 0x2c, 0x22, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x50, 0x61, 0x74, 0x68, 0x22, 0x3a, 0x22, 0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x22, 0x2c, 0x22, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x3a, 0x22, 0x6e, 0x67, 0x69, 0x6e, 0x78, 0x2d, 0x74, 0x65, 0x73, 0x74, 0x22, 0x2c, 0x22, 0x72, 0x65, 0x61, 0x64, 0x4f, 0x6e, 0x6c, 0x79, 0x22, 0x3a, 0x74, 0x72, 0x75, 0x65, 0x7d, 0x5d, 0x7d}, Object:runtime.Object(nil)}}, common.ApplicationTrait{Type:"ingress", Properties:runtime.RawExtension{Raw:[]uint8{0x7b, 0x22, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0x3a, 0x22, 0x62, 0x79, 0x77, 0x69, 0x6e, 0x2e, 0x72, 0x64, 0x63, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x63, 0x6f, 0x6d, 0x22, 0x2c, 0x22, 0x68, 0x74, 0x74, 0x70, 0x22, 0x3a, 0x7b, 0x22, 0x2f, 0x22, 0x3a, 0x38, 0x30, 0x7d, 0x7d}, Object:runtime.Object(nil)}}}, Scopes:map[string]string(nil)}}, Policies:[]v1beta1.AppPolicy(nil), Workflow:(*v1beta1.Workflow)(nil), RolloutPlan:(*v1alpha1.RolloutPlan)(nil)}, Status:common.AppStatus{ConditionedStatus:condition.ConditionedStatus{Conditions:[]condition.Condition(nil)}, ObservedGeneration:0, Rollout:common.AppRolloutStatus{RolloutStatus:v1alpha1.RolloutStatus{ConditionedStatus:condition.ConditionedStatus{Conditions:[]condition.Condition(nil)}, RolloutOriginalSize:0, RolloutTargetSize:0, NewPodTemplateIdentifier:"", LastAppliedPodTemplateIdentifier:"", RollingState:"", BatchRollingState:"", CurrentBatch:0, UpgradedReplicas:0, UpgradedReadyReplicas:0}, LastUpgradedTargetAppRevision:"", LastSourceAppRevision:""}, Phase:"", Components:[]v1.ObjectReference(nil), Services:[]common.ApplicationComponentStatus(nil), ResourceTracker:(*v1.ObjectReference)(nil), Workflow:(*common.WorkflowStatus)(nil), LatestRevision:(*common.Revision)(nil), AppliedResources:[]common.ClusterObjectReference(nil)}}: cannot evaluate trait "ingress": invalid context of trait ingress: missing ',' in struct literal

```
> the normal yaml which can apply success
```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  annotations:
    app.oam.dev/description: instance test remark
    app.oam.dev/version: v1
  creationTimestamp: null
  name: configmap-test
  namespace: default
spec:
  components:
  - name: centos:7
    type: webservice
    properties:
      cmd:
      - /bin/bash
    traits:
    - properties:
        domain: test.configmap.com
        http:
          /: 80
      type: ingress
    - type: configmap
      properties:
        volumes:
        - data:
            nginx.conf: "nginx config"
          mountPath: /workspace
          name: nginx-test
          readOnly: true
```

**Expected behavior**

**Screenshots**

**KubeVela Version**

**Cluster information**
version :v1.19.2

**Additional context**

**Comment by hprotzek** [comment]
I also got this problem with our own components and traits.

This is failing:
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: "snprobe-rabbitmq-2-test"
  namespace: test
spec:
  components:
    - name: "snprobe-rabbitmq-2-test"
      type: snstateless
      properties:
        image: rabbitmq:3.9-management-alpine
        resources:
          memory: 1Gi
        ports:
          - name: amqp
            containerPort: 5672
            servicePort: 5672
            protocol: tcp
          - name: mgmt
            containerPort: 15672
            servicePort: 15672
            protocol: http
          - name: metrics
            containerPort: 15692
            servicePort: 15692
            protocol: http
      traits:
        - type: sningress
          properties:
            routes:
              - route: myrabbit-ui
                servicePort: 15672
              - route: myrabbit-metrics
                servicePort: 15692
        - type: snprobe
          properties:
            livenessProbe:
              initialDelaySeconds: 120
              timeoutSeconds: 10
              exec:
                command:
                  - "rabbitmq-diagnostics"
                  - "check_port_listener"
                  - "5672"
```

`cannot evaluate trait "snprobe": invalid context of trait snprobe: missing ',' in struct literal (and 1 more errors)`

This is working:
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: "snprobe-rabbitmq-2-test"
  namespace: test
spec:
  components:
    - name: "snprobe-rabbitmq-2-test"
      type: snstateless
      properties:
        image: rabbitmq:3.9-management-alpine
        resources:
          memory: 1Gi
        ports:
          - name: amqp
            containerPort: 5672
            servicePort: 5672
            protocol: tcp
          - name: mgmt
            containerPort: 15672
            servicePort: 15672
            protocol: http
          - name: metrics
            containerPort: 15692
            servicePort: 15692
            protocol: http
      traits:
        - type: snprobe
          properties:
            livenessProbe:
              initialDelaySeconds: 120
              timeoutSeconds: 10
              exec:
                command:
                  - "rabbitmq-diagnostics"
                  - "check_port_listener"
                  - "5672"
        - type: sningress
          properties:
            routes:
              - route: myrabbit-ui
                servicePort: 15672
              - route: myrabbit-metrics
                servicePort: 15692
```
