### ISSUE TITLE
status wirte back cannot import cue tool package

### ISSUE THREAD

**Issue by Chwetion** [oam-dev/kubevela#2578]
**Describe the bug**
When use import when defining status.customStatus in ComponentDefinition, will get an error: `compile customStatus template: expected label or '':'', found ''STRING'' "packageName"'`

**To Reproduce**

ComponentDefinition as follow:

```yaml
# comp.yaml
apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  name: nginx
spec:
  workload:
    definition:
      apiVersion: apps/v1
      kind: Deployment
  schematic:
    cue:
      template: |
        parameter: {}
        output: {
            apiVersion: "apps/v1"
            kind:       "Deployment"
            metadata: {
                name: context.name
            }
            spec: {
                selector: matchLabels: {
                    "app": context.name
                }
                template: {
                    metadata: labels: {
                        "app": context.name
                    }
                    spec: {
                        containers: [{
                            name: "nginx"
                            image: "nginx"
                        }]
                    }
                }
            }
        }
  status:
    healthPolicy: |
      isHealth: true
    customStatus: |
      import "strconv"
      message: "currentReplicas: " + strconv.FormatInt(context.output.status.replicas,10)
```

Application as follow:

```yaml
# app.yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: test-app
spec:
  components:
  - type: nginx
    name: nginx
    properties: {}
```

Reproduce step as follow:

1. kubectl create -f comp.yaml`
2. `kubectl create -f app.yaml`
3. `kubectl get app test-app -oyaml` can see application workflow step is error, and currentReplicas cannot write back to status.services.message

```yaml
  status:
    ...
    services:
    - healthy: true
      message: 'error occurs in health check : compile customStatus template: expected
        label or '':'', found ''STRING'' "encoding/json"'
      name: testapp
      scopes:
      - apiVersion: core.oam.dev/v1alpha2
        kind: HealthScope
        name: status-wirte-back
        namespace: default
        uid: 68e1dd35-d0dd-477a-8b79-ff824e3b1f69
      traits:
      - healthy: true
        type: hc.manualscaler
      workloadDefinition:
        apiVersion: apps/v1
        kind: Deployment
    status: runningWorkflow
    workflow:
      appRevision: testapp-v3:4d85bf5aca392d22
      contextBackend:
        apiVersion: v1
        kind: ConfigMap
        name: workflow-testapp-context
        uid: 1f6e4dc7-d0df-4238-8e76-73e119d628b0
      mode: StepByStep
      steps:
      - id: vekbmqptyc
        message: 'step apply: run step(provider=oam,do=component-apply): CollectHealthStatus:
          app=testapp, comp=testapp, evaluate workload status message error: compile
          customStatus template: expected label or '':'', found ''STRING'' "encoding/json"'
        name: canary
        phase: failed
        reason: Execute
        type: hc.deployment-rollingupdate
      suspend: false
      terminated: false
```

**Expected behavior**

cue package tools can be imported in custom status write back template, not only convert int to string, and other tools such encoding package

**KubeVela Version**

vela core v1.1.5

**Cluster information**

```
[root@vela status-write-back]# kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.15", GitCommit:"73dd5c840662bb066a146d0871216333181f4b64", GitTreeState:"clean", BuildDate:"2021-01-13T13:14:05Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.18) exceeds the supported minor version skew of +/-1
```

**Additional context**
expect that the custom write back status can be extended, not only to support string, but to support custom objects
