### ISSUE TITLE
Allow specifying a Terraform component's referenced Provider in an application 

### ISSUE THREAD

**Issue by zzxwill** [oam-dev/kubevela#2595]
Currently, the Provider which is linked to a Configuration is expressed in ComponentlDefinition, like Azure MariaDB.

```
apiVersion: core.oam.dev/v1alpha2
kind: ComponentDefinition
metadata:
  name: azure-database-mariadb
  ...
spec:
  workload:
    definition:
      apiVersion: terraform.core.oam.dev/v1beta1
      kind: Configuration
  schematic:
    terraform:
      configuration: |
        provider "azurerm" {
          features {}
        }
        ...

      providerRef:
        name: azure
        namespace: default

```

In a Component of an application, the Provider could not be specified. For example, the specified Provider `azure-2` won't take effect.

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: mariadb-backend
spec:
  components:
    - name: mariadb-backend
      type: azure-database-mariadb
      properties:
        ...
        providerRef:
          name: azure-2
          namespace: default
```

We made the design based on these reasons:

- A Configuration needs a Provider
Every Configuration needs a Provider which represents a cloud provider, like Azure.

- End-users doesn't need to under the concept `Provider`
All they need to do is to enable addon `terraform/provider-azure` with Azure credentials and set the properties for the Terraform component.

But here are some drawbacks:

- The Provider name of a Configuration is hardcoded with the name of the addon `terraform/provider-xxx`
For example, when enabling addon `terraform/provider-azure`, we set the Provider name to `azure`, and in the ComponentDefinition `ComponentDefinition`, we hardcoded Provider name as `azure`.

- An Application could not use multiple Providers to group cloud resources by users
We intend to support the multiple-tenant feature, in which, cloud resources provisioned are grouped in different tenants, ie, the users behind different Providers.

![image](https://user-images.githubusercontent.com/2805315/139667718-7c117253-c366-44ca-bb35-d4fad1b9214f.png)

I am proposing the different changes:

- Support users to set the name and namespace of a Provider when enabling addon `terraform/provider-xxx`

- Support users to specify a referenced Provider in a Terraform component in an application
The Provider in the application will override the one set in the ComponentDefinition of the component.
