### ISSUE TITLE
[BUG] Object Kind is missing

### ISSUE THREAD

**Issue by hprotzek** [oam-dev/kubevela#2640]
Using this trait:
```
sningress: {
	type: "trait"
	description: "Create ingress routes"
	labels: {}
	annotations: {}
	attributes: {
		podDisruptive: false
		appliesToWorkloads: ["*"]
	}
}

template: outputs: {
		for i, r in parameter.routes {
			"virtualservice-\(i)": {
				apiVersion: "networking.istio.io/v1beta1"
				kind:       "VirtualService"
				metadata: name: "\(context.name)-\(i)"
				spec: {
					hosts: [r.route]
					gateways: [
						"mesh",
						"istio-system/private",
						"istio-system/public",
					]
					http: [
						{
							name: "\(context.name)-\(i)-\(context.namespace)-ingress"
							route: [{
								destination: {
									host:     "\(context.name).\(context.namespace).svc.cluster.local"
									port: number: r.servicePort
								}
							}]
						}
					]
				}
			}
		}
	parameter: {
		// +usage=Routes to access HTTP service
		routes: [...{
			route: string
			servicePort: int
		}]
	}
}
```
with this application:
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: test
  namespace: default
spec:
  components:
    - name: test
      type: webservice
      properties:
        image: rabbitmq:3.9-management-alpine
      traits:
        - type: sningress
          properties:
            routes:
              - route: test-a.xxx
                servicePort: 15672
              - route: test-b.xxx
                servicePort: 15692
```

fails in the application workflow status with

```
steps:
    - id: vwlofa2lv2
      message: 'step apply: run step(provider=oam,do=component-apply): GenerateComponentManifest:
        evaluate trait=parameter template for component=test app=test:
        Object ''Kind'' is missing in ''{"routes":[]}'''
      name: test
      phase: failed
      reason: Execute
      type: apply-component
```

K8s version: 1.22.2-gke.1901
Vela: 1.1.8
