### ISSUE TITLE
The secret generated by Terraform won't regenerate after it's manually deleted

### ISSUE THREAD

**Issue by zzxwill** [oam-dev/kubevela#2693]
If a user deleted the secret generated by Terraform Controller, like `oss-conn` as below, it won't restore.

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: webapp
spec:
  components:
    - name: sample-oss
      type: alibaba-oss
      properties:
        bucket: vela-website
        acl: private
        writeConnectionSecretToRef:
          name: oss-conn
```
