### ISSUE TITLE
Error when using hardcoded array value

### ISSUE THREAD

**Issue by kgonyon** [oam-dev/kubevela#2791]
**Describe the bug**
If you loop an array that has a hard coded value it throws the following error.
```  
status:
  conditions:                                                                                                              
  - lastTransitionTime: "2021-11-23T17:34:21Z"                                                                                   
    message: |-                                                                                                            
      cannot store capability test in ConfigMap: failed to generate OpenAPI v3 JSON schema for capability test: error unmarshaling JSON: Error while unmarshalling property 'components' (*openapi3.Components): Error while unmarshalling property 'schemas' (*openapi3.Schemas): Error while unmarshalling property 'properties' (*openapi3.Schemas): Error while unmarshalling property 'items' (*openapi3.SchemaRef): Error while unmarshalling property 'properties' (*openapi3.Schemas): Error while unmarshalling property 'items' (*openapi3.SchemaRef): Failed to unmarshal extension properties: json: cannot unmarshal array into Go value of type map[string]json.RawMessage 
      Input: [{"enum":["sh"],"type":"string"}]
     reason: ReconcileError
     status: "False"
```

**To Reproduce**
```yaml
apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  annotations:
    definition.oam.dev/description: "Test"
  name: test
  namespace: vela-system
spec:
  schematic:
    cue:
      template: |
        parameter: {
          steps: [...#Step]
        }
        output: {
        }
        #Step: {
          command: [...string] | *["sh"]
          test: [
            for i, cmd in command {
              cmd
            }
          ]
        }
  workload:
    definition:
      apiVersion: apps/v1
      kind: Deployment
```
1. Apply the above yaml

**Expected behavior**
Create component with no errors

**KubeVela Version**
1.1.10

**Cluster information**
Kubernetes Version: 1.21
Hosted on AWS EKS

**Additional context**
