### ISSUE TITLE
[BUG] Changes to workflow doesn't trigger garbage collection of legacy resources

### ISSUE THREAD

**Issue by kinsolee** [oam-dev/kubevela#2902]
**Describe the bug**

Changes applied to application workflow will not generate a new apprev. Now we have to modify components' fields to trigger garbage collection. Since GC depends on resourcetracker related to apprev, the legacy resources will still be there.

**To Reproduce**

1.  Create 2 components from official demo application:
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: first-vela-app
  namespace: default
spec:
  components:
    - name: express-server1
      type: webservice
      properties:
        image: crccheck/hello-world
        port: 8000
    - name: express-server2
      type: webservice
      properties:
        image: crccheck/hello-world
        port: 8000
  workflow:
    steps:
    - type: apply-remaining
      name: deploy
```

Now there are 2 deployments.
```
NAME              READY   UP-TO-DATE   AVAILABLE   AGE
express-server1   1/1     1            1           6m6s
express-server2   1/1     1            1           6m6s
```
2. Modify workflow to exclude express-server2 component
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: first-vela-app
  namespace: default
spec:
  components:
    - name: express-server1
      type: webservice
      properties:
        image: crccheck/hello-world
        port: 8000
    - name: express-server2
      type: webservice
      properties:
        image: crccheck/hello-world
        port: 8000
  workflow:
    steps:
    - type: apply-remaining
      name: deploy
      properties:
       // The application output resources will not include express-server2
        exceptions:
          - "express-server2"
```
3.  Verify bug

`kubectl get app -n default first-vela-app -o yaml`

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  annotations:
    oam.dev/kubevela-version: latest
  finalizers:
  - app.oam.dev/resource-tracker-finalizer
  generation: 2
  name: first-vela-app
  namespace: default
spec:
  components:
  - name: express-server1
    properties:
      image: crccheck/hello-world
      port: 8000
    type: webservice
  - name: express-server2
    properties:
      image: crccheck/hello-world
      port: 8000
    type: webservice
  workflow:
    steps:
    - name: deploy
      properties:
        exceptions:
        - express-server2
      type: apply-remaining
status:
  appliedResources:
  - apiVersion: apps/v1
    creator: workflow
    kind: Deployment
    name: express-server1
    namespace: default
  conditions:
  - lastTransitionTime: "2021-12-08T10:19:35Z"
    reason: Available
    status: "True"
    type: Parsed
  - lastTransitionTime: "2021-12-08T10:19:35Z"
    reason: Available
    status: "True"
    type: Revision
  - lastTransitionTime: "2021-12-08T10:19:35Z"
    reason: Available
    status: "True"
    type: Policy
  - lastTransitionTime: "2021-12-08T10:24:33Z"
    reason: Available
    status: "True"
    type: Workflow
  - lastTransitionTime: "2021-12-08T10:24:33Z"
    reason: Available
    status: "True"
    type: Render
  - lastTransitionTime: "2021-12-08T10:24:33Z"
    reason: ReconcileSuccess
    status: "True"
    type: Ready
  latestRevision:
    name: first-vela-app-v1
    revision: 1
    revisionHash: f7d150b128ed2e54
  observedGeneration: 2
  resourceTracker:
    name: first-vela-app-v1-default
    uid: 7aabdf08-e238-484c-9c64-d81b574513f3
  services:
  - healthy: true
    message: Ready:1/1
    name: express-server1
    workloadDefinition:
      apiVersion: apps/v1
      kind: Deployment
  status: running
  workflow:
    appRevision: first-vela-app-v1:263a07fd119c514d
    contextBackend:
      apiVersion: v1
      kind: ConfigMap
      name: workflow-first-vela-app-context
      uid: 12838245-017a-4589-8ff6-16bd0ad1c500
    finished: true
    mode: StepByStep
    startTime: "2021-12-08T10:24:32Z"
    steps:
    - firstExecuteTime: "2021-12-08T10:24:32Z"
      id: xb9bgfwo4v
      lastExecuteTime: "2021-12-08T10:24:32Z"
      name: deploy
      phase: succeeded
      type: apply-remaining
    suspend: false
    terminated: false
```

Noted that `express-server2` doesn't exist in `status.appliedResources`

But deployment `express-server2` still exist.

`kubectl get deployment -n default`

```
NAME              READY   UP-TO-DATE   AVAILABLE   AGE
express-server1   1/1     1            1           10m
express-server2   1/1     1            1           10m
```

This may be attributed to `resourcetracker`:

`kubectl get resourcetracker first-vela-app-v1-default -o yaml`

```
apiVersion: core.oam.dev/v1beta1
kind: ResourceTracker
metadata:
  creationTimestamp: "2021-12-08T10:19:35Z"
  generation: 1
  labels:
    app.oam.dev/name: first-vela-app
    app.oam.dev/namespace: default
  name: first-vela-app-v1-default
  resourceVersion: "49132"
  uid: 7aabdf08-e238-484c-9c64-d81b574513f3
status:
  trackedResources:
  - apiVersion: apps/v1
    kind: Deployment
    name: express-server1
    namespace: default
    uid: d95c508d-69d3-43d4-b3b4-25ea3148f73e
  - apiVersion: apps/v1
    kind: Deployment
    name: express-server2
    namespace: default
    uid: a66e31a8-9d55-4887-9105-4cc035818a95
```

**Expected behavior**

I think during the GC, controller should diff `Application.status.appliedResources` and `ResourceTracker.status.trackedResources` , then clean up the legacy resources.

**KubeVela Version**
Version: master
GitRevision: git-cdb83c2f
GolangVersion: go1.17.1

**Cluster information**
Client Version: 4.9.0-0.okd-2021-11-28-035710
Server Version: 4.9.0-0.okd-2021-11-28-035710
Kubernetes Version: v1.22.1-1820+4dd1b5a1afc832-dirty
