### ISSUE TITLE
One component of an application won't be dispatched until the previous one gets ready

### ISSUE THREAD

**Issue by zzxwill** [oam-dev/kubevela#2922]
**Describe the bug**

One component of an application won't be dispatched until the previous one gets ready though it's not dependent on the previous one. The dispatch order is the component order in the application. It will take more time (*Number_Of_components) compared the old dispatch mechanism.

**To Reproduce**

1. Apply the application
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  labels:
    addons.oam.dev/name: observability
  name: addon-observability
  namespace: vela-system
spec:
  components:
  - name: grafana-registration
    properties:
      chart: ./chart
      git:
        branch: master
      repoType: git
      targetNamespace: vela-system
      url: https://github.com/oam-dev/grafana-registration
      values:
        replicaCount: 1
    type: helm
  - name: loki
    properties:
      chart: loki-stack
      releaseName: loki
      repoType: helm
      targetNamespace: vela-system
      url: https://charts.kubevela.net/addons
      version: 2.4.1
    traits:
    - properties:
        access: proxy
        credentialSecret: grafana
        credentialSecretNamespace: vela-system
        grafanaServiceName: grafana
        grafanaServiceNamespace: vela-system
        name: loki
        namespace: vela-system
        service: loki
        type: loki
      type: register-grafana-datasource
    type: helm
  - name: kube-state-metrics
    properties:
      chart: kube-state-metrics
      repoType: helm
      targetNamespace: vela-system
      url: https://charts.kubevela.net/addons
      values:
        image:
          repository: oamdev/kube-state-metrics
          tag: v2.1.0
      version: 3.4.1
    type: helm
  - name: grafana
    properties:
      chart: grafana
      releaseName: grafana
      repoType: helm
      targetNamespace: vela-system
      url: https://charts.kubevela.net/addons
      version: 6.14.1
    traits:
    - properties:
        domain: abc.com
        http:
          /: 80
      type: pure-ingress
    - properties:
        credentialSecret: grafana
        credentialSecretNamespace: vela-system
        grafanaServiceName: grafana
        grafanaServiceNamespace: vela-system
        urls:
        - https://charts.kubevela.net/addons/dashboards/kubevela_core_logging.json
        - https://charts.kubevela.net/addons/dashboards/kubevela_core_monitoring.json
        - https://charts.kubevela.net/addons/dashboards/kubevela_application_logging.json
        - https://charts.kubevela.net/addons/dashboards/flux2/cluster.json
      type: import-grafana-dashboard
    type: helm
  - name: prometheus-server
    properties:
      chart: prometheus
      releaseName: prometheus
      repoType: helm
      targetNamespace: vela-system
      url: https://charts.kubevela.net/addons
      version: 14.4.1
    traits:
    - properties:
        access: proxy
        credentialSecret: grafana
        credentialSecretNamespace: vela-system
        grafanaServiceName: grafana
        grafanaServiceNamespace: vela-system
        name: prometheus
        namespace: vela-system
        service: prometheus-server
        type: prometheus
      type: register-grafana-datasource
    type: helm
  policies:
  - name: grafana-domain
    properties:
      envs: null
    type: env-binding
  workflow:
    steps:
    - name: apply-resources
      type: apply-remaining
```

2. Normally it will take 2-3 minutes to get ready, now it will get 10-15 minutes. And look the age of `helmrelease`, one won't run until the previous one gets ready.

```
➜  ~ k get helmreleases.helm.toolkit.fluxcd.io -A
NAMESPACE     NAME                   READY     STATUS                             AGE
vela-system   grafana                True      Release reconciliation succeeded   9m25s
vela-system   grafana-registration   True      Release reconciliation succeeded   13m
vela-system   kube-state-metrics     True      Release reconciliation succeeded   10m
vela-system   loki                   True      Release reconciliation succeeded   12m
vela-system   prometheus-server      Unknown   Reconciliation in progress         8m15s
```

**Expected behavior**

**Screenshots**

**KubeVela Version**

**Cluster information**

**Additional context**
