### ISSUE TITLE
pod spec: ephemeral-storage cannot be configured

### ISSUE THREAD

**Issue by dengqian** [oam-dev/kubevela#2928]
**Describe the bug**

if I quote struct with definition:
```
	#Resources: {
                 ephemeral-storage?: string
		limits?:   #quota
		requests?: #quota
	}
```

I will get an error:
```
invalid cue template of workload deploy-test01: missing ',' in struct literal (and 1 more errors)
```

**To Reproduce**

1. The YAML files of Component/Trait I used.
```
apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  annotations:
    definition.oam.dev/description: "Add pod resources"
    definitionrevision.oam.dev/name: "1.0.0"
  name: resources
spec:
  appliesToWorkloads:
    - '*'
  podDisruptive: true
  schematic:
    cue:
      template: |
        patch: {
          if context.output.kind == "SidecarSet" {
            spec: {
                // +patchKey=name
                containers: [{
                  resources: parameter.resources
                }]
            }
          }
          if context.output.kind != "SidecarSet" {
            spec: template: spec: {
                // +patchKey=name
                containers: [{
                  resources: parameter.resources
                }]
            }
          }
        }

        #quota: {
          cpu?: string | int
          memory?: string
          ephemeral-storage?: string
        }

        #resources: {
          limits?: #quota
          requests?: #quota
        }

        parameter: {
          resources?: #resources
        }

```
2. The YAML file of Application I applied.
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: deploy-test01
spec:
  components:
  - name: deploy-test01
    properties:
      containers:
      - image: nginx1.20
        name: deploy-test01
    type: webserices

    - properties:
        resources:
          limits:
            cpu: 1
            memory: "1Gi"
            ephemeral-storage: "1Gi"
      type: resources

```

**Screenshots**

![image](https://user-images.githubusercontent.com/6399971/146005785-3512acd2-b16f-4d8b-96bc-47340ff4120e.png)

**KubeVela Version**

$ vela version
Version: refs/tags/v1.1.7
GitRevision: git-d083039
GolangVersion: go1.16.9

**Cluster information**

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:52:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.9-aliyunedge.1", GitCommit:"687f4f4", GitTreeState:"", BuildDate:"2021-03-08T09:56:01Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.16) exceeds the supported minor version skew of +/-1
