### ISSUE TITLE
Traits patching envFrom with configMapRef and secretRef for the same component cause conflicts

### ISSUE THREAD

**Issue by entigo-mart-erlenheim** [oam-dev/kubevela#2939]
**Describe the bug**

It's not possible to patch a component with traits that modify the envFrom with configMapRef and secretRef values at the same time. This error doesn't happen if both traits use either configMapRef or secretRef. This is possibly caused by a patchKey conflict.

**To Reproduce**

Trait definitions
```
apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  annotations:
    definition.oam.dev/description: Create a Secret and set it as environmental variables
  name: secrets-env
  namespace: vela-system
spec:
  appliesToWorkloads:
    - deployments.apps
  podDisruptive: true
  schematic:
    cue:
      template: |
        patch: {
            spec: template: spec: {
                // +patchKey=name
                containers: [{
                    name: context.name
                    // +patchKey=secretRef.name
                    envFrom: [{ secretRef: name: context.name }]
                }]
            }
        }
        outputs: secret: {
            apiVersion: "v1"
            kind: "Secret"
            metadata: name: context.name
            type: "Opaque"
            data: {
                for k, v in parameter.secrets {
                    "\(k)": v
                }
            }
        }
        parameter: {
            // +usage=Specify the secrets as key and value
            secrets: [string]: string
        }
```
```
apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  annotations:
    definition.oam.dev/description: Create a ConfigMap and set environment variables
  name: env-vars
  namespace: vela-system
spec:
  appliesToWorkloads:
    - deployments.apps
  podDisruptive: true
  schematic:
    cue:
      template: |
        patch: {
            spec: template: spec: {
                // +patchKey=name
                containers: [{
                    name: context.name
                    // +patchKey=configMapRef.name
                    envFrom: [{ configMapRef: name: context.name }]
                }]
            }
        }
        outputs: configmap: {
            apiVersion: "v1"
            kind: "ConfigMap"
            metadata: name: context.name
            data: {
                for k, v in parameter.envVars {
                    "\(k)": v
                }
            }
        }
        parameter: {
            // +usage=Specify the environment variables as key and value
            envVars: [string]: string
        }
```
Application
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: application-1
spec:
  components:
    - name: application-1
      type: webservice
      properties:
        image: busybox
      traits:
        - type: secrets-env
          properties:
            secrets:
              key-one: dmFsdWUteA==
        - type: env-vars
          properties:
            envVars:
              key-1: value-a
```
Error
```
'step apply: run step(provider=oam,do=component-apply): DispatchStandardWorkload:
        cannot apply manifest, name: "application-1" apiVersion: "apps/v1" kind: "Deployment":
        cannot create object: Deployment.apps "application-1" is invalid: spec.template.spec.containers[0].envFrom:
        Invalid value: "": may not have more than one field specified at a time'
```

**Expected behavior**

Resulting pod should have envFrom list with both configMapRef and secretRef values
```
        envFrom:
        - configMapRef:
            name: application-1
        - secretRef:
            name: application-1
```

**KubeVela Version**

vela-core-1.1.13

**Cluster information**

Kubernetes server version v1.19.7
