### ISSUE TITLE
[BUG] output key can not contain '-' 

### ISSUE THREAD

**Issue by dengqian** [oam-dev/kubevela#2949]
**Describe the bug**
my trait definition:
```
apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  annotations:
    definition.oam.dev/description: Create/Attach configmaps on K8s pod for your workload which follows the pod spec in path 'spec.template'.
  name: configmap
spec:
  appliesToWorkloads:
    - '*'
  podDisruptive: true
  schematic:
    cue:
      template: |
        patch: spec: template: spec: {
        	// +patchKey=name
        	containers: [{
        		// +patchKey=name
        		volumeMounts: [
        			for v in parameter.volumes {
        				{
        					name:      "volume-\(v.name)"
        					mountPath: v.mountPath
        					readOnly:  v.readOnly
        				}
        			},
        		]
        	}, ...]
        	// +patchKey=name
        	volumes: [
        		for v in parameter.volumes {
        			{
        				name: "volume-\(v.name)"
        				configMap: name: v.name
        			}
        		},
        	]
        }
        outputs: {
        	for v in parameter.volumes {
        		if v.data != _|_ {
        			"\(v.name)": {
        				apiVersion: "v1"
        				kind:       "ConfigMap"
        				metadata: name: v.name
        				data: v.data
        			}
        		}
        	}
        }
        parameter: {
        	// +usage=Specify mounted configmap names and their mount paths in the container
        	volumes: [...{
        		name:      string
        		mountPath: string
        		readOnly:  *false | bool
        		data?: [string]: string
        	}]
        }

```

when parameter "name" contains '-', error  "invalid context of trait configmap: missing ',' in struct literal " occurs.

**To Reproduce**
application configuration:
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  annotations:
  name: test-1
spec:
  components:
  - name: test-1
    properties:
      image: nginx1.20
      
    traits:
    - properties:
        volumes:
        - name: test-app-1
          mountPath: /home/admin/bbb
          data:
            a: b
            b: c
      type: configmap    
    type: deployment

```

I know when use cue:
```
 #parameter: {
     name:  string
     image: string
     env: [string]: string
 }

output: {
    "spe-c": {
        containers: [{
            name:  parameter.name
            image: parameter.image
            env: [
                for k, v in parameter.env {
                    name:  k
                    value: v
                },
            ]
        }]
    }
}
```
if  replace "spe-c":  to spe-c:, when execute `cue vet xxx.cue` we will get the same error : missing ',' in struct literal: 

but this error should not occur when spe-c is enclosed in "".

**KubeVela Version**

$ vela version
Version: refs/tags/v1.1.7
GitRevision: git-d083039
GolangVersion: go1.16.9

**Cluster information**

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:52:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.9-aliyunedge.1", GitCommit:"687f4f4", GitTreeState:"", BuildDate:"2021-03-08T09:56:01Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.16) exceeds the supported minor version skew of +/-1
