### ISSUE TITLE
【Bug】 Delete an application in running workflow status, and the deployment created by the component still exists

### ISSUE THREAD

**Issue by YokeCheng** [oam-dev/kubevela#3017]
**Describe the bug**
Delete an application in runningworkflow state (imagepullbackoff appears in pod state). The application will be deleted, but the component resource will be recreated

**Screenshots**
Before Delete
![image](https://user-images.githubusercontent.com/24696946/147549545-3760fc0a-460b-4077-b2e5-fff0e22ef9f9.png)

After Delete
![image](https://user-images.githubusercontent.com/24696946/147549568-1fde6642-6286-4da9-ae23-f6ff2eebb89a.png)

Core Logs
![image](https://user-images.githubusercontent.com/24696946/147551995-a82f3112-d774-4c6f-9aed-54a21125f560.png)

**KubeVela Version**
[v1.2.0-rc.1]

**Kubernetes Version**
[v1.17]

**Comment by Somefive** [comment]
Could you give a detail spec of your application?

**Comment by YokeCheng** [comment]
During the delete operation, set the PropagationPolicy in the DeleteOptions to Background to delete normally
![image](https://user-images.githubusercontent.com/24696946/147555413-d830e338-2589-46bf-9d05-adcb638eef26.png)
`	deletionOption := metav1.DeletePropagationBackground
	_ = client.Namespace(namespace).Delete(context.Background(), name, metav1.DeleteOptions{PropagationPolicy: &deletionOption})`

**Comment by du86796922** [comment]
May be v1.20.0-rc remove Owner Reassures

**Comment by YokeCheng** [comment]
> Could you give a detail spec of your application?
```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  creationTimestamp: null
  finalizers:
  - app.oam.dev/resource-tracker-finalizer
  labels:
    WORKER_IDG_UNIQUEID: deployment-test-5
    app: oam-mulit-test-13
    deploy_type: deployment
    deployserver_appid: 4d13ef89ef534d8c86277257cac46bad
    deployserver_appversion: 0.0.67
    deployserver_env: development
    deployserver_type: deployment
    parent_app: oam-mulit-test-13
    resource_type: kubevela
  name: oam-mulit-test-13
  namespace: ns-ypc-vela
spec:
  components:
  - name: service-name-test-131
    properties:
      containers:
      - env:
        - name: CPU_REQUESTS
          valueFrom:
            resourceFieldRef:
              containerName: container-name-test-131
              divisor: 1m
              resource: requests.cpu
        - name: CPU_LIMITS
          valueFrom:
            resourceFieldRef:
              containerName: container-name-test-131
              divisor: 1m
              resource: limits.cpu
        - name: MEM_LIMITS
          valueFrom:
            resourceFieldRef:
              containerName: container-name-test-131
              divisor: 1Mi
              resource: limits.memory
        - name: MEM_REQUESTS
          valueFrom:
            resourceFieldRef:
              containerName: container-name-test-131
              divisor: 1Mi
              resource: requests.memory        
        envFrom:
        - configMapRef:
            name: configmap-test-131
        image: nginx222
        imagePullPolicy: IfNotPresent
        lifecycle: {}
        name: container-name-test-131
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - mountPath: /etc/my_init.d/dynamic-update-init.sh
          name: config-dynamic-update-extensions
          subPath: dynamic-update-init.sh
        - mountPath: /configmap
          name: configmap-test-131
        - mountPath: /configmap-test-131
          name: config-volume
        - mountPath: /tmp/dynamic_extensions
          name: php-dynamic-extensions
        - mountPath: /empty-dir
          name: empty-dir-name
      imagePullSecrets:
      - name: harbor-registry
      labels:
        WORKER_IDG_UNIQUEID: deployment-test-5
        app: service-name-test-131
        deploy_type: deployment
        deployserver_appid: 4d13ef89ef534d8c86277257cac46bad
        deployserver_appversion: 1.2.16
        deployserver_env: development
        deployserver_type: deployment
        parent_app: oam-mulit-test-13
        resource_type: kubevela
      podLabels:
        WORKER_IDG_UNIQUEID: deployment-test-5
        app: service-name-test-131
        deploy_type: deployment
        deployserver_appid: 4d13ef89ef534d8c86277257cac46bad
        deployserver_appversion: 1.2.16
        deployserver_env: development
        deployserver_type: deployment
        parent_app: oam-mulit-test-13
        resource_type: kubevela
      restartPolicy: Always
      volumes:
      - configMap:
          defaultMode: 493
          name: dynamic-update-init
        name: config-dynamic-update-extensions
      - configMap:
          name: configmap-test-131
        name: config-volume
      - configMap:
          name: configmap-test-131
        name: configmap-test-131
      - emptyDir: {}
        name: empty-dir-name
      - emptyDir: {}
        name: php-dynamic-extensions
    traits:
    - properties:
        initcontainers:
        - args:
          - -c
          - cp -r /dynamic_extensions/* /tmp/dynamic_extensions/
          command:
          - /bin/sh
          env:
          - name: CPU_REQUESTS
            valueFrom:
              resourceFieldRef:
                containerName: php-dynamic-extensions
                divisor: 1m
                resource: requests.cpu
          - name: CPU_LIMITS
            valueFrom:
              resourceFieldRef:
                containerName: php-dynamic-extensions
                divisor: 1m
                resource: limits.cpu
          - name: MEM_LIMITS
            valueFrom:
              resourceFieldRef:
                containerName: php-dynamic-extensions
                divisor: 1Mi
                resource: limits.memory
          - name: MEM_REQUESTS
            valueFrom:
              resourceFieldRef:
                containerName: php-dynamic-extensions
                divisor: 1Mi
                resource: requests.memory
          - name: PODNAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: PODIP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: NODENAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: NODEIP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: CONTAINERNAME
            value: $(PODNAME)-php-dynamic-extensions
          image: harbor.oneitfarm.com/zhirenyun/php:dynamic_extensions
          imagePullSecrets: Always
          name: php-dynamic-extensions
          resources:
            limits:
              cpu: 100m
              memory: 64Mi
            requests:
              cpu: 1m
              memory: 1Mi
          volumeMounts:
          - mountPath: /tmp/dynamic_extensions
            name: php-dynamic-extensions
      type: t-init-container
    - properties:
        affinity:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                - key: deploy_type
                  operator: In
                  values:
                  - deployment
              weight: 100
            - preference:
                matchExpressions:
                - key: deploy_type
                  operator: In
                  values:
                  - workspace
              weight: 90
        tolerations:
        - effect: NoExecute
          key: key
          operator: Equal
          tolerationSeconds: 6000
          value: value
      type: t-affinity
    - properties:
        replicas: 1
      type: scaler
    - properties:
        ings:
        - annotations:
            konghq.com/backend-protocol: http
            konghq.com/deploy-original-metadata: '{"class":"kong","name":"test-ingress-test-131","hosts":[{"domain":"dp1.test-131.oneitfarm.com","target_service_name":"svc-test","port":"80"}],"annotations":null}'
            konghq.com/enable-security-provider-mtls: "false"
            konghq.com/preserve-host: "true"
            konghq.com/protocols: http,https
            konghq.com/strip-path: "false"
            kubernetes.io/ingress.class: kong
          labels:
            WORKER_IDG_UNIQUEID: deployment-test-5
            app: service-name-test-131
            deploy_type: deployment
            deployserver_appid: 4d13ef89ef534d8c86277257cac46bad
            deployserver_appversion: 1.2.16
            deployserver_env: development
            deployserver_type: deployment
            parent_app: oam-mulit-test-13
            resource_type: kubevela
          name: test-ingress-test-131
          rules:
          - host: dp1.test-131.oneitfarm.com
            http:
              paths:
              - backend:
                  serviceName: svc-test
                  servicePort: 80
      type: t-ingress
    - properties:
        svcs:
        - labels:
            WORKER_IDG_UNIQUEID: deployment-test-5
            app: service-name-test-131
            deploy_type: deployment
            deployserver_appid: 4d13ef89ef534d8c86277257cac46bad
            deployserver_appversion: 1.2.16
            deployserver_env: development
            deployserver_type: deployment
            parent_app: oam-mulit-test-13
            resource_type: kubevela
          name: svc-test-test-131
          ports:
          - name: svc-test-test-131-0
            port: 80
            protocol: TCP
            targetPort: 80
          type: ClusterIP
      type: t-service
    - properties: {}
      type: t-secret
    - properties:
        cms:
        - data:
            aa: aa
          labels:
            WORKER_IDG_UNIQUEID: deployment-test-5
            app: service-name-test-131
            deploy_type: deployment
            deployserver_appid: 4d13ef89ef534d8c86277257cac46bad
            deployserver_appversion: 1.2.16
            deployserver_env: development
            deployserver_type: deployment
            parent_app: oam-mulit-test-13
            resource_type: kubevela
          name: configmap-test-131
      type: t-configmap
    type: t-deploy
status: {}
```

**Comment by YokeCheng** [comment]
> Could you give a detail spec of your application?
@Somefive 
```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  creationTimestamp: null
  finalizers:
  - app.oam.dev/resource-tracker-finalizer
  labels:
    WORKER_IDG_UNIQUEID: deployment-test-5
    app: oam-mulit-test-13
    deploy_type: deployment
    deployserver_appid: 4d13ef89ef534d8c86277257cac46bad
    deployserver_appversion: 0.0.67
    deployserver_env: development
    deployserver_type: deployment
    parent_app: oam-mulit-test-13
    resource_type: kubevela
  name: oam-mulit-test-13
  namespace: ns-ypc-vela
spec:
  components:
  - name: service-name-test-131
    properties:
      containers:
      - env:
        - name: CPU_REQUESTS
          valueFrom:
            resourceFieldRef:
              containerName: container-name-test-131
              divisor: 1m
              resource: requests.cpu
        - name: CPU_LIMITS
          valueFrom:
            resourceFieldRef:
              containerName: container-name-test-131
              divisor: 1m
              resource: limits.cpu
        - name: MEM_LIMITS
          valueFrom:
            resourceFieldRef:
              containerName: container-name-test-131
              divisor: 1Mi
              resource: limits.memory
        - name: MEM_REQUESTS
          valueFrom:
            resourceFieldRef:
              containerName: container-name-test-131
              divisor: 1Mi
              resource: requests.memory        
        envFrom:
        - configMapRef:
            name: configmap-test-131
        image: nginx222
        imagePullPolicy: IfNotPresent
        lifecycle: {}
        name: container-name-test-131
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - mountPath: /etc/my_init.d/dynamic-update-init.sh
          name: config-dynamic-update-extensions
          subPath: dynamic-update-init.sh
        - mountPath: /configmap
          name: configmap-test-131
        - mountPath: /configmap-test-131
          name: config-volume
        - mountPath: /tmp/dynamic_extensions
          name: php-dynamic-extensions
        - mountPath: /empty-dir
          name: empty-dir-name
      imagePullSecrets:
      - name: harbor-registry
      labels:
        WORKER_IDG_UNIQUEID: deployment-test-5
        app: service-name-test-131
        deploy_type: deployment
        deployserver_appid: 4d13ef89ef534d8c86277257cac46bad
        deployserver_appversion: 1.2.16
        deployserver_env: development
        deployserver_type: deployment
        parent_app: oam-mulit-test-13
        resource_type: kubevela
      podLabels:
        WORKER_IDG_UNIQUEID: deployment-test-5
        app: service-name-test-131
        deploy_type: deployment
        deployserver_appid: 4d13ef89ef534d8c86277257cac46bad
        deployserver_appversion: 1.2.16
        deployserver_env: development
        deployserver_type: deployment
        parent_app: oam-mulit-test-13
        resource_type: kubevela
      restartPolicy: Always
      volumes:
      - configMap:
          defaultMode: 493
          name: dynamic-update-init
        name: config-dynamic-update-extensions
      - configMap:
          name: configmap-test-131
        name: config-volume
      - configMap:
          name: configmap-test-131
        name: configmap-test-131
      - emptyDir: {}
        name: empty-dir-name
      - emptyDir: {}
        name: php-dynamic-extensions
    traits:
    - properties:
        initcontainers:
        - args:
          - -c
          - cp -r /dynamic_extensions/* /tmp/dynamic_extensions/
          command:
          - /bin/sh
          env:
          - name: CPU_REQUESTS
            valueFrom:
              resourceFieldRef:
                containerName: php-dynamic-extensions
                divisor: 1m
                resource: requests.cpu
          - name: CPU_LIMITS
            valueFrom:
              resourceFieldRef:
                containerName: php-dynamic-extensions
                divisor: 1m
                resource: limits.cpu
          - name: MEM_LIMITS
            valueFrom:
              resourceFieldRef:
                containerName: php-dynamic-extensions
                divisor: 1Mi
                resource: limits.memory
          - name: MEM_REQUESTS
            valueFrom:
              resourceFieldRef:
                containerName: php-dynamic-extensions
                divisor: 1Mi
                resource: requests.memory
          - name: PODNAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: PODIP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: NODENAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: NODEIP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: CONTAINERNAME
            value: $(PODNAME)-php-dynamic-extensions
          image: harbor.oneitfarm.com/zhirenyun/php:dynamic_extensions
          imagePullSecrets: Always
          name: php-dynamic-extensions
          resources:
            limits:
              cpu: 100m
              memory: 64Mi
            requests:
              cpu: 1m
              memory: 1Mi
          volumeMounts:
          - mountPath: /tmp/dynamic_extensions
            name: php-dynamic-extensions
      type: t-init-container
    - properties:
        affinity:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                - key: deploy_type
                  operator: In
                  values:
                  - deployment
              weight: 100
            - preference:
                matchExpressions:
                - key: deploy_type
                  operator: In
                  values:
                  - workspace
              weight: 90
        tolerations:
        - effect: NoExecute
          key: key
          operator: Equal
          tolerationSeconds: 6000
          value: value
      type: t-affinity
    - properties:
        replicas: 1
      type: scaler
    - properties:
        ings:
        - annotations:
            konghq.com/backend-protocol: http
            konghq.com/deploy-original-metadata: '{"class":"kong","name":"test-ingress-test-131","hosts":[{"domain":"dp1.test-131.oneitfarm.com","target_service_name":"svc-test","port":"80"}],"annotations":null}'
            konghq.com/enable-security-provider-mtls: "false"
            konghq.com/preserve-host: "true"
            konghq.com/protocols: http,https
            konghq.com/strip-path: "false"
            kubernetes.io/ingress.class: kong
          labels:
            WORKER_IDG_UNIQUEID: deployment-test-5
            app: service-name-test-131
            deploy_type: deployment
            deployserver_appid: 4d13ef89ef534d8c86277257cac46bad
            deployserver_appversion: 1.2.16
            deployserver_env: development
            deployserver_type: deployment
            parent_app: oam-mulit-test-13
            resource_type: kubevela
          name: test-ingress-test-131
          rules:
          - host: dp1.test-131.oneitfarm.com
            http:
              paths:
              - backend:
                  serviceName: svc-test
                  servicePort: 80
      type: t-ingress
    - properties:
        svcs:
        - labels:
            WORKER_IDG_UNIQUEID: deployment-test-5
            app: service-name-test-131
            deploy_type: deployment
            deployserver_appid: 4d13ef89ef534d8c86277257cac46bad
            deployserver_appversion: 1.2.16
            deployserver_env: development
            deployserver_type: deployment
            parent_app: oam-mulit-test-13
            resource_type: kubevela
          name: svc-test-test-131
          ports:
          - name: svc-test-test-131-0
            port: 80
            protocol: TCP
            targetPort: 80
          type: ClusterIP
      type: t-service
    - properties: {}
      type: t-secret
    - properties:
        cms:
        - data:
            aa: aa
          labels:
            WORKER_IDG_UNIQUEID: deployment-test-5
            app: service-name-test-131
            deploy_type: deployment
            deployserver_appid: 4d13ef89ef534d8c86277257cac46bad
            deployserver_appversion: 1.2.16
            deployserver_env: development
            deployserver_type: deployment
            parent_app: oam-mulit-test-13
            resource_type: kubevela
          name: configmap-test-131
      type: t-configmap
    type: t-deploy
status: {}
```

**Comment by Somefive** [comment]
1. Could you check the labels and annotations in the recreated deployment? If the kubevela related labels and annotations exists, then it is KubeVela Controller to recreate it.

**Comment by du86796922** [comment]
> @YokeCheng
> 
> 1. Could you check the labels and annotations in the recreated deployment? If the kubevela related labels and annotations exists, then it is KubeVela Controller to recreate it.
> 2. You can debug the KubeVela system by watching the changes of ResourceTracker. Run `kubectl get rt -w` to see how they changes.
> 3. As for the PropagationPolicy, I think it is associated with the garbage collection of indirect resources like Pods created by the Deployment, but it should not affect the Deployment directly managed by Application.
> 
> As @du86796922 said, it is a breaking change for v1.2.0-beta.3+ version where ownerReference mechanism is removed after a thorough internal discussion. One of the major reason is that the native ownerReference mechanism does not support multi-cluster, and prevents us running garbage collection with orders, which we might introduce in the future.

auditing the @YokeCheng  log, I found that the controller does have creation behavior.
@YokeCheng Can you provide a full log?

I read his yaml file, found add finalizers @seanly , I don't know if version 1.20 has this finalizers?
```yaml
metadata:
  creationTimestamp: null
  finalizers:
  - app.oam.dev/resource-tracker-finalizer
```
