### ISSUE TITLE
The error message is not correct when AWS provider is not available

### ISSUE THREAD

**Issue by zzxwill** [oam-dev/kubevela#3046]
**Describe the bug**

Reported by a user from Slack.

I am using the latest v1.2.0-rc.2 (it was the same with rc.1). It seems terraform controller needs a provider named “default”, it does not use the one specify in the ComponentDefinition under providerRef
```
terraform-controller-8487d64549-m5v97 terraform-controller E1230 17:32:25.284602       1 credentials.go:257] "failed to get Provider object" err="Provider.terraform.core.oam.dev \"default\" not found" Name="default"
terraform-controller-8487d64549-m5v97 terraform-controller 2021-12-30T17:32:25.284Z     ERROR   controller      Reconciler error        {"reconcilerGroup": "terraform.core.oam.dev", "reconcilerKind": "Configuration", "controller": "configuration", "name": "oam-cars-rds", "namespace": "default", "error": "Provider is not ready: failed to get the region from the provider: failed to get Provider object: Provider.terraform.core.oam.dev \"default\" not found", "errorVerbose": "Provider.terraform.core.oam.dev \"default\" not found\nfailed to get Provider object\ngithub.com/oam-dev/terraform-controller/controllers/provider.GetProviderFromConfiguration\n\t/workspace/controllers/provider/credentials.go:258\ngithub
```

then if I add a provider name default it works
```
apiVersion: terraform.core.oam.dev/v1beta1
kind: Provider
metadata:
  name: default
  namespace: default
spec:
  provider: aws
  region: us-west-2
  credentials:
    source: Secret
    secretRef:
      namespace: vela-system
      name: aws-account-creds
      key: credentials
The component definition include the following providerRef details
  schematic:
    terraform:
      providerRef:
        name: aws
        namespace: default
      configuration: |
 ```

**To Reproduce**

**Expected behavior**

**Screenshots**

**KubeVela Version**

**Cluster information**

**Additional context**
