### ISSUE TITLE
[BUG]application controller do not resync due to event filter in SetupWithManager

### ISSUE THREAD

**Issue by songminglong** [oam-dev/kubevela#3055]
**Describe the bug**

Kubevela will support repairing the abnormal deletion of managed resources, trigger application controller reconcile through the manager resync mechanism, and then create the deleted managed resources.
However, during the initialization phase of SetupWithManager, the application controller will filter the application update event according to the content of the app, thereby filtering out the event triggered by resync. As a result, the deleted managed resource will not be created

**To Reproduce**

1. Edit kubevela-vela-core deployment, and add --informer-re-sync-interval=60s to container cmd， and then restart vela-core pod。

   ```
   containers:
         - args:
           - --metrics-addr=:8080
           - --enable-leader-election
           - --use-webhook=true
           - --webhook-port=9443
           - --webhook-cert-dir=/etc/k8s-webhook-certs
           - --autogen-workload-definition=true
           - --health-addr=:9440
           - --apply-once-only=off
           - --system-definition-namespace=vela-system
           - --application-revision-limit=10
           - --definition-revision-limit=20
           - --oam-spec-ver=v0.3
           - --enable-cluster-gateway=true
           - --informer-re-sync-interval=60s
   ```

   

2. Create an application using webservice component

   ```
   apiVersion: core.oam.dev/v1beta1
   kind: Application
   metadata:
     name: website
   spec:
     components:
       - name: frontend              # This is the component I want to deploy
         type: webservice
         properties:
           image: nginx
         traits:
           - type: cpuscaler         # Automatically scale the component by CPU usage after deployed
             properties:
               targetKind: Deployment
               targetAPIVersion: apps/v1
               min: 1
               max: 10
               cpuUtil: 60
           - type: labels
             properties:
               "release": "stable"
   ```

   

3. Delete deployment of app

   ```
   #kubectl delete deployment frontend
   ```

4. Waiting for deleted deployment to be created

**Expected behavior**

The deleted deployment frontend will be created

**Screenshots**

Application controller does not periodically reconcile
![image](https://user-images.githubusercontent.com/8907867/148485090-8a294778-082d-4a41-90dd-17d6f7966ff7.png)

**KubeVela Version**

vela cli version: v1.2.0-beta.2

vela-core version: master

**Cluster information**

Describe your kubernetes cluster information.

- Kubernetes Version [e.g. 1.22.2]

**Additional context**
