### ISSUE TITLE
DryRun on ConfigMap Volume type generate error

### ISSUE THREAD

**Issue by josephlim75** [oam-dev/kubevela#3072]
**Describe the bug**

When trying to perform `dry-run` on our `app.yml` file with volume type `configMap`, we get an error.  If the volume is removed, the `dry-run` works fine.  We did not include any `configMap` parameters/traits in the `app.yml` because the `configMap` is managed outside of `kubevela` system

Error
```
E0110 19:12:23.984964    3150 instance.go:80] "failed to have the workload/trait unstructured" err="cue: marshal error: spec.template.spec.volumes.0.configMap.name: cannot convert incomplete value \"string\" to JSON" Definition="apiVersion: \"apps/v1\"\nkind:       \"Deployment\"\nspec: {\n\tselector: {\n\t\tmatchLabels: {\n\t\t\t\"app.oam.dev/component\": \"fake-api\"\n\t\t}\n\t}\n\ttemplate: {\n\t\tspec: {\n\t\t\tcontainers: [{\n\t\t\t\tname: \"fake-api\"\n\t\t\t\tenv: [{\n\t\t\t\t\t// +usage=Environment variable name\n\t\t\t\t\tname: \"VERSION_TAG\"\n\t\t\t\t\t// +usage=The value of the environment variable\n\t\t\t\t\tvalue: \"${VERSION_TAG}\"\n\t\t\t\t\t// +usage=Specifies a source the value of this var should come from\n\t\t\t\t\tvalueFrom?: {\n\t\t\t\t\t\t// +usage=Selects a key of a secret in the pod's namespace\n\t\t\t\t\t\tsecretKeyRef: {\n\t\t\t\t\t\t\t// +usage=The name of the secret in the pod's namespace to select from\n\t\t\t\t\t\t\tname: string\n\t\t\t\t\t\t\t// +usage=The key of the secret to select from. Must be a valid secret key\n\t\t\t\t\t\t\tkey: string\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}, ...]\n\t\t\t\timage: \"harbor.interos.io/interos-dev/fake-api\"\n\t\t\t\tports: [{\n\t\t\t\t\tcontainerPort: 8000\n\t\t\t\t}, ...]\n\t\t\t\tvolumeMounts: [{\n\t\t\t\t\tname:      \"example-config\"\n\t\t\t\t\tmountPath: \"/configs\"\n\t\t\t\t}, ...]\n\t\t\t}, ...]\n\t\t\tvolumes: [{\n\t\t\t\tname: \"example-config\"\n\t\t\t\tconfigMap: {\n\t\t\t\t\tname:        string\n\t\t\t\t\tdefaultMode: *420 | int\n\t\t\t\t}\n\t\t\t}, ...]\n\t\t}\n\t\tmetadata: {\n\t\t\tlabels: {\n\t\t\t\t\"app.oam.dev/component\": \"fake-api\"\n\t\t\t\t\"app.oam.dev/revision\":  \"KUBEVELA_COMPONENT_REVISION_PLACEHOLDER\"\n\t\t\t}\n\t\t}\n\t}\n}\n"
Error: generate OAM objects: cannot generate AppConfig and Components: evaluate base template component=fake-api app=fake-api: failed to have the workload/trait unstructured: cue: marshal error: spec.template.spec.volumes.0.configMap.name: cannot convert incomplete value "string" to JSON
```
**To Reproduce**

Filename: app.yaml

```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: fake-api
  namespace: dev
spec:
  components:
    - name: fake-api
      type: webservice
      properties:
        image: fake-api
        env:
          - name: "VERSION_TAG"
            value: "${VERSION_TAG}"
        port: 8000
        resources:
          cpu: 
            required: 100m
          memory:
            required: 200m
        volumes:
          - name: example-config
            mountPath: /configs
            type: configMap
``` 
Command executed 
`vela dry-run -f app.yaml`

**Expected behavior**

Dry run should produce valid k8s manifest deployment as below
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app.oam.dev/appRevision: ""
    app.oam.dev/component: fake-api
    app.oam.dev/name: fake-api
    app.oam.dev/resourceType: WORKLOAD
    workload.oam.dev/type: webservice
  name: fake-api
  namespace: dev
spec:
  selector:
    matchLabels:
      app.oam.dev/component: fake-api
  template:
    metadata:
      labels:
        app.oam.dev/component: fake-api
        app.oam.dev/revision: KUBEVELA_COMPONENT_REVISION_PLACEHOLDER
    spec:
      containers:
      - env:
        - name: VERSION_TAG
          value: ${VERSION_TAG}
        image: fake-api
        name: fake-api
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: example-config
          mountPath: /configs/
      volumes:
      - name: example-config
        configMap:
          name: example-config
```

**KubeVela Version**

Kubevela Version: `1.1.13`

**Comment by josephlim75** [comment]
Found the answer for the `volume` spec.  It turns out that I am missing the `cmName` attribute/property
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: fake-api
  namespace: dev
spec:
  components:
    - name: fake-api
      type: webservice
      properties:
        image: fake-api
        env:
          - name: "VERSION_TAG"
            value: "${VERSION_TAG}"
        port: 8000
        resources:
          cpu: 
            required: 100m
          memory:
            required: 200m
        volumes:
          - name: vol-example-config
            mountPath: /configs
            type: configMap
            cmName: example-config
```
