### ISSUE TITLE
component webservice: outputs service ports missing "name" if mutil ports

### ISSUE THREAD

**Issue by rainwolf01** [oam-dev/kubevela#3093]
**Describe the bug**

> webservice not support mutil ports
```
E0114 16:21:40.235962       1 task.go:210] "do steps" err="step apply: run step(provider=oam,do=component-apply): DispatchTraits: cannot apply manifest, name: xxxxxx-service apiVersion: v1 kind: Service: cannot create object: Service \"xxxxxx-service\" is invalid: [spec.ports[0].name: Required value, spec.ports[1].name: Required value]" application="xxxx-dev/xxxx-dev-xxxxxx-basesvc" controller="application" resource_version="200223918" workflow_version="xxxx-dev-xxxxxx-basesvc-v1:ff7b7d085e891479" step_name="xxxxxx-service" step_type="apply-component" spanID="i-bdvw3xze.workflow.rnrviq2tz2"
```

see [k8s api document](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#serviceport-v1-core)
```
name: Optional if only one ServicePort is defined on this service.
```

**To Reproduce**

```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: xxxx-service
spec:
  components:
    - name: xxxx-service
      type: webservice
      properties:
        image: imagerepo-path
        ports:
          - port: 8080
            expose: true
          - port: 9999
            expose: true
```

**Expected behavior**

```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: xxxx-service
spec:
  components:
    - name: xxxx-service
      type: webservice
      properties:
        image: imagerepo-path
        ports:
          - name: http   # define name
            port: 8080
            expose: true
          - name: rpc    # define name
            port: 9999
            expose: true
```

**KubeVela Version**
- KubeVela 1.2.0
