### ISSUE TITLE
[feature] vela secret to manage secret for information passing

### ISSUE THREAD

**Issue by resouer** [oam-dev/kubevela#31]
Otherwise all Secret based sensitive information pass will not work.

**Comment by xishengcai** [comment]
how to overwrite config by configmap

**Comment by wonderflow** [comment]
@xishengcai  We don't have a very clear design now. I suggest you describe your use case here , so we can have more input for this design.

In my mind, we could make configmap/secret workflow in kubevela like this:


## Firstly, Create Secret by CLI/Dashboard

We could load secret from local like this:

```
vela secret create my-secret  --from-literal=username=devuser --from-literal=password='S!B\*d$zDsb='
vela secret create my-secret --from-file=/my/path/to/secret.txt
```

## Bind the Secret in App

Under the hood, we can use AppConfig like this. 


### Use Service binding

(Note: this is already implemented now)

```
kind: ApplicationConfiguration
spec:
  components:
  - componentName: my-web
    dataInputs:
    - fieldPaths: [] # This data input is for ordering purpose only
      valueFrom:
        dataOutputName: my-secret-binding
    traits:
    - trait:
        apiVersion: core.oam.dev/v1alpha1
        kind: ServiceBinding
        metadata:
          name: my-secret-binding
        spec:
          from:
            secret:
              name: my-secret
          to:
            env: true
      dataOutputs:
        - name: my-secret-binding
          fieldPath: status.ready
```

**Comment by resouer** [comment]
@wonderflow If kubevela can create/import secret/configmap, then `PodSpecWorklaod` can consume the secret/configmap directly. Not sure why use service binding trait? Seems we just need to design a cue template to make this simple to use.

For the future of service binding trait, maybe re-implement the trait based on https://github.com/k8s-service-bindings/spec? PTAL. The main scenario IMO will be binding information from external system (i.e. alternative to service broker in vela).

**Comment by resouer** [comment]
Let's ship a `vela secret` command first like `vela config` and allow workload type to consume.

**Comment by wonderflow** [comment]
As we already has Initializer now, we should align vela secrets with the Initializer, refer to #1836 .

But secrets are sensitive data, so we should not create by an initializer object, it should be created locally and just add a metadata is fine.


```
kind: Initializer
metadata:
  name: test-env
spec:
  appTemplate:
    spec:
      components:
        - name: my-test-namespace
          type: namespace
          properties:
            name: test-namespace
        - name: metadata
          type: configmap
          properties:
            namespace: test-namespace
            email: my.email.com
            secretes: ["mysecret-key"]
```
