### ISSUE TITLE
namespace vela-system is deleted when disable one special addon

### ISSUE THREAD

**Issue by StevenLeiZhang** [oam-dev/kubevela#3108]
**Describe the bug**
Namespace vela-system is deleted when disable one special addon, and all the vela's pods are deleted.
Vela is crashed.

**To Reproduce**

1.  create one customized addon.
2. specify vela-system to be needNamespace in this addon's metadata.yml
```
needNamespace:
  - vela-system
```
3. add my private github addon registry, which holds this addon
4. go to velaux webpage, and enable this addon
5. wait for addon is installed
6. go to velaux and disable this addon
7.  Namespace vela-system and its resources are deleted

**Expected behavior**
1.only the addon is uninstalled, vela should not be impacted

**KubeVela Version**

```
Version: v1.2.0
GitRevision: git-6cee468
GolangVersion: go1.16.13
```

**Comment by StevenLeiZhang** [comment]
After debugging, here is my investigation:

If user specify need namespace vela-system in addon's metadata as below
```
needNamespace:
  - vela-system
```


When vela enables this addon, it renders Application of addon, and one namespace Component is attached to Application

```
apiVersion: core.oam.dev/v1beta1
kind: Application
# ignore something here
spec:
  components:
# ignore something here
  - name: vela-system-namespace
    properties:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: vela-system
    type: raw
```


"vela-system" namespace is patched some labels as below:

```
apiVersion: v1
kind: Namespace
metadata:
  labels:
    addons.oam.dev/name: mytest-middleware
    addons.oam.dev/registry: github-catalog
    app.oam.dev/app-revision-hash: e0c334973f055758
    app.oam.dev/appRevision: addon-mytest-middleware-v1
    app.oam.dev/cluster: ""
    app.oam.dev/component: vela-system-namespace
    app.oam.dev/name: addon-mytest-middleware
    app.oam.dev/namespace: vela-system
    app.oam.dev/resourceType: WORKLOAD
    app.oam.dev/revision: vela-system-namespace-v1
    kubernetes.io/metadata.name: vela-system
    name: vela-system
    oam.dev/render-hash: d36a385f6a56b1ac
    workload.oam.dev/type: raw
```

So, this addon could be enabled normally, but when user disable this addon, both the Application and namespace Component are deleted.

I think this vulnerability may be used by Malicious User or Attacker. Attacker could provide  such addon  to destroy vela system.

Actually, "vela-system" namespace do not need to be randered as one Component, because this namespace is already created when user install KubeVela.
If user want to enable vela addon, KubeVela and its namespace must exist already.
