### ISSUE TITLE
[BUG] existing resource with same render-hash of desired resource was patched again

### ISSUE THREAD

**Issue by kinsolee** [oam-dev/kubevela#3123]
**Describe the bug**

If the render-resource's hash doesn't change, the existing resource should not be applied. 

**To Reproduce**
Let's say we have an application with a scaler:

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: express-server
  namespace: vela-system
spec:
  components:
  - name: express-server
    properties:
      image: oamdev/hello-world:v1
      port: 8000
    traits:
    - properties:
        replicas: 1
      type: scaler
    type: webservice
  workflow:
    steps:
    - name: deploy
      type: apply-application
```

Then we have an deploy with `labels.oam.dev/render-hash=8729dd851d006643`

```
❯ kubectl get deploy -n vela-system express-server
NAME             READY   UP-TO-DATE   AVAILABLE   AGE
express-server   1/1     1            1           20m

❯ k get deploy -n vela-system express-server -ojsonpath="{.metadata['labels.oam\.dev\/render\-hash']}"
8729dd851d006643

```

Now we manually scale deployment it to zero.

```
❯ kubectl scale --replicas=0 deploy/express-server -n vela-system
deployment.apps/express-server scaled

❯ kubectl get deploy -n vela-system express-server
NAME             READY   UP-TO-DATE   AVAILABLE   AGE
express-server   0/0     0            0           22m
```

Then we restart the workflow:
```
❯ vela workflow restart -n vela-system express-server
Successfully restart workflow: express-server

// The replicas was overwritten! 
❯ kubectl get deploy -n vela-system express-server
NAME             READY   UP-TO-DATE   AVAILABLE   AGE
express-server   1/1     1            1           23m

❯ k get deploy -n vela-system express-server -ojsonpath="{.metadata['labels.oam\.dev\/render\-hash']}"
8729dd851d006643
```
Note that the render-hash remains the same.

**Expected behavior**
If there is no changes to the app(render-hash), skip the existing resource update.

**KubeVela Version**
Version: v1.2.1
GitRevision: git-488ceb4a
GolangVersion: go1.17.6

**Cluster information**
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:33:37Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:35:25Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/arm64"}
```
