### ISSUE TITLE
can not scale application in rollout traits 

### ISSUE THREAD

**Issue by basuotian** [oam-dev/kubevela#3150]
**Describe the bug**

Using rollout traits in scale-down case follow the offical doc: 
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: rollout-trait-test
spec:
  components:
    - name: express-server
      type: webservice
      externalRevision: express-server-v2
      properties:
        image: stefanprodan/podinfo:5.0.2
      traits:
        - type: rollout
          properties:
            targetRevision: express-server-v1
            # current replicas is 7, reduce to 5。
            targetSize: 5
```
As we don't fill `rolloutBatches` field, rollout-controller will fill it with the diff between current replicas and targetSize;
but in the next scale (like 5 ->  1), the rollout-controller will report an error because the batches mismatch to targetSize

**To Reproduce**

**Expected behavior**

support multiple scale in rollout traits, overwrite rolloutBatches in scale operation

**Screenshots**

**KubeVela Version**

**Cluster information**

**Additional context**
