### ISSUE TITLE
[Bug] TraitDefinition updating triggers Application and Pod updating

### ISSUE THREAD

**Issue by dengqian** [oam-dev/kubevela#3168]
**Describe the bug**
Version: v1.2.1
Bug describe : 
I updated a TraitDefinition which will change pod template, after updating the TraitDefinition, all my Application using this trait triggered reconcile and all my pod updated. 

my application yaml: 

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  creationTimestamp: null
  name: ggl-test
spec:
  components:
  - name: ggl-test
    properties:
      appName: ggl-test
      containers:
      - command:
        - openresty
        - -g
        - daemon off;
        image: vikings/openresty
    traits:
    - properties:
        annotations:
        - name: io.kubernetes.runtime
          value: kata-runtime
      type: annotations
    traits:
    - properties:
        aliyunuid: "1693358898281414"
        platform: "appcenter"
        appName: ggl-test
        cluster: cn3691
        tenant: t-e3496bc319e941ed8ec8349b8c65b366
        virtualCluster: vc-ac0fc5c4
        appLabels:
          "core.hangu.io/global-scheduling": "true"
          "alibabacloud.com/environment": "proc"
      type: platformlabels
    type: deployment
```

**Comment by tossmilestone** [comment]
I think I could help to fix it

**Comment by tossmilestone** [comment]
@Somefive Is this a behavior by design?

**Comment by dengqian** [comment]
> - properties:
>         aliyunuid: "1693358898281414"
>         platform: "appcenter"
>         appName: ggl-test
>         cluster: cn3691
>         tenant: t-e3496bc319e941ed8ec8349b8c65b366
>         virtualCluster: vc-ac0fc5c4
>         appLabels:
>           "core.hangu.io/global-scheduling": "true"
>           "alibabacloud.com/environment": "proc"
>       type: platformlabels
   I update the definition of this trait:
```
    - properties:
        aliyunuid: "1693358898281414"
        platform: "appcenter"
        appName: ggl-test
        cluster: cn3691
        tenant: t-e3496bc319e941ed8ec8349b8c65b366
        virtualCluster: vc-ac0fc5c4
        appLabels:
          "core.hangu.io/global-scheduling": "true"
          "alibabacloud.com/environment": "proc"
      type: platformlabels
```
The new version will add labels in "appLabels" to pod, the old version just ignored parameter "appLabels", after updating this traitdefinition, old application who has parameter "appLabels" triggered pod updating
