### ISSUE TITLE
[Feature] Improve the capabilities of KubeVela GitOps to make it a standalone Addon

### ISSUE THREAD

**Issue by FogDong** [oam-dev/kubevela#3205]
**Is your feature request related to a problem? Please describe.**

Right now the capability of KubeVela GitOps is integrated into `fluxcd` addon, but `fluxcd` is just one implementation of GitOps.

We should separate GitOps to a standalone addon and make it easy to debug.

For more infomation of KubeVela GitOps, please refer to [Using GitOps + KubeVela for Application Continuous Delivery](https://kubevela.net/blog/2021/10/10/kubevela-gitops).

**Describe the solution you'd like**

The `gitops` addon should install some necessary resources first and have one `componentDefinition` called `gitops`. Users can use it like below:

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: my-gitops-app
  namespace: default
spec:
  components:
    - name: my-gitops-server
      type: gitops
      properties:
          # user can choose the implementation of gitops like fluxcd or argocd
          # it can also be an optional field, default to fluxcd
           type: fluxcd
          # the configuration of git
           git:
               .....
           # the configuration of image repo
           imageRepository:
               .....
```

**Describe alternatives you've considered**

Our gitops is hard to debug right now since we use fluxcd but we did not give out fluxcd messages in KubeVela app.

We should give out the under messages either in KubeVela application or use vela cli like `vela status`.

**Additional context**
