### ISSUE TITLE
Using the same method for CUE Patch component properties has inconsistent structure

### ISSUE THREAD

**Issue by wxuedong** [oam-dev/kubevela#3367]
**Describe the bug**

define a component  workload is Argo Rollout ,and then define a trait 

```
"stateless-service": {
	attributes: workload: definition: {
		apiVersion: "argoproj.io/v1alpha1"
		kind:       "Rollout"
	}
	type: "component"
}
template: {
   output: {
		metadata: {
			name: context.name
		}
		spec: {
			replicas: parameter.replicas
			revisionHistoryLimit: parameter.revisionHistoryLimit
			selector: matchLabels: app: context.name
			strategy: {
				canary:{steps:[{"setWeight":100}]}
			}
			template: {
				metadata: {
					labels: {
						app:            context.name
					}
				}
				spec: {
					 ...
				}
		  }
	  }
		apiVersion: "argoproj.io/v1alpha1"
		kind:       "Rollout"
	}
	parameter: {
		replicas: *1 | int
		// +usage=Which image would you like to use for your service
		// +short=i
		image: string
    ...
  }
}
```

```
"canary": {
	annotations: {}
	attributes: {
		appliesToWorkloads: ["rollout.argoproj.io"]
		podDisruptive: true
	}
	labels: {}
	type: "trait"
}
template: {
  	patch: spec: strategy: {
			// +patchStrategy=retainKeys
			canary: {
			    maxUnavailable: 0
			    steps:[
				{ "setWeight": 20},
           	                 { "pause": {} },
           	                 { "setWeight": 40},
			        { "pause": {} },
			        { "setWeight": 100},
			        { "pause": {} },
	]
			}
    }
}
```

Create an app

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: first-vela-app
spec:
  components:
    - name: first-vela-app-serivce
      type: stateless-service
      properties:
        image: xxx..x
      traits:
        - type: "canary"

```
Patch data：

Yaml：
<img width="833" alt="image" src="https://user-images.githubusercontent.com/15843627/156682877-c65989b4-9794-44d9-9ba3-432acd29c9e2.png">

Json
<img width="647" alt="image" src="https://user-images.githubusercontent.com/15843627/156683133-139c4c2b-cfa5-4a55-9b82-64f1fb4eaa56.png">

After the application is submitted everything works fine  .

**And then redefine a new trait**

```
"canary": {
	annotations: {}
	attributes: {
		appliesToWorkloads: ["rollout.argoproj.io"]
		podDisruptive: true
	}
	labels: {}
	type: "trait"
}
template: {
  	patch: spec: strategy: {
			// +patchStrategy=retainKeys
			canary: {
			  maxUnavailable: 0
			  steps:[
			    for _, v  in parameter.weights {
			        { "setWeight": v},
			        { "pause": {} },
			    }
			  ]
			}
    }
    parameter: {
      weights: [...int]
    }
}
```

Update  app:

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: first-vela-app
spec:
  components:
    - name: first-vela-app-serivce
      type: stateless-service
      properties:
        image: xxx..x
      traits:
        - type: "canary"
           properties:
              weights:
                - 50
                - 70
                - 100
```

Patch data：

Yaml:
<img width="883" alt="image" src="https://user-images.githubusercontent.com/15843627/156683621-1e1ee0b4-6797-4bdb-8959-a5db95752ca3.png">

Json:
<img width="733" alt="image" src="https://user-images.githubusercontent.com/15843627/156683689-7c96dad0-3b82-492b-b8f9-4d0bd58edd17.png">

**Why are the two results different? What is the problem?**
