### ISSUE TITLE
can not pass arguments to array by "inputs"

### ISSUE THREAD

**Issue by StevenLeiZhang** [oam-dev/kubevela#3392]
**Describe the bug**
Inputs is made of from and parameterKey. Input uses from to reference output, parameterKey is a expression that assigns the value of the input to the corresponding field.

but Inputs can not pass arguments to array object.
for example, my Application as below, User can not use Inputs to set  "bar" of env .

```yaml

apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: website
spec:
  components:
    - name: frontend
      type: webservice
      properties:
        image: oamdev/testapp:v1
        cmd: ["node", "server.js"]
        port: 8080
        cpu: "0.1"
        env:
          - name: FOO
            value: bar
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**KubeVela Version**

**Cluster information**

**Additional context**
