### ISSUE TITLE
An application with outputs and inputs could not be resumed when the workflow suspended.

### ISSUE THREAD

**Issue by zzxwill** [oam-dev/kubevela#3431]
**Describe the bug**

**To Reproduce**

1. Apply application 

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: a-static-website
spec:
  components:
    - name: create-bucket
      type: alibaba-oss-website
      properties:
        bucket: deploy-website-dev
        acl: public-read
        index_document: index.html
        error_document: error/index.html
        writeConnectionSecretToRef:
          name: oss-website-conn
      outputs:
        - name: bucket
          valueFrom: output.status.apply.outputs.BUCKET_NAME.value
        - name: endpoint
          valueFrom: output.status.apply.outputs.EXTERNAL_ENDPOINT.value
        - name: index_document
          # valueFrom: properties.index_document
          valueFrom: output.spec.variable.index_document

    - name: deploy-website
      type: deploy-website
      inputs:
        - from: bucket
          parameterKey: properties.bucket
        - from: endpoint
          parameterKey: properties.endpoint
        - from: index_document
          parameterKey: properties.index_document
      properties:
        static_web_url: "https://github.com/cloudacademy/static-website-example.git"
```

2. Wait for it to fail and try to resume the workflow

```
  Workflow:
    App Revision:  a-static-website-v2:e1343cc3c40d3c6f
    Context Backend:
      API Version:  v1
      Kind:         ConfigMap
      Name:         workflow-a-static-website-context
      UID:          dfab9f23-44cf-4c8f-b9a2-3b83cad534ad
    Finished:       false
    Message:        The workflow suspends automatically because the failed times of steps have reached the limit(10 times)
    Mode:           DAG
    Start Time:     2022-03-12T08:22:06Z
    Steps:
      First Execute Time:  2022-03-12T08:22:06Z
      Id:                  xz9dhy7kvt
      Last Execute Time:   2022-03-12T08:22:57Z
      Message:             from source
      Name:                create-bucket
      Phase:               failed
      Reason:              Output
      Type:                apply-component
    Suspend:               true
    Terminated:            false
Events:
  Type    Reason           Age                    From         Message
  ----    ------           ----                   ----         -------
  Normal  Revisioned       6m13s (x6 over 6m16s)  Application  Revisioned successfully
  Normal  PolicyGenerated  6m13s (x6 over 6m16s)  Application  Policy generated successfully
  Normal  Rendered         6m13s (x6 over 6m16s)  Application  Rendered successfully
  Normal  Parsed           73s (x28 over 6m16s)   Application  Parsed successfully
➜  catalog git:(alibaba-oss-website) ✗ vela workflow restart a-static-website
Error: the application must have workflow
```

**Expected behavior**

**Screenshots**

**KubeVela Version**

**Cluster information**

**Additional context**
