### ISSUE TITLE
[BUG] Refresh Traitdefinition spec.appliesToWorkloads field for webservice/backend/job

### ISSUE THREAD

**Issue by zzxwill** [oam-dev/kubevela#346]
With the introduce three workloads webservice/backend/job, let's refresh spec.appliesToWorkloads field for all Traits `Metrics`, `Route` and `Scale`. In Dashboard, when a trait is about to be attached to a workload, we will check whether it's allowed by checking the field.

```
apiVersion: core.oam.dev/v1alpha2
kind: TraitDefinition
metadata:
  name: metricstraits.standard.oam.dev
  namespace: default
  annotations:
    definition.oam.dev/apiVersion: standard.oam.dev/v1alpha1
    definition.oam.dev/kind: MetricsTrait
spec:
  appliesToWorkloads:
    - containerizedworkloads.core.oam.dev
    - clonesetworkloads.apps.kruise.io
    - deployments.apps
    - statefulsets.apps
```
