### ISSUE TITLE
vela dry-run CLI didn't report for the application format error

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela#3484]
The application format is wrong, but vela dry-run CLI didn't report for that, I think this is an issue:

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: website
spec:
  components:
    - name: custom-component
      type: test-stateful
      properties:
        image: nginx:latest
        replicas: 1
  traits:
    - type: storageclass
      properties:
        volumeClaimTemplates:
          - name: test
            requests: 10Gi
            storageClassName: cbs
            mountPath: /usr/share/nginx/html
```

The right format should be:

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: website
spec:
  components:
    - name: custom-component
      type: test-stateful
      properties:
        image: nginx:latest
        replicas: 1
      traits:
        - type: storageclass
          properties:
            volumeClaimTemplates:
              - name: test
                requests: 10Gi
                storageClassName: cbs
                mountPath: /usr/share/nginx/html
```

As a fact, if we try to apply the application yaml to K8s, it will report error:

```
$ kubectl apply -f references/appfile/dryrun/testdata/temp-2022-3-21.yaml
error: error validating "references/appfile/dryrun/testdata/temp-2022-3-21.yaml": error validating data: ValidationError(Application.spec): unknown field "traits" in dev.oam.core.v1beta1.Application.spec; if you choose to ignore these errors, turn validation off with --validate=false
```

So I think maybe we can rely on something that dry-in for Application CR in K8s serverside for this check.

_Originally posted by @wonderflow in https://github.com/oam-dev/kubevela/discussions/3473#discussioncomment-2405354_
