### ISSUE TITLE
[BUG] Don't show "definition" in vela workloads

### ISSUE THREAD

**Issue by resouer** [oam-dev/kubevela#349]
`containerizeds.standard.oam.dev` is the schema for "Backend Worker" workload type, not definition, also, it should not be exposed to users of vela.

It should be sth like:

```console
$ vela workloads
NAME         	DESCRIPTION                                                  
backend      	Backend worker without ports exposed          
task         	One-time off task or job
webservice   	Long running service with ports exposed
```

**Comment by wonderflow** [comment]
Totally agree with this proposal, but we don't have any field for description. I propose two way for this need；

1. add a description field in extention

```
apiVersion: core.oam.dev/v1alpha2
kind: WorkloadDefinition
metadata:
  name: webservice
spec:
  definitionRef:
    name: podspecworkloads.standard.oam.dev
  childResourceKinds:
    - apiVersion: apps/v1
      kind: Deployment
    - apiVersion: v1
      kind: Service
  extension:
    description: Long running service with ports exposed
    ...
```

2. add an annotation for description

```
apiVersion: core.oam.dev/v1alpha2
kind: WorkloadDefinition
metadata:
  name: webservice
  annotations:
     definition.oam.dev/description: Long running service with ports exposed
spec:
  definitionRef:
    name: podspecworkloads.standard.oam.dev
  childResourceKinds:
    - apiVersion: apps/v1
      kind: Deployment
    - apiVersion: v1
      kind: Service
  extension:
    ...
```

Which one do you feel better? @resouer @ryanzhang-oss @hongchaodeng @zzxwill
