### ISSUE TITLE
The storage trait of configMap type does not support number value

### ISSUE THREAD

**Issue by fzy-Line** [oam-dev/kubevela#3494]
When the data value of a ConfigMap  is a number, the ConfigMap will not be created. For example, I use the vela up command to deploy the follow application, but the test1 configMap is not be created. 

```
# sample.yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: storage-app
spec:
  components:
    - name: express-server
      type: webservice
      properties:
        image: crccheck/hello-world
        ports:
          - port: 8000
      traits:
        - type: storage
          properties:
            # ConfigMap type storage
            configMap:
              - name: test1
                mountPath: /test/mount/cm
                # Mount ConfigMap to Env
                mountToEnv:
                  envName: TEST_ENV
                  configMapKey: key1
                data:
                  key1: 123   # number value
                  key2: value2
```

The I try to use the `vela dry-run` to generate the k8s resources manifests.

```
apiVersion: v1
data:
  key1: 123
  key2: value2
kind: ConfigMap
metadata:
  annotations: {}
  labels:
    app.oam.dev/appRevision: ""
    app.oam.dev/component: express-server
    app.oam.dev/name: storage-app
    app.oam.dev/namespace: default
    app.oam.dev/resourceType: TRAIT
    trait.oam.dev/resource: configmap-test1
    trait.oam.dev/type: storage
  name: test1
  namespace: default
```
Finally, I use the `kubectl apply` command to deploy this configMap, I got this error

```
Error from server (BadRequest): error when creating "cm.yaml": ConfigMap in version "v1" cannot be handled as a ConfigMap: v1.ConfigMap.Data: ReadString: expects " or n, but found 1, error found in #10 byte of ...|:{"key1":123,"key2":|..., bigger context ...|{"apiVersion":"v1","data":{"key1":123,"key2":"value2"},"kind":"ConfigMap","metadata":|...
```

The official documentation shows that the type of the configMap data property in the storage trait is `map[string](null|bool|string|bytes|{...}|[...]|number)`.
