### ISSUE TITLE
notification email doesn't work

### ISSUE THREAD

**Issue by huanggze** [oam-dev/kubevela#3518]
**Describe the bug**

The workflowstep of notification.email doesn't work. Application hang.

**To Reproduce**

I'm pretty sure my email setting is correct. But no email sent out. Checking with the message from `vela status` (see snapshots), I am guessing something is wrong [here](https://github.com/oam-dev/kubevela/blob/v1.2.5/vela-templates/definitions/internal/workflowstep/notification.cue#L298)? There seems no field of `value` for `parameter.email.from`. So `address:  parameter.email.from.value` should be `address:  parameter.email.from.address`?

```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: nginx
  namespace: default
spec:
  components:
  - name: nginx
    properties:
      cpu: "0.2"
      exposeType: ClusterIP
      image: nginx
      memory: 200Mi
      ports:
      - expose: true
        port: 80
        protocol: TCP
    traits:
    - properties:
        replicas: 1
      type: scaler
    type: webservice
  policies:
  - name: env-bindings-default
    properties:
      envs:
      - name: default
        patch: {}
        placement:
          clusterSelector:
            name: local
          namespaceSelector:
            name: default
    type: env-binding
  workflow:
    steps:
    - name: default
      properties:
        env: default
        policy: env-bindings-default
      type: deploy2env
    - name: email
      properties:
        email:
          content:
            body: test
            subject: test
          from:
            address: xxx@163.com
            host: smtp.163.com
            password:
              value: xxx
            port: 465
          to:
          - xxx@163.com
      type: notification
```

**Expected behavior**

**Screenshots**

<img width="1433" alt="image" src="https://user-images.githubusercontent.com/22350668/160235300-e0d844af-8ed6-4363-93fd-b030c1c52cdb.png">

<img width="1292" alt="image" src="https://user-images.githubusercontent.com/22350668/160235341-51145541-c0bf-4205-bc1f-22554a7f1ae1.png">

**KubeVela Version**

CLI Version: v1.2.5
Core Version: 1.2.5
GitRevision: git-ef80b66
GolangVersion: go1.17.7

**Cluster information**

v1.22.3

**Additional context**
