### ISSUE TITLE
[Feature] Application CustomStatus

### ISSUE THREAD

**Issue by Somefive** [oam-dev/kubevela#3561]
**Is your feature request related to a problem? Please describe.**

In some cases, users might want to use customized application status to aggregate information inside the application. We should provide some ways for user to do this extension.

```bash
$ kubectl get app demo
NAME  COMPONENT    TYPE        PHASE    HEALTHY  AGE  STATUS
demo  hello-world  webservice  running  true     19h  pod: 1
```
```yaml
# app.yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: demo
spec:
  components:
    - name: hello-world
      type: webservice
      properties:
        image: crccheck/hello-world
        port: 8000
  policies:
    - type: custom-status
      name: example-custom-status-policy
      properties:
        view: pod-view
  status:
    customStatus:
      message: "pod: 1"
      details:
        pods:
          - image: crccheck/hello-world
            name: hello-world-xxx
```
```
# pod-view.cue
import (
    "vela/ql"
)
load: op.#Steps & {
    rt: ql.#LoadResourceTracker @step(1)
    deployments: [for rsc in rt.spec.managedResources if rsc.Kind == "Deployment" && rsc.APIVersion == "apps/v1" && rsc.raw != _|_ {rsc}] @step(2)
    deploymentPods: [for deploy in deployments {
        ql.#List & {
            apiVersion: "v1"
            kind: "Pod"
            cluster: deploy.cluster
            namespace: deploy.namespace
            matchLabels: rsc.raw.spec.selector.matchLabels
        }
    }] @step(3)
    pods: Flatten(deploymentPods) @step(4)
}
output: {
    details: pods: [for pod in load.pods {
        image: pod.spec.containers[0].image
        name: pod.metadata.name
    }]
    message: "pod: \(len(details.pods))"
}
```

The pod-view.cue should be store in ConfigMap or some CRDs like `QueryView`. Then a controller like HealthScopeController will take charge of calculating status based on the cue template and write the status back to the application. 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
