### ISSUE TITLE
vela-core does not report error, when component depends on invalid component

### ISSUE THREAD

**Issue by StevenLeiZhang** [oam-dev/kubevela#3635]
**Describe the bug**
vela-core does not report error, when component depends on invalid component

**To Reproduce**
1. apply one application, Please note that "express-server-3" depends on one invalid component "express-server-0"
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: first-vela-app
spec:
  components:
    - name: express-server-1
      type: webservice
      properties:
        image: crccheck/hello-world
        port: 8000
    - name: express-server-2
      type: webservice
      dependsOn:
       -  express-server-1
      properties:
        image: crccheck/hello-world
        port: 8080
    - name: express-server-3
      type: webservice
      dependsOn:
       -  express-server-0
      properties:
        image: crccheck/hello-world
        port: 8088
```

2. check application status
```
kubectl -n vela-system describe applications.core.oam.dev first-vela-app

```

```
Events:
  Type    Reason           Age                From         Message
  ----    ------           ----               ----         -------
  Normal  Revisioned       39s (x6 over 42s)  Application  Revisioned successfully
  Normal  PolicyGenerated  39s (x6 over 42s)  Application  Policy generated successfully
  Normal  Rendered         39s (x6 over 42s)  Application  Rendered successfully
  Normal  Parsed           38s (x7 over 42s)  Application  Parsed successfully
```

3. there is not error message reported in both "kubectl describe" and vela-core' log

**Expected behavior**
1. vela-core reports some error messages to indicate this mistake.

**Screenshots**

**KubeVela Version**

```
➜  KubeVela vela version
CLI Version: v1.3.0
Core Version: 1.3.0
GitRevision: git-3aa4412
GolangVersion: go1.17.8
➜  KubeVela
```

**Cluster information**

**Additional context**
