### ISSUE TITLE
The app with from-inner-system source-of-truth is synced to VelaUX database.

### ISSUE THREAD

**Issue by barnettZQG** [oam-dev/kubevela#3653]
**Describe the bug**

The app spec:
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  annotations:
    config.oam.dev/alias: ""
    oam.dev/kubevela-version: v1.3.0-beta.2
  creationTimestamp: "2022-04-14T08:43:09Z"
  finalizers:
  - app.oam.dev/resource-tracker-finalizer
  generation: 1
  labels:
    app.oam.dev/source-of-truth: from-inner-system
    config.oam.dev/catalog: velacore-config
    config.oam.dev/project: default
    config.oam.dev/type: config-image-registry
  name: test-hub
  namespace: vela-system
```

**Screenshots**
![image](https://user-images.githubusercontent.com/18493394/163352172-1711110b-e4ed-430f-af42-9fb40ee29b9d.png)

**KubeVela Version**
1.3.0

**Additional context**

This app is for integrations.
