### ISSUE TITLE
[Feature] Add some tags to a bound of cloud resources

### ISSUE THREAD

**Issue by zzxwill** [oam-dev/kubevela#3671]
For the terraform modules, is there a way to extend the component definition yaml to say require certain fields like some tags we want every resource that is created to have as a parameter and not just depend on the tf?

**Comment by zzxwill** [comment]
Does the tag is like https://docs.aws.amazon.com/general/latest/gr/aws_tagging.html?

**Comment by quintonm** [comment]
The basic idea is that we have required tags for K8s resources (including the application) and AWS resources. Some tags are only applied in K8s or AWS but many of them overlap (with different tag names potentially). We are looking for a way to validate that these tags have been applied and fail the application deployment if they have not.

**Comment by zzxwill** [comment]
@quintonm Could you please please provide one to two examples of how you would like a normal and a Terraform application to be tagged?

**Comment by quintonm** [comment]
@zzxwill Here is an example application for crossplane (terraform would require the same AWS tags).


```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: test-application
  labels:
    "app.kubernetes.io/name": test-application
    "app.kubernetes.io/part-of": claim-manager
    "app.kubernetes.io/managed-by": kubevela
    "atmos.guidewire.com/dept": "123"
    "atmos.guidewire.com/tenancy-scope": single
    "atmos.guidewire.com/tenant-name": acme
spec:
  components:
    - name: pending-review
      type: atmos-xp-aws-sqs  # crossplane composition to provision AWS SQS queue
      properties:
        fifoQueue: true
        quadrant: mdev # needed for AWS tag

```

AWS Tags
```
gwcp:v1:resource-type:managed-by = app.kubernetes.io/managed-by (k8s label)
atmos.guidewire.com/dept = atmos.guidewire.com/dept (k8s label)
gwcp:v1:tenant:name = atmos.guidewire.com/tenant-name (k8s label)
gwcp:v1:resource-type:provisioning-source = atmos-xp-aws-sqs/1.0.1 (component type / addon version)
gwcp:v1:quadrant:name = quadrant (component parameter)
```

As you can see, there is some overlap between the k8s labels and AWS tags. Crosslane allows me to validate anything that I map to the managed resource (like the atmos.guidewire.com/dept label).  This provides a way for me to enforce adding the labels that overlap with AWS tags but not the labels that are just for K8s.

For applications that do not use terraform or crossplane, I would still like to validate that the k8s labels were supplied.
