### ISSUE TITLE
[Feature] apisevier trigger webhook supports different images in different environments

### ISSUE THREAD

**Issue by zhiyuone** [oam-dev/kubevela#3707]
**Is your feature request related to a problem? Please describe.**

In one application, maybe different environment need difference images, such as:
```yaml
spec:
  workflow:
    steps:
      - name: prod
        properties:
          env: prod
          image: nginx:stable
          policy: env-bindings-dev
        type: deploy2env
      - name: test
        properties:
          env: test
          image: nginx:wip
          policy: env-bindings-dev
        type: deploy2env
```

**Describe the solution you'd like**

I think we need a webhook(apiserver trigger) to update this.

**Describe alternatives you've considered**

**Additional context**
