### ISSUE TITLE
Unable to create application due to component name collision

### ISSUE THREAD

**Issue by dhiguero** [oam-dev/kubevela#3716]
**Describe the bug**

When trying to deploy two applications, if one of them share the same component name, the system returns an obscure error.

**To Reproduce**

Deploy two applications, for example using the `first-vela-app` one from the example without the trait.

<details>
<summary>Application 1</summary>

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: first-vela-app1
spec:
  components:
    - name: express-server
      type: webservice
      properties:
        image: crccheck/hello-world
        port: 8000
```

</details>

<details>
<summary>Application 2</summary>

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: first-vela-app2
spec:
  components:
    - name: express-server
      type: webservice
      properties:
        image: crccheck/hello-world
        port: 8000
```

</details>

```
$ kubectl create -f first-vela-app1.yaml
application.core.oam.dev/first-vela-app1 created

$ kubectl create -f first-vela-app2.yaml
The request is invalid
```

**Expected behavior**

Both applications should be deployed independently of which is the name of the component in the application. From the point of view of an environment where different developers are collaborating, it is not possible to validate that none of the components have the same name.

**Screenshots**

**KubeVela Version**

* Kubevela 1.3.0

**Cluster information**

* Kind with Kubernetes v1.20.7

**Additional context**

I think this may be related with the underlying deployment name. I think it should be possible to add a suffix to the deployment name upon instantiation to avoid this issue (in the same way K8s suffixes pods).
