### ISSUE TITLE
vela addon enable XX does not behave consistent with or without policy

### ISSUE THREAD

**Issue by cezhang** [oam-dev/kubevela#3734]
**Describe the bug**

Hi, I am the contributor of Argocd addon, and I am working on helm support of argocd addon. Here I experience inconsistent behavior when I develop the new application.   

----------

**What I want is to apply all **yaml** resources(these yaml files does not specify namespace) to a specified namespace **"argocd"**, and **only** deploy to **runtime clusters****
```
argocd
├── definitions
│   ├── XXXX.cue
│   ├─_.....
├── resources
│   └── xxxxx.yaml 
│   └── ......
├── readme.md
└── template.yaml
```

So first I try using the **apply-remaining** with namespace property to specify the target namespace, like the following:
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: argocd
  namespace: vela-system
spec:

 workflow:
   steps:
     - name: apply-remaining
       type: apply-remaining
       properties:
         namespace: argocd
``` 
It doesn't work, so I check the source code from [addon.go](https://github.com/oam-dev/kubevela/blob/master/pkg/addon/addon.go) and found the workflow would be hardcode to these two step. The approach does not work
```
switch {
	case isDeployToRuntimeOnly(addon):
		if len(deployClusters) == 0 {
			// deploy to all clusters
			app.Spec.Workflow = &v1beta1.Workflow{Steps: []v1beta1.WorkflowStep{
				{
					Name: "deploy-control-plane",
					Type: "apply-application",
				},
				{
					Name: "deploy-runtime",
					Type: "deploy2runtime",
				},
			}}
```
Then, I got suggestion by using the new **policy** feature. So I try this time.
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: argocd
  namespace: vela-system
spec:
  policies:
  - name: apply-to-ns
    type: topology
    properties:
      clusters: ["local"]
      namespace: argocd
```
For using policy feature, I must run "vela addon enable argo/ -c local". 
Again, [addon.go](https://github.com/oam-dev/kubevela/blob/master/pkg/addon/addon.go) will generate two policies, one for cluster local with argocd namespace and the one also for cluster local but without namespace(it will eventually use the default vela namespace, vela-system).  
The vela will actually deploy two sets resources in argocd namespace and vela-system namespace !!!!!
```
} else {
			var found bool
			for _, c := range deployClusters {
				if c == multicluster.ClusterLocalName {
					found = true
					break
				}
			}
			if !found {
				deployClusters = append(deployClusters, multicluster.ClusterLocalName)
			}
			// deploy to specified clusters
			if app.Spec.Policies == nil {
				app.Spec.Policies = []v1beta1.AppPolicy{}
			}
			body, _ := json.Marshal(map[string][]string{types.ClustersArg: deployClusters})
			app.Spec.Policies = append(app.Spec.Policies, v1beta1.AppPolicy{
				Name:       "specified-addon-clusters",
				Type:       v1alpha1.TopologyPolicyType,
				Properties: &runtime.RawExtension{Raw: body},
			})
			// addon should not contain workflow, this also update legacy addon with deploy2runtime steps
			app.Spec.Workflow = nil
		}
```

I took a look of fluxcd addon, its yaml resources file are hardcoded with namespace "flux-system", I can do that for workaround in this case, but I instead want to configure in the addon template,  and also keep those file close to official release.

BTW, it's not convenient to upgrade the next version with changing namespace file by file ( the yaml files are all come from official argo release, and default without namespace).

**To Reproduce**

**Expected behavior**

**Screenshots**

**KubeVela Version**
CLI Version: 1.3.1
Core Version: 1.3.1

**Cluster information**

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:51:05Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6+k3s1", GitCommit:"3228d9cb9a4727d48f60de4f1ab472f7c50df904", GitTreeState:"clean", BuildDate:"2022-01-25T01:27:44Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}

**Additional context**
