### ISSUE TITLE
change the replicas via the scaler trait lead to all pod recreated

### ISSUE THREAD

**Issue by barnettZQG** [oam-dev/kubevela#3751]
**Describe the bug**

As stated in the title.

**To Reproduce**

1.  create an application with scaler trait.
2. change the replicas and apply the configuration.
3. watch the pod change.

**Expected behavior**

Only create new pods or delete extra pods.

**Screenshots**

![image](https://user-images.githubusercontent.com/18493394/165081714-810f5f14-d999-46f5-bda1-afc05ce2ea1d.png)

**KubeVela Version**

1.3.2

**Cluster information**
Kubernetes version: 1.22

**Additional context**

The reason for this issue is the pod template has a component version label, after changing the trait, the version is changed. Vela not should add the version label to the pod template.

```
...
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.oam.dev/component: express-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.oam.dev/component: express-server
        app.oam.dev/revision: express-server-v3
    spec:
      containers:
...
```
