### ISSUE TITLE
[Feature] Support trait with custom resource be dispatched to hubcluster

### ISSUE THREAD

**Issue by fourierr** [oam-dev/kubevela#3754]
**Is your feature request related to a problem? Please describe.**

By default, traits cr are dispatched to managed clusters along with component, and we want the ability for traits to be dispatch to hubcluster.

**Describe the solution you'd like**

Firstly, add a new field `hubClusterDispatchOnlyEnabled` in the trait-definition and applicationrevision to identify whether the trait is delivered to the hubcluster
```yaml
            spec:
              description: A TraitDefinitionSpec defines the desired state of a TraitDefinition.
              properties:
                appliesToWorkloads:
                  items:
                    type: string
                  type: array
                conflictsWith:
                  description: 'ConflictsWith specifies the list of traits(CRD name,
                  Definition name, CRD group) which could not apply to the same workloads
                  with this trait. Traits that omit this field can work with any other
                  traits. Example rules: "service" # Trait definition name "services.k8s.io"
                  # API resource/crd name "*.networking.k8s.io" # API group "labelSelector:foo=bar"
                  # label selector labelSelector format: https://pkg.go.dev/k8s.io/apimachinery/pkg/labels#Parse'
                  items:
                    type: string
                  type: array
                manageWorkload:
                  description: ManageWorkload defines the trait would be responsible
                    for creating the workload
                  type: boolean
                podDisruptive:
                  description: PodDisruptive specifies whether using the trait will
                    cause the pod to restart or not.
                  type: boolean
                revisionEnabled:
                  description: Revision indicates whether a trait is aware of component
                    revision
                  type: boolean
                hubClusterDispatchOnlyEnabled:
                  description: hubClusterDispatchOnlyEnabled indicates which cluster is dispatched to
                  type: boolean
```
Secondly, deploy the hubcluster trait cr separately
```go
		readyWorkload, readyTraits, err := renderComponentsAndTraits(h.r.Client, manifest, appRev, overrideNamespace, env)
		if err != nil {
			return nil, nil, false, err
		}
		checkSkipApplyWorkload(wl)
		dispatchResources, hubClusterOnlyTraits := checkHubClusterOnlyTraits(wl.Traits, readyTraits, af.Namespace)
		if !wl.SkipApplyWorkload {
			dispatchResources = append(dispatchResources, readyWorkload)
		}

		if err := h.Dispatch(ctx, clusterName, common.WorkflowResourceCreator, dispatchResources...); err != nil {
			return nil, nil, false, errors.WithMessage(err, "Dispatch")
		}
		localCtx := multicluster.ContextWithClusterName(ctx, "local")
		if err := h.Dispatch(localCtx, "local", common.WorkflowResourceCreator, hubClusterOnlyTraits...); err != nil {
			return nil, nil, false, errors.WithMessage(err, "Dispatch")
		}
```
Thirdly, some examples are as follows

- An example of hubClusterDispatchOnlyTrait `hubcpuscaler` is as follows
```cue
hubcpuscaler: {
	type: "trait"
	annotations: {}
	labels: {
		"ui-hidden": "true"
	}
	description: "Automatically scale the component based on CPU usage."
	attributes: {
		appliesToWorkloads: ["deployments.apps"]
		hubClusterDispatchOnlyEnabled: true
	}
}

template: {
	outputs: hubcpuscaler: {
		apiVersion: "autoscaling/v1"
		kind:       "HorizontalPodAutoscaler"
		metadata: name: context.name
		spec: {
			scaleTargetRef: {
				apiVersion: parameter.targetAPIVersion
				kind:       parameter.targetKind
				name:       context.name
			}
			minReplicas:                    parameter.min
			maxReplicas:                    parameter.max
			targetCPUUtilizationPercentage: parameter.cpuUtil
		}
	}

	parameter: {
		min: *1 | int
		max: *10 | int
		cpuUtil: *50 | int
		targetAPIVersion: *"apps/v1" | string
		targetKind: *"Deployment" | string
	}
}
```
- An example of application with hubClusterDispatchOnlyTrait `hubcpuscaler`  is as follows
```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: fourierapp03
  namespace: fourier
spec:
  components:
    - name: fourierapp03-fouriercomponent-01
      type: webservice
      properties:
        image: busybox:latest
        imagePullPolicy: IfNotPresent
        cmd: [ "sleep", "1000000000" ]
        cpu: "0.1"
        mem: "100Mi"
      traits:
        - type: hubcpuscaler
          properties:
            min: 1
            max: 10
            cpuPercent: 60
        - type: annotations
          properties:
            abc: "def"
        - type: expose
          properties:
            port: [ 80 ]
  policies:
    - name: fourierapp03-topology-01
      type: topology
      properties:
        clusters: [ "kind01" ]
        namespace: fourier01
    - name: fourierapp03-topology-02
      type: topology
      properties:
        clusters: [ "kind02" ]
        namespace: fourier02
  workflow:
    steps:
      - type: deploy
        name: fourierapp03-deploy-01
        properties:
          policies: [ "fourierapp03-topology-01","fourierapp03-topology-02" ]
```
**Describe the situation you'd expected**

![image](https://user-images.githubusercontent.com/35767528/165214695-34814112-3676-4a95-ae88-5bb5f3ad70e8.png)

**Additional context**

- HubClusterDispatchOnlyTraits does not currently support deployment in the form of helm release, Git Repo, etc.
