### ISSUE TITLE
Health status is not updated if the trait status is changed

### ISSUE THREAD

**Issue by tossmilestone** [oam-dev/kubevela#3765]
**Describe the bug**

We developed a trait definition `generic-patch` to patch a rendered object with `json patch`， using `customStatus` and `healthPolicy` to check the health status of the trait. The trait will create a `PatchTrait` cr, and the controller will apply the patch to the target object in the `PatchTrait`.

The service status in the application won't be updated if the `PatchTrait` cr has change its status after updating the application. The status will be updated correctly only we update the application again with change to the application spec.

The code of collecting the service status is in `AppHandler.collectHealthStatus` of `pkg/controller/core.oam.dev/v1alpha2/application/apply.go`.  `collectHealthStatus` is called in `AppHandler.applyComponentFunc`. And the `applyComponentFunc` will only be executed when the workflow is restarted again.

**To Reproduce**

1. The YAML files of Component/Trait I used.

The trait definition:
```
kind: TraitDefinition
metadata:
  annotations:
    definition.oam.dev/description: Patch the k8s resources of components with json patch.
  name: generic-patch
  namespace: vela-system
spec:
  appliesToWorkloads:
    - webservice
    - statefulservice
  definitionRef:
    name: patches.oam.alauda.io
  podDisruptive: true
  schematic:
    cue:
      template: |
        outputs: patch: {
                apiVersion: "oam.alauda.io/v1alpha1"
                kind:       "PatchTrait"
                metadata: name: context.name
                spec: patches:  parameter.patches
        }
        parameter: {
                // +usage=Specify the patches
                patches: [...{
                        // +usage=The json-patch string
                        patch: [...string]
                        // +usage=The target resource to patch
                        target: {
                                // +usage=The kuberntes resource type to patch
                                resource: string
                                // +usage=The name of the kubernetes resource
                                name: string
                        }
                },
                ]
        }
  status:
    customStatus: |-
      if context.outputs.patch.status.message != _|_ {
        message: context.outputs.patch.status.message
      }
      if context.outputs.patch.status.message == _|_ {
        message: ""
      }
    healthPolicy: 'isHealth: context.outputs.patch.status.phase == "success"'
  workloadRefPath: spec.workloadRef
```

The `PatchTrait` CRD:
```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: patchtraits.oam.alauda.io
spec:
  conversion:
    strategy: None
  group: oam.alauda.io
  names:
    kind: PatchTrait
    listKind: PatchTraitList
    plural: patchtraits
    singular: patchtrait
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: PatchTrait is the trait to patch the resources of component
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              patches:
                description: Patches is the patches to be applied
                items:
                  properties:
                    patch:
                      description: Patch is the json patches to be applied
                      items:
                        type: string
                      type: array
                    target:
                      description: Target is the resource to be patched
                      properties:
                        name:
                          description: Name is the name of the resource to be patched
                          type: string
                        resource:
                          description: Resource is the resource type to be patched
                          type: string
                      type: object
                  type: object
                type: array
              workloadRef:
                description: WorkloadReference to the workload who is applied with
                  the action
                properties:
                  apiVersion:
                    description: API version of the referent.
                    type: string
                  fieldPath:
                    description: 'If referring to a piece of an object instead of
                      an entire object, this string should contain a valid JSON/Go
                      field access statement, such as desiredState.manifest.containers[2].
                      For example, if the object reference is to a container within
                      a pod, this would take on a value like: "spec.containers{name}"
                      (where "name" refers to the name of the container that triggered
                      the event) or if no container name is specified "spec.containers[2]"
                      (container with index 2 in this pod). This syntax is chosen
                      only to have some well-defined way of referencing a part of
                      an object. TODO: this design is not final and this field is
                      subject to change in the future.'
                    type: string
                  kind:
                    description: 'Kind of the referent. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
                    type: string
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names'
                    type: string
                  namespace:
                    description: 'Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/'
                    type: string
                  resourceVersion:
                    description: 'Specific resourceVersion to which this reference
                      is made, if any. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency'
                    type: string
                  uid:
                    description: 'UID of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#uids'
                    type: string
                type: object
            required:
            - patches
            type: object
          status:
            properties:
              conditions:
                description: Conditions of the resource.
                items:
                  description: A Condition that may apply to a resource.
                  properties:
                    lastTransitionTime:
                      description: LastTransitionTime is the last time this condition
                        transitioned from one status to another.
                      format: date-time
                      type: string
                    message:
                      description: A Message containing details about this condition's
                        last transition from one status to another, if any.
                      type: string
                    reason:
                      description: A Reason for this condition's last transition from
                        one status to another.
                      type: string
                    status:
                      description: Status of this condition; is it currently True,
                        False, or Unknown?
                      type: string
                    type:
                      description: Type of this condition. At most one of each condition
                        type may apply to a resource at any point in time.
                      type: string
                  required:
                  - lastTransitionTime
                  - reason
                  - status
                  - type
                  type: object
                type: array
              message:
                type: string
              phase:
                type: string
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
```

3. The YAML file of Application I applied.

Create the application with:
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: health
  namespace: default
spec:
  components:
    - name: nginx
      properties:
        env: []
        image: nginx
        ports: []
        volumes: []
      traits:
        - properties:
            action: start
            replicas: 1
          type: scaler
        - properties:
            patches:
              - patch:
                  - '{"op":"add","path":"/metadata/annotations/a","value":"b"}'
                target:
                  name: nginx
                  resource: deployment
          type: generic-patch
      type: webservice
```

then update it with:
```
kind: Application
apiVersion: core.oam.dev/v1beta1
metadata:
  name: health
  namespace: default
spec:
  components:
    - name: nginx
      properties:
        env: []
        image: nginx
        ports: []
        volumes: []
      traits:
        - properties:
            action: start
            replicas: 1
          type: scaler
        - properties:
            patches:
              - patch:
                  - '{"op":"add","path":"/metadata/annotations/a","value":"b"}'
                target:
                  name: nginx
                  resource: deployment
              - patch:
                  - '{"op":"remove","path":"/metadata/annotations/b","value":""}'
                target:
                  name: nginx
                  resource: deployment
          type: generic-patch
      type: webservice
```
5. See error

The `PatchTrait` should have error in status:
```
apiVersion: oam.alauda.io/v1alpha1
kind: PatchTrait
metadata:
  name: nginx
  namespace: default
spec:
  patches:
  - patch:
    - '{"op":"add","path":"/metadata/annotations/a","value":"b"}'
    target:
      name: nginx
      resource: deployment
  - patch:
    - '{"op":"remove","path":"/metadata/annotations/b","value":""}'
    target:
      name: nginx
      resource: deployment
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx
status:
  conditions:
  - lastTransitionTime: "2022-04-26T09:18:50Z"
    message: failed to apply the patches of the workload
    reason: ReconcileError
    status: "False"
    type: Synced
  message: 'error in remove for path: ''/metadata/annotations/b'': Unable to remove
    nonexistent key: b: missing value'
  phase: failed
```

But the status in application still has the patch trait with success status.
```
  services:
    - healthy: true
      name: nginx
      traits:
        - healthy: true
          type: scaler
        - healthy: true
          message: Patch Success
          type: generic-patch
      workloadDefinition:
        apiVersion: apps/v1
        kind: Deployment
```

**Expected behavior**

The application should update the status of the `generic-patch` trait align with the status of the `PatchTrait` cr.

**Screenshots**

**KubeVela Version**
v1.2.4

**Cluster information**

- Kubernetes Version: 1.21.10
**Additional context**
