### ISSUE TITLE
[BUG] traitDefinition metadata.name v.s. trait name 

### ISSUE THREAD

**Issue by captainroy-hy** [oam-dev/kubevela#425]
**Describe the bug**

Since currently appConfig controller uses TraitTypeLabel(traitName) to get trait definition, it's necessary to make TraitDefinition's metadata.name identical to the parameter name in definition yaml file, right? 

If so, it seems something wrong with current definitions of manualscale and metrics.
https://github.com/oam-dev/kubevela/blob/cbc8a90152fab0055dc046335c5961ef8199752b/charts/vela-core/templates/definitions/manualscalars.yaml#L8
```yaml
apiVersion: core.oam.dev/v1alpha2
kind: TraitDefinition
metadata:
  annotations:
    definition.oam.dev/apiVersion: core.oam.dev/v1alpha2
    definition.oam.dev/kind: ManualScalerTrait
    definition.oam.dev/description: "Scale replica for workload"
  name: scaler # should be `scale`?
  namespace: default
...
  extension:
    template: |-
      output: {
      	apiVersion: "core.oam.dev/v1alpha2"
      	kind:       "ManualScalerTrait"
      	spec: {
      		replicaCount: parameter.replica
      	}
      }
      #scale: {
      	//+short=r
      	replica: *2 | int
      }
      parameter: #scale
```
The same occurs in Metrics trait.

**To Reproduce**

`vela scale xxx` and AppConfig raises an error as below:
> cannot find trait definition "core.oam.dev/v1alpha2" "ManualScalerTrait" "mysvc-trait-84bfd46f4d": TraitDefinition.core.oam.dev "scale" not found

**Expected behavior**

**Screenshots**

**Cluster information**

**Additional context**
