### ISSUE TITLE
[BUG] Use CUE template as schema for Web Service

### ISSUE THREAD

**Issue by resouer** [oam-dev/kubevela#443]
As next step, we will use CUE template directly as the schema for Web Service workload, and even for many trait.

For example:

```yaml
apiVersion: core.oam.dev/v1alpha2
kind: WorkloadDefinition
metadata:
  name: webservice
spec:
  definitionRef:
    name: apps.deployment
  extension:
    template: |
      outputs: service: {
        apiVersion: "v1"
        kind: "Service"
        metadata:
          name: context.name
        spec: {
          ...
        }
      }
      
      outputs: deployment: {
        apiVersion: "apps/v1"
        kind: "Deployment"
        spec: {
          ...
        }
      }
     #webservice: {
        name: string
        // +usage=specify app image
        // +short=i
        image: string
        // +usage=specify port for container
        // +short=p
        port: *6379 | int
        }
     parameter: #webservice
```
