### ISSUE TITLE
[Feature]  in appfile struct trait order was missing

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela#460]
In AppFile, we use a golang map to store all traits along with workload properties.

```
services:
  express-server:
    # this image will be used in both build and deploy config
    image: oamdev/testapp:v1

    route:
      domain: example.com
      http: # match the longest prefix
        "/": 8080

    scale:
      replica: 2
```

In OAM AppConfig, we use array like:

```
kind: applicationconfiguration
spec:
  components:
  - componentName: express-server
     traits:
     - type: route
       properties:
         domain: example.com
         http: # match the longest prefix
              "/": 8080
     - type:    scale
       properties:
        replica: 2
```

So we lose trait order which could be defined in AppConfig.
