### ISSUE TITLE
[BUG] should print error message if parameter value doesn't satisfy the type

### ISSUE THREAD

**Issue by zzxwill** [oam-dev/kubevela#574]
# Issue description
Deploy an application by `vela up`. The type of parameter `cpuRequests` is string, but the value is set to float or int like `0.5`, With Appfile CUE module processing, the output will leave out parameter `cpuRequests`.
```
name: testapp

services:
  express-server:
    # this image will be used in both build and deploy steps
    image: zzxwill/kubevela-appfile-demo:v1

    build:
      push:
        local: kind

      # Here more runtime specific build templates will be supported, like NodeJS, Go, Python, Ruby.
      docker:
        file: Dockerfile
        context: .

    cmd: ["node", "server.js"]
    port: 8080

    cpuRequests: 0.5
```

# Expectation:
Print error message about the type issue before deploying the application.
