### ISSUE TITLE
[BUG] Error message from underlying scaler (KEDA) should be thrown back to autoscaler and applicationconfiguration event

### ISSUE THREAD

**Issue by zzxwill** [oam-dev/kubevela#575]
If `cpu` value of Autoscale is not set as an string which could be converted to int, like,
cli: `vela autoscale helloworld --svc frontend --min 1 --max 5 --cpu 0.5`
appfile:
```
name: testapp

services:
  express-server:
    # this image will be used in both build and deploy steps
    image: zzxwill/kubevela-appfile-demo:v1

    build:
      push:
        local: kind

      # Here more runtime specific build templates will be supported, like NodeJS, Go, Python, Ruby.
      docker:
        file: Dockerfile
        context: .

    cmd: ["node", "server.js"]
    port: 8080

    cpuRequests: "0.5"

    autoscale:
      min: 1
      max: 4
      cpu: "0.5"

```

Autoscaler won't be successfully deployed due to the following error message.

```
2020-11-11T10:14:15.691Z	ERROR	controller	Reconciler error	{"reconcilerGroup": "keda.sh", "reconcilerKind": "ScaledObject", "controller": "scaledobject", "name": "express-server-trait-56966c9f4f", "namespace": "default", "error": "error getting scaler for trigger #0: error parsing cpu metadata: strconv.Atoi: parsing \"0.05\": invalid syntax"}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:237
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:209
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:188
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
	/go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.Until
	/go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:90
```

Here are what I can think of to avoid the problem.
- The error message should be thrown backup to autoscaler and applicationconfiguration event, which could be retrieved by `vela status`.
- Maybe it should also be checked like #574 But CUE might not support to verify a string which could be converted to int

**Comment by resouer** [comment]
```
    autoscale:
      min: 1
      max: 4
      cpu: "0.5"
```
What does `cpu: "0.5"` mean? CPU usage is more than `50%`? Then why not `cpuPercent: 50`
