### ISSUE TITLE
[Feature] Use CUE to unify definition and template

### ISSUE THREAD

**Issue by hongchaodeng** [oam-dev/kubevela#588]
Currently the definition is written in [yaml](https://github.com/oam-dev/kubevela/tree/master/charts/vela-core/templates/defwithtemplate).

However, it includes a CUE template as raw string:
```yaml
    template: |
      output: {
      	apiVersion: "standard.oam.dev/v1alpha1"
      	kind:       "Autoscaler"
      	spec: {
      		minReplicas: parameter.min
      		maxReplicas: parameter.max
      	}
      }
```

Currently, we write cue template in one file and the rest of definition in another yaml file, and then merge them using scripts.

Ideally,  we should unify these two files into one -- that is, we should use CUE to describe the whole definition like this:

```
apiVersion: "core.oam.dev/v1alpha2"
kind:       "TraitDefinition"
metadata: {
  name: "autoscale"
  annotations: "definition.oam.dev/description": "Automatically scale workloads"
}
spec: {
  appliesToWorkloads: [
    "webservice",
    "backend",
  ]
  workloadRefPath: "spec.workloadRef"
  definitionRef: name: "autoscalers.standard.oam.dev"
  
  extension: template: {
    output: {
      apiVersion: "standard.oam.dev/v1alpha1"
      kind:       "Autoscaler"
      spec: {
        minReplicas: parameter.min
        maxReplicas: parameter.max
      }
    }
  }
}

```
