### ISSUE TITLE
How service to deploy A/B test and adapter istio destination rule

### ISSUE THREAD

**Issue by lklkxcxc** [oam-dev/kubevela#638]
**Is your feature request related to a problem? Please describe.**
How service to deploy A/B test？I don't see A/B test-related release being done. Istio prompts Miss app and version
labels

**Describe the solution you'd like**

![Alt text](http://chuantu.xyz/t6/741/1605843325x1700339730.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by wonderflow** [comment]
Yes, currently it's not supported yet, we're planning to support this in the following weeks. It's high priority on our plan.

**Comment by resouer** [comment]
@lklkxcxc Just want to add the dependency of KubeVela's rollout capability is [Flagger](https://kubevela.io/#/en/developers/references/traits/rollout?id=how-rollout-works) which supports A/B test strategy by default. So in nutshell, we just need to add another trait based on Flagger A/B test following [this guide](https://kubevela.io/#/en/platform-engineers/trait). 

> Note that we currently made some critical changes in Flagger to make it more stable and fits to production usage (it's [forked here](https://docs.flagger.app/tutorials/istio-ab-testing)).

**Comment by resouer** [comment]
I will reopen this issue since Istio support is still not released yet.

The missing parts including:
1. Istio labels
2. A Traffic CRD to carry VirtualService, DestinationRules configurations
3. An application level Service (could be an ApplictionScope) which is required for Istio to work (this is anti-pattern but yes it's how Istio is designed)
4. A ApplicationScope to model Gateway of Istio.

**Comment by kinsolee** [comment]
Is there a temporary solution for A/B test or traffic management at this stage? My team is currently working on an application platform (integrated with a UI dashboard like [kiali](https://github.com/kiali/kiali)) which is based on Kubevela. A/B test and traffic management are significant features of it. 

Before `ApplicationScope` is being released, we'd like to find a makeshift to generate one cross-revision Service and multiple 
revision deployments within an application, so that we can develop and debug our platform features on top of the CRs generated by Kubevela.

An inelegant form of application is like this:
```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: multiversion-hello-world
  namespace: default
spec:
  components:
  - name: hello-world-v1-0-1
    type: webservice
    properties:
      image: crccheck/hello-world
      port: 8000
      version: v1.0.4
    traits:
    // Here outputs a service with label `app=hello-world` which would also be on all deployment components.
      - type: route
  - name: hello-world-v1-0-2
    type: webservice
    properties:
      image: crccheck/hello-world
      port: 8000
      version: v1.0.2
  - name: hello-world-v1-0-3
    type: webservice
    properties:
      image: crccheck/hello-world
      port: 8000
      version: v1.0.3
      env:
      - name: COMMIT_VERSION
        value: v1.0.3
```

I would be glad if there is a better solution. Also, I hope `ApplicationScope` could be implemented as soon as possible.
