### ISSUE TITLE
[Feature] The env section in workload could be simpler

### ISSUE THREAD

**Issue by resouer** [oam-dev/kubevela#647]
The current format is verbose:
```yaml
    env:
      - name: PGDATABASE
        value: postgres
      - name: PGHOST
        valueFrom:
          secretKeyRef:
            name: db-conn
            key: endpoint
```

We may be able to define secret (and config) to a seperate section, ref: https://docs.docker.com/engine/swarm/secrets/#use-secrets-in-compose, and ref the secret directly by name and key.

/cc @hongchaodeng

**Comment by hongchaodeng** [comment]
This could be simplified via templating. See:

- Already supported to define config: https://kubevela.io/#/en/developers/config-app
- Users can always define KV pairs config in CUE template like [this](https://github.com/oam-dev/kubevela/blob/03259630c2f85ef0b8ca66108600a0efd0813504/pkg/cue/base_template.go#L8-L11)

**Comment by hongchaodeng** [comment]
ref #31

**Comment by hongchaodeng** [comment]
After second thought, this is just a templating problem. We could simplify it like what I suggested in [here](https://hackmd.io/7CAp_xklTHmutHnMo5lt2w?view):

```yaml
services:
  express-server:
    env:
      - FOO=bar
      - FOO2=sec:my-secret # map the key same as the env name (`FOO2`) from my-secret to env var
      - FOO3=sec:my-secret:key # map specific key from my-secret to env var
      - sec:my-secret # map all KV pairs from my-secret to env var

    files: # Mount secret as a file
      - /mnt/path=sec:my-secret
```
