### ISSUE TITLE
[Feature] Appfile should support/contain env info

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela#654]
Now `vela env` is contained in the cli environment, appfile itself doesn't contain this information. We should add a section into appfile so `vela up` will contain full information of an app.

For example:

```
name: first-vela-app
env:
  namespace: default
  email: example@example.com
  ...
services:
  testsvc:
    type: webservice
    image: crccheck/hello-world
    port: 8000
    route:
      domain: testsvc.example.com
```
