### ISSUE TITLE
Data passing and processing via CUE templating

### ISSUE THREAD

**Issue by hongchaodeng** [oam-dev/kubevela#656]
There have been offline discussion about supporting data passing and processing (aka. Patch Trait) via CUE templating.
In this issue, I'm gonna summarize the discussion and converge us onto final solution here.

## Background

Currently, some Traits are designed to decompose a monolithic resource definition. For example, a Deployment has too many fields and we only want to expose fields like 'image', 'env' to developers as Workload, and other fields like 'replica', 'tolerations' are exposed as separate Traits. **We want to pass data from such Traits directly onto Workload CR.**

## Data Passing (Patching)

A data passing is an action to get data from an object and do a json-patch to specific field of another object.
In our case we only have scenarios of Trait -> Workload.

A typical example is that, patch `spec.replicaCount` of ManualScalerTrait to `spec.replicas` of Deployment workload. In this example, We want to render trait data into Deployment resource at compile time before anything is applied to APIServer. To do so, we add a new field called `patch` into CUE template:

```yaml
apiVersion: core.oam.dev/v1alpha2
kind: TraitDefinition
metadata:
  name: manualscaler
spec:
  template: |
    patch: {
        spec: replicas: parameter.replicas
    }
    parameter: {
        replicas: int & >0
    }
```

The result is, when an appfile like below is deployed:

```yaml
services:
  express-server:
    type: webservice
    image: bitnami/nodejs
    manualscaler:
      replicas: 1
```

It would NOT create a new *manualscaler* resource, but patches the `replicas` data into `spec.replicas` field of Workload resource which is Deployment resource containing `spec.replicas` field.

This is the general idea. More details will be considered in final design doc.

## Data Processing

There are use cases where input data needs to be further processed. The processing logic could be done in simple scripting. This is known as scripting layer or code automation. See:

- https://cuelang.org/docs/usecases/scripting/
- https://github.com/cuelang/cue/discussions/431

An example is that an `auth` Trait calls an external URL to retrieve `TOKEN`, and the patches the TOKEN into Workload resource.

Auth Trait definition:

```yaml
apiVersion: core.oam.dev/v1alpha1
kind: Trait
metadata:
  name: auth-service
spec:
  template: |
    import "cuelang.org/go/pkg/tool/http"

    parameter: {
        serviceURL: string
    }

    processing: {
      output: {
        token: string
      }
      # task shall output a json result and output will correlate fields by name.
      task: http.Get & {
        url: parameter.serviceURL
      }
    }

    patch: {
      data: token: processing.output.token
    }
```

In above example, instead of using parameter, patch uses processed results from processing logic.

In this example, I have used a CUE scripting example only to demonstrate the idea. But this is quite general design and open to discuss. For example, **shell/python scripting could also be supported.**
