### ISSUE TITLE
[BUG] missing webhooks for AppConfig&Comp in vela-core chart

### ISSUE THREAD

**Issue by captainroy-hy** [oam-dev/kubevela#661]
Below 4 webhooks are not configurated in [vela-core chart](https://github.com/oam-dev/kubevela/blob/master/charts/vela-core/templates/webhook.yaml).
```yaml
kind: ValidatingWebhookConfiguration
webhooks:
  - name: "validate.applicationconfigurations.core.oam.dev"
...
  - name: "validate.component.core.oam.dev"
...
---
kind: MutatingWebhookConfiguration
  - name: "mutate.applicationconfigurations.core.oam.dev"
...
  - name: "mutate.component.core.oam.dev"
...
```
