### ISSUE TITLE
"vela port-forward" issue: Error: trait route in 'wordpress' must be map

### ISSUE THREAD

**Issue by zzxwill** [oam-dev/kubevela#719]
Deploy an application with the following Appfile.

```
✗ cat vela.yaml
name: blog

services:
  wordpress:
    type: webservice # could be skipped
    image: wordpress:php7.4-apache
    port: 80
    cpu: "1"

    route:
```

`vela port-forward` hit an issue.
```
✗ vela port-forward blog
Error: trait route in 'wordpress' must be map
```

Appfile needs to check whether `route` configuration is complete before deploy the application.
