### ISSUE TITLE
Why the default local port is 8080 in "vela port-forward"

### ISSUE THREAD

**Issue by zzxwill** [oam-dev/kubevela#720]
Deploy an application with the following Appfile.

```
✗ cat vela.yaml
name: blog

services:
  wordpress:
    type: webservice # could be skipped
    image: wordpress:php7.4-apache
    port: 80
    cpu: "1"
```

`vela port-forward` shows the default local port is 8080, why?
```
✗ vela port-forward blog
Forwarding from 127.0.0.1:8080 -> 80
Forwarding from [::1]:8080 -> 80

Forward successfully! Opening browser ...
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
```
