### ISSUE TITLE
[Question] vela status doesn't show the trait and its status

### ISSUE THREAD

**Issue by zzxwill** [oam-dev/kubevela#721]
Deploy the app with the Appfile.
```
✗ cat vela.yaml
name: blog

services:
  wordpress:
    type: webservice # could be skipped
    image: wordpress:php7.4-apache
    port: 80
    cpu: "1"
```

Append the trait field and `vela up` again.
```
✗ cat vela.yaml
name: blog

services:
  wordpress:
    type: webservice # could be skipped
    image: wordpress:php7.4-apache
    port: 80
    cpu: "1"

    route:
      domain: zhouzhengxi.com
      issuer: tls
      rules:
        - path: /wordpress
          rewriteTarget: /
```

The trait information doesn't show up in `vela status`.

```
➜  /Users/zhouzhengxi/Programming/golang/src/github.com/zzxwill/try-cloudnative/try-oam/blog git:(master) ✗ vela status blog
About:

  Name:      	blog
  Namespace: 	default
  Created at:	2020-12-04 16:42:22.089454 +0800 CST
  Updated at:	2020-12-04 16:42:22.089455 +0800 CST

Services:

  - Name: wordpress
    Type: webservice
    HEALTHY Ready:1/1
    Traits:

    Last Deployment:
      Created at: 2020-12-04 16:31:46 +0800 CST
      Updated at: 2020-12-04T16:42:22+08:00
➜  /Users/zhouzhengxi/Programming/golang/src/github.com/zzxwill/try-cloudnative/try-oam/blog git:(master) ✗ vela ls
SERVICE       	APP           	TYPE      	TRAITS	STATUS  	CREATED-TIME
wordpress     	blog          	webservice	route 	Deployed	2020-12-04 16:31:46 +0800 CST
```
