### ISSUE TITLE
A detailed workflow of extending KubeVela

### ISSUE THREAD

**Issue by zzxwill** [oam-dev/kubevela#731]
# Background
I pretend to be a platform builder, who try to build a PaaS based on KubeVela and a cloud provider, like Alibaba Cloud. I'd like to provide a trait `LoadBalancer` to provider load-balancing to the application and publish its service, for all our application developers. 

Here are what I did to achieve the goal and some thoughts on docs/features enhancements.

# Build the trait
## develop the trait
I am so lucky to find out a Service with type `LoadBalancer` perfectly meets my requirement. So I won't need any code to develop the trait.

```
apiVersion: v1
kind: Service
metadata:
  name: lb-svc
  namespace: default
spec:
  ports:
  - name: poc
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: wordpress
  type: "LoadBalancer"
```

### read related docs first
I looked through [kubevela.io](https://kubevela.io), but I could not find where I should start. Then this part might help me.
![image](https://user-images.githubusercontent.com/2805315/101241630-c51f7e00-3732-11eb-8c95-5bdaf25ab8c6.png)

But they are all reference docs on how to use the current capabilities.

Maybe `appfile` or `Extensibility` can help, but no luck.
![image](https://user-images.githubusercontent.com/2805315/101241738-c604df80-3733-11eb-8bf2-72ca13a3b55e.png)

Then I find doc `design/vela-core/appfile-design.md` suits me well.

**Suggestion**:
1). Create a doc section on the offiicial site for platform builders.
2). Convert information related to platform builders from `design/vela-core/appfile-design.md` and push it to the official site.

### write TraitDefinition
- write `cue` section
I need to write a TraitDefinition like this. Inside `spec.extension.parameter`, I should write Cuelang. But I am a newbie and it's my first to know Cuelang.

```yaml
apiVersion: core.oam.dev/v1alpha2
kind: TraitDefinition
...
spec:
  extension:
    template: |
      parameter: {
      ...
```

To make it simple, I can write the `.cue` part first and then resemble the whole TraitDefinition. Okay, here is my `.cue` file finally.

```
output: {
  apiVersion: "v1"
  kind: "Service"
  spec:
    ports: parameter.ports
    selector: parameter.selector
    type: "LoadBalancer"
}

parameter: {
  ports: [...{
    name: string
    port: *80 | int
    protocol: *"TCP" | string
    targetPort: int
  }]
  selector: [string]: string
}
```
How can I make sure what I write is valid. 

**Suggestion**
1). write docs on using `cue eval/export` to valid `.cue` files.

- write definition part
I don't know whether I should keep `spec.workloadRefPath` or not, and what I should set `spec.definitionRef`.

And this traits could be regard as a wrapper to Service, so it took me some time to set `spec.definitionRef.name` to `service`

**Suggestion**
1). explain how to fill those fields, or provide the link https://github.com/oam-dev/spec/blob/master/6.traits.md#trait-definition.

```
apiVersion: core.oam.dev/v1alpha2
kind: TraitDefinition
metadata:
  name: loadbalancer
  annotations:
    definition.oam.dev/description: Provide loadbalancer for an application and publish its service"
spec:
  appliesToWorkloads:
    - webservice
  workloadRefPath: spec.workloadRef
  definitionRef:
    name: service
  extension:
    template: |
```

- prepare the complete TraitDefinition
I also learnt from KubeVela maintainers that there is a tool `hack/vela-templates/gen_definitions.sh` locally to generate a complete TraitDefinition with `.cue` and the part of TraitDefinition file.

**Suggestion**
1) make some flags to the script like `--cue` and `--def` to generate a complete TraitDefinition.

Here is my TraitDefinition `traitdefinition-lb-svc.yaml`.

```
apiVersion: core.oam.dev/v1alpha2
kind: TraitDefinition
metadata:
  name: loadbalancer
  annotations:
    definition.oam.dev/description: Provide loadbalancer for an application and publish its service"
spec:
  appliesToWorkloads:
    - webservice
  workloadRefPath: spec.workloadRef
  definitionRef:
    name: service
  extension:
    template: |
      output: {
        apiVersion: "v1"
        kind: "Service"
        spec: 
          ports: parameter.ports
          selector: 
            "app.oam.dev/component": context.name
          selector: parameter.selector
          type: "LoadBalancer"
          
      }

      parameter: {
      	ports: [...{
            name: string
            port: *80 | int
            protocol: *"TCP" | string
            targetPort: int
      	}]
      }
```

## Verify the trait
- apply the traitdefinition
***Suggestion**
1). Provide some steps on how to verify the trait.

Apply the trait definition and verify whether it could be listed by `vela traits`.
I hit an issue #730.

```
$ kubectl apply -f traitdefinition-lb-svc.yaml

$ vela traits
``` 

I want to make sure whether it works if an application developer use the trait. I hit an issue and I find the TraitDefinition is not right.

```
# yaml format is wrong
apiVersion: "v1"
        kind: "Service"
        spec: 
          ports: parameter.ports
          selector: 
            "app.oam.dev/component": context.name
          selector: parameter.selector
          type: "LoadBalancer"

# json format is right
apiVersion: "v1"
        kind: "Service"
        spec: {
          ports: parameter.ports
          selector: {
            "app.oam.dev/component": context.name
          }
          type: "LoadBalancer"
        }
```

**Suggestion**
1). Explain why KubeVela needs json format.

- any solution on label sector?

In `appfile-design`, it mentions `vela template context`. I believe it's very important, as it could be considered as a mechanism to provider workload labels, as KubeVela will automatically set labels for workload

For example.

```
selector: {
            "app.oam.dev/component": context.name
          }
```

**Suggestion**
1). Explain more about `context`.

- Verify the trait by deploying an application
Apply the final TraitDefinition.
```
apiVersion: core.oam.dev/v1alpha2
kind: TraitDefinition
metadata:
  name: loadbalancer
  annotations:
    definition.oam.dev/description: Provide loadbalancer for an application and publish its service"
spec:
  appliesToWorkloads:
    - webservice
  workloadRefPath: spec.workloadRef
  definitionRef:
    name: service
  extension:
    template: |
      output: {
        apiVersion: "v1"
        kind: "Service"
        spec: {
          ports: parameter.ports
          selector: {
            "app.oam.dev/component": context.name
          }
          type: "LoadBalancer"
        }
      }

      parameter: {
      	ports: [...{
            name: string
            port: *80 | int
            protocol: *"TCP" | string
            targetPort: int
      	}]
      }

```

Apply the application by `vela up`
```
name: blog

services:
  wordpress:
    type: webservice # could be skipped
    image: wordpress:php7.4-apache
    port: 80
    cpu: "1"

    loadbalancer:
      ports:
        - name: poc
          port: 8080
          protocol: TCP
          targetPort: 80

```

It succeeded.

```
✗ k get svc
wordpress-loadbalancer-6d948f9f68   LoadBalancer   172.21.11.241   47.242.220.100   8080:30469/TCP   61m
```

![image](https://user-images.githubusercontent.com/2805315/101243203-85a86000-3739-11eb-9363-2b265ca8ff8d.png)

**Suggestion**
1. I get the external IP by `kubectl get svc` as I could get it by `vela status`
```
✗ vela status blog
About:

  Name:      	blog
  Namespace: 	default
  Created at:	2020-12-05 20:35:43.529371 +0800 CST
  Updated at:	2020-12-05 20:35:43.529371 +0800 CST

Services:

  - Name: wordpress
    Type: webservice
    HEALTHY Ready:1/1
    Traits:
      - ✅ loadbalancer: ports=[map[name:poc port:8080 protocol:TCP targetPort:80]]

    Last Deployment:
      Created at: 2020-12-05 20:35:44 +0800 CST
      Updated at: 2020-12-05T20:35:43+08:00
```

So KubeVela needs to provider a way to show extended trait to expose important imformation.
