### ISSUE TITLE
[Feature] Vela-Cli should support live-diff（dry-run） for users to see the difference of underlying resource after upgrade

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela#733]
This could be very helpful for production serious use.

For example, if a user has already running a deployment like below:

```
kind: Deployment
metadata:
  name: myweb
spec:
  template:
     containers:
     - image: nginx:v1
```

When running a new application called `myapp.yaml`

```
kind: Application
metadata:
  name: myapp
spec:
  components:
  - name: myweb:
    properties:
      image: "nginx:v2"
```

We could support command like this:

```
$ vela system live-diff -f myapp.yaml
DIFF
---
kind: Deployment
metadata:
  name: myweb
spec:
  template:
     containers:
-    - image: nginx:v1
+    - image: nginx:v2
```

This command will not actually update, but will execute like `dry-run` and do live diff for underlying resource.

What's more, we can specify the revision using `appRevision`

```
$ vela system live-diff -f myapp.yaml --revision myapp-v1
```
