### ISSUE TITLE
[Feature] Support Definition Reference be Optional

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela#749]
We're supporting appliction object #742, which could let a definition to be a patch.

![image](https://user-images.githubusercontent.com/2173670/101584206-16bc5700-3a18-11eb-8f8a-9ea22fb8db15.png)

This means, the definition will not have any CRD operator behind it, so we should support the definition reference to be optional.

In the picture, we're using "null", instead of that, we should leave the whole section empty.

```
apiVersion: core.oam.dev/v1alpha2
kind: TraitDefinition
metadata:
  annotations:
    definition.oam.dev/description: "add sidecar to the app"
  name: sidecar
spec:
  appliesToWorkloads:
    - webservice
    - worker
  extension:
    template: |-
      _containers: context.input.spec.template.spec.containers+[parameter]
      patch: {
         spec: template: spec: containers: _containers
      }
      parameter: {
         name: string
         image: string
         command?: [...string]
      }
```
