### ISSUE TITLE
[BUG]`vela ls` command triggers build flow

### ISSUE THREAD

**Issue by TomorJM** [oam-dev/kubevela#851]
**Describe the bug**
Run official website demo project, execute "vela ls" command, and trigger the build process

**To Reproduce**
- dir path: kubevela/docs/examples/testapp
- modify the vela.yaml
```
name: testapp

services:
  express-server:
    image: oamdev/testapp:v1
    build:
      docker:
        file: Dockerfile
        context: .
      push:
        local: kind
    cmd: ["node", "server.js"]
    port: 8080
    route:
      domain: example.com
      rules:
        - path: /testapp
          rewriteTarget: /
```

**Screenshots**
![image](https://user-images.githubusercontent.com/11410549/103396907-be88f880-4b70-11eb-89cc-9ca274a91057.png)
![image](https://user-images.githubusercontent.com/11410549/103396913-c9438d80-4b70-11eb-8889-41d906bd32da.png)

**Cluster information**
- Version: 0.2.2
- GitRevision: git-2943bc7
- GolangVersion: go1.15.6
