### ISSUE TITLE
[Feature] generate Secret/ConfigMap from vela config

### ISSUE THREAD

**Issue by zzxwill** [oam-dev/kubevela#862]
Normally we set container env from ConfigMap or Secret as below.

```
name: hello

services:
  express-server:
    type: webservice
    image: oamdev/postgresql-flask-web-application:v0.1
    env:
      - name: DB_HOST
        valueFrom:
          configMapKeyRef:
            name: rds-config
            key: endpoint
      - name: DB_USER
        valueFrom:
          configMapKeyRef:
            name: rds-config
            key: username
      - name: DB_PASSWORD
        valueFrom:
          configMapKeyRef:
            name: rds-config
            key: password
      ports: 80
```

Sometimes, we might want to use vela config data, as it's very convenient to store key-value data in config by vela core or vela cli. For example, if a workload generate database connection information and store it in config as below.

```
services:
  db:
    type: aliyun-oss
    engine_version: "8.0"
    instance_type: "rds.mysql.c1.large"
    instance_name: "poc"
    account_name: "oam"
    password: "Xyfe83jfewGGf"
    config: "rds-config"
```

It would be useful if there is an option to generate Secret/ConfigMap based on the config data as env can directly retrieve the data form Secret/ConfigMap.

/cc @hongchaodeng
