### ISSUE TITLE
[Feature] Helm chart as capability module

### ISSUE THREAD

**Issue by resouer** [oam-dev/kubevela#864]
**Is your feature request related to a problem? Please describe.**

#### Consider using Helm Chart as Component (by referring a chart as WorkloadDefinition module)

As helm chart already provide both templating and parametering, and many platform builders know how to make helm chart (correct me if I'm wrong).
Furthermore, the chart also provides json schema, so many things work today (e.g. doc-gen, openapi-schema-gen) still work.

And user will also be able to use AppDeployment to rollout the workload, this process could be naturally integrated with GitOps tool (Flux or ArgoCD) to form a modern app delivery system: GitOps to sync the app, and AppDeployment to rollout/rollback the app.

#### What about Traits?

Similarly, trait can also be provided by Helm chart in TraitDefinition. KubeVela will be responsible to inject correct workload ref as today (ideally, via `.values`, instead of hacking Helm templating thing). This also means we will NOT allow packaging traits templates (such as HPA, Ingress, etc) in a workload module (Service is part of the it though).

The alternative is, we allow platform team package traits together with workload templates in same chart and allow WorkloadDefinition and TraitDefinition ref same chart as provider. But this seems heavily impacted the clarity and flexibility (unless we use sub-chart).

/cc @ryanzhang-oss who has expressed interested on this, and open for further discussion.

A off topic issue is we should move template related fields out of extension, they have been proven to be useful (and this is NOT a break change).

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by hongchaodeng** [comment]
I think this is the problem that the [Catalog and Package design](https://github.com/oam-dev/kubevela/blob/master/design/vela-core/APIServer-Catalog.md) resolves.

One difference is that, instead of putting the modules in the Definition yaml, the design creates another abstraction called Catalog to manage them. In this way, we can decouple the Capability Definition and Package, because they are stored and managed in separate logical workflows and physical places.

**Comment by wonderflow** [comment]
If we close the issue when we have only merge a design proposal, do we need to raise a new issue to implement the design?

**Comment by resouer** [comment]
It's automatically closed by keyword. Reopen.

**Comment by resouer** [comment]
Draft design idea (impl is based on Helm operator from Flux):

```yaml
apiVersion: core.oam.dev/v1alpha2
kind: Application
metadata:
  name: podinfo
  namespace: podinfo
spec:
  components:
    - name: podinfo # helm chart release name
      type: webapp-chart # definition = helm chart
      settings: # helm chart values
        cache: redis-master.redis:6379
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
          path: "/"
```

```yaml
apiVersion: core.oam.dev/v1alpha2
kind: WorkloadDefinition
metadata:
  name: webapp-chart
spec:
  module:
    helm:
      chart:
        spec:
          chart: podinfo
          sourceRef: # TODO: can embed source here
            kind: HelmRepository
            name: podinfo
            namespace: flux-system
      interval: 5m
      install:
        remediation:
          retries: 3
```
