### ISSUE TITLE
[Feature] Bypass C/AC orchestrator when dependency & dataInput/output is not required

### ISSUE THREAD

**Issue by resouer** [oam-dev/kubevela#867]
**Is your feature request related to a problem? Please describe.**
Today we blindly render `Application` into C/AC and rely on AC controller to render k8s raw resources, it introduced a extra jump.

This is fine in short term, while in long term, we should evaluate bypassing the C/AC orchestrator when dependency & dataInput/output is not claimed in `Application` (which tends to be the majority case).

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kinsolee** [comment]
Consider this situation,  we have two applications both consist of `backend` service.

We first `vela up` first one.
```
name: app-test1
services:
  backend:
    type: webservice
    version: v1.1.1
    image: crccheck/hello-world
    port: 8000
```
When we `vela up` the second one,
```
name: app-test2
services:
  backend:
    type: webservice
    version: v1.1.1
    image: crccheck/another-hello-world
    port: 8000
```
The controller will logs below:
```
2021-01-21T11:19:59.486+0800    DEBUG   controller-runtime.manager.events       Warning {"object": {"kind":"ApplicationConfiguration","namespace":"default","name":"app-test2","uid":"c937773b-e957-42e7-a0f9-0b33b392232a","apiVersion":"core.oam.dev/v1alpha2","resourceVersion":"39437950"}, "reason": "CannotApplyComponents", "message": "cannot apply workload \"backend\": existing object is not controlled by UID \"c937773b-e957-42e7-a0f9-0b33b392232a\""}
```
It blocks the same service name between two applications. 

Can bypassing C/AC solve this problem?
