### ISSUE TITLE
Proposal: Data passing mechanism for Application

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela#873]
# Background

When two services need to pass data from one to another in application, we need a solution for application.

In oam-runtime layer(AppConfig+Component), we already implemented [data input/output mechanism](https://github.com/crossplane/oam-kubernetes-runtime/blob/master/design/resource-dependency.md).

In this proposal, we try to figure out a way to support data passing in Application Object layer.

# Proposal

Data passing mechanism will contain two parts, 1) how to define output data, 2) how to define input data, and let output data to be used as input data.

## Define output data

We use template for abstraction in Application, we will use similar way to define data output.

Actually the data output can be easily defined in Definition:

### 1) output as outside object

```
kind: WorkloadDefinition
metadata:
  name: rds
spec:
    ...
    dataOutputs:      
       condition: |
            if context.status.instanceID == _|_ || context.status.instanceID == " "
                || context.status.instanceClass != _|_ || context.status.instanceClass != " " {
                  false
            } 
       output: |
         object: {
            apiVersion: "v1"
            kind: "ConfigMap"
            metadata: name: context.output-args[0]
            spec: data:{
                redis: {
                  instanceID: context.status.instanceID
                  instanceClass: context.status.instanceClass
                }
            }
         }
```

1. KubeVela Runtime will get the real underlying workload CR as context.
2. KubeVela Runtime can check the output data `condition` in a more flexible way by using cue template, if the value is false, the condition was not meet the requirement, and we should periodically check.
3. When the condition meet requirement, output the object template and create the resource with the name defined in the template.

### 2) output as AppConfig dataoutput

```
kind: WorkloadDefinition
metadata:
  name: rds
spec:
    ...
    dataOutputs:      
       condition: |
            if context.status.instanceID == _|_ || context.status.instanceID == " "
                || context.status.instanceClass != _|_ || context.status.instanceClass != " " {
                  false
            } 
       outputFields:
         - name: context.output-args[0]
           field: "status.instanceID"
         - name:  context.output-args[1]
            field: "status.instanceClass"
```

The appfile will be defined like:

```
name: vela-app
services:
  svc-output:
    type: rds
    image: crccheck/hello-world
    output-args: ["instanceID", "instanceClass"]
```

It will be translate to the AppConfig mechanism like:

```
kind: ApplicationConfiguration
spec:
  components:
  - componentName: myrds
    dataOutputs:
       - name: "instanceID"
         field: "status.instanceID"
       - name: "instanceClass"
          field: "status.instanceClass"
```

The quoted `"instanceID"` and `"instanceClass"` were rendered from appfile.  When we finished these translation, we will rely on the same mechanism as AppConfig.

**Both of "output as outside object" and "output as AppConfig Configs" can be implemented in oam-runtime layer.**

### 1) Use parameter as input parameter

The input part is interesting because it could be extremely easy. You don't need to change anything. When we define a prameter of a workloaddefinition, we have already defined a data input.

```
apiVersion: core.oam.dev/v1alpha2
kind: WorkloadDefinition
metadata:
  name: webservice
spec:
  definitionRef:
    name: deployments.apps
  extension:
    template: |
      output: {
      	apiVersion: "apps/v1"
      	kind:       "Deployment"
      	spec: {
      		template: {
      			spec: {
      				containers: [{
      					image: parameter.image
                                         env: [{name: "instanceID", value: parameter.instanceID},
                                                 {name: "instanceID", value: parameter.instanceClass}]
      		} }}
      }
      parameter: {
      	image: string
        instanceID: string
        instanceClass: string
      }      
```

But we need to define in appfile to let the runtime know it's rely on an output.

```
name: vela-app
services:
  svc-output:
    type: rds
    image: crccheck/hello-world
    output-args: ["instanceID", "instanceClass"]
  svc-input:
    type: webservice
    image: crccheck/hello-world
    instanceID:  dependsOn(svc-output,"instanceID")
    instanceClass: dependsOn(svc-output,"instanceClass")        
```

The `dependsOn()` section will be a magic function, the runtime will know the parameter `instanceID` relys on the output from service(`svc-output`) and args(`instanceID`).

**In this way, the application controller MUST wait until value of the parameter is ready, then render the output.**

In other words, we are re-implementing the dependency system in Application.  (We can also put the whole cue mechanism to AppConfig layer. @ryanzhang-oss )

### 2) translate to AppConfig datainput

For a compromise way, we can define a  section in cue template to just translate to AC datainput mechanism.

```
apiVersion: core.oam.dev/v1alpha2
kind: WorkloadDefinition
metadata:
  name: webservice
spec:
  definitionRef:
    name: deployments.apps
  extension:
    dataInputs:      
       condition: |
            // input conditions
       inputFields:
         - paramName: context.input-args[0]
           field: "spec.tamplate.containers[0].env[0].value"
         - paramName: context.input-args[1]
            field: "spec.tamplate.containers[0].env[1].value"
    template: |
      ...
```

Using this way in appfile can be very straightforward.

```
name: vela-app
services:
  svc-output:
    type: rds
    image: crccheck/hello-world
    output-args: ["instanceID", "instanceClass"]
  svc-input:
    type: webservice
    image: crccheck/hello-world
    input-args: ["instanceID","instanceClass"]
```

We just translate it into AppConfig datainput like below:

```
kind: ApplicationConfiguration
spec:
  components:
  - componentName: svc-output
    dataOutputs:
       - name: "instanceID"
         field: "status.instanceID"
       - name: "instanceClass"
          field: "status.instanceClass"
  - componentName: svc-input
    dataInputs:
       - name: "instanceID"
         field: "spec.tamplate.containers[0].env[0].value"
       - name: "instanceClass"
          field: "spec.tamplate.containers[0].env[1].value"
```

The drawbacks of both `1)` and `2)` are that they can't support complex datainput. But it's not big problem if the workload can understand the complext object itself. For example, if the output-side output a ConfigMap. The input-side can define a parameter that is exactly the configmap name.

```
apiVersion: core.oam.dev/v1alpha2
kind: WorkloadDefinition
metadata:
  name: webservice
spec:
  definitionRef:
    name: deployments.apps
  extension:
    template: |
      output: {
      	apiVersion: "apps/v1"
      	kind:       "Deployment"
      	spec: {
      		template: {
      			spec: {
      				containers: [{
      					image: parameter.image
                                         envFrom: [{
                                            configMapRef: {
                                                name: parameter.rdsinfo
                                             }
                                         }]
                          }
                }
       }
      parameter: {
      	image: string
        rdsinfo: string
      }      
```

In this case, the parameter `rdsinfo` is a configmap name.

### 3) Support complex datainput by using trait

For complex datainput that you want to control the operations like patch, we should implement as patch trait:

```
kind: TraitDefinition
metadata:
  name: rds-data-patch
spec:
   ...
  extension:
    template: |-
      patch: {
        for i,v in context.input.spec.template.spec.containers[0].env{
               if v.name == "instanceID" && v.value != parameter.instanceClass {
                    context.input.spec.template.spec.containers[0].env[0].value: parameter.instanceClass
               }
        }
      }
      parameter: {
         instanceClass: string
      }
```

The condition and operations can be embeded into the patch logic, and we can easily do more extensions. 

```
name: vela-app
services:
  svc-output:
    type: rds
    image: crccheck/hello-world
    output-args: ["instanceID", "instanceClass"]
  svc-input:
    type: webservice
    image: crccheck/hello-world
    rds-data-patch:
       instanceClass: dependsOn(svc-output,"instanceClass")       
```

# Conclusion

The main idea of this proposal is to support abstracted data paasing mechanisom in application(appfile). We can put all the complex model into Definition and MUST make the application/appfile model clean.

Generally, I give a way to do translation that rely on the oam-runtime(AppConfig)  to do the real data passing.

@resouer @ryanzhang-oss @hongchaodeng  what do you think?

**Comment by hongchaodeng** [comment]
The idea sounds awesome. But the proposal lacks many details that need to be explained:

First, the background section doesn't explain the motivation with enough details. Here are some of the questions to be answered:

- What are the user scenarios that could not be solved by current Vela implementation and will be solved in this proposal?
- Why solve it in Vela instead of relying on external tools? Why put it in Application instead of another object?

Second, I saw the condition use CUE to do the checking:
```
    if context.status.instanceID == _|_ || context.status.instanceID == " "
                || context.status.instanceClass != _|_ || context.status.instanceClass != " " {
                  false
            } 
```

The question is how is status field gets propagated into CUE? The workload definitions could be from third party. In this case how could Vela handle that?

Third, why add input/output in appfile like the following:

```
name: vela-app
services:
  svc-output:
    type: rds
    image: crccheck/hello-world
    output-args: ["instanceID", "instanceClass"]
  svc-input:
    type: webservice
    image: crccheck/hello-world
    input-args: ["instanceID","instanceClass"]
```

Why couldn't these be put in definitions instead?
Again, this is related to the motivation part which hasn't been explained well. This needs to be explained with more details of use cases.

Fourth, I saw this statement:

> For complex datainput that you want to control the operations like patch, we should implement as patch trait:

Why "implement as patch trait"? There is not justification for this. I have mentioned a couple of times before that we should just use data input/output to replace patch trait. Why isn't this the correct way?

**Comment by hongchaodeng** [comment]
Here's an update notes based on discussion between @wonderflow and me:

1. Currently, the user scenario is that we need to support data passing in representation layer (appfile/application) so that we can further decouple inputs/outputs and reuse them across services.

1. It is gonna be implemented in Vela because we don't want to add external tooling dependencies to users (e.g. Tekton pipelines).

1. Data input/output should be defined by platform builders. That's because only platform builders know about such details as which fields to export and whether to use intermediate store. Thus, it will be defined in Definition objects. Below is an example:

    - A definition object will add the outputs field:
      ```yaml
      kind: WorkloadDefinition
      metadata:
        name: db
      spec:
        outputs:
          db_name:
            field: metadata.name
      ```
    - For a definition object, its schema exposed to users will include outputs as well:
      ```yaml
      # `vela show webservice` to show the reference doc of webservice definition
      webservice:
        parameters:
          - name: xxx
        outputs:
          - name: "db_name"
            type: string
            description: the name of the database
      ```
    - Once users get this information, in representation layer (appfile/application) they can use `depends_on(service, output)` to define service dependencies:
      ```yaml
      name: app
      services:
        web:
          image: xxx
          port: xxx
          db_name: depends_on(db, db_name)
        db:
          name: "db-1"
      ```
    - To add intermediate store as designed in https://github.com/oam-dev/kubevela/issues/770, define the store in definition as well:
    
      ```yaml
        # db definition
        outputs:
          db_name:
            field: metadata.name
            store:
              configmap: "cm-1"
              key: "db_name"
      ```
      With this information we will see below that it is enough to defer intermediate store in both input and output sides.

    - Note that the previous design suggests that each output's name is a variable. Based on the discussion by now, the outputs should be predefined schema and all variables should be included in `parameters` section.

      For example, if we want to make the configmap name a variable in definition:
      
        ```yaml
          # db definition
          parameters:
            cm_name: string
          outputs:
            db_name:
              field: metadata.name
              store:
                configmap: parameter.cm_name
                key: "db_name"
        ```

      and add it in appfile:

        ```yaml
        name: app
        services:
          web:
            image: xxx
            db_name: depends_on(db, db_name)
          db:
            name: "db-1"
            cm_name: "cm-1"
        ```

4. Here's a little dive-in on how this works under the hood:
    - The following is based on this example:

      ```yaml
      services:
        web:
          type: webservice
          db_name: depends_on(db, db_name)
        db:
          name: "db-1"
      ```

    - The dependency engine will parse the yaml file and builds dependency graph based on `depends_on` keyword. Here it will know that web -> db.

    - web will wait, and db resource will be created first.
    
      - If intermediate store is used, the output data will be transferred to the store as well. This information could be derived from the db definition.

    - Once the dependency is satisfied, it will start creating the web resource.

      - If no store is used (derived from db definition), then the field name will be retrieved (derived from db definition) and filled into the web resource corresponding fields (derived from appfile).

      - If store is used (derived from db definition), then the engine will get the data first and fill corresponding fields in the web resource (derived from appfile).
