### ISSUE TITLE
Saving parameter reference information of a Workload Type or Trait in ConfigMap

### ISSUE THREAD

**Issue by zzxwill** [oam-dev/kubevela#899]
[Comments](https://github.com/oam-dev/kubevela/pull/886#issuecomment-761237621) from @hongchaodeng 

> Currently, the reference docs in the website is auto generated and put into the website files. We can do the same for the CLI/UI as well by saving those data on server side. For the long term, we should let the /definitions API endpoint return the documentation too. For now, the CLI doesn't talk to the API Server yet, so we could probably save it as a ConfigMap on k8s.

另外，存储阶段应该是「能力安装」，也就是用户 `kubectl apply -f workloadDefinition.yaml/traitDefinition.yaml` 时。
[Comments](https://github.com/oam-dev/kubevela/discussions/880#discussioncomment-277552) from @resouer 
>请先解决生成出的文档保存在哪里的问题，直接放在本地远端用户是/上层产品看不到的。另外 hack/doc-gen 应该是“能力安装”这个流程的一个自动化环节，而不是手动执行。

**Comment by wonderflow** [comment]
Create a Definition controller, generate the `parameter reference information`(doc info)  and  `json schema`(Dashboard UI) in a configmap. VelaCP will integrate with the configmap.

**Comment by wonderflow** [comment]
related issue #1038

**Comment by zzxwill** [comment]
# Design of storing definition reference in ConfigMap

# How to store in ConfigMap
### Naming
`def-${uppercase(DefinitionaName)}`

For example, the ConfigMap name to store information for WorkloadDefinition `webservice` is `def-webservice`.

### Namespace
Same as the namespace of VelaCore, like `vela-system`.

### Data
Two types of data to store.
- OpenAPI v2 JSON schema
  for API Server
- Reference docs
  for vala cli (website + console)

Sample: 
```yaml
apiVersion: v1
kind: ConfigMap
data: 
    openapi-v3-json-schema: "{\"properties\":{\"cmd\":{\"description\":\"Commands to run in the container\",\"items\":{\"type\":\"string\"},\"title\":\"cmd\",\"type\":\"array\"},\"cpu\":{\"description\":\"Number of CPU units for the service, like `0.5` (0.5 CPU core), `1` (1 CPU core)\",\"title\":\"cpu\",\"type\":\"string\"},\"env\":{\"description\":\"Define arguments by using environment variables\",\"items\":{\"properties\":{\"name\":{\"description\":\"Environment variable name\",\"title\":\"name\",\"type\":\"string\"},\"value\":{\"description\":\"The value of the environment variable\",\"title\":\"value\",\"type\":\"string\"},\"valueFrom\":{\"description\":\"Specifies a source the value of this var should come from\",\"properties\":{\"secretKeyRef\":{\"description\":\"Selects a key of a secret in the pod's namespace\",\"properties\":{\"key\":{\"description\":\"The key of the secret to select from. Must be a valid secret key\",\"title\":\"key\",\"type\":\"string\"},\"name\":{\"description\":\"The name of the secret in the pod's namespace to select from\",\"title\":\"name\",\"type\":\"string\"}},\"required\":[\"name\",\"key\"],\"title\":\"secretKeyRef\",\"type\":\"object\"}},\"required\":[\"secretKeyRef\"],\"title\":\"valueFrom\",\"type\":\"object\"}},\"required\":[\"name\"],\"type\":\"object\"},\"title\":\"env\",\"type\":\"array\"},\"image\":{\"description\":\"Which image would you like to use for your service\",\"title\":\"image\",\"type\":\"string\"},\"port\":{\"default\":80,\"description\":\"Which port do you want customer traffic sent to\",\"title\":\"port\",\"type\":\"integer\"}},\"required\":[\"image\",\"port\"],\"type\":\"object\"}"
    cli-reference-console: "| NAME  |                                   DESCRIPTION                                    |     TYPE      | REQUIRED | DEFAULT |..."
    cli-reference-website: "..."

```

## How to get processed definition data from ConfigMap

### API Server

`/api/definitions/${DefinitionaName}` --> get ConfigMap `def-${uppercase(DefinitionaName)}` in namespace `vela-system` --> get date by key `openapi-v3-json-schema`

### `vela show`

`vela show ${DefinitionaName}` --> get ConfigMap `def-${uppercase(DefinitionaName)}` in namespace `vela-system`  --> get date by key `cli-reference-console` or `cli-reference-website`
