### ISSUE TITLE
 lack of documentation of Application object

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela#904]
Need to add documentation to explain how to use the Application Object and how it works.

``` 
apiVersion: core.oam.dev/v1alpha2
kind: Application
metadata:
  name: application-sample
spec:
  components:
    - name: myweb
      type: worker
      settings:
        image: "busybox"
        cmd:
        - sleep
        - "1000"
      traits:
        - name: scaler
          properties:
            replicas: 10
        - name: sidecar
          properties:
            name: "sidecar-test"
            image: "nginx"
```
