### ISSUE TITLE
[Feature] Add base parameters to context

### ISSUE THREAD

**Issue by joscha-alisch** [oam-dev/kubevela#959]
When creating a trait, it seems we currently need to define base parameters again, because they don't seem to be in the context. Take this example

```yaml
name: my-app
services:
  app:
    type: webservice
    image: crccheck/hello-world
    port: 8000
    myTrait:
      port: 8000
```

In `myTrait` we need to redefine port, in order to use it in the trait to create a service resource. Please correct me if I'm wrong and it is to be found somewhere.

It would be good, if those base parameters would be available. Maybe in `context.port`?
