### ISSUE TITLE
[Feature] Following Istio labels in abstraction rendering

### ISSUE THREAD

**Issue by resouer** [oam-dev/kubevela#968]
Since we want to support Istio based traffic management in [AppDeployment](https://github.com/oam-dev/kubevela/pull/963), we need to follow the Istio practice in abstraction engine. In detail, Istio use `app: foo` as the label for app name and `version: x` for app revision, it means:

For a given web service component named `helloworld`, besides the per-revision `Service` and `Deployment`, vela also needs to render a root `Service` which is cross-revision:

The root `Service`:

```yaml
apiVersion: v1
kind: Service
metadata:
name: helloworld # root service name, it's also the component's name
labels:
  app: helloworld
spec:
  selector:
    app: helloworld
  ...
```

The per-revision `Service` and `Deployment`:

Immutable component `helloworld-v1`:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld # must be the root service name
        version: v1 # revision
        component.oam.dev/name: helloworld-v1
    spec:
      containers:
      - image: nginx-v1
        ...
---
apiVersion: v1
kind: Service
metadata:
name: helloworld-service_trait-v1
labels:
  component.oam.dev/name: helloworld-v1
spec:
  selector:
    component.oam.dev/name: helloworld-v1
  ...
```
Immutable component `helloworld-v2`:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-v2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld # must be the root service name
        version: v2 # revision
        component.oam.dev/name: helloworld-v2
    spec:
      containers:
      - image: nginx-v2
        ...
---
apiVersion: v1
kind: Service
metadata:
name: helloworld-service_trait-v2
labels:
  component.oam.dev/name: helloworld-v2
spec:
  selector:
    component.oam.dev/name: helloworld-v2
  ...
```

Then, uses can now directly use Istio to do canary:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: canary
spec:
  hosts:
    - helloworld # root service name
  http:
  - route:
    - destination:
        host: helloworld # root service name
        subset: v1 # revision
      weight: 90
    - destination:
        host: helloworld # root service name
        subset: v2 # revision
      weight: 10
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: canary
spec:
  host: helloworld # root service name
  subsets:
  - name: v1
    labels:
      version: v1 # revision
  - name: v2
    labels:
      version: v2 # revision
```

Similarly, the `AppDeployment` can rollout the `Deployment` just by component name and revisions, and it can directly rollout the raw Deployment which follows Istio label practice.

This fixes https://github.com/oam-dev/kubevela/issues/638
