### ISSUE TITLE
keep reconciling when application deployed but don't force override user's change

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela#970]
Now we don't keep reconciling when application was deployed. The AC and Component will. And it will use clientside 3-way-merge patch to update the resource.

There's a case that we should consider:

When user want to change a field temporarily, for some emergency fix, the AC or application controller should detect this change a report an error instead of override it.

**Comment by resouer** [comment]
Note that https://kubernetes.io/docs/reference/using-api/server-side-apply/ could be helpful for this issue, but it's not stable yet and require very latest k8s version.

**Comment by wonderflow** [comment]
Another case on this issue is our status check.

Our trait has status check：

```
apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  annotations:
    definition.oam.dev/description: "Enable public web traffic for the component."
  name: ingress
  namespace: {{.Values.systemDefinitionNamespace}}
spec:
  status:
    customStatus: |-
      let igs = context.outputs.ingress.status.loadBalancer.ingress
      if igs == _|_ {
        message: "No loadBalancer found, visiting by using 'vela port-forward " + context.appName + " --route'\n"
      }
      if len(igs) > 0 {
        if igs[0].ip != _|_ {
          message: "Visiting URL: " + context.outputs.ingress.spec.rules[0].host + ", IP: " + igs[0].ip
        }
        if igs[0].ip == _|_ {
          message: "Visiting URL: " + context.outputs.ingress.spec.rules[0].host
        }
      }
    healthPolicy: |
      isHealth: len(context.outputs.service.spec.clusterIP) > 0
```

But after deployed, the ingress didn't respond the loadBalancer IP so it reports:

```
  services:
  - healthy: true
    name: express-server
    traits:
    - healthy: true
      message: No loadBalancer found, visiting by using 'vela port-forward express-server' --route
      type: ingress
    workloadDefinition:
      apiVersion: apps/v1
      kind: Deployment
```

After a while, the ingress repond the right loadBalancer IP, but because kubevela didn't reconclie frequently, so it didn't show the right status in time. 

We can also define a standalone health check, then it relates with #914
